-- ============================================================
-- 第8章 立体几何初步 补题（14学期, 知识点 97-114）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0097-1','math','高中',14,'hs-kp-0097','single_choice',0.55,'斜二测画法中，y 轴方向长度变为原来的？','[{"key":"A","text":"1/2"},{"key":"B","text":"√2/2"},{"key":"C","text":"1"},{"key":"D","text":"2"}]','A','斜二测：y 轴方向长度减半，x 轴不变','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0097-2','math','高中',14,'hs-kp-0097','single_choice',0.55,'斜二测画法中，y 轴方向长度变为原来的？','[{"key":"D","text":"2"},{"key":"C","text":"1"},{"key":"B","text":"√2/2"},{"key":"A","text":"1/2"}]','A','斜二测：y 轴方向长度减半，x 轴不变','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0097-3','math','高中',14,'hs-kp-0097','single_choice',0.55,'斜二测画法中，y 轴方向长度变为原来的？','[{"key":"D","text":"2"},{"key":"C","text":"1"},{"key":"A","text":"1/2"},{"key":"B","text":"√2/2"}]','A','斜二测：y 轴方向长度减半，x 轴不变','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0098-1','math','高中',14,'hs-kp-0098','single_choice',0.65,'水平放置的正方形，其斜二测直观图面积是原面积的？','[{"key":"A","text":"√2/4"},{"key":"B","text":"1/2"},{"key":"C","text":"√2/2"},{"key":"D","text":"1/4"}]','A','直观图面积 = 原面积 × √2/4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0098-2','math','高中',14,'hs-kp-0098','single_choice',0.65,'水平放置的正方形，其斜二测直观图面积是原面积的？','[{"key":"C","text":"√2/2"},{"key":"B","text":"1/2"},{"key":"A","text":"√2/4"},{"key":"D","text":"1/4"}]','A','直观图面积 = 原面积 × √2/4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0098-3','math','高中',14,'hs-kp-0098','single_choice',0.65,'水平放置的正方形，其斜二测直观图面积是原面积的？','[{"key":"D","text":"1/4"},{"key":"A","text":"√2/4"},{"key":"C","text":"√2/2"},{"key":"B","text":"1/2"}]','A','直观图面积 = 原面积 × √2/4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0099-1','math','高中',14,'hs-kp-0099','single_choice',0.75,'三个不共线的点可以确定？','[{"key":"A","text":"一个平面"},{"key":"B","text":"一条直线"},{"key":"C","text":"两个平面"},{"key":"D","text":"一个点"}]','A','公理：不共线三点确定一个平面','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0099-2','math','高中',14,'hs-kp-0099','single_choice',0.75,'三个不共线的点可以确定？','[{"key":"B","text":"一条直线"},{"key":"A","text":"一个平面"},{"key":"D","text":"一个点"},{"key":"C","text":"两个平面"}]','A','公理：不共线三点确定一个平面','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0100-1','math','高中',14,'hs-kp-0100','single_choice',0.35,'空间中，若 a∥b 且 b∥c，则 a 与 c 的关系是？','[{"key":"A","text":"平行"},{"key":"B","text":"垂直"},{"key":"C","text":"相交"},{"key":"D","text":"异面"}]','A','平行公理：平行于同一直线的两直线平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0100-2','math','高中',14,'hs-kp-0100','single_choice',0.35,'空间中，若 a∥b 且 b∥c，则 a 与 c 的关系是？','[{"key":"B","text":"垂直"},{"key":"D","text":"异面"},{"key":"C","text":"相交"},{"key":"A","text":"平行"}]','A','平行公理：平行于同一直线的两直线平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0100-3','math','高中',14,'hs-kp-0100','single_choice',0.35,'空间中，若 a∥b 且 b∥c，则 a 与 c 的关系是？','[{"key":"A","text":"平行"},{"key":"B","text":"垂直"},{"key":"D","text":"异面"},{"key":"C","text":"相交"}]','A','平行公理：平行于同一直线的两直线平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0101-1','math','高中',14,'hs-kp-0101','single_choice',0.45,'线面平行判定定理：a∥b，a 在面外，b 在面内 → a 与面？','[{"key":"A","text":"平行"},{"key":"B","text":"垂直"},{"key":"C","text":"相交"},{"key":"D","text":"无法确定"}]','A','线面平行判定：线线平行→线面平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0101-2','math','高中',14,'hs-kp-0101','single_choice',0.45,'线面平行判定定理：a∥b，a 在面外，b 在面内 → a 与面？','[{"key":"B","text":"垂直"},{"key":"D","text":"无法确定"},{"key":"A","text":"平行"},{"key":"C","text":"相交"}]','A','线面平行判定：线线平行→线面平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0101-3','math','高中',14,'hs-kp-0101','single_choice',0.45,'线面平行判定定理：a∥b，a 在面外，b 在面内 → a 与面？','[{"key":"C","text":"相交"},{"key":"D","text":"无法确定"},{"key":"B","text":"垂直"},{"key":"A","text":"平行"}]','A','线面平行判定：线线平行→线面平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0102-1','math','高中',14,'hs-kp-0102','single_choice',0.55,'面面平行判定：一个面内两条相交直线都平行于另一个面 → 两面？','[{"key":"A","text":"平行"},{"key":"B","text":"垂直"},{"key":"C","text":"相交"},{"key":"D","text":"重合"}]','A','面面平行判定：面内两相交线平行于另一面','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0102-2','math','高中',14,'hs-kp-0102','single_choice',0.55,'面面平行判定：一个面内两条相交直线都平行于另一个面 → 两面？','[{"key":"B","text":"垂直"},{"key":"A","text":"平行"},{"key":"D","text":"重合"},{"key":"C","text":"相交"}]','A','面面平行判定：面内两相交线平行于另一面','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0102-3','math','高中',14,'hs-kp-0102','single_choice',0.55,'面面平行判定：一个面内两条相交直线都平行于另一个面 → 两面？','[{"key":"D","text":"重合"},{"key":"B","text":"垂直"},{"key":"A","text":"平行"},{"key":"C","text":"相交"}]','A','面面平行判定：面内两相交线平行于另一面','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0103-1','math','高中',14,'hs-kp-0103','single_choice',0.65,'线面垂直判定：直线垂直于面内两条相交直线 → 直线与面？','[{"key":"A","text":"垂直"},{"key":"B","text":"平行"},{"key":"C","text":"斜交"},{"key":"D","text":"无法确定"}]','A','线面垂直判定定理','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0103-2','math','高中',14,'hs-kp-0103','single_choice',0.65,'线面垂直判定：直线垂直于面内两条相交直线 → 直线与面？','[{"key":"B","text":"平行"},{"key":"C","text":"斜交"},{"key":"A","text":"垂直"},{"key":"D","text":"无法确定"}]','A','线面垂直判定定理','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0103-3','math','高中',14,'hs-kp-0103','single_choice',0.65,'线面垂直判定：直线垂直于面内两条相交直线 → 直线与面？','[{"key":"D","text":"无法确定"},{"key":"A","text":"垂直"},{"key":"B","text":"平行"},{"key":"C","text":"斜交"}]','A','线面垂直判定定理','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0104-1','math','高中',14,'hs-kp-0104','single_choice',0.75,'面面垂直判定：一个面过另一个面的垂线 → 两面？','[{"key":"A","text":"垂直"},{"key":"B","text":"平行"},{"key":"C","text":"相交不垂直"},{"key":"D","text":"重合"}]','A','面面垂直判定定理','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0104-2','math','高中',14,'hs-kp-0104','single_choice',0.75,'面面垂直判定：一个面过另一个面的垂线 → 两面？','[{"key":"B","text":"平行"},{"key":"D","text":"重合"},{"key":"A","text":"垂直"},{"key":"C","text":"相交不垂直"}]','A','面面垂直判定定理','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0104-3','math','高中',14,'hs-kp-0104','single_choice',0.75,'面面垂直判定：一个面过另一个面的垂线 → 两面？','[{"key":"D","text":"重合"},{"key":"C","text":"相交不垂直"},{"key":"B","text":"平行"},{"key":"A","text":"垂直"}]','A','面面垂直判定定理','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0105-1','math','高中',14,'hs-kp-0105','single_choice',0.35,'若直线 a⊥面 α，则 a 与面 α 内任意直线？','[{"key":"A","text":"垂直"},{"key":"B","text":"平行"},{"key":"C","text":"相交但不垂直"},{"key":"D","text":"异面"}]','A','线面垂直定义：垂直于面内所有直线','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0105-2','math','高中',14,'hs-kp-0105','single_choice',0.35,'若直线 a⊥面 α，则 a 与面 α 内任意直线？','[{"key":"C","text":"相交但不垂直"},{"key":"D","text":"异面"},{"key":"B","text":"平行"},{"key":"A","text":"垂直"}]','A','线面垂直定义：垂直于面内所有直线','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0105-3','math','高中',14,'hs-kp-0105','single_choice',0.35,'若直线 a⊥面 α，则 a 与面 α 内任意直线？','[{"key":"D","text":"异面"},{"key":"C","text":"相交但不垂直"},{"key":"B","text":"平行"},{"key":"A","text":"垂直"}]','A','线面垂直定义：垂直于面内所有直线','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0106-1','math','高中',14,'hs-kp-0106','single_choice',0.45,'正方体 ABCD-A₁B₁C₁D₁ 中，AB 与 A₁D₁ 所成角？','[{"key":"A","text":"45°"},{"key":"B","text":"90°"},{"key":"C","text":"30°"},{"key":"D","text":"60°"}]','A','AB 与 A₁D₁ 异面，平移后夹角为 45°（与面对角线）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0107-1','math','高中',14,'hs-kp-0107','single_choice',0.55,'正方体中，体对角线 AC₁ 与底面 ABCD 所成角的正切值为？','[{"key":"A","text":"√2"},{"key":"B","text":"1"},{"key":"C","text":"√3"},{"key":"D","text":"1/√3"}]','A','线面角：tanθ=AA₁/AC=1/√2×√2=√2/2×2=√2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0107-2','math','高中',14,'hs-kp-0107','single_choice',0.55,'正方体中，体对角线 AC₁ 与底面 ABCD 所成角的正切值为？','[{"key":"D","text":"1/√3"},{"key":"A","text":"√2"},{"key":"B","text":"1"},{"key":"C","text":"√3"}]','A','线面角：tanθ=AA₁/AC=1/√2×√2=√2/2×2=√2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0108-1','math','高中',14,'hs-kp-0108','single_choice',0.65,'二面角的范围是？','[{"key":"A","text":"[0°,180°]"},{"key":"B","text":"[0°,90°]"},{"key":"C","text":"(0°,90°)"},{"key":"D","text":"[0°,360°]"}]','A','二面角范围 [0°,180°]','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0108-2','math','高中',14,'hs-kp-0108','single_choice',0.65,'二面角的范围是？','[{"key":"C","text":"(0°,90°)"},{"key":"A","text":"[0°,180°]"},{"key":"D","text":"[0°,360°]"},{"key":"B","text":"[0°,90°]"}]','A','二面角范围 [0°,180°]','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0108-3','math','高中',14,'hs-kp-0108','single_choice',0.65,'二面角的范围是？','[{"key":"D","text":"[0°,360°]"},{"key":"C","text":"(0°,90°)"},{"key":"B","text":"[0°,90°]"},{"key":"A","text":"[0°,180°]"}]','A','二面角范围 [0°,180°]','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0109-1','math','高中',14,'hs-kp-0109','single_choice',0.75,'正方体棱长 2，顶点到对面距离 = ？','[{"key":"A","text":"2"},{"key":"B","text":"4"},{"key":"C","text":"2.8284271247461903"},{"key":"D","text":"1"}]','A','点到对面距离 = 棱长 = 2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0109-2','math','高中',14,'hs-kp-0109','single_choice',0.75,'正方体棱长 4，顶点到对面距离 = ？','[{"key":"A","text":"4"},{"key":"B","text":"8"},{"key":"C","text":"5.656854249492381"},{"key":"D","text":"2"}]','A','点到对面距离 = 棱长 = 4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0109-3','math','高中',14,'hs-kp-0109','single_choice',0.75,'正方体棱长 5，顶点到对面距离 = ？','[{"key":"A","text":"5"},{"key":"B","text":"10"},{"key":"C","text":"7.0710678118654755"},{"key":"D","text":"2.5"}]','A','点到对面距离 = 棱长 = 5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0110-1','math','高中',14,'hs-kp-0110','single_choice',0.35,'正方体棱长 2，表面积 = ？','[{"key":"A","text":"24"},{"key":"B","text":"4"},{"key":"C","text":"8"},{"key":"D","text":"24"}]','A','S=6a²=6×2²=24','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0110-2','math','高中',14,'hs-kp-0110','single_choice',0.35,'正方体棱长 4，表面积 = ？','[{"key":"A","text":"96"},{"key":"B","text":"16"},{"key":"C","text":"64"},{"key":"D","text":"48"}]','A','S=6a²=6×4²=96','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0110-3','math','高中',14,'hs-kp-0110','single_choice',0.35,'正方体棱长 3，表面积 = ？','[{"key":"A","text":"54"},{"key":"B","text":"9"},{"key":"C","text":"27"},{"key":"D","text":"36"}]','A','S=6a²=6×3²=54','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0111-1','math','高中',14,'hs-kp-0111','single_choice',0.45,'正方体棱长 2，体积 = ？','[{"key":"A","text":"8"},{"key":"B","text":"24"},{"key":"C","text":"6"},{"key":"D","text":"4"}]','A','V=a³=2³=8','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0111-2','math','高中',14,'hs-kp-0111','single_choice',0.45,'正方体棱长 4，体积 = ？','[{"key":"A","text":"64"},{"key":"B","text":"96"},{"key":"C","text":"12"},{"key":"D","text":"8"}]','A','V=a³=4³=64','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0111-3','math','高中',14,'hs-kp-0111','single_choice',0.45,'正方体棱长 3，体积 = ？','[{"key":"A","text":"27"},{"key":"B","text":"54"},{"key":"C","text":"9"},{"key":"D","text":"6"}]','A','V=a³=3³=27','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0112-1','math','高中',14,'hs-kp-0112','single_choice',0.55,'空间中两条直线的关系不包括？','[{"key":"A","text":"重合"},{"key":"B","text":"平行"},{"key":"C","text":"相交"},{"key":"D","text":"异面"}]','A','空间中两直线：平行、相交、异面（不含重合，重合视为一条）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0112-2','math','高中',14,'hs-kp-0112','single_choice',0.55,'空间中两条直线的关系不包括？','[{"key":"A","text":"重合"},{"key":"D","text":"异面"},{"key":"B","text":"平行"},{"key":"C","text":"相交"}]','A','空间中两直线：平行、相交、异面（不含重合，重合视为一条）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0112-3','math','高中',14,'hs-kp-0112','single_choice',0.55,'空间中两条直线的关系不包括？','[{"key":"B","text":"平行"},{"key":"A","text":"重合"},{"key":"D","text":"异面"},{"key":"C","text":"相交"}]','A','空间中两直线：平行、相交、异面（不含重合，重合视为一条）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0113-1','math','高中',14,'hs-kp-0113','single_choice',0.65,'线面垂直 + 线在面内 → 面面？的判定正确是？','[{"key":"A","text":"线垂直面，线在另一面内 → 两面垂直"},{"key":"B","text":"线平行面 → 两面平行"},{"key":"C","text":"线垂直面 → 两面平行"},{"key":"D","text":"无法判断"}]','A','面面垂直判定：一平面过另一平面的垂线','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0113-2','math','高中',14,'hs-kp-0113','single_choice',0.65,'线面垂直 + 线在面内 → 面面？的判定正确是？','[{"key":"C","text":"线垂直面 → 两面平行"},{"key":"B","text":"线平行面 → 两面平行"},{"key":"D","text":"无法判断"},{"key":"A","text":"线垂直面，线在另一面内 → 两面垂直"}]','A','面面垂直判定：一平面过另一平面的垂线','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0113-3','math','高中',14,'hs-kp-0113','single_choice',0.65,'线面垂直 + 线在面内 → 面面？的判定正确是？','[{"key":"B","text":"线平行面 → 两面平行"},{"key":"A","text":"线垂直面，线在另一面内 → 两面垂直"},{"key":"D","text":"无法判断"},{"key":"C","text":"线垂直面 → 两面平行"}]','A','面面垂直判定：一平面过另一平面的垂线','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0114-1','math','高中',14,'hs-kp-0114','single_choice',0.75,'三视图：主视图反映物体的？','[{"key":"A","text":"长和高"},{"key":"B","text":"长和宽"},{"key":"C","text":"宽和高"},{"key":"D","text":"长宽高"}]','A','主视图（正视图）反映长和高','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0114-2','math','高中',14,'hs-kp-0114','single_choice',0.75,'三视图：主视图反映物体的？','[{"key":"B","text":"长和宽"},{"key":"A","text":"长和高"},{"key":"C","text":"宽和高"},{"key":"D","text":"长宽高"}]','A','主视图（正视图）反映长和高','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0114-3','math','高中',14,'hs-kp-0114','single_choice',0.75,'三视图：主视图反映物体的？','[{"key":"C","text":"宽和高"},{"key":"A","text":"长和高"},{"key":"B","text":"长和宽"},{"key":"D","text":"长宽高"}]','A','主视图（正视图）反映长和高','template-hs','approved','通用');