-- ============================================================
-- 第9章 统计 补题（14学期, 知识点 115-126）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0115-1','math','高中',14,'hs-kp-0115','single_choice',0.35,'总体 193 人，分 5 层，各层人数 50,93,50，按比例分层抽 12 人，第一层抽几人？(按 50:93:50)','[{"key":"A","text":"3"},{"key":"B","text":"4"},{"key":"C","text":"12"},{"key":"D","text":"6"}]','A','按比例：3 人','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0116-1','math','高中',14,'hs-kp-0116','single_choice',0.45,'频率分布直方图中，所有小矩形面积之和 = ？','[{"key":"A","text":"1"},{"key":"B","text":"20"},{"key":"C","text":"0.5"},{"key":"D","text":"100"}]','A','直方图面积=频率，总和=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0117-1','math','高中',14,'hs-kp-0117','single_choice',0.55,'数据 4,7,5 的平均数 = ？','[{"key":"A","text":"5.3"},{"key":"B","text":"16"},{"key":"C","text":"6.3"},{"key":"D","text":"4.3"}]','A','平均数=(4+7+5)/3=5.3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0118-1','math','高中',14,'hs-kp-0118','single_choice',0.65,'10 个数据，第 30 百分位数对应的位置 k = n×p/100 = ？(n=7,p=30)','[{"key":"A","text":"2.1"},{"key":"B","text":"7"},{"key":"C","text":"3"},{"key":"D","text":"21"}]','A','k=7×30/100=2.1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0119-1','math','高中',14,'hs-kp-0119','single_choice',0.75,'直方图中，中位数对应的位置是？','[{"key":"A","text":"面积平分处（50%）"},{"key":"B","text":"最高柱处"},{"key":"C","text":"第一柱处"},{"key":"D","text":"最后一柱处"}]','A','中位数：直方图面积左右各 50% 处','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0120-1','math','高中',14,'hs-kp-0120','single_choice',0.35,'数据 2,3,6 的方差 ≈ ？','[{"key":"A","text":"2.8"},{"key":"B","text":"3.8"},{"key":"C","text":"0"},{"key":"D","text":"3.6666666666666665"}]','A','方差 = Σ(xi-x̄)²/n ≈ 2.8','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0121-1','math','高中',14,'hs-kp-0121','single_choice',0.45,'简单随机抽样的常用方法是？','[{"key":"A","text":"抽签法/随机数法"},{"key":"B","text":"按成绩排"},{"key":"C","text":"按学号奇偶"},{"key":"D","text":"按班级分层"}]','A','简单随机抽样：抽签法、随机数法','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0122-1','math','高中',14,'hs-kp-0122','single_choice',0.55,'样本容量越大，估计总体的误差通常？','[{"key":"A","text":"越小"},{"key":"B","text":"越大"},{"key":"C","text":"不变"},{"key":"D","text":"不确定"}]','A','大数定律：样本越大估计越准','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0123-1','math','高中',14,'hs-kp-0123','single_choice',0.65,'整理数据时，常用图表不包括？','[{"key":"A","text":"立体透视模型"},{"key":"B","text":"频率分布直方图"},{"key":"C","text":"茎叶图"},{"key":"D","text":"折线图"}]','A','统计图表：直方图、茎叶图、折线图等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0124-1','math','高中',14,'hs-kp-0124','single_choice',0.75,'用样本估计总体的思想称为？','[{"key":"A","text":"用样本估计总体"},{"key":"B","text":"精确计算"},{"key":"C","text":"主观臆断"},{"key":"D","text":"枚举所有"}]','A','统计核心思想：样本估计总体','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0125-1','math','高中',14,'hs-kp-0125','single_choice',0.35,'数据 1,4,2,5,4 的中位数 = ？','[{"key":"A","text":"4"},{"key":"B","text":"1"},{"key":"C","text":"5"},{"key":"D","text":"3.2"}]','A','排序后 1,2,4,4,5，中位数=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0126-1','math','高中',14,'hs-kp-0126','single_choice',0.45,'能同时看数据分布和原始数值的图表是？','[{"key":"A","text":"茎叶图"},{"key":"B","text":"饼图"},{"key":"C","text":"条形图"},{"key":"D","text":"折线图"}]','A','茎叶图保留原始数据','template-hs','approved','通用');