-- ============================================================
-- 第3章 函数的概念与性质 补题（13学期, 知识点 31-48）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0031-1','math','高中',13,'hs-kp-0031','single_choice',0.45,'函数 f(x)=√(x-9) 的定义域是？','[{"key":"A","text":"x≥9"},{"key":"B","text":"x>9"},{"key":"C","text":"x≤9"},{"key":"D","text":"x≠9"}]','A','偶次根式非负：x-9≥0 → x≥9','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0031-2','math','高中',13,'hs-kp-0031','single_choice',0.45,'函数 f(x)=√(x-7) 的定义域是？','[{"key":"A","text":"x≥7"},{"key":"B","text":"x>7"},{"key":"C","text":"x≤7"},{"key":"D","text":"x≠7"}]','A','偶次根式非负：x-7≥0 → x≥7','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0031-3','math','高中',13,'hs-kp-0031','single_choice',0.45,'函数 f(x)=√(x-8) 的定义域是？','[{"key":"A","text":"x≥8"},{"key":"B","text":"x>8"},{"key":"C","text":"x≤8"},{"key":"D","text":"x≠8"}]','A','偶次根式非负：x-8≥0 → x≥8','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0032-1','math','高中',13,'hs-kp-0032','single_choice',0.55,'f(x+1) 定义域为 [-1,1]，则 f(x) 定义域？','[{"key":"A","text":"[0,2]"},{"key":"B","text":"[-1,1]"},{"key":"C","text":"[-0,0]"},{"key":"D","text":"[1,3]"}]','A','令 t=x+1，t∈[-2,2]','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0032-2','math','高中',13,'hs-kp-0032','single_choice',0.55,'f(x+1) 定义域为 [-3,3]，则 f(x) 定义域？','[{"key":"A","text":"[-2,4]"},{"key":"B","text":"[-3,3]"},{"key":"C","text":"[-2,2]"},{"key":"D","text":"[3,5]"}]','A','令 t=x+1，t∈[-4,4]','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0032-3','math','高中',13,'hs-kp-0032','single_choice',0.55,'f(x+1) 定义域为 [-4,4]，则 f(x) 定义域？','[{"key":"A","text":"[-3,5]"},{"key":"B","text":"[-4,4]"},{"key":"C","text":"[-3,3]"},{"key":"D","text":"[4,6]"}]','A','令 t=x+1，t∈[-5,5]','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0033-1','math','高中',13,'hs-kp-0033','single_choice',0.65,'f(x)=x²-4x+4 在 [1,4] 单调性？','[{"key":"A","text":"先减后增"},{"key":"B","text":"先增后减"},{"key":"C","text":"单调递增"},{"key":"D","text":"单调递减"}]','A','对称轴 x=4/2 ∈ [1,4] → 先减后增','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0033-2','math','高中',13,'hs-kp-0033','single_choice',0.65,'f(x)=x²-6x+1 在 [1,6] 单调性？','[{"key":"A","text":"先减后增"},{"key":"B","text":"先增后减"},{"key":"C","text":"单调递增"},{"key":"D","text":"单调递减"}]','A','对称轴 x=6/2 ∈ [1,6] → 先减后增','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0033-3','math','高中',13,'hs-kp-0033','single_choice',0.65,'f(x)=x²-6x+2 在 [1,6] 单调性？','[{"key":"A","text":"先减后增"},{"key":"B","text":"先增后减"},{"key":"C","text":"单调递增"},{"key":"D","text":"单调递减"}]','A','对称轴 x=6/2 ∈ [1,6] → 先减后增','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0034-1','math','高中',13,'hs-kp-0034','single_choice',0.75,'若 y=f(u) 增，u=x² 在 (0,+∞) 减，则 y=f(x²) 在 (0,+∞) 单调？','[{"key":"A","text":"递减"},{"key":"B","text":"递增"},{"key":"C","text":"不单调"},{"key":"D","text":"无法确定"}]','A','同增异减：外层增内层减 → 复合减','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0034-2','math','高中',13,'hs-kp-0034','single_choice',0.75,'若 y=f(u) 增，u=-x 在 (0,+∞) 减，则 y=f(-x) 在 (0,+∞) 单调？','[{"key":"A","text":"递减"},{"key":"B","text":"递增"},{"key":"C","text":"不单调"},{"key":"D","text":"无法确定"}]','A','同增异减：外层增内层减 → 复合减','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0034-3','math','高中',13,'hs-kp-0034','single_choice',0.75,'若 y=f(u) 增，u=2x 在 (0,+∞) 减，则 y=f(2x) 在 (0,+∞) 单调？','[{"key":"A","text":"递减"},{"key":"B","text":"递增"},{"key":"C","text":"不单调"},{"key":"D","text":"无法确定"}]','A','同增异减：外层增内层减 → 复合减','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0035-1','math','高中',13,'hs-kp-0035','single_choice',0.35,'若 f 与 g 均在 R 上递增，则 f+g 单调？','[{"key":"A","text":"递增"},{"key":"B","text":"递减"},{"key":"C","text":"不单调"},{"key":"D","text":"无法判断"}]','A','增+增=增','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0035-2','math','高中',13,'hs-kp-0035','single_choice',0.35,'若 f 与 g 均在 R 上递增，则 f+g 单调？','[{"key":"D","text":"无法判断"},{"key":"A","text":"递增"},{"key":"B","text":"递减"},{"key":"C","text":"不单调"}]','A','增+增=增','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0035-3','math','高中',13,'hs-kp-0035','single_choice',0.35,'若 f 与 g 均在 R 上递增，则 f+g 单调？','[{"key":"A","text":"递增"},{"key":"D","text":"无法判断"},{"key":"C","text":"不单调"},{"key":"B","text":"递减"}]','A','增+增=增','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0036-1','math','高中',13,'hs-kp-0036','single_choice',0.45,'y=f(x) 右移 1 上移 5 → ?','[{"key":"A","text":"y=f(x-1)+5"},{"key":"B","text":"y=f(x+1)+5"},{"key":"C","text":"y=f(x-1)-5"},{"key":"D","text":"y=f(x+1)-5"}]','A','左加右减、上加下减','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0036-2','math','高中',13,'hs-kp-0036','single_choice',0.45,'y=f(x) 右移 4 上移 2 → ?','[{"key":"A","text":"y=f(x-4)+2"},{"key":"B","text":"y=f(x+4)+2"},{"key":"C","text":"y=f(x-4)-2"},{"key":"D","text":"y=f(x+4)-2"}]','A','左加右减、上加下减','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0036-3','math','高中',13,'hs-kp-0036','single_choice',0.45,'y=f(x) 右移 2 上移 4 → ?','[{"key":"A","text":"y=f(x-2)+4"},{"key":"B","text":"y=f(x+2)+4"},{"key":"C","text":"y=f(x-2)-4"},{"key":"D","text":"y=f(x+2)-4"}]','A','左加右减、上加下减','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0037-1','math','高中',13,'hs-kp-0037','single_choice',0.55,'y=f(x) 纵坐标伸长为 4 倍 → ?','[{"key":"A","text":"y=4f(x)"},{"key":"B","text":"y=f(4x)"},{"key":"C","text":"y=f(x)/4"},{"key":"D","text":"y=f(x+4)"}]','A','纵伸改变函数值：y=4f(x)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0037-2','math','高中',13,'hs-kp-0037','single_choice',0.55,'y=f(x) 纵坐标伸长为 3 倍 → ?','[{"key":"A","text":"y=3f(x)"},{"key":"B","text":"y=f(3x)"},{"key":"C","text":"y=f(x)/3"},{"key":"D","text":"y=f(x+3)"}]','A','纵伸改变函数值：y=3f(x)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0037-3','math','高中',13,'hs-kp-0037','single_choice',0.55,'y=f(x) 纵坐标伸长为 4 倍 → ?','[{"key":"D","text":"y=f(x+4)"},{"key":"C","text":"y=f(x)/4"},{"key":"B","text":"y=f(4x)"},{"key":"A","text":"y=4f(x)"}]','A','纵伸改变函数值：y=4f(x)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0038-1','math','高中',13,'hs-kp-0038','single_choice',0.65,'y=f(x) 关于 x 轴对称翻折 → ?','[{"key":"A","text":"y=-f(x)"},{"key":"B","text":"y=f(-x)"},{"key":"C","text":"y=|f(x)|"},{"key":"D","text":"y=f(|x|)"}]','A','关于 x 轴对称：y→-y','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0038-2','math','高中',13,'hs-kp-0038','single_choice',0.65,'y=f(x) 关于 x 轴对称翻折 → ?','[{"key":"A","text":"y=-f(x)"},{"key":"D","text":"y=f(|x|)"},{"key":"B","text":"y=f(-x)"},{"key":"C","text":"y=|f(x)|"}]','A','关于 x 轴对称：y→-y','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0038-3','math','高中',13,'hs-kp-0038','single_choice',0.65,'y=f(x) 关于 x 轴对称翻折 → ?','[{"key":"D","text":"y=f(|x|)"},{"key":"C","text":"y=|f(x)|"},{"key":"B","text":"y=f(-x)"},{"key":"A","text":"y=-f(x)"}]','A','关于 x 轴对称：y→-y','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0039-1','math','高中',13,'hs-kp-0039','single_choice',0.75,'f(x)=2x²+1 是？','[{"key":"A","text":"偶函数"},{"key":"B","text":"奇函数"},{"key":"C","text":"非奇非偶"},{"key":"D","text":"既是奇又是偶"}]','A','f(-x)=2x²+1=f(x) → 偶函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0039-2','math','高中',13,'hs-kp-0039','single_choice',0.75,'f(x)=5x²+1 是？','[{"key":"A","text":"偶函数"},{"key":"B","text":"奇函数"},{"key":"C","text":"非奇非偶"},{"key":"D","text":"既是奇又是偶"}]','A','f(-x)=5x²+1=f(x) → 偶函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0039-3','math','高中',13,'hs-kp-0039','single_choice',0.75,'f(x)=4x²+1 是？','[{"key":"A","text":"偶函数"},{"key":"B","text":"奇函数"},{"key":"C","text":"非奇非偶"},{"key":"D","text":"既是奇又是偶"}]','A','f(-x)=4x²+1=f(x) → 偶函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0040-1','math','高中',13,'hs-kp-0040','single_choice',0.35,'f(x)=1x³ 是？','[{"key":"A","text":"奇函数"},{"key":"B","text":"偶函数"},{"key":"C","text":"非奇非偶"},{"key":"D","text":"既是奇又是偶"}]','A','f(-x)=-1x³=-f(x) → 奇函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0040-2','math','高中',13,'hs-kp-0040','single_choice',0.35,'f(x)=5x³ 是？','[{"key":"A","text":"奇函数"},{"key":"B","text":"偶函数"},{"key":"C","text":"非奇非偶"},{"key":"D","text":"既是奇又是偶"}]','A','f(-x)=-5x³=-f(x) → 奇函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0040-3','math','高中',13,'hs-kp-0040','single_choice',0.35,'f(x)=4x³ 是？','[{"key":"A","text":"奇函数"},{"key":"B","text":"偶函数"},{"key":"C","text":"非奇非偶"},{"key":"D","text":"既是奇又是偶"}]','A','f(-x)=-4x³=-f(x) → 奇函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0041-1','math','高中',13,'hs-kp-0041','single_choice',0.45,'奇函数 + 偶函数 = ?','[{"key":"A","text":"一般非奇非偶"},{"key":"B","text":"必为奇函数"},{"key":"C","text":"必为偶函数"},{"key":"D","text":"必为常函数"}]','A','奇+偶一般不具奇偶性','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0041-2','math','高中',13,'hs-kp-0041','single_choice',0.45,'奇函数 + 偶函数 = ?','[{"key":"D","text":"必为常函数"},{"key":"C","text":"必为偶函数"},{"key":"B","text":"必为奇函数"},{"key":"A","text":"一般非奇非偶"}]','A','奇+偶一般不具奇偶性','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0041-3','math','高中',13,'hs-kp-0041','single_choice',0.45,'奇函数 + 偶函数 = ?','[{"key":"A","text":"一般非奇非偶"},{"key":"D","text":"必为常函数"},{"key":"B","text":"必为奇函数"},{"key":"C","text":"必为偶函数"}]','A','奇+偶一般不具奇偶性','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0042-1','math','高中',13,'hs-kp-0042','single_choice',0.55,'f 奇、g 偶，则 f(g(x)) 是？','[{"key":"A","text":"偶函数"},{"key":"B","text":"奇函数"},{"key":"C","text":"非奇非偶"},{"key":"D","text":"无法判断"}]','A','f(g(-x))=f(g(x)) → 偶函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0042-2','math','高中',13,'hs-kp-0042','single_choice',0.55,'f 奇、g 偶，则 f(g(x)) 是？','[{"key":"B","text":"奇函数"},{"key":"A","text":"偶函数"},{"key":"C","text":"非奇非偶"},{"key":"D","text":"无法判断"}]','A','f(g(-x))=f(g(x)) → 偶函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0043-1','math','高中',13,'hs-kp-0043','single_choice',0.65,'下列为常见奇函数的是？','[{"key":"A","text":"y=x³"},{"key":"B","text":"y=x²"},{"key":"C","text":"y=|x|"},{"key":"D","text":"y=cos x"}]','A','奇次幂函数为奇函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0043-2','math','高中',13,'hs-kp-0043','single_choice',0.65,'下列为常见奇函数的是？','[{"key":"A","text":"y=x³"},{"key":"D","text":"y=cos x"},{"key":"B","text":"y=x²"},{"key":"C","text":"y=|x|"}]','A','奇次幂函数为奇函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0043-3','math','高中',13,'hs-kp-0043','single_choice',0.65,'下列为常见奇函数的是？','[{"key":"D","text":"y=cos x"},{"key":"A","text":"y=x³"},{"key":"B","text":"y=x²"},{"key":"C","text":"y=|x|"}]','A','奇次幂函数为奇函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0044-1','math','高中',13,'hs-kp-0044','single_choice',0.75,'下列为常见偶函数的是？','[{"key":"A","text":"y=x²"},{"key":"B","text":"y=x³"},{"key":"C","text":"y=x"},{"key":"D","text":"y=1/x"}]','A','偶次幂函数为偶函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0044-2','math','高中',13,'hs-kp-0044','single_choice',0.75,'下列为常见偶函数的是？','[{"key":"D","text":"y=1/x"},{"key":"A","text":"y=x²"},{"key":"B","text":"y=x³"},{"key":"C","text":"y=x"}]','A','偶次幂函数为偶函数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0045-1','math','高中',13,'hs-kp-0045','single_choice',0.35,'f(x+3)=f(x) 恒成立，周期为？','[{"key":"A","text":"3"},{"key":"B","text":"6"},{"key":"C","text":"1"},{"key":"D","text":"0"}]','A','由定义，3 是周期','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0045-2','math','高中',13,'hs-kp-0045','single_choice',0.35,'f(x+6)=f(x) 恒成立，周期为？','[{"key":"A","text":"6"},{"key":"B","text":"12"},{"key":"C","text":"1"},{"key":"D","text":"0"}]','A','由定义，6 是周期','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0045-3','math','高中',13,'hs-kp-0045','single_choice',0.35,'f(x+5)=f(x) 恒成立，周期为？','[{"key":"A","text":"5"},{"key":"B","text":"10"},{"key":"C","text":"1"},{"key":"D","text":"0"}]','A','由定义，5 是周期','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0046-1','math','高中',13,'hs-kp-0046','single_choice',0.45,'f(2+x)=f(2-x) 恒成立 → 关于？对称','[{"key":"A","text":"直线 x=2"},{"key":"B","text":"y 轴"},{"key":"C","text":"直线 x=-2"},{"key":"D","text":"x 轴"}]','A','关于直线 x=2 对称','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0046-2','math','高中',13,'hs-kp-0046','single_choice',0.45,'f(1+x)=f(1-x) 恒成立 → 关于？对称','[{"key":"A","text":"直线 x=1"},{"key":"B","text":"y 轴"},{"key":"C","text":"直线 x=-1"},{"key":"D","text":"x 轴"}]','A','关于直线 x=1 对称','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0046-3','math','高中',13,'hs-kp-0046','single_choice',0.45,'f(3+x)=f(3-x) 恒成立 → 关于？对称','[{"key":"A","text":"直线 x=3"},{"key":"B","text":"y 轴"},{"key":"C","text":"直线 x=-3"},{"key":"D","text":"x 轴"}]','A','关于直线 x=3 对称','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0047-1','math','高中',13,'hs-kp-0047','single_choice',0.55,'f(3+x)+f(3-x)=2b → 关于？对称','[{"key":"A","text":"点 (3,b) 中心对称"},{"key":"B","text":"直线 x=3"},{"key":"C","text":"点 (b,3)"},{"key":"D","text":"y 轴"}]','A','关于点 (3,b) 中心对称','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0047-2','math','高中',13,'hs-kp-0047','single_choice',0.55,'f(2+x)+f(2-x)=2b → 关于？对称','[{"key":"A","text":"点 (2,b) 中心对称"},{"key":"B","text":"直线 x=2"},{"key":"C","text":"点 (b,2)"},{"key":"D","text":"y 轴"}]','A','关于点 (2,b) 中心对称','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0047-3','math','高中',13,'hs-kp-0047','single_choice',0.55,'f(4+x)+f(4-x)=2b → 关于？对称','[{"key":"A","text":"点 (4,b) 中心对称"},{"key":"B","text":"直线 x=4"},{"key":"C","text":"点 (b,4)"},{"key":"D","text":"y 轴"}]','A','关于点 (4,b) 中心对称','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0048-1','math','高中',13,'hs-kp-0048','single_choice',0.65,'f 周期 2 且关于 x=1 对称 → 新周期为？','[{"key":"A","text":"4"},{"key":"B","text":"2"},{"key":"C","text":"3"},{"key":"D","text":"2"}]','A','有对称轴的周期函数存在半周期对称，2T 必为周期','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0048-2','math','高中',13,'hs-kp-0048','single_choice',0.65,'f 周期 3 且关于 x=2 对称 → 新周期为？','[{"key":"A","text":"6"},{"key":"B","text":"3"},{"key":"C","text":"5"},{"key":"D","text":"4"}]','A','有对称轴的周期函数存在半周期对称，2T 必为周期','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0048-3','math','高中',13,'hs-kp-0048','single_choice',0.65,'f 周期 2 且关于 x=3 对称 → 新周期为？','[{"key":"A","text":"4"},{"key":"B","text":"2"},{"key":"C","text":"5"},{"key":"D","text":"6"}]','A','有对称轴的周期函数存在半周期对称，2T 必为周期','template-hs','approved','通用');