-- ============================================================
-- 第14章 数列 补题（16学期, 知识点 187-198）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0187-1','math','高中',16,'hs-kp-0187','single_choice',0.55,'Sₙ=2n²+n，则 a₁ = S₁ = ？','[{"key":"A","text":"3"},{"key":"B","text":"2"},{"key":"C","text":"4"},{"key":"D","text":"1"}]','A','a₁=S₁=2×1+1=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0187-2','math','高中',16,'hs-kp-0187','single_choice',0.55,'Sₙ=5n²+n，则 a₁ = S₁ = ？','[{"key":"A","text":"6"},{"key":"B","text":"5"},{"key":"C","text":"10"},{"key":"D","text":"1"}]','A','a₁=S₁=5×1+1=6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0187-3','math','高中',16,'hs-kp-0187','single_choice',0.55,'Sₙ=3n²+n，则 a₁ = S₁ = ？','[{"key":"A","text":"4"},{"key":"B","text":"3"},{"key":"C","text":"6"},{"key":"D","text":"1"}]','A','a₁=S₁=3×1+1=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0188-1','math','高中',16,'hs-kp-0188','single_choice',0.65,'等差数列 a₁=3，d=3，a6 = ？','[{"key":"A","text":"18"},{"key":"B","text":"21"},{"key":"C","text":"3"},{"key":"D","text":"21"}]','A','aₙ=a₁+(n-1)d=3+(6-1)×3=18','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0188-2','math','高中',16,'hs-kp-0188','single_choice',0.65,'等差数列 a₁=1，d=3，a7 = ？','[{"key":"A","text":"19"},{"key":"B","text":"22"},{"key":"C","text":"1"},{"key":"D","text":"22"}]','A','aₙ=a₁+(n-1)d=1+(7-1)×3=19','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0188-3','math','高中',16,'hs-kp-0188','single_choice',0.65,'等差数列 a₁=3，d=2，a7 = ？','[{"key":"A","text":"15"},{"key":"B","text":"17"},{"key":"C","text":"3"},{"key":"D","text":"17"}]','A','aₙ=a₁+(n-1)d=3+(7-1)×2=15','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0189-1','math','高中',16,'hs-kp-0189','single_choice',0.75,'等比数列 a₁=1，q=3，a5 = ？','[{"key":"A","text":"81"},{"key":"B","text":"243"},{"key":"C","text":"13"},{"key":"D","text":"1"}]','A','aₙ=a₁qⁿ⁻¹=1×3^4=81','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0189-2','math','高中',16,'hs-kp-0189','single_choice',0.75,'等比数列 a₁=1，q=2，a3 = ？','[{"key":"A","text":"4"},{"key":"B","text":"8"},{"key":"C","text":"5"},{"key":"D","text":"1"}]','A','aₙ=a₁qⁿ⁻¹=1×2^2=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0189-3','math','高中',16,'hs-kp-0189','single_choice',0.75,'等比数列 a₁=2，q=3，a5 = ？','[{"key":"A","text":"162"},{"key":"B","text":"486"},{"key":"C","text":"14"},{"key":"D","text":"2"}]','A','aₙ=a₁qⁿ⁻¹=2×3^4=162','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0190-1','math','高中',16,'hs-kp-0190','single_choice',0.35,'等差数列 a₁=4，d=3，S5 = ？','[{"key":"A","text":"50"},{"key":"B","text":"55"},{"key":"C","text":"20"},{"key":"D","text":"47"}]','A','Sₙ=na₁+n(n-1)d/2=5×4+5×4×3/2=50','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0190-2','math','高中',16,'hs-kp-0190','single_choice',0.35,'等差数列 a₁=4，d=2，S5 = ？','[{"key":"A","text":"40"},{"key":"B","text":"45"},{"key":"C","text":"20"},{"key":"D","text":"38"}]','A','Sₙ=na₁+n(n-1)d/2=5×4+5×4×2/2=40','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0190-3','math','高中',16,'hs-kp-0190','single_choice',0.35,'等差数列 a₁=3，d=2，S8 = ？','[{"key":"A","text":"80"},{"key":"B","text":"88"},{"key":"C","text":"24"},{"key":"D","text":"78"}]','A','Sₙ=na₁+n(n-1)d/2=8×3+8×7×2/2=80','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0191-1','math','高中',16,'hs-kp-0191','single_choice',0.45,'等比数列 a₁=2，q=3，S3 = ？','[{"key":"A","text":"26"},{"key":"B","text":"6"},{"key":"C","text":"78"},{"key":"D","text":"6"}]','A','Sₙ=a₁(1-qⁿ)/(1-q)=2×(1-3^3)/(1-3)=26','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0191-2','math','高中',16,'hs-kp-0191','single_choice',0.45,'等比数列 a₁=3，q=3，S5 = ？','[{"key":"A","text":"363"},{"key":"B","text":"15"},{"key":"C","text":"1089"},{"key":"D","text":"9"}]','A','Sₙ=a₁(1-qⁿ)/(1-q)=3×(1-3^5)/(1-3)=363','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0191-3','math','高中',16,'hs-kp-0191','single_choice',0.45,'等比数列 a₁=1，q=2，S5 = ？','[{"key":"A","text":"31"},{"key":"B","text":"5"},{"key":"C","text":"62"},{"key":"D","text":"2"}]','A','Sₙ=a₁(1-qⁿ)/(1-q)=1×(1-2^5)/(1-2)=31','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0192-1','math','高中',16,'hs-kp-0192','single_choice',0.55,'5 与 3 的等差中项 = ？','[{"key":"A","text":"4"},{"key":"B","text":"8"},{"key":"C","text":"15"},{"key":"D","text":"3.872983346207417"}]','A','等差中项=(5+3)/2=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0192-2','math','高中',16,'hs-kp-0192','single_choice',0.55,'3 与 3 的等差中项 = ？','[{"key":"A","text":"3"},{"key":"B","text":"6"},{"key":"C","text":"9"},{"key":"D","text":"3"}]','A','等差中项=(3+3)/2=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0192-3','math','高中',16,'hs-kp-0192','single_choice',0.55,'2 与 4 的等差中项 = ？','[{"key":"A","text":"3"},{"key":"B","text":"6"},{"key":"C","text":"8"},{"key":"D","text":"2.8284271247461903"}]','A','等差中项=(2+4)/2=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0193-1','math','高中',16,'hs-kp-0193','single_choice',0.65,'等差数列 a₁=3，d=3，a₂+a₅ = ？','[{"key":"A","text":"21"},{"key":"B","text":"6"},{"key":"C","text":"15"},{"key":"D","text":"6"}]','A','a₂=6，a₅=15，和=21','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0193-2','math','高中',16,'hs-kp-0193','single_choice',0.65,'等差数列 a₁=3，d=4，a₂+a₅ = ？','[{"key":"A","text":"26"},{"key":"B","text":"6"},{"key":"C","text":"19"},{"key":"D","text":"7"}]','A','a₂=7，a₅=19，和=26','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0193-3','math','高中',16,'hs-kp-0193','single_choice',0.65,'等差数列 a₁=4，d=3，a₂+a₅ = ？','[{"key":"A","text":"23"},{"key":"B","text":"8"},{"key":"C","text":"16"},{"key":"D","text":"7"}]','A','a₂=7，a₅=16，和=23','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0194-1','math','高中',16,'hs-kp-0194','single_choice',0.75,'等比数列 a₁=5，q=3，a₃ = ？','[{"key":"A","text":"45"},{"key":"B","text":"15"},{"key":"C","text":"11"},{"key":"D","text":"5"}]','A','a₃=a₁q²=5×3²=45','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0194-2','math','高中',16,'hs-kp-0194','single_choice',0.75,'等比数列 a₁=3，q=2，a₃ = ？','[{"key":"A","text":"12"},{"key":"B","text":"6"},{"key":"C","text":"7"},{"key":"D","text":"3"}]','A','a₃=a₁q²=3×2²=12','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0194-3','math','高中',16,'hs-kp-0194','single_choice',0.75,'等比数列 a₁=5，q=2，a₃ = ？','[{"key":"A","text":"20"},{"key":"B","text":"10"},{"key":"C","text":"9"},{"key":"D","text":"5"}]','A','a₃=a₁q²=5×2²=20','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0195-1','math','高中',16,'hs-kp-0195','single_choice',0.35,'数列 {n·2ⁿ} 前 n 项和常用？求和法','[{"key":"A","text":"错位相减法"},{"key":"B","text":"裂项相消法"},{"key":"C","text":"累加法"},{"key":"D","text":"累乘法"}]','A','等差×等比 → 错位相减','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0195-2','math','高中',16,'hs-kp-0195','single_choice',0.35,'数列 {n·2ⁿ} 前 n 项和常用？求和法','[{"key":"D","text":"累乘法"},{"key":"C","text":"累加法"},{"key":"B","text":"裂项相消法"},{"key":"A","text":"错位相减法"}]','A','等差×等比 → 错位相减','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0196-1','math','高中',16,'hs-kp-0196','single_choice',0.45,'1/(1×2)+1/(2×3)+...+1/(n×(n+1)) = n/(n+1)，n=5 → ？','[{"key":"A","text":"5/6"},{"key":"B","text":"1.2"},{"key":"C","text":"5"},{"key":"D","text":"1/5"}]','A','裂项相消：1/k-1/(k+1)，和=5/6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0196-2','math','高中',16,'hs-kp-0196','single_choice',0.45,'1/(1×2)+1/(2×3)+...+1/(n×(n+1)) = n/(n+1)，n=6 → ？','[{"key":"A","text":"6/7"},{"key":"B","text":"1.1666666666666667"},{"key":"C","text":"6"},{"key":"D","text":"1/6"}]','A','裂项相消：1/k-1/(k+1)，和=6/7','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0196-3','math','高中',16,'hs-kp-0196','single_choice',0.45,'1/(1×2)+1/(2×3)+...+1/(n×(n+1)) = n/(n+1)，n=3 → ？','[{"key":"A","text":"3/4"},{"key":"B","text":"1.3333333333333333"},{"key":"C","text":"3"},{"key":"D","text":"1/3"}]','A','裂项相消：1/k-1/(k+1)，和=3/4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0197-1','math','高中',16,'hs-kp-0197','single_choice',0.55,'aₙ-aₙ₋₁=n，a₁=1，则 a3 = 1+2+...+3 = ？','[{"key":"A","text":"6"},{"key":"B","text":"3"},{"key":"C","text":"9"},{"key":"D","text":"4"}]','A','累加法：aₙ=1+2+...+n=6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0197-2','math','高中',16,'hs-kp-0197','single_choice',0.55,'aₙ-aₙ₋₁=n，a₁=1，则 a4 = 1+2+...+4 = ？','[{"key":"A","text":"10"},{"key":"B","text":"4"},{"key":"C","text":"16"},{"key":"D","text":"5"}]','A','累加法：aₙ=1+2+...+n=10','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0197-3','math','高中',16,'hs-kp-0197','single_choice',0.55,'aₙ-aₙ₋₁=n，a₁=1，则 a3 = 1+2+...+3 = ？','[{"key":"A","text":"6"},{"key":"B","text":"3"},{"key":"D","text":"4"},{"key":"C","text":"9"}]','A','累加法：aₙ=1+2+...+n=6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0198-1','math','高中',16,'hs-kp-0198','single_choice',0.65,'aₙ/aₙ₋₁=n/(n-1)，a₁=1，则 a5 = ？','[{"key":"A","text":"5"},{"key":"B","text":"4"},{"key":"C","text":"25"},{"key":"D","text":"1"}]','A','累乘法：aₙ=a₁×2/1×3/2×...×n/(n-1)=5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0198-2','math','高中',16,'hs-kp-0198','single_choice',0.65,'aₙ/aₙ₋₁=n/(n-1)，a₁=1，则 a3 = ？','[{"key":"A","text":"3"},{"key":"B","text":"2"},{"key":"C","text":"9"},{"key":"D","text":"1"}]','A','累乘法：aₙ=a₁×2/1×3/2×...×n/(n-1)=3','template-hs','approved','通用');