-- ============================================================
-- 第5章 三角函数 补题（13学期, 知识点 63-72）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0063-1','math','高中',13,'hs-kp-0063','single_choice',0.65,'180° = ？弧度','[{"key":"A","text":"π"},{"key":"B","text":"180π/180"},{"key":"C","text":"π"},{"key":"D","text":"2π"}]','A','180° = 180×π/180 = π','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0063-2','math','高中',13,'hs-kp-0063','single_choice',0.65,'90° = ？弧度','[{"key":"A","text":"π/2"},{"key":"B","text":"90π/180"},{"key":"C","text":"π"},{"key":"D","text":"2π"}]','A','90° = 90×π/180 = π/2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0063-3','math','高中',13,'hs-kp-0063','single_choice',0.65,'270° = ？弧度','[{"key":"A","text":"3π/2"},{"key":"B","text":"270π/180"},{"key":"C","text":"π"},{"key":"D","text":"2π"}]','A','270° = 270×π/180 = 3π/2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0064-1','math','高中',13,'hs-kp-0064','single_choice',0.75,'半径 4、圆心角 45° 的弧长 l = ？','[{"key":"A","text":"4×π/4"},{"key":"B","text":"4"},{"key":"C","text":"180"},{"key":"D","text":"π"}]','A','l = rθ = 4×45°(弧度) = 4×π/4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0064-2','math','高中',13,'hs-kp-0064','single_choice',0.75,'半径 2、圆心角 90° 的弧长 l = ？','[{"key":"A","text":"2×π/2"},{"key":"B","text":"2"},{"key":"C","text":"180"},{"key":"D","text":"π"}]','A','l = rθ = 2×90°(弧度) = 2×π/2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0064-3','math','高中',13,'hs-kp-0064','single_choice',0.75,'半径 4、圆心角 30° 的弧长 l = ？','[{"key":"A","text":"4×π/6"},{"key":"B","text":"4"},{"key":"C","text":"120"},{"key":"D","text":"π"}]','A','l = rθ = 4×30°(弧度) = 4×π/6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0065-1','math','高中',13,'hs-kp-0065','single_choice',0.35,'角 α 终边过点 (3,5)，sinα = ？','[{"key":"A","text":"5/5.8309518948453"},{"key":"B","text":"3/5.8309518948453"},{"key":"C","text":"3/5"},{"key":"D","text":"5.8309518948453/5"}]','A','r=√(3²+5²)=5.8309518948453，sinα=y/r=5/5.8309518948453','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0065-2','math','高中',13,'hs-kp-0065','single_choice',0.35,'角 α 终边过点 (5,4)，sinα = ？','[{"key":"A","text":"4/6.4031242374328485"},{"key":"B","text":"5/6.4031242374328485"},{"key":"C","text":"5/4"},{"key":"D","text":"6.4031242374328485/4"}]','A','r=√(5²+4²)=6.4031242374328485，sinα=y/r=4/6.4031242374328485','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0065-3','math','高中',13,'hs-kp-0065','single_choice',0.35,'角 α 终边过点 (5,6)，sinα = ？','[{"key":"A","text":"6/7.810249675906656"},{"key":"B","text":"5/7.810249675906656"},{"key":"C","text":"5/6"},{"key":"D","text":"7.810249675906656/6"}]','A','r=√(5²+6²)=7.810249675906656，sinα=y/r=6/7.810249675906656','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0066-1','math','高中',13,'hs-kp-0066','single_choice',0.45,'角 α 在第二象限，sinα 的符号是？','[{"key":"A","text":"正"},{"key":"B","text":"负"},{"key":"C","text":"0"},{"key":"D","text":"不确定"}]','A','第二象限 sin>0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0067-1','math','高中',13,'hs-kp-0067','single_choice',0.55,'sinα=3/5，α 为锐角，则 cosα = ？','[{"key":"A","text":"4/5"},{"key":"B","text":"3/5"},{"key":"C","text":"5/4"},{"key":"D","text":"5/3"}]','A','cosα=√(1-sin²α)=√(1-9/25)=4/5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0067-2','math','高中',13,'hs-kp-0067','single_choice',0.55,'sinα=3/5，α 为锐角，则 cosα = ？','[{"key":"B","text":"3/5"},{"key":"A","text":"4/5"},{"key":"C","text":"5/4"},{"key":"D","text":"5/3"}]','A','cosα=√(1-sin²α)=√(1-9/25)=4/5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0067-3','math','高中',13,'hs-kp-0067','single_choice',0.55,'sinα=3/5，α 为锐角，则 cosα = ？','[{"key":"D","text":"5/3"},{"key":"A","text":"4/5"},{"key":"B","text":"3/5"},{"key":"C","text":"5/4"}]','A','cosα=√(1-sin²α)=√(1-9/25)=4/5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0068-1','math','高中',13,'hs-kp-0068','single_choice',0.65,'sin(210°) = ？','[{"key":"A","text":"-1/2"},{"key":"B","text":"1/2"},{"key":"C","text":"0"},{"key":"D","text":"1"}]','A','sin(210°)=-sin30°=-1/2（诱导公式）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0068-2','math','高中',13,'hs-kp-0068','single_choice',0.65,'sin(240°) = ？','[{"key":"A","text":"-√3/2"},{"key":"B","text":"√3/2"},{"key":"C","text":"0"},{"key":"D","text":"1"}]','A','sin(240°)=-sin60°=-√3/2（诱导公式）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0068-3','math','高中',13,'hs-kp-0068','single_choice',0.65,'sin(225°) = ？','[{"key":"A","text":"-√2/2"},{"key":"B","text":"√2/2"},{"key":"C","text":"0"},{"key":"D","text":"1"}]','A','sin(225°)=-sin45°=-√2/2（诱导公式）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0069-1','math','高中',13,'hs-kp-0069','single_choice',0.75,'函数 y=sin(1x) 的最小正周期 T = ？','[{"key":"A","text":"2π"},{"key":"B","text":"π"},{"key":"C","text":"2π"},{"key":"D","text":"4π"}]','A','T=2π/ω=2π/1=2π','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0069-2','math','高中',13,'hs-kp-0069','single_choice',0.75,'函数 y=sin(3x) 的最小正周期 T = ？','[{"key":"A","text":"2π/3"},{"key":"B","text":"π"},{"key":"C","text":"2π"},{"key":"D","text":"4π"}]','A','T=2π/ω=2π/3=2π/3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0069-3','math','高中',13,'hs-kp-0069','single_choice',0.75,'函数 y=sin(1x) 的最小正周期 T = ？','[{"key":"A","text":"2π"},{"key":"B","text":"π"},{"key":"D","text":"4π"},{"key":"C","text":"2π"}]','A','T=2π/ω=2π/1=2π','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0070-1','math','高中',13,'hs-kp-0070','single_choice',0.35,'y=sin x 图像横坐标缩短到 1/3 → y=？','[{"key":"A","text":"y=sin(3x)"},{"key":"B","text":"y=sin(x/3)"},{"key":"C","text":"y=3sin x"},{"key":"D","text":"y=sin(x+3)"}]','A','横缩：x→3x，即 y=sin(3x)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0070-2','math','高中',13,'hs-kp-0070','single_choice',0.35,'y=sin x 图像横坐标缩短到 1/4 → y=？','[{"key":"A","text":"y=sin(4x)"},{"key":"B","text":"y=sin(x/4)"},{"key":"C","text":"y=4sin x"},{"key":"D","text":"y=sin(x+4)"}]','A','横缩：x→4x，即 y=sin(4x)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0070-3','math','高中',13,'hs-kp-0070','single_choice',0.35,'y=sin x 图像横坐标缩短到 1/2 → y=？','[{"key":"A","text":"y=sin(2x)"},{"key":"B","text":"y=sin(x/2)"},{"key":"C","text":"y=2sin x"},{"key":"D","text":"y=sin(x+2)"}]','A','横缩：x→2x，即 y=sin(2x)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0071-1','math','高中',13,'hs-kp-0071','single_choice',0.45,'asin x + bcos x = R·sin(x+φ)，R = ？ (a=4,b=1)','[{"key":"A","text":"√17"},{"key":"B","text":"5"},{"key":"C","text":"4"},{"key":"D","text":"3"}]','A','R=√(a²+b²)=√(16+1)=√17','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0071-2','math','高中',13,'hs-kp-0071','single_choice',0.45,'asin x + bcos x = R·sin(x+φ)，R = ？ (a=2,b=2)','[{"key":"A","text":"√8"},{"key":"B","text":"4"},{"key":"C","text":"4"},{"key":"D","text":"0"}]','A','R=√(a²+b²)=√(4+4)=√8','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0071-3','math','高中',13,'hs-kp-0071','single_choice',0.45,'asin x + bcos x = R·sin(x+φ)，R = ？ (a=4,b=5)','[{"key":"A","text":"√41"},{"key":"B","text":"9"},{"key":"C","text":"20"},{"key":"D","text":"1"}]','A','R=√(a²+b²)=√(16+25)=√41','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0072-1','math','高中',13,'hs-kp-0072','single_choice',0.55,'sin60°cos30°+cos60°sin30° = sin90° = ？','[{"key":"A","text":"1"},{"key":"B","text":"0.5"},{"key":"C","text":"0"},{"key":"D","text":"2"}]','A','sin60°cos30°+cos60°sin30°=sin(60°+30°)=sin90°=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0072-2','math','高中',13,'hs-kp-0072','single_choice',0.55,'sin60°cos30°+cos60°sin30° = sin90° = ？','[{"key":"A","text":"1"},{"key":"D","text":"2"},{"key":"B","text":"0.5"},{"key":"C","text":"0"}]','A','sin60°cos30°+cos60°sin30°=sin(60°+30°)=sin90°=1','template-hs','approved','通用');