-- ============================================================
-- 第18章 成对数据的统计分析 补题（16学期, 知识点 239-252）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0239-1','math','高中',16,'hs-kp-0239','single_choice',0.75,'下列对「变量相关关系判断」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','变量相关关系判断是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0240-1','math','高中',16,'hs-kp-0240','single_choice',0.35,'下列对「散点图分析正负相关」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','散点图分析正负相关是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0241-1','math','高中',16,'hs-kp-0241','single_choice',0.45,'下列对「线性相关系数r」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','线性相关系数r是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0242-1','math','高中',16,'hs-kp-0242','single_choice',0.55,'下列对「相关系数强弱判定」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','相关系数强弱判定是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0243-1','math','高中',16,'hs-kp-0243','single_choice',0.65,'下列对「一元线性回归方程」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','一元线性回归方程是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0244-1','math','高中',16,'hs-kp-0244','single_choice',0.75,'下列对「回归直线过样本中心点」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','回归直线过样本中心点是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0245-1','math','高中',16,'hs-kp-0245','single_choice',0.35,'下列对「回归斜率几何意义」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','回归斜率几何意义是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0246-1','math','高中',16,'hs-kp-0246','single_choice',0.45,'下列对「残差定义与计算」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','残差定义与计算是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0247-1','math','高中',16,'hs-kp-0247','single_choice',0.55,'下列对「残差平方和」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','残差平方和是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0248-1','math','高中',16,'hs-kp-0248','single_choice',0.65,'下列对「拟合度（相关指数）」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','拟合度（相关指数）是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0249-1','math','高中',16,'hs-kp-0249','single_choice',0.75,'下列对「线性相关性综合判断」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','线性相关性综合判断是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0250-1','math','高中',16,'hs-kp-0250','single_choice',0.35,'下列对「2×2列联表」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','2×2列联表是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0251-1','math','高中',16,'hs-kp-0251','single_choice',0.45,'下列对「卡方χ²统计量计算」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','卡方χ²统计量计算是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0252-1','math','高中',16,'hs-kp-0252','single_choice',0.55,'下列对「独立性检验临界值判定」的理解正确的是？','[{"key":"A","text":"它属于成对数据的统计分析的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','独立性检验临界值判定是成对数据的统计分析（第18章）的正式知识点','template-hs','approved','通用');