-- ============================================================
-- 第6章 平面向量及其应用 补题（14学期, 知识点 73-87）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0073-1','math','高中',14,'hs-kp-0073','single_choice',0.65,'a=(4,4)，b=(1,2)，a+b = ？','[{"key":"A","text":"(5,6)"},{"key":"B","text":"(3,2)"},{"key":"C","text":"(4,2)"},{"key":"D","text":"(1,4)"}]','A','向量加法坐标相加：(5,6)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0074-1','math','高中',14,'hs-kp-0074','single_choice',0.75,'a=(3,5)，b=(4,4)，a-b = ？','[{"key":"A","text":"(-1,1)"},{"key":"B","text":"(7,9)"},{"key":"C","text":"(3,4)"},{"key":"D","text":"(4,5)"}]','A','向量减法坐标相减：(-1,1)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0075-1','math','高中',14,'hs-kp-0075','single_choice',0.35,'a=(1,2)，b=(3,6)，则 a 与 b？','[{"key":"A","text":"平行"},{"key":"B","text":"垂直"},{"key":"C","text":"夹角60°"},{"key":"D","text":"夹角30°"}]','A','b=3a → 共线平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0076-1','math','高中',14,'hs-kp-0076','single_choice',0.45,'a=(4,2)，b=(2,-4)，则 a·b = ？','[{"key":"A","text":"0"},{"key":"B","text":"8"},{"key":"C","text":"4"},{"key":"D","text":"2"}]','A','a·b=4×2+2×(-4)=0=0 → 垂直','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0077-1','math','高中',14,'hs-kp-0077','single_choice',0.55,'a=(4,3)，b=(4,4)，a·b = ？','[{"key":"A","text":"28"},{"key":"B","text":"16"},{"key":"C","text":"12"},{"key":"D","text":"16"}]','A','a·b=4×4+3×4=28','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0078-1','math','高中',14,'hs-kp-0078','single_choice',0.65,'a=(5,4)，|a| = ？','[{"key":"A","text":"6.4031242374328485"},{"key":"B","text":"9"},{"key":"C","text":"20"},{"key":"D","text":"4.47213595499958"}]','A','|a|=√(5²+4²)=6.4031242374328485','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0079-1','math','高中',14,'hs-kp-0079','single_choice',0.75,'a=(2,0)，b=(2,2)，b 在 a 上的投影 = ？','[{"key":"A","text":"2"},{"key":"B","text":"2"},{"key":"C","text":"2"},{"key":"D","text":"0"}]','A','投影 = b·a/|a| = 2×2/2 = 2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0080-1','math','高中',14,'hs-kp-0080','single_choice',0.35,'a=(1,1)，b=(1,0)，a 与 b 夹角 = ？','[{"key":"A","text":"60°"},{"key":"B","text":"30°"},{"key":"C","text":"120°"},{"key":"D","text":"180°"}]','A','cosθ=a·b/(|a||b|)=1/2.0000000000000004=0.50 → 夹角60°','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0081-1','math','高中',14,'hs-kp-0081','single_choice',0.45,'a=(3,3)，a 的单位向量 = ？','[{"key":"A","text":"(3/4.242640687119286,3/4.242640687119286)"},{"key":"B","text":"(4.242640687119286/3,4.242640687119286/3)"},{"key":"C","text":"(3,3)"},{"key":"D","text":"(3,3)"}]','A','e = a/|a| = (3/4.242640687119286,3/4.242640687119286)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0082-1','math','高中',14,'hs-kp-0082','single_choice',0.55,'A(1,0)，B(2,0)，C(4,0)，则 A、B、C？','[{"key":"A","text":"三点共线"},{"key":"B","text":"构成三角形"},{"key":"C","text":"互不相关"},{"key":"D","text":"构成矩形"}]','A','三点纵坐标均为 0，在 x 轴上 → 共线','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0083-1','math','高中',14,'hs-kp-0083','single_choice',0.65,'△ABC 重心 G 满足 GA+GB+GC = ？','[{"key":"A","text":"0"},{"key":"B","text":"AB"},{"key":"C","text":"AC"},{"key":"D","text":"BC"}]','A','重心性质：三条中线交点，GA+GB+GC=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0084-1','math','高中',14,'hs-kp-0084','single_choice',0.75,'△ABC 中 a=2，∠A=30°，∠B=60°，则 b = ？','[{"key":"A","text":"3.4641016151377544"},{"key":"B","text":"1"},{"key":"C","text":"4"},{"key":"D","text":"1.3333333333333333"}]','A','正弦定理 b/sin60°=a/sin30° → b=2√3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0085-1','math','高中',14,'hs-kp-0085','single_choice',0.35,'△ABC 中 a=3，b=4，∠C=90°，c = ？','[{"key":"A","text":"5"},{"key":"B","text":"7"},{"key":"C","text":"12"},{"key":"D","text":"6"}]','A','余弦定理 c²=a²+b²=25=25 → c=5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0086-1','math','高中',14,'hs-kp-0086','single_choice',0.45,'△ABC 中 ∠C=90°，a=4，b=5，面积 S = ？','[{"key":"A","text":"10"},{"key":"B","text":"20"},{"key":"C","text":"9"},{"key":"D","text":"5"}]','A','S=½ab=½×4×5=10','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0087-1','math','高中',14,'hs-kp-0087','single_choice',0.55,'△ABC 中 a=6，b=6，∠C=60°，c² = ？','[{"key":"A","text":"36"},{"key":"B","text":"72"},{"key":"C","text":"108"},{"key":"D","text":"18"}]','A','c²=a²+b²-2abcos60°=36+36-36=36','template-hs','approved','通用');