-- ============================================================
-- 第11章 空间向量与立体几何 补题（15学期, 知识点 139-156）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0139-1','math','高中',15,'hs-kp-0139','single_choice',0.75,'空间向量共面定理：三个向量共面的条件是？','[{"key":"A","text":"其中一个可由另外两个线性表示"},{"key":"B","text":"三个都相等"},{"key":"C","text":"三个都垂直"},{"key":"D","text":"模都相等"}]','A','共面定理：存在实数 λ,μ 使 c=λa+μb','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0140-1','math','高中',15,'hs-kp-0140','single_choice',0.35,'空间向量基本定理：任意向量可由？表示','[{"key":"A","text":"三个不共面向量唯一表示"},{"key":"B","text":"两个向量表示"},{"key":"C","text":"一个向量表示"},{"key":"D","text":"四个向量唯一表示"}]','A','空间向量基本定理：三个不共面向量张成整个空间','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0141-1','math','高中',15,'hs-kp-0141','single_choice',0.45,'a=(3,4,1)，|a| = ？','[{"key":"A","text":"5.0990195135927845"},{"key":"B","text":"8"},{"key":"C","text":"12"},{"key":"D","text":"26"}]','A','|a|=√(3²+4²+1²)=5.0990195135927845','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0142-1','math','高中',15,'hs-kp-0142','single_choice',0.55,'a=(3,2,3)，b=(3,2,1)，a·b = ？','[{"key":"A","text":"16"},{"key":"B","text":"9"},{"key":"C","text":"8"},{"key":"D","text":"6"}]','A','a·b=3×3+2×2+3×1=16','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0143-1','math','高中',15,'hs-kp-0143','single_choice',0.65,'a=(1,2,3)，b=(2,4,6)，a 与 b？','[{"key":"A","text":"平行"},{"key":"B","text":"垂直"},{"key":"C","text":"夹角60°"},{"key":"D","text":"夹角30°"}]','A','b=2a → 平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0144-1','math','高中',15,'hs-kp-0144','single_choice',0.75,'a=(1,0,0)，b=(1,0,1)，cos<a,b> = ？','[{"key":"A","text":"1/√2"},{"key":"B","text":"0.5"},{"key":"C","text":"0"},{"key":"D","text":"1"}]','A','cosθ=a·b/(|a||b|)=1/√(1²+1)=1/√2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0145-1','math','高中',15,'hs-kp-0145','single_choice',0.35,'平面 α 法向量 n 满足 n⊥α，若 α 过原点，n=(1,1,1) 则 α 的方程是？','[{"key":"A","text":"1x+y+z=0"},{"key":"B","text":"x+y+z=1"},{"key":"C","text":"1x+y+z=1"},{"key":"D","text":"x=y=z"}]','A','过原点且法向量 n：1x+y+z=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0146-1','math','高中',15,'hs-kp-0146','single_choice',0.45,'向量法判定线面平行：直线方向向量 d ⊥ 法向量 n → 线面？','[{"key":"A","text":"平行"},{"key":"B","text":"垂直"},{"key":"C","text":"斜交"},{"key":"D","text":"无法确定"}]','A','d·n=0 → 线面平行（或线在面内）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0147-1','math','高中',15,'hs-kp-0147','single_choice',0.55,'向量法求线线角：cosθ = |a·b|/(|a||b|)，a=(1,0,0)，b=(3,0,1)，θ = ？','[{"key":"A","text":"arccos(3/√10)"},{"key":"B","text":"90°"},{"key":"C","text":"0°"},{"key":"D","text":"60°"}]','A','cosθ=3/√10 → θ=arccos(3/√10)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0148-1','math','高中',15,'hs-kp-0148','single_choice',0.65,'向量法求线面角：sinθ = |d·n|/(|d||n|)，其中 d 是？','[{"key":"A","text":"直线方向向量"},{"key":"B","text":"平面法向量"},{"key":"C","text":"平面内任意向量"},{"key":"D","text":"直线的法向量"}]','A','线面角用直线方向向量与法向量夹角求','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0149-1','math','高中',15,'hs-kp-0149','single_choice',0.75,'向量法求二面角：cosθ = |n₁·n₂|/(|n₁||n₂|)，n₁、n₂ 是？','[{"key":"A","text":"两个面的法向量"},{"key":"B","text":"两个面的方向向量"},{"key":"C","text":"交线方向向量"},{"key":"D","text":"棱上两点"}]','A','二面角用两平面法向量夹角求','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0150-1','math','高中',15,'hs-kp-0150','single_choice',0.35,'点到直线距离 d = |PA×v|/|v|，P(1,2,0)，A(0,0,0)，v=(3,2,0)，d = ？','[{"key":"A","text":"0.2773500981126145"},{"key":"B","text":"3.6055512754639896"},{"key":"C","text":"3"},{"key":"D","text":"1"}]','A','d=|PA×v|/|v|，计算得 0.28','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0151-1','math','高中',15,'hs-kp-0151','single_choice',0.45,'异面直线距离可用？求解','[{"key":"A","text":"公垂线段长/向量法"},{"key":"B","text":"任意两点距离"},{"key":"C","text":"两线夹角"},{"key":"D","text":"投影长"}]','A','异面直线距离：公垂线段长度','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0152-1','math','高中',15,'hs-kp-0152','single_choice',0.55,'点 P(0,0,0) 到平面 1x+y+z=1 的距离 = ？','[{"key":"A","text":"1/√3"},{"key":"B","text":"1.7320508075688772"},{"key":"C","text":"1"},{"key":"D","text":"1"}]','A','d=|ax₀+by₀+cz₀+d|/√(a²+b²+c²)=1/√(1²+1+1)=1/√3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0153-1','math','高中',15,'hs-kp-0153','single_choice',0.65,'建立空间直角坐标系，常用？确定坐标轴','[{"key":"A","text":"三条两两垂直的直线（右手系）"},{"key":"B","text":"任意三条直线"},{"key":"C","text":"两条直线"},{"key":"D","text":"一条直线"}]','A','空间直角坐标系：三条两两垂直且有公共原点的数轴','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0154-1','math','高中',15,'hs-kp-0154','single_choice',0.75,'a=(3,3,3)，ka = ？','[{"key":"A","text":"(6,6,6)"},{"key":"B","text":"(1.5,1.5,1.5)"},{"key":"C","text":"(5,5,5)"},{"key":"D","text":"(3,3,3)"}]','A','数乘：ka=(6,6,6)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0155-1','math','高中',15,'hs-kp-0155','single_choice',0.35,'用向量法证明线面垂直：直线方向向量 d 与法向量 n 的关系？','[{"key":"A","text":"d∥n"},{"key":"B","text":"d⊥n"},{"key":"C","text":"d·n=1"},{"key":"D","text":"d=n+1"}]','A','线面垂直 ⇔ 方向向量平行于法向量','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0156-1','math','高中',15,'hs-kp-0156','single_choice',0.45,'正方体棱长 2，体对角线 = ？','[{"key":"A","text":"3.4641016151377544"},{"key":"B","text":"2.8284271247461903"},{"key":"C","text":"6"},{"key":"D","text":"4"}]','A','体对角线=√3·a=2√3','template-hs','approved','通用');