-- ============================================================
-- 第11章 空间向量与立体几何 补题（15学期, 知识点 139-156）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0139-1','math','高中',15,'hs-kp-0139','single_choice',0.75,'空间向量共面定理：三个向量共面的条件是？','[{"key":"A","text":"其中一个可由另外两个线性表示"},{"key":"B","text":"三个都相等"},{"key":"C","text":"三个都垂直"},{"key":"D","text":"模都相等"}]','A','共面定理：存在实数 λ,μ 使 c=λa+μb','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0139-2','math','高中',15,'hs-kp-0139','single_choice',0.75,'空间向量共面定理：三个向量共面的条件是？','[{"key":"B","text":"三个都相等"},{"key":"A","text":"其中一个可由另外两个线性表示"},{"key":"C","text":"三个都垂直"},{"key":"D","text":"模都相等"}]','A','共面定理：存在实数 λ,μ 使 c=λa+μb','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0139-3','math','高中',15,'hs-kp-0139','single_choice',0.75,'空间向量共面定理：三个向量共面的条件是？','[{"key":"D","text":"模都相等"},{"key":"B","text":"三个都相等"},{"key":"A","text":"其中一个可由另外两个线性表示"},{"key":"C","text":"三个都垂直"}]','A','共面定理：存在实数 λ,μ 使 c=λa+μb','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0140-1','math','高中',15,'hs-kp-0140','single_choice',0.35,'空间向量基本定理：任意向量可由？表示','[{"key":"A","text":"三个不共面向量唯一表示"},{"key":"B","text":"两个向量表示"},{"key":"C","text":"一个向量表示"},{"key":"D","text":"四个向量唯一表示"}]','A','空间向量基本定理：三个不共面向量张成整个空间','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0140-2','math','高中',15,'hs-kp-0140','single_choice',0.35,'空间向量基本定理：任意向量可由？表示','[{"key":"A","text":"三个不共面向量唯一表示"},{"key":"D","text":"四个向量唯一表示"},{"key":"B","text":"两个向量表示"},{"key":"C","text":"一个向量表示"}]','A','空间向量基本定理：三个不共面向量张成整个空间','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0141-1','math','高中',15,'hs-kp-0141','single_choice',0.45,'a=(1,2,2)，|a| = ？','[{"key":"A","text":"3"},{"key":"B","text":"5"},{"key":"C","text":"4"},{"key":"D","text":"9"}]','A','|a|=√(1²+2²+2²)=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0141-2','math','高中',15,'hs-kp-0141','single_choice',0.45,'a=(1,2,1)，|a| = ？','[{"key":"A","text":"2.449489742783178"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"6"}]','A','|a|=√(1²+2²+1²)=2.449489742783178','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0141-3','math','高中',15,'hs-kp-0141','single_choice',0.45,'a=(2,2,3)，|a| = ？','[{"key":"A","text":"4.123105625617661"},{"key":"B","text":"7"},{"key":"C","text":"12"},{"key":"D","text":"17"}]','A','|a|=√(2²+2²+3²)=4.123105625617661','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0142-1','math','高中',15,'hs-kp-0142','single_choice',0.55,'a=(3,3,3)，b=(3,1,2)，a·b = ？','[{"key":"A","text":"18"},{"key":"B","text":"9"},{"key":"C","text":"9"},{"key":"D","text":"6"}]','A','a·b=3×3+3×1+3×2=18','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0142-2','math','高中',15,'hs-kp-0142','single_choice',0.55,'a=(2,2,1)，b=(2,2,3)，a·b = ？','[{"key":"A","text":"11"},{"key":"B","text":"4"},{"key":"C","text":"5"},{"key":"D","text":"7"}]','A','a·b=2×2+2×2+1×3=11','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0142-3','math','高中',15,'hs-kp-0142','single_choice',0.55,'a=(3,1,3)，b=(2,2,3)，a·b = ？','[{"key":"A","text":"17"},{"key":"B","text":"6"},{"key":"C","text":"7"},{"key":"D","text":"7"}]','A','a·b=3×2+1×2+3×3=17','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0143-1','math','高中',15,'hs-kp-0143','single_choice',0.65,'a=(1,2,3)，b=(4,8,12)，a 与 b？','[{"key":"A","text":"平行"},{"key":"B","text":"垂直"},{"key":"C","text":"夹角60°"},{"key":"D","text":"夹角30°"}]','A','b=4a → 平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0143-2','math','高中',15,'hs-kp-0143','single_choice',0.65,'a=(1,2,3)，b=(2,4,6)，a 与 b？','[{"key":"A","text":"平行"},{"key":"B","text":"垂直"},{"key":"C","text":"夹角60°"},{"key":"D","text":"夹角30°"}]','A','b=2a → 平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0143-3','math','高中',15,'hs-kp-0143','single_choice',0.65,'a=(1,2,3)，b=(4,8,12)，a 与 b？','[{"key":"D","text":"夹角30°"},{"key":"C","text":"夹角60°"},{"key":"B","text":"垂直"},{"key":"A","text":"平行"}]','A','b=4a → 平行','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0144-1','math','高中',15,'hs-kp-0144','single_choice',0.75,'a=(1,0,0)，b=(1,0,1)，cos<a,b> = ？','[{"key":"A","text":"1/√2"},{"key":"B","text":"0.5"},{"key":"C","text":"0"},{"key":"D","text":"1"}]','A','cosθ=a·b/(|a||b|)=1/√(1²+1)=1/√2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0144-2','math','高中',15,'hs-kp-0144','single_choice',0.75,'a=(1,0,0)，b=(3,0,1)，cos<a,b> = ？','[{"key":"A","text":"3/√10"},{"key":"B","text":"0.9"},{"key":"C","text":"0"},{"key":"D","text":"1"}]','A','cosθ=a·b/(|a||b|)=3/√(3²+1)=3/√10','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0144-3','math','高中',15,'hs-kp-0144','single_choice',0.75,'a=(1,0,0)，b=(2,0,1)，cos<a,b> = ？','[{"key":"A","text":"2/√5"},{"key":"B","text":"0.8"},{"key":"C","text":"0"},{"key":"D","text":"1"}]','A','cosθ=a·b/(|a||b|)=2/√(2²+1)=2/√5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0145-1','math','高中',15,'hs-kp-0145','single_choice',0.35,'平面 α 法向量 n 满足 n⊥α，若 α 过原点，n=(3,1,1) 则 α 的方程是？','[{"key":"A","text":"3x+y+z=0"},{"key":"B","text":"x+y+z=3"},{"key":"C","text":"3x+y+z=1"},{"key":"D","text":"x=y=z"}]','A','过原点且法向量 n：3x+y+z=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0145-2','math','高中',15,'hs-kp-0145','single_choice',0.35,'平面 α 法向量 n 满足 n⊥α，若 α 过原点，n=(2,1,1) 则 α 的方程是？','[{"key":"A","text":"2x+y+z=0"},{"key":"B","text":"x+y+z=2"},{"key":"C","text":"2x+y+z=1"},{"key":"D","text":"x=y=z"}]','A','过原点且法向量 n：2x+y+z=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0145-3','math','高中',15,'hs-kp-0145','single_choice',0.35,'平面 α 法向量 n 满足 n⊥α，若 α 过原点，n=(3,1,1) 则 α 的方程是？','[{"key":"D","text":"x=y=z"},{"key":"C","text":"3x+y+z=1"},{"key":"B","text":"x+y+z=3"},{"key":"A","text":"3x+y+z=0"}]','A','过原点且法向量 n：3x+y+z=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0146-1','math','高中',15,'hs-kp-0146','single_choice',0.45,'向量法判定线面平行：直线方向向量 d ⊥ 法向量 n → 线面？','[{"key":"A","text":"平行"},{"key":"B","text":"垂直"},{"key":"C","text":"斜交"},{"key":"D","text":"无法确定"}]','A','d·n=0 → 线面平行（或线在面内）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0146-2','math','高中',15,'hs-kp-0146','single_choice',0.45,'向量法判定线面平行：直线方向向量 d ⊥ 法向量 n → 线面？','[{"key":"D","text":"无法确定"},{"key":"B","text":"垂直"},{"key":"C","text":"斜交"},{"key":"A","text":"平行"}]','A','d·n=0 → 线面平行（或线在面内）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0147-1','math','高中',15,'hs-kp-0147','single_choice',0.55,'向量法求线线角：cosθ = |a·b|/(|a||b|)，a=(1,0,0)，b=(2,0,1)，θ = ？','[{"key":"A","text":"arccos(2/√5)"},{"key":"B","text":"90°"},{"key":"C","text":"0°"},{"key":"D","text":"60°"}]','A','cosθ=2/√5 → θ=arccos(2/√5)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0147-2','math','高中',15,'hs-kp-0147','single_choice',0.55,'向量法求线线角：cosθ = |a·b|/(|a||b|)，a=(1,0,0)，b=(3,0,1)，θ = ？','[{"key":"A","text":"arccos(3/√10)"},{"key":"B","text":"90°"},{"key":"C","text":"0°"},{"key":"D","text":"60°"}]','A','cosθ=3/√10 → θ=arccos(3/√10)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0147-3','math','高中',15,'hs-kp-0147','single_choice',0.55,'向量法求线线角：cosθ = |a·b|/(|a||b|)，a=(1,0,0)，b=(1,0,1)，θ = ？','[{"key":"A","text":"arccos(1/√2)"},{"key":"B","text":"90°"},{"key":"C","text":"0°"},{"key":"D","text":"60°"}]','A','cosθ=1/√2 → θ=arccos(1/√2)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0148-1','math','高中',15,'hs-kp-0148','single_choice',0.65,'向量法求线面角：sinθ = |d·n|/(|d||n|)，其中 d 是？','[{"key":"A","text":"直线方向向量"},{"key":"B","text":"平面法向量"},{"key":"C","text":"平面内任意向量"},{"key":"D","text":"直线的法向量"}]','A','线面角用直线方向向量与法向量夹角求','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0148-2','math','高中',15,'hs-kp-0148','single_choice',0.65,'向量法求线面角：sinθ = |d·n|/(|d||n|)，其中 d 是？','[{"key":"A","text":"直线方向向量"},{"key":"D","text":"直线的法向量"},{"key":"B","text":"平面法向量"},{"key":"C","text":"平面内任意向量"}]','A','线面角用直线方向向量与法向量夹角求','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0148-3','math','高中',15,'hs-kp-0148','single_choice',0.65,'向量法求线面角：sinθ = |d·n|/(|d||n|)，其中 d 是？','[{"key":"D","text":"直线的法向量"},{"key":"C","text":"平面内任意向量"},{"key":"B","text":"平面法向量"},{"key":"A","text":"直线方向向量"}]','A','线面角用直线方向向量与法向量夹角求','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0149-1','math','高中',15,'hs-kp-0149','single_choice',0.75,'向量法求二面角：cosθ = |n₁·n₂|/(|n₁||n₂|)，n₁、n₂ 是？','[{"key":"A","text":"两个面的法向量"},{"key":"B","text":"两个面的方向向量"},{"key":"C","text":"交线方向向量"},{"key":"D","text":"棱上两点"}]','A','二面角用两平面法向量夹角求','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0149-2','math','高中',15,'hs-kp-0149','single_choice',0.75,'向量法求二面角：cosθ = |n₁·n₂|/(|n₁||n₂|)，n₁、n₂ 是？','[{"key":"C","text":"交线方向向量"},{"key":"D","text":"棱上两点"},{"key":"B","text":"两个面的方向向量"},{"key":"A","text":"两个面的法向量"}]','A','二面角用两平面法向量夹角求','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0149-3','math','高中',15,'hs-kp-0149','single_choice',0.75,'向量法求二面角：cosθ = |n₁·n₂|/(|n₁||n₂|)，n₁、n₂ 是？','[{"key":"A","text":"两个面的法向量"},{"key":"B","text":"两个面的方向向量"},{"key":"D","text":"棱上两点"},{"key":"C","text":"交线方向向量"}]','A','二面角用两平面法向量夹角求','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0150-1','math','高中',15,'hs-kp-0150','single_choice',0.35,'点到直线距离 d = |PA×v|/|v|，P(1,2,0)，A(0,0,0)，v=(1,3,0)，d = ？','[{"key":"A","text":"0.6324555320336759"},{"key":"B","text":"3.1622776601683795"},{"key":"C","text":"1"},{"key":"D","text":"1"}]','A','d=|PA×v|/|v|，计算得 0.63','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0150-2','math','高中',15,'hs-kp-0150','single_choice',0.35,'点到直线距离 d = |PA×v|/|v|，P(1,2,0)，A(0,0,0)，v=(3,3,0)，d = ？','[{"key":"A","text":"0"},{"key":"B","text":"4.242640687119286"},{"key":"C","text":"3"},{"key":"D","text":"1"}]','A','d=|PA×v|/|v|，计算得 0.00','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0150-3','math','高中',15,'hs-kp-0150','single_choice',0.35,'点到直线距离 d = |PA×v|/|v|，P(1,2,0)，A(0,0,0)，v=(3,1,0)，d = ？','[{"key":"A","text":"0.6324555320336759"},{"key":"B","text":"3.1622776601683795"},{"key":"C","text":"3"},{"key":"D","text":"1"}]','A','d=|PA×v|/|v|，计算得 0.63','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0151-1','math','高中',15,'hs-kp-0151','single_choice',0.45,'异面直线距离可用？求解','[{"key":"A","text":"公垂线段长/向量法"},{"key":"B","text":"任意两点距离"},{"key":"C","text":"两线夹角"},{"key":"D","text":"投影长"}]','A','异面直线距离：公垂线段长度','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0151-2','math','高中',15,'hs-kp-0151','single_choice',0.45,'异面直线距离可用？求解','[{"key":"A","text":"公垂线段长/向量法"},{"key":"B","text":"任意两点距离"},{"key":"D","text":"投影长"},{"key":"C","text":"两线夹角"}]','A','异面直线距离：公垂线段长度','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0152-1','math','高中',15,'hs-kp-0152','single_choice',0.55,'点 P(0,0,0) 到平面 1x+y+z=1 的距离 = ？','[{"key":"A","text":"1/√3"},{"key":"B","text":"1.7320508075688772"},{"key":"C","text":"1"},{"key":"D","text":"1"}]','A','d=|ax₀+by₀+cz₀+d|/√(a²+b²+c²)=1/√(1²+1+1)=1/√3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0152-2','math','高中',15,'hs-kp-0152','single_choice',0.55,'点 P(0,0,0) 到平面 3x+y+z=1 的距离 = ？','[{"key":"A","text":"1/√11"},{"key":"B","text":"4.358898943540673"},{"key":"C","text":"1"},{"key":"D","text":"3"}]','A','d=|ax₀+by₀+cz₀+d|/√(a²+b²+c²)=1/√(3²+1+1)=1/√11','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0152-3','math','高中',15,'hs-kp-0152','single_choice',0.55,'点 P(0,0,0) 到平面 2x+y+z=1 的距离 = ？','[{"key":"A","text":"1/√6"},{"key":"B","text":"3"},{"key":"C","text":"1"},{"key":"D","text":"2"}]','A','d=|ax₀+by₀+cz₀+d|/√(a²+b²+c²)=1/√(2²+1+1)=1/√6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0153-1','math','高中',15,'hs-kp-0153','single_choice',0.65,'建立空间直角坐标系，常用？确定坐标轴','[{"key":"A","text":"三条两两垂直的直线（右手系）"},{"key":"B","text":"任意三条直线"},{"key":"C","text":"两条直线"},{"key":"D","text":"一条直线"}]','A','空间直角坐标系：三条两两垂直且有公共原点的数轴','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0153-2','math','高中',15,'hs-kp-0153','single_choice',0.65,'建立空间直角坐标系，常用？确定坐标轴','[{"key":"C","text":"两条直线"},{"key":"D","text":"一条直线"},{"key":"B","text":"任意三条直线"},{"key":"A","text":"三条两两垂直的直线（右手系）"}]','A','空间直角坐标系：三条两两垂直且有公共原点的数轴','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0154-1','math','高中',15,'hs-kp-0154','single_choice',0.75,'a=(1,2,1)，ka = ？','[{"key":"A","text":"(3,6,3)"},{"key":"B","text":"(0.3333333333333333,0.6666666666666666,0.3333333333333333)"},{"key":"C","text":"(4,5,4)"},{"key":"D","text":"(1,2,1)"}]','A','数乘：ka=(3,6,3)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0154-2','math','高中',15,'hs-kp-0154','single_choice',0.75,'a=(2,1,1)，ka = ？','[{"key":"A","text":"(6,3,3)"},{"key":"B","text":"(0.6666666666666666,0.3333333333333333,0.3333333333333333)"},{"key":"C","text":"(5,4,4)"},{"key":"D","text":"(2,1,1)"}]','A','数乘：ka=(6,3,3)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0154-3','math','高中',15,'hs-kp-0154','single_choice',0.75,'a=(2,3,2)，ka = ？','[{"key":"A","text":"(4,6,4)"},{"key":"B","text":"(1,1.5,1)"},{"key":"C","text":"(4,5,4)"},{"key":"D","text":"(2,3,2)"}]','A','数乘：ka=(4,6,4)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0155-1','math','高中',15,'hs-kp-0155','single_choice',0.35,'用向量法证明线面垂直：直线方向向量 d 与法向量 n 的关系？','[{"key":"A","text":"d∥n"},{"key":"B","text":"d⊥n"},{"key":"C","text":"d·n=1"},{"key":"D","text":"d=n+1"}]','A','线面垂直 ⇔ 方向向量平行于法向量','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0155-2','math','高中',15,'hs-kp-0155','single_choice',0.35,'用向量法证明线面垂直：直线方向向量 d 与法向量 n 的关系？','[{"key":"D","text":"d=n+1"},{"key":"A","text":"d∥n"},{"key":"B","text":"d⊥n"},{"key":"C","text":"d·n=1"}]','A','线面垂直 ⇔ 方向向量平行于法向量','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0156-1','math','高中',15,'hs-kp-0156','single_choice',0.45,'正方体棱长 4，体对角线 = ？','[{"key":"A","text":"6.928203230275509"},{"key":"B","text":"5.656854249492381"},{"key":"C","text":"12"},{"key":"D","text":"8"}]','A','体对角线=√3·a=4√3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0156-2','math','高中',15,'hs-kp-0156','single_choice',0.45,'正方体棱长 3，体对角线 = ？','[{"key":"A","text":"5.196152422706632"},{"key":"B","text":"4.242640687119286"},{"key":"C","text":"9"},{"key":"D","text":"6"}]','A','体对角线=√3·a=3√3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0156-3','math','高中',15,'hs-kp-0156','single_choice',0.45,'正方体棱长 1，体对角线 = ？','[{"key":"A","text":"1.7320508075688772"},{"key":"B","text":"1.4142135623730951"},{"key":"C","text":"3"},{"key":"D","text":"2"}]','A','体对角线=√3·a=1√3','template-hs','approved','通用');