-- ============================================================
-- 第9章 统计 补题（14学期, 知识点 115-126）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0115-1','math','高中',14,'hs-kp-0115','single_choice',0.35,'总体 139 人，分 4 层，各层人数 50,39,50，按比例分层抽 14 人，第一层抽几人？(按 50:39:50)','[{"key":"A","text":"5"},{"key":"B","text":"5"},{"key":"C","text":"14"},{"key":"D","text":"4"}]','A','按比例：5 人','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0115-2','math','高中',14,'hs-kp-0115','single_choice',0.35,'总体 123 人，分 5 层，各层人数 50,23,50，按比例分层抽 16 人，第一层抽几人？(按 50:23:50)','[{"key":"A","text":"7"},{"key":"B","text":"5"},{"key":"C","text":"16"},{"key":"D","text":"3"}]','A','按比例：7 人','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0115-3','math','高中',14,'hs-kp-0115','single_choice',0.35,'总体 144 人，分 4 层，各层人数 50,44,50，按比例分层抽 13 人，第一层抽几人？(按 50:44:50)','[{"key":"A","text":"5"},{"key":"B","text":"4"},{"key":"C","text":"13"},{"key":"D","text":"4"}]','A','按比例：5 人','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0116-1','math','高中',14,'hs-kp-0116','single_choice',0.45,'频率分布直方图中，所有小矩形面积之和 = ？','[{"key":"A","text":"1"},{"key":"B","text":"13"},{"key":"C","text":"0.5"},{"key":"D","text":"100"}]','A','直方图面积=频率，总和=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0116-2','math','高中',14,'hs-kp-0116','single_choice',0.45,'频率分布直方图中，所有小矩形面积之和 = ？','[{"key":"B","text":"13"},{"key":"D","text":"100"},{"key":"A","text":"1"},{"key":"C","text":"0.5"}]','A','直方图面积=频率，总和=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0116-3','math','高中',14,'hs-kp-0116','single_choice',0.45,'频率分布直方图中，所有小矩形面积之和 = ？','[{"key":"D","text":"100"},{"key":"C","text":"0.5"},{"key":"B","text":"13"},{"key":"A","text":"1"}]','A','直方图面积=频率，总和=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0117-1','math','高中',14,'hs-kp-0117','single_choice',0.55,'数据 6,1,2 的平均数 = ？','[{"key":"A","text":"3"},{"key":"B","text":"9"},{"key":"C","text":"4"},{"key":"D","text":"2"}]','A','平均数=(6+1+2)/3=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0117-2','math','高中',14,'hs-kp-0117','single_choice',0.55,'数据 7,8,8 的平均数 = ？','[{"key":"A","text":"7.6"},{"key":"B","text":"23"},{"key":"C","text":"8.6"},{"key":"D","text":"6.6"}]','A','平均数=(7+8+8)/3=7.6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0117-3','math','高中',14,'hs-kp-0117','single_choice',0.55,'数据 9,3,3 的平均数 = ？','[{"key":"A","text":"5"},{"key":"B","text":"15"},{"key":"C","text":"6"},{"key":"D","text":"4"}]','A','平均数=(9+3+3)/3=5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0118-1','math','高中',14,'hs-kp-0118','single_choice',0.65,'10 个数据，第 30 百分位数对应的位置 k = n×p/100 = ？(n=8,p=30)','[{"key":"A","text":"2.4"},{"key":"B","text":"8"},{"key":"C","text":"3"},{"key":"D","text":"24"}]','A','k=8×30/100=2.4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0118-2','math','高中',14,'hs-kp-0118','single_choice',0.65,'10 个数据，第 20 百分位数对应的位置 k = n×p/100 = ？(n=8,p=20)','[{"key":"A","text":"1.6"},{"key":"B","text":"8"},{"key":"C","text":"2"},{"key":"D","text":"16"}]','A','k=8×20/100=1.6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0118-3','math','高中',14,'hs-kp-0118','single_choice',0.65,'10 个数据，第 40 百分位数对应的位置 k = n×p/100 = ？(n=9,p=40)','[{"key":"A","text":"3.6"},{"key":"B","text":"9"},{"key":"C","text":"4"},{"key":"D","text":"36"}]','A','k=9×40/100=3.6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0119-1','math','高中',14,'hs-kp-0119','single_choice',0.75,'直方图中，中位数对应的位置是？','[{"key":"A","text":"面积平分处（50%）"},{"key":"B","text":"最高柱处"},{"key":"C","text":"第一柱处"},{"key":"D","text":"最后一柱处"}]','A','中位数：直方图面积左右各 50% 处','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0119-2','math','高中',14,'hs-kp-0119','single_choice',0.75,'直方图中，中位数对应的位置是？','[{"key":"C","text":"第一柱处"},{"key":"A","text":"面积平分处（50%）"},{"key":"B","text":"最高柱处"},{"key":"D","text":"最后一柱处"}]','A','中位数：直方图面积左右各 50% 处','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0119-3','math','高中',14,'hs-kp-0119','single_choice',0.75,'直方图中，中位数对应的位置是？','[{"key":"A","text":"面积平分处（50%）"},{"key":"D","text":"最后一柱处"},{"key":"B","text":"最高柱处"},{"key":"C","text":"第一柱处"}]','A','中位数：直方图面积左右各 50% 处','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0120-1','math','高中',14,'hs-kp-0120','single_choice',0.35,'数据 4,4,8 的方差 ≈ ？','[{"key":"A","text":"3.5"},{"key":"B","text":"4.5"},{"key":"C","text":"0"},{"key":"D","text":"5.333333333333333"}]','A','方差 = Σ(xi-x̄)²/n ≈ 3.5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0120-2','math','高中',14,'hs-kp-0120','single_choice',0.35,'数据 5,6,8 的方差 ≈ ？','[{"key":"A","text":"1.5"},{"key":"B","text":"2.5"},{"key":"C","text":"0"},{"key":"D","text":"6.333333333333333"}]','A','方差 = Σ(xi-x̄)²/n ≈ 1.5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0120-3','math','高中',14,'hs-kp-0120','single_choice',0.35,'数据 4,7,4 的方差 ≈ ？','[{"key":"A","text":"2"},{"key":"B","text":"3"},{"key":"C","text":"0"},{"key":"D","text":"5"}]','A','方差 = Σ(xi-x̄)²/n ≈ 2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0121-1','math','高中',14,'hs-kp-0121','single_choice',0.45,'简单随机抽样的常用方法是？','[{"key":"A","text":"抽签法/随机数法"},{"key":"B","text":"按成绩排"},{"key":"C","text":"按学号奇偶"},{"key":"D","text":"按班级分层"}]','A','简单随机抽样：抽签法、随机数法','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0121-2','math','高中',14,'hs-kp-0121','single_choice',0.45,'简单随机抽样的常用方法是？','[{"key":"A","text":"抽签法/随机数法"},{"key":"B","text":"按成绩排"},{"key":"D","text":"按班级分层"},{"key":"C","text":"按学号奇偶"}]','A','简单随机抽样：抽签法、随机数法','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0122-1','math','高中',14,'hs-kp-0122','single_choice',0.55,'样本容量越大，估计总体的误差通常？','[{"key":"A","text":"越小"},{"key":"B","text":"越大"},{"key":"C","text":"不变"},{"key":"D","text":"不确定"}]','A','大数定律：样本越大估计越准','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0122-2','math','高中',14,'hs-kp-0122','single_choice',0.55,'样本容量越大，估计总体的误差通常？','[{"key":"B","text":"越大"},{"key":"A","text":"越小"},{"key":"D","text":"不确定"},{"key":"C","text":"不变"}]','A','大数定律：样本越大估计越准','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0122-3','math','高中',14,'hs-kp-0122','single_choice',0.55,'样本容量越大，估计总体的误差通常？','[{"key":"D","text":"不确定"},{"key":"C","text":"不变"},{"key":"B","text":"越大"},{"key":"A","text":"越小"}]','A','大数定律：样本越大估计越准','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0123-1','math','高中',14,'hs-kp-0123','single_choice',0.65,'整理数据时，常用图表不包括？','[{"key":"A","text":"立体透视模型"},{"key":"B","text":"频率分布直方图"},{"key":"C","text":"茎叶图"},{"key":"D","text":"折线图"}]','A','统计图表：直方图、茎叶图、折线图等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0123-2','math','高中',14,'hs-kp-0123','single_choice',0.65,'整理数据时，常用图表不包括？','[{"key":"D","text":"折线图"},{"key":"C","text":"茎叶图"},{"key":"B","text":"频率分布直方图"},{"key":"A","text":"立体透视模型"}]','A','统计图表：直方图、茎叶图、折线图等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0123-3','math','高中',14,'hs-kp-0123','single_choice',0.65,'整理数据时，常用图表不包括？','[{"key":"D","text":"折线图"},{"key":"A","text":"立体透视模型"},{"key":"B","text":"频率分布直方图"},{"key":"C","text":"茎叶图"}]','A','统计图表：直方图、茎叶图、折线图等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0124-1','math','高中',14,'hs-kp-0124','single_choice',0.75,'用样本估计总体的思想称为？','[{"key":"A","text":"用样本估计总体"},{"key":"B","text":"精确计算"},{"key":"C","text":"主观臆断"},{"key":"D","text":"枚举所有"}]','A','统计核心思想：样本估计总体','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0124-2','math','高中',14,'hs-kp-0124','single_choice',0.75,'用样本估计总体的思想称为？','[{"key":"D","text":"枚举所有"},{"key":"C","text":"主观臆断"},{"key":"B","text":"精确计算"},{"key":"A","text":"用样本估计总体"}]','A','统计核心思想：样本估计总体','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0124-3','math','高中',14,'hs-kp-0124','single_choice',0.75,'用样本估计总体的思想称为？','[{"key":"A","text":"用样本估计总体"},{"key":"B","text":"精确计算"},{"key":"D","text":"枚举所有"},{"key":"C","text":"主观臆断"}]','A','统计核心思想：样本估计总体','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0125-1','math','高中',14,'hs-kp-0125','single_choice',0.35,'数据 5,1,5,1,3 的中位数 = ？','[{"key":"A","text":"3"},{"key":"B","text":"1"},{"key":"C","text":"5"},{"key":"D","text":"3"}]','A','排序后 1,1,3,5,5，中位数=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0125-2','math','高中',14,'hs-kp-0125','single_choice',0.35,'数据 2,3,3,2,5 的中位数 = ？','[{"key":"A","text":"3"},{"key":"B","text":"2"},{"key":"C","text":"5"},{"key":"D","text":"3"}]','A','排序后 2,2,3,3,5，中位数=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0125-3','math','高中',14,'hs-kp-0125','single_choice',0.35,'数据 4,4,3,2,2 的中位数 = ？','[{"key":"A","text":"3"},{"key":"B","text":"2"},{"key":"C","text":"4"},{"key":"D","text":"3"}]','A','排序后 2,2,3,4,4，中位数=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0126-1','math','高中',14,'hs-kp-0126','single_choice',0.45,'能同时看数据分布和原始数值的图表是？','[{"key":"A","text":"茎叶图"},{"key":"B","text":"饼图"},{"key":"C","text":"条形图"},{"key":"D","text":"折线图"}]','A','茎叶图保留原始数据','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0126-2','math','高中',14,'hs-kp-0126','single_choice',0.45,'能同时看数据分布和原始数值的图表是？','[{"key":"A","text":"茎叶图"},{"key":"C","text":"条形图"},{"key":"B","text":"饼图"},{"key":"D","text":"折线图"}]','A','茎叶图保留原始数据','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0126-3','math','高中',14,'hs-kp-0126','single_choice',0.45,'能同时看数据分布和原始数值的图表是？','[{"key":"D","text":"折线图"},{"key":"B","text":"饼图"},{"key":"C","text":"条形图"},{"key":"A","text":"茎叶图"}]','A','茎叶图保留原始数据','template-hs','approved','通用');