-- ============================================================
-- 第2章 一元二次函数、方程和不等式 补题（13学期, 知识点 15-30）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0015-1','math','高中',13,'hs-kp-0015','single_choice',0.35,'(a+b)² = ？ (a=4, b=2 为例验证)','[{"key":"A","text":"a²+2ab+b²"},{"key":"B","text":"a²+b²"},{"key":"C","text":"a²-2ab+b²"},{"key":"D","text":"2ab"}]','A','完全平方和公式：(a+b)²=a²+2ab+b²','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0015-2','math','高中',13,'hs-kp-0015','single_choice',0.35,'(a+b)² = ？ (a=2, b=4 为例验证)','[{"key":"A","text":"a²+2ab+b²"},{"key":"B","text":"a²+b²"},{"key":"C","text":"a²-2ab+b²"},{"key":"D","text":"2ab"}]','A','完全平方和公式：(a+b)²=a²+2ab+b²','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0015-3','math','高中',13,'hs-kp-0015','single_choice',0.35,'(a+b)² = ？ (a=4, b=5 为例验证)','[{"key":"A","text":"a²+2ab+b²"},{"key":"B","text":"a²+b²"},{"key":"C","text":"a²-2ab+b²"},{"key":"D","text":"2ab"}]','A','完全平方和公式：(a+b)²=a²+2ab+b²','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0016-1','math','高中',13,'hs-kp-0016','single_choice',0.45,'若 a>b (a=8, b=3)，则下列正确的是？','[{"key":"A","text":"a+1 > b+1"},{"key":"B","text":"a-2 < b-2"},{"key":"C","text":"-a > -b"},{"key":"D","text":"a < b"}]','A','不等式同加同减不变号：a>b ⇒ a+1>b+1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0016-2','math','高中',13,'hs-kp-0016','single_choice',0.45,'若 a>b (a=4, b=2)，则下列正确的是？','[{"key":"A","text":"a+1 > b+1"},{"key":"B","text":"a-2 < b-2"},{"key":"C","text":"-a > -b"},{"key":"D","text":"a < b"}]','A','不等式同加同减不变号：a>b ⇒ a+1>b+1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0016-3','math','高中',13,'hs-kp-0016','single_choice',0.45,'若 a>b (a=7, b=3)，则下列正确的是？','[{"key":"A","text":"a+1 > b+1"},{"key":"B","text":"a-2 < b-2"},{"key":"C","text":"-a > -b"},{"key":"D","text":"a < b"}]','A','不等式同加同减不变号：a>b ⇒ a+1>b+1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0017-1','math','高中',13,'hs-kp-0017','single_choice',0.55,'若 |x| < 4，则 x 的取值范围是？','[{"key":"A","text":"-4<x<4"},{"key":"B","text":"x>4"},{"key":"C","text":"x<-4"},{"key":"D","text":"x=4"}]','A','|x|<a ⇔ -a<x<a，故 -4<x<4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0017-2','math','高中',13,'hs-kp-0017','single_choice',0.55,'若 |x| < 2，则 x 的取值范围是？','[{"key":"A","text":"-2<x<2"},{"key":"B","text":"x>2"},{"key":"C","text":"x<-2"},{"key":"D","text":"x=2"}]','A','|x|<a ⇔ -a<x<a，故 -2<x<2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0017-3','math','高中',13,'hs-kp-0017','single_choice',0.55,'若 |x| < 3，则 x 的取值范围是？','[{"key":"A","text":"-3<x<3"},{"key":"B","text":"x>3"},{"key":"C","text":"x<-3"},{"key":"D","text":"x=3"}]','A','|x|<a ⇔ -a<x<a，故 -3<x<3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0018-1','math','高中',13,'hs-kp-0018','single_choice',0.65,'已知 a>0，则 a + 1/a 的最小值是（a=8 验证）？','[{"key":"A","text":"2"},{"key":"B","text":"1"},{"key":"C","text":"4"},{"key":"D","text":"3"}]','A','均值不等式：a+1/a ≥ 2√(a·1/a)=2，当 a=1 时取等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0018-2','math','高中',13,'hs-kp-0018','single_choice',0.65,'已知 a>0，则 a + 1/a 的最小值是（a=9 验证）？','[{"key":"A","text":"2"},{"key":"B","text":"1"},{"key":"C","text":"4"},{"key":"D","text":"3"}]','A','均值不等式：a+1/a ≥ 2√(a·1/a)=2，当 a=1 时取等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0018-3','math','高中',13,'hs-kp-0018','single_choice',0.65,'已知 a>0，则 a + 1/a 的最小值是（a=6 验证）？','[{"key":"A","text":"2"},{"key":"B","text":"1"},{"key":"C","text":"4"},{"key":"D","text":"3"}]','A','均值不等式：a+1/a ≥ 2√(a·1/a)=2，当 a=1 时取等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0019-1','math','高中',13,'hs-kp-0019','single_choice',0.75,'已知 a,b>0，则 (a+b)/2 与 √(ab) 的关系是？','[{"key":"A","text":"(a+b)/2 ≥ √(ab)"},{"key":"B","text":"(a+b)/2 ≤ √(ab)"},{"key":"C","text":"(a+b)/2 = √(ab)"},{"key":"D","text":"无法比较"}]','A','均值不等式：(a+b)/2 ≥ √(ab)，当 a=b 时取等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0019-2','math','高中',13,'hs-kp-0019','single_choice',0.75,'已知 a,b>0，则 (a+b)/2 与 √(ab) 的关系是？','[{"key":"C","text":"(a+b)/2 = √(ab)"},{"key":"A","text":"(a+b)/2 ≥ √(ab)"},{"key":"B","text":"(a+b)/2 ≤ √(ab)"},{"key":"D","text":"无法比较"}]','A','均值不等式：(a+b)/2 ≥ √(ab)，当 a=b 时取等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0020-1','math','高中',13,'hs-kp-0020','single_choice',0.35,'均值不等式链中，调和平均数 H 与几何平均数 G 的关系是？','[{"key":"A","text":"H ≤ G"},{"key":"B","text":"H ≥ G"},{"key":"C","text":"H = G"},{"key":"D","text":"无法比较"}]','A','均值不等式链：H ≤ G ≤ A ≤ Q（调和≤几何≤算术≤平方）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0020-2','math','高中',13,'hs-kp-0020','single_choice',0.35,'均值不等式链中，调和平均数 H 与几何平均数 G 的关系是？','[{"key":"A","text":"H ≤ G"},{"key":"D","text":"无法比较"},{"key":"B","text":"H ≥ G"},{"key":"C","text":"H = G"}]','A','均值不等式链：H ≤ G ≤ A ≤ Q（调和≤几何≤算术≤平方）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0020-3','math','高中',13,'hs-kp-0020','single_choice',0.35,'均值不等式链中，调和平均数 H 与几何平均数 G 的关系是？','[{"key":"A","text":"H ≤ G"},{"key":"B","text":"H ≥ G"},{"key":"D","text":"无法比较"},{"key":"C","text":"H = G"}]','A','均值不等式链：H ≤ G ≤ A ≤ Q（调和≤几何≤算术≤平方）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0021-1','math','高中',13,'hs-kp-0021','single_choice',0.45,'已知 x>0，y>0，xy=9，则 x+y 的最小值是？','[{"key":"A","text":"6"},{"key":"B","text":"9"},{"key":"C","text":"18"},{"key":"D","text":"3"}]','A','积定和最小：x+y ≥ 2√(xy)=2√9','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0021-2','math','高中',13,'hs-kp-0021','single_choice',0.45,'已知 x>0，y>0，xy=10，则 x+y 的最小值是？','[{"key":"A","text":"6.324555320336759"},{"key":"B","text":"10"},{"key":"C","text":"20"},{"key":"D","text":"3.1622776601683795"}]','A','积定和最小：x+y ≥ 2√(xy)=2√10','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0021-3','math','高中',13,'hs-kp-0021','single_choice',0.45,'已知 x>0，y>0，xy=12，则 x+y 的最小值是？','[{"key":"A","text":"6.928203230275509"},{"key":"B","text":"12"},{"key":"C","text":"24"},{"key":"D","text":"3.4641016151377544"}]','A','积定和最小：x+y ≥ 2√(xy)=2√12','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0022-1','math','高中',13,'hs-kp-0022','single_choice',0.55,'已知 x>0，y>0，x+y=14，则 xy 的最大值是？','[{"key":"A","text":"49"},{"key":"B","text":"14"},{"key":"C","text":"7"},{"key":"D","text":"28"}]','A','和定积最大：xy ≤ ((14)/2)²=49','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0022-2','math','高中',13,'hs-kp-0022','single_choice',0.55,'已知 x>0，y>0，x+y=13，则 xy 的最大值是？','[{"key":"A","text":"42.25"},{"key":"B","text":"13"},{"key":"C","text":"6.5"},{"key":"D","text":"26"}]','A','和定积最大：xy ≤ ((13)/2)²=42.25','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0022-3','math','高中',13,'hs-kp-0022','single_choice',0.55,'已知 x>0，y>0，x+y=9，则 xy 的最大值是？','[{"key":"A","text":"20.25"},{"key":"B","text":"9"},{"key":"C","text":"4.5"},{"key":"D","text":"18"}]','A','和定积最大：xy ≤ ((9)/2)²=20.25','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0023-1','math','高中',13,'hs-kp-0023','single_choice',0.65,'糖水不等式：若 a>b>0，m>0，则 b/a 与 (b+m)/(a+m) 的关系？','[{"key":"A","text":"b/a < (b+m)/(a+m)"},{"key":"B","text":"b/a > (b+m)/(a+m)"},{"key":"C","text":"相等"},{"key":"D","text":"无法确定"}]','A','糖水加糖变甜：b/a < (b+m)/(a+m)（真分数加同正数变大）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0023-2','math','高中',13,'hs-kp-0023','single_choice',0.65,'糖水不等式：若 a>b>0，m>0，则 b/a 与 (b+m)/(a+m) 的关系？','[{"key":"D","text":"无法确定"},{"key":"A","text":"b/a < (b+m)/(a+m)"},{"key":"C","text":"相等"},{"key":"B","text":"b/a > (b+m)/(a+m)"}]','A','糖水加糖变甜：b/a < (b+m)/(a+m)（真分数加同正数变大）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0024-1','math','高中',13,'hs-kp-0024','single_choice',0.75,'方程 x²-5x+6=0 的两根之和是？','[{"key":"A","text":"5"},{"key":"B","text":"6"},{"key":"C","text":"-5"},{"key":"D","text":"10"}]','A','韦达定理：x₁+x₂=5（两根为 2 和 3）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0024-2','math','高中',13,'hs-kp-0024','single_choice',0.75,'方程 x²-4x+4=0 的两根之和是？','[{"key":"A","text":"4"},{"key":"B","text":"4"},{"key":"C","text":"-4"},{"key":"D","text":"8"}]','A','韦达定理：x₁+x₂=4（两根为 2 和 2）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0024-3','math','高中',13,'hs-kp-0024','single_choice',0.75,'方程 x²-6x+9=0 的两根之和是？','[{"key":"A","text":"6"},{"key":"B","text":"9"},{"key":"C","text":"-6"},{"key":"D","text":"12"}]','A','韦达定理：x₁+x₂=6（两根为 3 和 3）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0025-1','math','高中',13,'hs-kp-0025','single_choice',0.35,'方程 x²-(p+q)x+pq=0（p=4,q=5）两根之积是？','[{"key":"A","text":"20"},{"key":"B","text":"9"},{"key":"C","text":"-20"},{"key":"D","text":"1"}]','A','韦达定理：x₁·x₂=c/a=20','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0025-2','math','高中',13,'hs-kp-0025','single_choice',0.35,'方程 x²-(p+q)x+pq=0（p=5,q=3）两根之积是？','[{"key":"A","text":"15"},{"key":"B","text":"8"},{"key":"C","text":"-15"},{"key":"D","text":"1"}]','A','韦达定理：x₁·x₂=c/a=15','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0025-3','math','高中',13,'hs-kp-0025','single_choice',0.35,'方程 x²-(p+q)x+pq=0（p=5,q=2）两根之积是？','[{"key":"A","text":"10"},{"key":"B","text":"7"},{"key":"C","text":"-10"},{"key":"D","text":"1"}]','A','韦达定理：x₁·x₂=c/a=10','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0026-1','math','高中',13,'hs-kp-0026','single_choice',0.45,'不等式 x²-8x+7<0 的解集是？','[{"key":"A","text":"1<x<7"},{"key":"B","text":"x<1 或 x>7"},{"key":"C","text":"x>1"},{"key":"D","text":"x<7"}]','A','对应方程两根 1、7，二次系数>0，小于取中间：1<x<7','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0026-2','math','高中',13,'hs-kp-0026','single_choice',0.45,'不等式 x²-21x+30<0 的解集是？','[{"key":"A","text":"2<x<5"},{"key":"B","text":"x<2 或 x>5"},{"key":"C","text":"x>2"},{"key":"D","text":"x<5"}]','A','对应方程两根 2、5，二次系数>0，小于取中间：2<x<5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0026-3','math','高中',13,'hs-kp-0026','single_choice',0.45,'不等式 x²-27x+24<0 的解集是？','[{"key":"A","text":"1<x<8"},{"key":"B","text":"x<1 或 x>8"},{"key":"C","text":"x>1"},{"key":"D","text":"x<8"}]','A','对应方程两根 1、8，二次系数>0，小于取中间：1<x<8','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0027-1','math','高中',13,'hs-kp-0027','single_choice',0.55,'若 ∀x∈R，x²+2x+1+1>0 恒成立，则满足？','[{"key":"A","text":"恒成立（判别式<0）"},{"key":"B","text":"需要 a>0"},{"key":"C","text":"需要 a<0"},{"key":"D","text":"不可能恒成立"}]','A','x²+2x+1+1=(x+1)²+1>0 恒成立','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0027-2','math','高中',13,'hs-kp-0027','single_choice',0.55,'若 ∀x∈R，x²+4x+4+1>0 恒成立，则满足？','[{"key":"A","text":"恒成立（判别式<0）"},{"key":"B","text":"需要 a>0"},{"key":"C","text":"需要 a<0"},{"key":"D","text":"不可能恒成立"}]','A','x²+4x+4+1=(x+2)²+1>0 恒成立','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0027-3','math','高中',13,'hs-kp-0027','single_choice',0.55,'若 ∀x∈R，x²+6x+9+1>0 恒成立，则满足？','[{"key":"A","text":"恒成立（判别式<0）"},{"key":"B","text":"需要 a>0"},{"key":"C","text":"需要 a<0"},{"key":"D","text":"不可能恒成立"}]','A','x²+6x+9+1=(x+3)²+1>0 恒成立','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0028-1','math','高中',13,'hs-kp-0028','single_choice',0.65,'若 ∃x∈R，x²=5，则 a 满足？','[{"key":"A","text":"a ≥ 0"},{"key":"B","text":"a > 0"},{"key":"C","text":"a ≤ 0"},{"key":"D","text":"a < 0"}]','A','x²=a 有解当且仅当 a≥0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0028-2','math','高中',13,'hs-kp-0028','single_choice',0.65,'若 ∃x∈R，x²=2，则 a 满足？','[{"key":"A","text":"a ≥ 0"},{"key":"B","text":"a > 0"},{"key":"C","text":"a ≤ 0"},{"key":"D","text":"a < 0"}]','A','x²=a 有解当且仅当 a≥0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0028-3','math','高中',13,'hs-kp-0028','single_choice',0.65,'若 ∃x∈R，x²=4，则 a 满足？','[{"key":"A","text":"a ≥ 0"},{"key":"B","text":"a > 0"},{"key":"C","text":"a ≤ 0"},{"key":"D","text":"a < 0"}]','A','x²=a 有解当且仅当 a≥0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0029-1','math','高中',13,'hs-kp-0029','single_choice',0.75,'二次函数 y=2x² 的开口方向是？','[{"key":"A","text":"向上"},{"key":"B","text":"向下"},{"key":"C","text":"向左"},{"key":"D","text":"向右"}]','A','二次项系数 2>0，开口向上','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0029-2','math','高中',13,'hs-kp-0029','single_choice',0.75,'二次函数 y=3x² 的开口方向是？','[{"key":"A","text":"向上"},{"key":"B","text":"向下"},{"key":"C","text":"向左"},{"key":"D","text":"向右"}]','A','二次项系数 3>0，开口向上','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0030-1','math','高中',13,'hs-kp-0030','single_choice',0.35,'二次函数 y=x²-4x+4 与 x 轴的交点个数是？','[{"key":"A","text":"1 个"},{"key":"B","text":"0 个"},{"key":"C","text":"2 个"},{"key":"D","text":"3 个"}]','A','y=(x-2)² 顶点在 x 轴上，Δ=0，恰 1 个交点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0030-2','math','高中',13,'hs-kp-0030','single_choice',0.35,'二次函数 y=x²-2x+1 与 x 轴的交点个数是？','[{"key":"A","text":"1 个"},{"key":"B","text":"0 个"},{"key":"C","text":"2 个"},{"key":"D","text":"3 个"}]','A','y=(x-1)² 顶点在 x 轴上，Δ=0，恰 1 个交点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0030-3','math','高中',13,'hs-kp-0030','single_choice',0.35,'二次函数 y=x²-6x+9 与 x 轴的交点个数是？','[{"key":"A","text":"1 个"},{"key":"B","text":"0 个"},{"key":"C","text":"2 个"},{"key":"D","text":"3 个"}]','A','y=(x-3)² 顶点在 x 轴上，Δ=0，恰 1 个交点','template-hs','approved','通用');