-- ============================================================
-- 第17章 随机变量及其分布 补题（16学期, 知识点 225-238）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0225-1','math','高中',16,'hs-kp-0225','single_choice',0.35,'下列对「离散型随机变量与分布列」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','离散型随机变量与分布列是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0226-1','math','高中',16,'hs-kp-0226','single_choice',0.45,'下列对「条件概率公式与性质」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','条件概率公式与性质是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0227-1','math','高中',16,'hs-kp-0227','single_choice',0.55,'下列对「概率乘法公式」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','概率乘法公式是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0228-1','math','高中',16,'hs-kp-0228','single_choice',0.65,'下列对「全概率公式、贝叶斯公式」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','全概率公式、贝叶斯公式是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0229-1','math','高中',16,'hs-kp-0229','single_choice',0.75,'下列对「离散型随机变量期望」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','离散型随机变量期望是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0230-1','math','高中',16,'hs-kp-0230','single_choice',0.35,'下列对「离散型随机变量方差」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','离散型随机变量方差是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0231-1','math','高中',16,'hs-kp-0231','single_choice',0.45,'下列对「期望方差运算性质」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','期望方差运算性质是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0232-1','math','高中',16,'hs-kp-0232','single_choice',0.55,'下列对「二项分布模型」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','二项分布模型是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0233-1','math','高中',16,'hs-kp-0233','single_choice',0.65,'下列对「二项分布期望方差」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','二项分布期望方差是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0234-1','math','高中',16,'hs-kp-0234','single_choice',0.75,'下列对「超几何分布模型」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','超几何分布模型是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0235-1','math','高中',16,'hs-kp-0235','single_choice',0.35,'下列对「超几何分布期望」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','超几何分布期望是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0236-1','math','高中',16,'hs-kp-0236','single_choice',0.45,'下列对「正态分布定义」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','正态分布定义是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0237-1','math','高中',16,'hs-kp-0237','single_choice',0.55,'下列对「正态曲线性质」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','正态曲线性质是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0238-1','math','高中',16,'hs-kp-0238','single_choice',0.65,'下列对「3σ原则应用」的理解正确的是？','[{"key":"A","text":"它属于随机变量及其分布的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','3σ原则应用是随机变量及其分布（第17章）的正式知识点','template-hs','approved','通用');