-- ============================================================
-- 第6章 平面向量及其应用 补题（14学期, 知识点 73-87）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0073-1','math','高中',14,'hs-kp-0073','single_choice',0.65,'下列对「向量加法法则」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量加法法则是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0074-1','math','高中',14,'hs-kp-0074','single_choice',0.75,'下列对「向量减法法则」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量减法法则是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0075-1','math','高中',14,'hs-kp-0075','single_choice',0.35,'下列对「向量平行判定」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量平行判定是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0076-1','math','高中',14,'hs-kp-0076','single_choice',0.45,'下列对「向量垂直判定」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量垂直判定是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0077-1','math','高中',14,'hs-kp-0077','single_choice',0.55,'下列对「向量数量积公式」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量数量积公式是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0078-1','math','高中',14,'hs-kp-0078','single_choice',0.65,'下列对「向量模长公式」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量模长公式是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0079-1','math','高中',14,'hs-kp-0079','single_choice',0.75,'下列对「向量投影计算」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量投影计算是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0080-1','math','高中',14,'hs-kp-0080','single_choice',0.35,'下列对「向量夹角公式」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量夹角公式是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0081-1','math','高中',14,'hs-kp-0081','single_choice',0.45,'下列对「单位向量求解」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','单位向量求解是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0082-1','math','高中',14,'hs-kp-0082','single_choice',0.55,'下列对「三点共线向量判定」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','三点共线向量判定是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0083-1','math','高中',14,'hs-kp-0083','single_choice',0.65,'下列对「三角形四心向量表示」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','三角形四心向量表示是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0084-1','math','高中',14,'hs-kp-0084','single_choice',0.75,'下列对「正弦定理及变形」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','正弦定理及变形是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0085-1','math','高中',14,'hs-kp-0085','single_choice',0.35,'下列对「余弦定理及变形」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','余弦定理及变形是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0086-1','math','高中',14,'hs-kp-0086','single_choice',0.45,'下列对「三角形面积公式」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','三角形面积公式是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0087-1','math','高中',14,'hs-kp-0087','single_choice',0.55,'下列对「解三角形综合问题」的理解正确的是？','[{"key":"A","text":"它属于平面向量及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','解三角形综合问题是平面向量及其应用（第6章）的正式知识点','template-hs','approved','通用');