-- ============================================================
-- 第13章 圆锥曲线的方程 补题（15学期, 知识点 172-186）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0172-1','math','高中',15,'hs-kp-0172','single_choice',0.55,'到两定点距离和为定值（大于焦距）的轨迹是？','[{"key":"A","text":"椭圆"},{"key":"B","text":"双曲线"},{"key":"C","text":"抛物线"},{"key":"D","text":"圆"}]','A','椭圆定义：到两焦点距离和为常数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0173-1','math','高中',15,'hs-kp-0173','single_choice',0.65,'椭圆 x²/16+y²/4=1 的 a = ？','[{"key":"A","text":"4"},{"key":"B","text":"2"},{"key":"C","text":"16"},{"key":"D","text":"4"}]','A','标准方程 x²/a²+y²/b²=1 → a=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0174-1','math','高中',15,'hs-kp-0174','single_choice',0.75,'椭圆 x²/25+y²/9=1 的离心率 e = ？','[{"key":"A","text":"0.80"},{"key":"B","text":"4"},{"key":"C","text":"5"},{"key":"D","text":"1"}]','A','c=√(a²-b²)=4，e=c/a=0.80','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0175-1','math','高中',15,'hs-kp-0175','single_choice',0.35,'双曲线 x²/16-y²/4=1 的渐近线 = ？','[{"key":"A","text":"y=±(2/4)x"},{"key":"B","text":"y=±(4/2)x"},{"key":"C","text":"y=±2x"},{"key":"D","text":"y=±4x"}]','A','渐近线 y=±(b/a)x=±(2/4)x','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0176-1','math','高中',15,'hs-kp-0176','single_choice',0.45,'等轴双曲线 x²-y²=4 的渐近线为？','[{"key":"A","text":"y=±x"},{"key":"B","text":"y=±2x"},{"key":"C","text":"y=±3x"},{"key":"D","text":"y=0"}]','A','等轴双曲线 a=b，渐近线 y=±x','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0177-1','math','高中',15,'hs-kp-0177','single_choice',0.55,'抛物线 y²=2x 的通径长 = ？','[{"key":"A","text":"2"},{"key":"B","text":"1"},{"key":"C","text":"4"},{"key":"D","text":"0.5"}]','A','通径=2p=2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0178-1','math','高中',15,'hs-kp-0178','single_choice',0.65,'双曲线 x²-y²/4=1，焦点(±√2,0)到渐近线 y=±2x 距离 = ？','[{"key":"A","text":"1.2649110640673518"},{"key":"B","text":"2"},{"key":"C","text":"1.4142135623730951"},{"key":"D","text":"1"}]','A','d=|b×√2|/√(b²+1)=1.26','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0179-1','math','高中',15,'hs-kp-0179','single_choice',0.75,'椭圆左焦点到右顶点的焦半径最大值 a+c，a=4,c=2 → ？','[{"key":"A","text":"6"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"2"}]','A','焦半径范围 [a-c,a+c]=[2,6]','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0180-1','math','高中',15,'hs-kp-0180','single_choice',0.35,'椭圆 x²/4+y²/4=1 焦点三角形面积最大 = b²·tan(θ/2)，b=2，θ=90° → S=？','[{"key":"A","text":"4"},{"key":"B","text":"8"},{"key":"C","text":"2"},{"key":"D","text":"2"}]','A','S=b²tan45°=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0181-1','math','高中',15,'hs-kp-0181','single_choice',0.45,'直线 y=x 与椭圆 x²/16+y²/16=1 的交点个数 = ？','[{"key":"A","text":"2"},{"key":"B","text":"0"},{"key":"C","text":"1"},{"key":"D","text":"3"}]','A','代入得 2x²=16，x=±4/√2 → 2 个交点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0182-1','math','高中',15,'hs-kp-0182','single_choice',0.55,'抛物线 y²=12x 焦点弦长（通径） = ？','[{"key":"A","text":"12"},{"key":"B","text":"6"},{"key":"C","text":"3"},{"key":"D","text":"24"}]','A','焦点弦长（通径）=2p=12','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0183-1','math','高中',15,'hs-kp-0183','single_choice',0.65,'抛物线焦点弦两端点纵坐标乘积为？','[{"key":"A","text":"-p²"},{"key":"B","text":"p²"},{"key":"C","text":"0"},{"key":"D","text":"2p"}]','A','焦点弦性质：y₁y₂=-p²','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0184-1','math','高中',15,'hs-kp-0184','single_choice',0.75,'直线与圆锥曲线相交，弦长公式 = ？','[{"key":"A","text":"√(1+k²)|x₁-x₂|"},{"key":"B","text":"|x₁-x₂|"},{"key":"C","text":"|y₁-y₂|"},{"key":"D","text":"(1+k²)|x₁-x₂|"}]','A','弦长=√(1+k²)|x₁-x₂|','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0185-1','math','高中',15,'hs-kp-0185','single_choice',0.35,'椭圆 x²/4+y²=1 在点 (2,0) 处切线 = ？','[{"key":"A","text":"x=2"},{"key":"B","text":"y=1"},{"key":"C","text":"x+y=2"},{"key":"D","text":"y=x"}]','A','顶点处切线垂直于 x 轴：x=2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0186-1','math','高中',15,'hs-kp-0186','single_choice',0.45,'椭圆 x²/16+y²/16=1 上点 P 与两焦点连线所成三角形周长为？','[{"key":"A","text":"8"},{"key":"B","text":"8"},{"key":"C","text":"16"},{"key":"D","text":"4"}]','A','周长=2a+2c，c=0 → 2a=8','template-hs','approved','通用');