-- ============================================================
-- 第7章 复数 补题（14学期, 知识点 88-96）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0088-1','math','高中',14,'hs-kp-0088','single_choice',0.65,'i^8 = ？','[{"key":"A","text":1},{"key":"B","text":"1"},{"key":"C","text":"-1"},{"key":"D","text":"i"}]','A','i 的幂以 4 为周期：i^8=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0088-2','math','高中',14,'hs-kp-0088','single_choice',0.65,'i^3 = ？','[{"key":"A","text":"-i"},{"key":"B","text":"1"},{"key":"C","text":"-1"},{"key":"D","text":"i"}]','A','i 的幂以 4 为周期：i^3=-i','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0088-3','math','高中',14,'hs-kp-0088','single_choice',0.65,'i^4 = ？','[{"key":"A","text":1},{"key":"B","text":"1"},{"key":"C","text":"-1"},{"key":"D","text":"i"}]','A','i 的幂以 4 为周期：i^4=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0089-1','math','高中',14,'hs-kp-0089','single_choice',0.75,'z=3+6i，|z| = ？','[{"key":"A","text":"6.708203932499369"},{"key":"B","text":"9"},{"key":"C","text":"18"},{"key":"D","text":"3"}]','A','|z|=√(3²+6²)=6.708203932499369','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0089-2','math','高中',14,'hs-kp-0089','single_choice',0.75,'z=2+3i，|z| = ？','[{"key":"A","text":"3.6055512754639896"},{"key":"B","text":"5"},{"key":"C","text":"6"},{"key":"D","text":"1"}]','A','|z|=√(2²+3²)=3.6055512754639896','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0089-3','math','高中',14,'hs-kp-0089','single_choice',0.75,'z=5+4i，|z| = ？','[{"key":"A","text":"6.4031242374328485"},{"key":"B","text":"9"},{"key":"C","text":"20"},{"key":"D","text":"-1"}]','A','|z|=√(5²+4²)=6.4031242374328485','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0090-1','math','高中',14,'hs-kp-0090','single_choice',0.35,'z=1+2i，则 z̄ = ？','[{"key":"A","text":"1-2i"},{"key":"B","text":"-1-2i"},{"key":"C","text":"-1+2i"},{"key":"D","text":"1+2i"}]','A','共轭复数：虚部变号，z̄=1-2i','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0090-2','math','高中',14,'hs-kp-0090','single_choice',0.35,'z=3+2i，则 z̄ = ？','[{"key":"A","text":"3-2i"},{"key":"B","text":"-3-2i"},{"key":"C","text":"-3+2i"},{"key":"D","text":"3+2i"}]','A','共轭复数：虚部变号，z̄=3-2i','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0090-3','math','高中',14,'hs-kp-0090','single_choice',0.35,'z=2+2i，则 z̄ = ？','[{"key":"A","text":"2-2i"},{"key":"B","text":"-2-2i"},{"key":"C","text":"-2+2i"},{"key":"D","text":"2+2i"}]','A','共轭复数：虚部变号，z̄=2-2i','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0091-1','math','高中',14,'hs-kp-0091','single_choice',0.45,'z=4+2i，z·z̄ = ？','[{"key":"A","text":"20"},{"key":"B","text":"16"},{"key":"C","text":"4"},{"key":"D","text":"6"}]','A','z·z̄=a²+b²=4²+2²=20','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0091-2','math','高中',14,'hs-kp-0091','single_choice',0.45,'z=5+1i，z·z̄ = ？','[{"key":"A","text":"26"},{"key":"B","text":"25"},{"key":"C","text":"1"},{"key":"D","text":"6"}]','A','z·z̄=a²+b²=5²+1²=26','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0091-3','math','高中',14,'hs-kp-0091','single_choice',0.45,'z=3+1i，z·z̄ = ？','[{"key":"A","text":"10"},{"key":"B","text":"9"},{"key":"C","text":"1"},{"key":"D","text":"4"}]','A','z·z̄=a²+b²=3²+1²=10','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0092-1','math','高中',14,'hs-kp-0092','single_choice',0.55,'(2+1i)+(1+3i) = ？','[{"key":"A","text":"3+4i"},{"key":"B","text":"3-4i"},{"key":"C","text":"1+-2i"},{"key":"D","text":"2+3i"}]','A','复数加法：实部加实部，虚部加虚部 = 3+4i','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0092-2','math','高中',14,'hs-kp-0092','single_choice',0.55,'(4+3i)+(2+1i) = ？','[{"key":"A","text":"6+4i"},{"key":"B","text":"6-4i"},{"key":"C","text":"2+2i"},{"key":"D","text":"8+3i"}]','A','复数加法：实部加实部，虚部加虚部 = 6+4i','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0092-3','math','高中',14,'hs-kp-0092','single_choice',0.55,'(2+1i)+(2+2i) = ？','[{"key":"A","text":"4+3i"},{"key":"B","text":"4-3i"},{"key":"C","text":"0+-1i"},{"key":"D","text":"4+2i"}]','A','复数加法：实部加实部，虚部加虚部 = 4+3i','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0093-1','math','高中',14,'hs-kp-0093','single_choice',0.65,'复数 z=4+4i 在复平面内对应的点？','[{"key":"A","text":"(4,4)"},{"key":"B","text":"(4,4)"},{"key":"C","text":"(4,-4)"},{"key":"D","text":"(-4,4)"}]','A','z=a+bi 对应点 (a,b) = (4,4)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0093-2','math','高中',14,'hs-kp-0093','single_choice',0.65,'复数 z=2+1i 在复平面内对应的点？','[{"key":"A","text":"(2,1)"},{"key":"B","text":"(1,2)"},{"key":"C","text":"(2,-1)"},{"key":"D","text":"(-2,1)"}]','A','z=a+bi 对应点 (a,b) = (2,1)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0093-3','math','高中',14,'hs-kp-0093','single_choice',0.65,'复数 z=3+4i 在复平面内对应的点？','[{"key":"A","text":"(3,4)"},{"key":"B","text":"(4,3)"},{"key":"C","text":"(3,-4)"},{"key":"D","text":"(-3,4)"}]','A','z=a+bi 对应点 (a,b) = (3,4)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0094-1','math','高中',14,'hs-kp-0094','single_choice',0.75,'若 3+3i = x+yi，则 x、y = ？','[{"key":"A","text":"x=3，y=3"},{"key":"B","text":"x=3，y=3"},{"key":"C","text":"x=3，y=-3"},{"key":"D","text":"x=-3，y=3"}]','A','复数相等：实部实部、虚部虚部相等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0094-2','math','高中',14,'hs-kp-0094','single_choice',0.75,'若 4+4i = x+yi，则 x、y = ？','[{"key":"A","text":"x=4，y=4"},{"key":"B","text":"x=4，y=4"},{"key":"C","text":"x=4，y=-4"},{"key":"D","text":"x=-4，y=4"}]','A','复数相等：实部实部、虚部虚部相等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0094-3','math','高中',14,'hs-kp-0094','single_choice',0.75,'若 2+1i = x+yi，则 x、y = ？','[{"key":"A","text":"x=2，y=1"},{"key":"B","text":"x=1，y=2"},{"key":"C","text":"x=2，y=-1"},{"key":"D","text":"x=-2，y=1"}]','A','复数相等：实部实部、虚部虚部相等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0095-1','math','高中',14,'hs-kp-0095','single_choice',0.35,'复数 z 为实数的条件是？','[{"key":"A","text":"虚部=0"},{"key":"B","text":"实部=0"},{"key":"C","text":"实部=虚部"},{"key":"D","text":"模=1"}]','A','z=a+bi 为实数 ⇔ b=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0095-2','math','高中',14,'hs-kp-0095','single_choice',0.35,'复数 z 为实数的条件是？','[{"key":"A","text":"虚部=0"},{"key":"D","text":"模=1"},{"key":"C","text":"实部=虚部"},{"key":"B","text":"实部=0"}]','A','z=a+bi 为实数 ⇔ b=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0096-1','math','高中',14,'hs-kp-0096','single_choice',0.45,'|3+3i| 与 |3+3i| 的关系？','[{"key":"A","text":"相等"},{"key":"B","text":"前者大"},{"key":"C","text":"后者大"},{"key":"D","text":"无法比较"}]','A','两者模均为 √18，相等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0096-2','math','高中',14,'hs-kp-0096','single_choice',0.45,'|2+2i| 与 |2+2i| 的关系？','[{"key":"A","text":"相等"},{"key":"B","text":"前者大"},{"key":"C","text":"后者大"},{"key":"D","text":"无法比较"}]','A','两者模均为 √8，相等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0096-3','math','高中',14,'hs-kp-0096','single_choice',0.45,'|2+3i| 与 |3+2i| 的关系？','[{"key":"A","text":"相等"},{"key":"B","text":"前者大"},{"key":"C","text":"后者大"},{"key":"D","text":"无法比较"}]','A','两者模均为 √13，相等','template-hs','approved','通用');