-- ============================================================
-- 第15章 一元函数的导数及其应用 补题（16学期, 知识点 199-212）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0199-1','math','高中',16,'hs-kp-0199','single_choice',0.75,'f''(x₀) = lim_{h→0} [f(x₀+h)-f(x₀)]/h 表示？','[{"key":"A","text":"x₀ 处瞬时变化率"},{"key":"B","text":"平均变化率"},{"key":"C","text":"函数值"},{"key":"D","text":"面积"}]','A','导数定义：瞬时变化率','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0200-1','math','高中',16,'hs-kp-0200','single_choice',0.35,'f(x)=x² 在 x=2 处的切线斜率 = f''(2) = ？','[{"key":"A","text":"4"},{"key":"B","text":"2"},{"key":"C","text":"4"},{"key":"D","text":"2"}]','A','f''(x)=2x，f''(2)=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0201-1','math','高中',16,'hs-kp-0201','single_choice',0.45,'(x^2)'' = ？','[{"key":"A","text":"2x^1"},{"key":"B","text":"x^1"},{"key":"C","text":"2x^2"},{"key":"D","text":"1x^1"}]','A','幂函数求导：2x^1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0202-1','math','高中',16,'hs-kp-0202','single_choice',0.55,'(x²+3x)'' = ？','[{"key":"A","text":"2x+3"},{"key":"B","text":"x+3"},{"key":"C","text":"2x"},{"key":"D","text":"3"}]','A','逐项求导：2x+3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0203-1','math','高中',16,'hs-kp-0203','single_choice',0.65,'(sin(4x))'' = ？','[{"key":"A","text":"4cos(4x)"},{"key":"B","text":"cos(4x)"},{"key":"C","text":"-4sin(4x)"},{"key":"D","text":"4sin(4x)"}]','A','复合求导：外层 cos × 内层 4 = 4cos(4x)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0204-1','math','高中',16,'hs-kp-0204','single_choice',0.75,'f(x)=x²，在点 (2,4) 处切线方程？','[{"key":"A","text":"y=4x-4"},{"key":"B","text":"y=2x"},{"key":"C","text":"y=4x"},{"key":"D","text":"y=x²"}]','A','k=f''(2)=4，切线 y-4=4(x-2) → y=4x-4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0205-1','math','高中',16,'hs-kp-0205','single_choice',0.35,'过曲线外一点求切线，步骤是先？','[{"key":"A","text":"设切点坐标，代入求切点"},{"key":"B","text":"直接求斜率"},{"key":"C","text":"求导数即可"},{"key":"D","text":"画图猜"}]','A','曲线外点切线：设切点 (x₀,f(x₀)) 求解','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0206-1','math','高中',16,'hs-kp-0206','single_choice',0.45,'f(x)=x²-4x，f''(x)=0 时 x = ？','[{"key":"A","text":"2"},{"key":"B","text":"4"},{"key":"C","text":"8"},{"key":"D","text":"0"}]','A','f''(x)=2x-4=0 → x=4/2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0207-1','math','高中',16,'hs-kp-0207','single_choice',0.55,'f(x)=x³-4x 的极值点 x = ±√(4/3) ≈ ？','[{"key":"A","text":"±√1.3"},{"key":"B","text":"±4"},{"key":"C","text":"±1.3333333333333333"},{"key":"D","text":"0"}]','A','f''(x)=3x²-4=0 → x=±√(4/3)=±√1.3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0208-1','math','高中',16,'hs-kp-0208','single_choice',0.65,'证明 x>1 时 x²>x-1，可构造函数？','[{"key":"A","text":"f(x)=x²-x+1"},{"key":"B","text":"f(x)=x"},{"key":"C","text":"f(x)=x²"},{"key":"D","text":"f(x)=x+1"}]','A','构造函数 f(x)=x²-x+1，求导证 f(x)>0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0209-1','math','高中',16,'hs-kp-0209','single_choice',0.75,'常用不等式 ln x ≤ x-1（x>0），则 ln 2 与 1 的关系？','[{"key":"A","text":"ln2<1"},{"key":"B","text":"ln2>1"},{"key":"C","text":"ln2=1"},{"key":"D","text":"无法比较"}]','A','ln x ≤ x-1，x=2 时 ln2 ≤ 1，且取不到等号 → ln2<1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0210-1','math','高中',16,'hs-kp-0210','single_choice',0.35,'e^x ≥ x+1（x∈R）恒成立，当 x=0 时？','[{"key":"A","text":"取等号"},{"key":"B","text":"取不到"},{"key":"C","text":"不成立"},{"key":"D","text":"无意义"}]','A','e⁰=1，0+1=1 → x=0 时取等','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0211-1','math','高中',16,'hs-kp-0211','single_choice',0.45,'f(x)=x²-2x 在 [1,2] 恒 ≤ 0 需 f(1)≤0 且 f(2)≤0 → a ≥ ？','[{"key":"A","text":"2"},{"key":"B","text":"2"},{"key":"C","text":"1"},{"key":"D","text":"2"}]','A','需 f(1)=1-2≤0 且 f(2)=4-4≤0 → a≥2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0212-1','math','高中',16,'hs-kp-0212','single_choice',0.55,'存在 x 使 x²=1 → 即 a 满足？','[{"key":"A","text":"a≥0"},{"key":"B","text":"a>0"},{"key":"C","text":"a≤0"},{"key":"D","text":"a<0"}]','A','x²=a 有解 ⇔ a≥0','template-hs','approved','通用');