-- ============================================================
-- 第12章 直线与圆的方程 补题（15学期, 知识点 157-171）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0157-1','math','高中',15,'hs-kp-0157','single_choice',0.55,'直线斜率 k=tanθ，θ=45°，k = ？','[{"key":"A","text":"1"},{"key":"B","text":"0"},{"key":"C","text":"√3"},{"key":"D","text":"不存在"}]','A','k=tan45°=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0157-2','math','高中',15,'hs-kp-0157','single_choice',0.55,'直线斜率 k=tanθ，θ=45°，k = ？','[{"key":"C","text":"√3"},{"key":"D","text":"不存在"},{"key":"B","text":"0"},{"key":"A","text":"1"}]','A','k=tan45°=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0157-3','math','高中',15,'hs-kp-0157','single_choice',0.55,'直线斜率 k=tanθ，θ=45°，k = ？','[{"key":"A","text":"1"},{"key":"C","text":"√3"},{"key":"B","text":"0"},{"key":"D","text":"不存在"}]','A','k=tan45°=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0158-1','math','高中',15,'hs-kp-0158','single_choice',0.65,'直线 y=3x+2 的斜截式对应的斜率是？','[{"key":"A","text":"3"},{"key":"B","text":"2"},{"key":"C","text":"-3"},{"key":"D","text":"-2"}]','A','y=kx+b 中斜率 k','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0158-2','math','高中',15,'hs-kp-0158','single_choice',0.65,'直线 y=4x+3 的斜截式对应的斜率是？','[{"key":"A","text":"4"},{"key":"B","text":"3"},{"key":"C","text":"-4"},{"key":"D","text":"-3"}]','A','y=kx+b 中斜率 k','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0158-3','math','高中',15,'hs-kp-0158','single_choice',0.65,'直线 y=1x+1 的斜截式对应的斜率是？','[{"key":"A","text":"1"},{"key":"B","text":"1"},{"key":"C","text":"-1"},{"key":"D","text":"-1"}]','A','y=kx+b 中斜率 k','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0159-1','math','高中',15,'hs-kp-0159','single_choice',0.75,'直线 y=k(x-2)+3 恒过定点？','[{"key":"A","text":"(2,3)"},{"key":"B","text":"(-2,3)"},{"key":"C","text":"(2,-3)"},{"key":"D","text":"(0,0)"}]','A','x=2 时 y=3，恒过 (2,3)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0159-2','math','高中',15,'hs-kp-0159','single_choice',0.75,'直线 y=k(x-2)+3 恒过定点？','[{"key":"D","text":"(0,0)"},{"key":"C","text":"(2,-3)"},{"key":"B","text":"(-2,3)"},{"key":"A","text":"(2,3)"}]','A','x=2 时 y=3，恒过 (2,3)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0159-3','math','高中',15,'hs-kp-0159','single_choice',0.75,'直线 y=k(x-2)+3 恒过定点？','[{"key":"B","text":"(-2,3)"},{"key":"C","text":"(2,-3)"},{"key":"D","text":"(0,0)"},{"key":"A","text":"(2,3)"}]','A','x=2 时 y=3，恒过 (2,3)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0160-1','math','高中',15,'hs-kp-0160','single_choice',0.35,'两直线 y=3x+1 与 y=-x/3 的关系（斜率乘积-1）？','[{"key":"A","text":"垂直"},{"key":"B","text":"平行"},{"key":"C","text":"重合"},{"key":"D","text":"斜交"}]','A','k₁·k₂=3×(-1/3)=-1 → 垂直','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0160-2','math','高中',15,'hs-kp-0160','single_choice',0.35,'两直线 y=2x+1 与 y=-x/2 的关系（斜率乘积-1）？','[{"key":"A","text":"垂直"},{"key":"B","text":"平行"},{"key":"C","text":"重合"},{"key":"D","text":"斜交"}]','A','k₁·k₂=2×(-1/2)=-1 → 垂直','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0160-3','math','高中',15,'hs-kp-0160','single_choice',0.35,'两直线 y=3x+1 与 y=-x/3 的关系（斜率乘积-1）？','[{"key":"A","text":"垂直"},{"key":"D","text":"斜交"},{"key":"C","text":"重合"},{"key":"B","text":"平行"}]','A','k₁·k₂=3×(-1/3)=-1 → 垂直','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0161-1','math','高中',15,'hs-kp-0161','single_choice',0.45,'点 P(1,1) 到直线 x-y+2=0 的距离 = ？','[{"key":"A","text":"2/√2"},{"key":"B","text":"2"},{"key":"C","text":"2.8284271247461903"},{"key":"D","text":"0"}]','A','d=|1-1+2|/√2=2/√2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0161-2','math','高中',15,'hs-kp-0161','single_choice',0.45,'点 P(1,1) 到直线 x-y+1=0 的距离 = ？','[{"key":"A","text":"1/√2"},{"key":"B","text":"1"},{"key":"C","text":"1.4142135623730951"},{"key":"D","text":"0"}]','A','d=|1-1+1|/√2=1/√2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0161-3','math','高中',15,'hs-kp-0161','single_choice',0.45,'点 P(1,1) 到直线 x-y+4=0 的距离 = ？','[{"key":"A","text":"4/√2"},{"key":"B","text":"4"},{"key":"C","text":"5.656854249492381"},{"key":"D","text":"0"}]','A','d=|1-1+4|/√2=4/√2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0162-1','math','高中',15,'hs-kp-0162','single_choice',0.55,'与直线 y=3x 平行的直线系方程为？','[{"key":"A","text":"y=3x+b (b 任意)"},{"key":"B","text":"y=-x/3+b"},{"key":"C","text":"y=3x"},{"key":"D","text":"x 任意"}]','A','平行直线系：斜率相同，截距任意','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0162-2','math','高中',15,'hs-kp-0162','single_choice',0.55,'与直线 y=4x 平行的直线系方程为？','[{"key":"A","text":"y=4x+b (b 任意)"},{"key":"B","text":"y=-x/4+b"},{"key":"C","text":"y=4x"},{"key":"D","text":"x 任意"}]','A','平行直线系：斜率相同，截距任意','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0162-3','math','高中',15,'hs-kp-0162','single_choice',0.55,'与直线 y=2x 平行的直线系方程为？','[{"key":"A","text":"y=2x+b (b 任意)"},{"key":"B","text":"y=-x/2+b"},{"key":"C","text":"y=2x"},{"key":"D","text":"x 任意"}]','A','平行直线系：斜率相同，截距任意','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0163-1','math','高中',15,'hs-kp-0163','single_choice',0.65,'圆心 (0,0) 半径 4 的圆方程 = ？','[{"key":"A","text":"x²+y²=16"},{"key":"B","text":"x²+y²=4"},{"key":"C","text":"x+y=4"},{"key":"D","text":"x²-y²=16"}]','A','标准方程：x²+y²=r²=16','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0163-2','math','高中',15,'hs-kp-0163','single_choice',0.65,'圆心 (0,0) 半径 3 的圆方程 = ？','[{"key":"A","text":"x²+y²=9"},{"key":"B","text":"x²+y²=3"},{"key":"C","text":"x+y=3"},{"key":"D","text":"x²-y²=9"}]','A','标准方程：x²+y²=r²=9','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0163-3','math','高中',15,'hs-kp-0163','single_choice',0.65,'圆心 (0,0) 半径 2 的圆方程 = ？','[{"key":"A","text":"x²+y²=4"},{"key":"B","text":"x²+y²=2"},{"key":"C","text":"x+y=2"},{"key":"D","text":"x²-y²=4"}]','A','标准方程：x²+y²=r²=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0164-1','math','高中',15,'hs-kp-0164','single_choice',0.75,'圆半径 6，弦心距 2，弦长 = ？','[{"key":"A","text":"2√32"},{"key":"B","text":"4"},{"key":"C","text":"4"},{"key":"D","text":"11.3"}]','A','弦长=2√(r²-d²)=2√(36-4)=2√32','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0164-2','math','高中',15,'hs-kp-0164','single_choice',0.75,'圆半径 5，弦心距 3，弦长 = ？','[{"key":"A","text":"2√16"},{"key":"B","text":"6"},{"key":"C","text":"2"},{"key":"D","text":"8"}]','A','弦长=2√(r²-d²)=2√(25-9)=2√16','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0164-3','math','高中',15,'hs-kp-0164','single_choice',0.75,'圆半径 6，弦心距 1，弦长 = ？','[{"key":"A","text":"2√35"},{"key":"B","text":"2"},{"key":"C","text":"5"},{"key":"D","text":"11.8"}]','A','弦长=2√(r²-d²)=2√(36-1)=2√35','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0165-1','math','高中',15,'hs-kp-0165','single_choice',0.35,'圆 x²+y²=9 上点 (3,0) 处的切线方程 = ？','[{"key":"A","text":"x=3"},{"key":"B","text":"y=3"},{"key":"C","text":"x+y=3"},{"key":"D","text":"x-y=3"}]','A','切点半径垂直切线，切线 x=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0165-2','math','高中',15,'hs-kp-0165','single_choice',0.35,'圆 x²+y²=16 上点 (4,0) 处的切线方程 = ？','[{"key":"A","text":"x=4"},{"key":"B","text":"y=4"},{"key":"C","text":"x+y=4"},{"key":"D","text":"x-y=4"}]','A','切点半径垂直切线，切线 x=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0165-3','math','高中',15,'hs-kp-0165','single_choice',0.35,'圆 x²+y²=4 上点 (2,0) 处的切线方程 = ？','[{"key":"A","text":"x=2"},{"key":"B","text":"y=2"},{"key":"C","text":"x+y=2"},{"key":"D","text":"x-y=2"}]','A','切点半径垂直切线，切线 x=2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0166-1','math','高中',15,'hs-kp-0166','single_choice',0.45,'圆心到直线距离 d=2，圆半径 r=2，直线与圆？','[{"key":"A","text":"相切"},{"key":"B","text":"相交"},{"key":"C","text":"相切"},{"key":"D","text":"相离"}]','A','d=2=r=2 → 相切','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0166-2','math','高中',15,'hs-kp-0166','single_choice',0.45,'圆心到直线距离 d=1，圆半径 r=2，直线与圆？','[{"key":"A","text":"相交"},{"key":"B","text":"相交"},{"key":"C","text":"相切"},{"key":"D","text":"相离"}]','A','d=1<r=2 → 相交','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0166-3','math','高中',15,'hs-kp-0166','single_choice',0.45,'圆心到直线距离 d=3，圆半径 r=4，直线与圆？','[{"key":"A","text":"相交"},{"key":"B","text":"相交"},{"key":"C","text":"相切"},{"key":"D","text":"相离"}]','A','d=3<r=4 → 相交','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0167-1','math','高中',15,'hs-kp-0167','single_choice',0.55,'两圆半径 3、2，圆心距 6，位置关系？','[{"key":"A","text":"外离"},{"key":"B","text":"内切"},{"key":"C","text":"内含"},{"key":"D","text":"无法确定"}]','A','d=6>r₁+r₂=5 → 外离','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0167-2','math','高中',15,'hs-kp-0167','single_choice',0.55,'两圆半径 2、2，圆心距 5，位置关系？','[{"key":"A","text":"外离"},{"key":"B","text":"内切"},{"key":"C","text":"内含"},{"key":"D","text":"无法确定"}]','A','d=5>r₁+r₂=4 → 外离','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0167-3','math','高中',15,'hs-kp-0167','single_choice',0.55,'两圆半径 3、2，圆心距 5，位置关系？','[{"key":"A","text":"外切"},{"key":"B","text":"内切"},{"key":"C","text":"内含"},{"key":"D","text":"无法确定"}]','A','d=5=r₁+r₂=5 → 外切','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0168-1','math','高中',15,'hs-kp-0168','single_choice',0.65,'两圆 x²+y²=1 与 x²+y²-2x=0 的公共弦所在直线方程？','[{"key":"A","text":"x=1/2"},{"key":"B","text":"y=1/2"},{"key":"C","text":"x=1"},{"key":"D","text":"y=1"}]','A','两圆方程相减得公共弦：2x=1 → x=1/2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0168-2','math','高中',15,'hs-kp-0168','single_choice',0.65,'两圆 x²+y²=1 与 x²+y²-2x=0 的公共弦所在直线方程？','[{"key":"B","text":"y=1/2"},{"key":"A","text":"x=1/2"},{"key":"C","text":"x=1"},{"key":"D","text":"y=1"}]','A','两圆方程相减得公共弦：2x=1 → x=1/2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0169-1','math','高中',15,'hs-kp-0169','single_choice',0.75,'过两圆交点的圆系方程为？','[{"key":"A","text":"C₁+λC₂=0"},{"key":"B","text":"C₁×C₂=0"},{"key":"C","text":"C₁=C₂"},{"key":"D","text":"C₁-C₂=1"}]','A','圆系：C₁+λC₂=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0169-2','math','高中',15,'hs-kp-0169','single_choice',0.75,'过两圆交点的圆系方程为？','[{"key":"C","text":"C₁=C₂"},{"key":"D","text":"C₁-C₂=1"},{"key":"B","text":"C₁×C₂=0"},{"key":"A","text":"C₁+λC₂=0"}]','A','圆系：C₁+λC₂=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0169-3','math','高中',15,'hs-kp-0169','single_choice',0.75,'过两圆交点的圆系方程为？','[{"key":"D","text":"C₁-C₂=1"},{"key":"A","text":"C₁+λC₂=0"},{"key":"B","text":"C₁×C₂=0"},{"key":"C","text":"C₁=C₂"}]','A','圆系：C₁+λC₂=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0170-1','math','高中',15,'hs-kp-0170','single_choice',0.35,'圆 x²+y²=4 上点到直线 x+y=0 距离最大值为？','[{"key":"A","text":"2"},{"key":"B","text":"4"},{"key":"C","text":"2.8284271247461903"},{"key":"D","text":"0"}]','A','圆心(0,0)到 x+y=0 距离 0，最大距离=圆心距+半径=2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0170-2','math','高中',15,'hs-kp-0170','single_choice',0.35,'圆 x²+y²=9 上点到直线 x+y=0 距离最大值为？','[{"key":"A","text":"3"},{"key":"B","text":"6"},{"key":"C","text":"4.242640687119286"},{"key":"D","text":"0"}]','A','圆心(0,0)到 x+y=0 距离 0，最大距离=圆心距+半径=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0170-3','math','高中',15,'hs-kp-0170','single_choice',0.35,'圆 x²+y²=4 上点到直线 x+y=0 距离最大值为？','[{"key":"D","text":"0"},{"key":"C","text":"2.8284271247461903"},{"key":"B","text":"4"},{"key":"A","text":"2"}]','A','圆心(0,0)到 x+y=0 距离 0，最大距离=圆心距+半径=2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0171-1','math','高中',15,'hs-kp-0171','single_choice',0.45,'到点 A(1,0) 距离等于 2 的点的轨迹是？','[{"key":"A","text":"圆 (x-1)²+y²=4"},{"key":"B","text":"直线 x=1"},{"key":"C","text":"抛物线"},{"key":"D","text":"双曲线"}]','A','到定点距离为定长 → 圆','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0171-2','math','高中',15,'hs-kp-0171','single_choice',0.45,'到点 A(1,0) 距离等于 2 的点的轨迹是？','[{"key":"D","text":"双曲线"},{"key":"C","text":"抛物线"},{"key":"B","text":"直线 x=1"},{"key":"A","text":"圆 (x-1)²+y²=4"}]','A','到定点距离为定长 → 圆','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0171-3','math','高中',15,'hs-kp-0171','single_choice',0.45,'到点 A(1,0) 距离等于 2 的点的轨迹是？','[{"key":"C","text":"抛物线"},{"key":"D","text":"双曲线"},{"key":"B","text":"直线 x=1"},{"key":"A","text":"圆 (x-1)²+y²=4"}]','A','到定点距离为定长 → 圆','template-hs','approved','通用');