-- ============================================================
-- 第4章 指数函数与对数函数 补题（13学期, 知识点 49-62）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0049-1','math','高中',13,'hs-kp-0049','single_choice',0.75,'√[2]{25} = ？','[{"key":"A","text":"5"},{"key":"B","text":"10"},{"key":"C","text":"25"},{"key":"D","text":"1"}]','A','5^2=25 → √[2]{25}=5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0050-1','math','高中',13,'hs-kp-0050','single_choice',0.35,'2^4 × 2^3 = ？','[{"key":"A","text":"128"},{"key":"B","text":"4096"},{"key":"C","text":"24"},{"key":"D","text":"2"}]','A','同底数幂相乘指数相加：2^7=128','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0051-1','math','高中',13,'hs-kp-0051','single_choice',0.45,'指数函数 y=2^x 恒过点？','[{"key":"A","text":"(0,1)"},{"key":"B","text":"(1,0)"},{"key":"C","text":"(0,0)"},{"key":"D","text":"(2,1)"}]','A','a⁰=1 → 恒过 (0,1)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0052-1','math','高中',13,'hs-kp-0052','single_choice',0.55,'log_3 1 = ？','[{"key":"A","text":"0"},{"key":"B","text":"1"},{"key":"C","text":"3"},{"key":"D","text":"-1"}]','A','任何底 log_a 1=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0053-1','math','高中',13,'hs-kp-0053','single_choice',0.65,'log₂32 + log₂16 = ？','[{"key":"A","text":"9"},{"key":"B","text":"5"},{"key":"C","text":"4"},{"key":"D","text":"20"}]','A','log₂32=5，log₂16=4，和=9','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0054-1','math','高中',13,'hs-kp-0054','single_choice',0.75,'换底公式 log_a b = ？','[{"key":"A","text":"log_c b / log_c a"},{"key":"B","text":"log_c a / log_c b"},{"key":"C","text":"log_a c × log_c b"},{"key":"D","text":"log_b c"}]','A','换底公式：log_a b = log_c b / log_c a','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0055-1','math','高中',13,'hs-kp-0055','single_choice',0.35,'对数函数 y=log_4 x 恒过点？','[{"key":"A","text":"(1,0)"},{"key":"B","text":"(0,1)"},{"key":"C","text":"(0,0)"},{"key":"D","text":"(1,1)"}]','A','log_a 1=0 → 恒过 (1,0)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0056-1','math','高中',13,'hs-kp-0056','single_choice',0.45,'幂函数 y=x^4 恒过点？','[{"key":"A","text":"(1,1)"},{"key":"B","text":"(0,1)"},{"key":"C","text":"(1,0)"},{"key":"D","text":"(4,0)"}]','A','1 的任何次幂为 1 → 恒过 (1,1)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0057-1','math','高中',13,'hs-kp-0057','single_choice',0.55,'f(x)=1x-3 的零点为？','[{"key":"A","text":"3"},{"key":"B","text":"-3"},{"key":"C","text":"3"},{"key":"D","text":"1"}]','A','令 f(x)=0 → x=3/1=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0058-1','math','高中',13,'hs-kp-0058','single_choice',0.65,'f(x)=x³-2x-1，若 f(2)·f(2+1)<0 → 零点区间？','[{"key":"A","text":"(2,3)"},{"key":"B","text":"(1,2)"},{"key":"C","text":"(3,4)"},{"key":"D","text":"无法确定"}]','A','零点存在性定理：端点异号则零点在区间内','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0059-1','math','高中',13,'hs-kp-0059','single_choice',0.75,'x²-5x+3=0 的判别式 Δ = ？','[{"key":"A","text":"13"},{"key":"B","text":"37"},{"key":"C","text":"-7"},{"key":"D","text":"12"}]','A','Δ=b²-4ac=5²-4×1×3=13','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0060-1','math','高中',13,'hs-kp-0060','single_choice',0.35,'比较 log₂6 与 log₂3 大小？','[{"key":"A","text":"前者大"},{"key":"B","text":"相等"},{"key":"C","text":"无法比较"},{"key":"D","text":"相等且最大"}]','A','log₂ 单调递增，6>3 → 前者大','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0061-1','math','高中',13,'hs-kp-0061','single_choice',0.45,'幂函数 y=x^4 在 (0,+∞) 单调？','[{"key":"A","text":"递增"},{"key":"B","text":"递减"},{"key":"C","text":"先增后减"},{"key":"D","text":"不单调"}]','A','指数 4>0 → 在 (0,+∞) 递增','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0062-1','math','高中',13,'hs-kp-0062','single_choice',0.55,'二分法求 f(x)=x²-4 零点，区间 [2,4] 第一次取中点？','[{"key":"A","text":"3"},{"key":"B","text":"1"},{"key":"C","text":"4"},{"key":"D","text":"2"}]','A','中点=(4+2)/2=3','template-hs','approved','通用');