-- ============================================================
-- 第17章 随机变量及其分布 补题（16学期, 知识点 225-238）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0225-1','math','高中',16,'hs-kp-0225','single_choice',0.35,'X 分布列：P(X=0)=2/10，P(X=1)=8/10，概率和 = ？','[{"key":"A","text":"1"},{"key":"B","text":"2/10"},{"key":"C","text":"8/10"},{"key":"D","text":"0.5"}]','A','分布列概率和为 1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0226-1','math','高中',16,'hs-kp-0226','single_choice',0.45,'P(B|A) = P(AB)/P(A)，P(AB)=5/10，P(A)=7/10 → P(B|A) = ？','[{"key":"A","text":"5/7"},{"key":"B","text":"5/10"},{"key":"C","text":"2/10"},{"key":"D","text":"7/10"}]','A','P(B|A)=(5/10)/(7/10)=5/7','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0227-1','math','高中',16,'hs-kp-0227','single_choice',0.55,'P(A)=3/10，P(B|A)=4/10，P(AB) = ？','[{"key":"A","text":"12/100"},{"key":"B","text":"3/10"},{"key":"C","text":"4/10"},{"key":"D","text":"1"}]','A','乘法公式：P(AB)=P(A)P(B|A)=3/10×4/10=12/100','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0228-1','math','高中',16,'hs-kp-0228','single_choice',0.65,'全概率公式：P(B) = ΣP(Aᵢ)P(B|Aᵢ)，用于？','[{"key":"A","text":"分情况求总概率"},{"key":"B","text":"求单一概率"},{"key":"C","text":"求方差"},{"key":"D","text":"求期望"}]','A','全概率公式：按互斥完备事件组分解','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0229-1','math','高中',16,'hs-kp-0229','single_choice',0.75,'X：P(X=0)=2/10，P(X=1)=8/10，E(X) = ？','[{"key":"A","text":"0.8"},{"key":"B","text":"2/10"},{"key":"C","text":"1"},{"key":"D","text":"0"}]','A','E(X)=0×2/10+1×8/10=0.8','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0230-1','math','高中',16,'hs-kp-0230','single_choice',0.35,'X~B(1,0.5)，D(X) = np(1-p) = ？','[{"key":"A","text":"0.25"},{"key":"B","text":"0.5"},{"key":"C","text":"1"},{"key":"D","text":"0.125"}]','A','D(X)=np(1-p)=1×0.5×0.5=0.25','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0231-1','math','高中',16,'hs-kp-0231','single_choice',0.45,'E(aX+b) = aE(X)+b，a=3,b=1，E(X)=2 → E(aX+b) = ？','[{"key":"A","text":"7"},{"key":"B","text":"6"},{"key":"C","text":"4"},{"key":"D","text":"2"}]','A','E=3×2+1=7','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0232-1','math','高中',16,'hs-kp-0232','single_choice',0.55,'X~B(4,0.5)，则 X 表示？','[{"key":"A","text":"4 次独立试验成功次数"},{"key":"B","text":"一次试验结果"},{"key":"C","text":"连续变量"},{"key":"D","text":"正态分布"}]','A','二项分布：n 重伯努利试验成功次数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0233-1','math','高中',16,'hs-kp-0233','single_choice',0.65,'X~B(4,0.5)，E(X) = 4×0.5 = ？','[{"key":"A","text":"2"},{"key":"B","text":"1"},{"key":"C","text":"4"},{"key":"D","text":"3"}]','A','E(X)=np=4×0.5=2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0234-1','math','高中',16,'hs-kp-0234','single_choice',0.75,'从 9 件（含 5 件次品）抽 4 件，次品数 X 服从？','[{"key":"A","text":"超几何分布"},{"key":"B","text":"二项分布"},{"key":"C","text":"正态分布"},{"key":"D","text":"均匀分布"}]','A','不放回抽样 → 超几何分布','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0235-1','math','高中',16,'hs-kp-0235','single_choice',0.35,'超几何：N=10,M=4,n=3，E(X) = nM/N = ？','[{"key":"A","text":"1.2"},{"key":"B","text":"4"},{"key":"C","text":"3"},{"key":"D","text":"0.4"}]','A','E(X)=nM/N=3×4/10=1.2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0236-1','math','高中',16,'hs-kp-0236','single_choice',0.45,'正态分布 X~N(μ,σ²)，其图像关于？对称','[{"key":"A","text":"直线 x=μ"},{"key":"B","text":"x 轴"},{"key":"C","text":"y 轴"},{"key":"D","text":"直线 x=σ"}]','A','正态曲线关于均值 μ 对称','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0237-1','math','高中',16,'hs-kp-0237','single_choice',0.55,'正态曲线在 x=μ 处取？','[{"key":"A","text":"最大值"},{"key":"B","text":"最小值"},{"key":"C","text":"0"},{"key":"D","text":"1"}]','A','正态曲线峰值在均值处','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0238-1','math','高中',16,'hs-kp-0238','single_choice',0.65,'3σ 原则：P(μ-3σ<X<μ+3σ) ≈ ？','[{"key":"A","text":"0.997"},{"key":"B","text":"0.68"},{"key":"C","text":"0.95"},{"key":"D","text":"1"}]','A','3σ 区间概率约 99.7%','template-hs','approved','通用');