-- ============================================================
-- 第3章 函数的概念与性质 补题（13学期, 知识点 31-48）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0031-1','math','高中',13,'hs-kp-0031','single_choice',0.45,'下列对「具体函数的定义域」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','具体函数的定义域是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0032-1','math','高中',13,'hs-kp-0032','single_choice',0.55,'下列对「抽象函数的定义域」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','抽象函数的定义域是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0033-1','math','高中',13,'hs-kp-0033','single_choice',0.65,'下列对「函数的单调性定义」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','函数的单调性定义是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0034-1','math','高中',13,'hs-kp-0034','single_choice',0.75,'下列对「复合函数的单调性」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','复合函数的单调性是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0035-1','math','高中',13,'hs-kp-0035','single_choice',0.35,'下列对「单调性的加减规律」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','单调性的加减规律是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0036-1','math','高中',13,'hs-kp-0036','single_choice',0.45,'下列对「函数图像的平移变换」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','函数图像的平移变换是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0037-1','math','高中',13,'hs-kp-0037','single_choice',0.55,'下列对「函数图像的伸缩变换」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','函数图像的伸缩变换是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0038-1','math','高中',13,'hs-kp-0038','single_choice',0.65,'下列对「函数图像的翻折变换」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','函数图像的翻折变换是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0039-1','math','高中',13,'hs-kp-0039','single_choice',0.75,'下列对「偶函数特性」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','偶函数特性是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0040-1','math','高中',13,'hs-kp-0040','single_choice',0.35,'下列对「奇函数特性」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','奇函数特性是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0041-1','math','高中',13,'hs-kp-0041','single_choice',0.45,'下列对「奇偶函数的四则运算」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','奇偶函数的四则运算是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0042-1','math','高中',13,'hs-kp-0042','single_choice',0.55,'下列对「复合函数的奇偶性」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','复合函数的奇偶性是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0043-1','math','高中',13,'hs-kp-0043','single_choice',0.65,'下列对「常见的奇函数」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','常见的奇函数是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0044-1','math','高中',13,'hs-kp-0044','single_choice',0.75,'下列对「常见的偶函数」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','常见的偶函数是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0045-1','math','高中',13,'hs-kp-0045','single_choice',0.35,'下列对「函数周期性结论」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','函数周期性结论是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0046-1','math','高中',13,'hs-kp-0046','single_choice',0.45,'下列对「函数的轴对称结论」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','函数的轴对称结论是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0047-1','math','高中',13,'hs-kp-0047','single_choice',0.55,'下列对「函数的中心对称结论」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','函数的中心对称结论是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0048-1','math','高中',13,'hs-kp-0048','single_choice',0.65,'下列对「对称性与周期性综合关系」的理解正确的是？','[{"key":"A","text":"它属于函数的概念与性质的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','对称性与周期性综合关系是函数的概念与性质（第3章）的正式知识点','template-hs','approved','通用');