-- ============================================================
-- 第4章 指数函数与对数函数 补题（13学期, 知识点 49-62）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0049-1','math','高中',13,'hs-kp-0049','single_choice',0.75,'下列对「根式性质」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','根式性质是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0050-1','math','高中',13,'hs-kp-0050','single_choice',0.35,'下列对「指数运算」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','指数运算是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0051-1','math','高中',13,'hs-kp-0051','single_choice',0.45,'下列对「指数函数图像规律」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','指数函数图像规律是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0052-1','math','高中',13,'hs-kp-0052','single_choice',0.55,'下列对「对数性质」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','对数性质是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0053-1','math','高中',13,'hs-kp-0053','single_choice',0.65,'下列对「对数运算」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','对数运算是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0054-1','math','高中',13,'hs-kp-0054','single_choice',0.75,'下列对「换底公式」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','换底公式是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0055-1','math','高中',13,'hs-kp-0055','single_choice',0.35,'下列对「对数函数图像规律」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','对数函数图像规律是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0056-1','math','高中',13,'hs-kp-0056','single_choice',0.45,'下列对「幂函数图像规律」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','幂函数图像规律是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0057-1','math','高中',13,'hs-kp-0057','single_choice',0.55,'下列对「函数的零点」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','函数的零点是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0058-1','math','高中',13,'hs-kp-0058','single_choice',0.65,'下列对「零点的存在性定理」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','零点的存在性定理是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0059-1','math','高中',13,'hs-kp-0059','single_choice',0.75,'下列对「二次函数根的分布问题」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','二次函数根的分布问题是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0060-1','math','高中',13,'hs-kp-0060','single_choice',0.35,'下列对「指数对数大小比较」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','指数对数大小比较是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0061-1','math','高中',13,'hs-kp-0061','single_choice',0.45,'下列对「幂函数基本性质」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','幂函数基本性质是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0062-1','math','高中',13,'hs-kp-0062','single_choice',0.55,'下列对「二分法求零点」的理解正确的是？','[{"key":"A","text":"它属于指数函数与对数函数的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','二分法求零点是指数函数与对数函数（第4章）的正式知识点','template-hs','approved','通用');