-- ============================================================
-- 第5章 三角函数 补题（13学期, 知识点 63-72）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0063-1','math','高中',13,'hs-kp-0063','single_choice',0.65,'45° = ？弧度','[{"key":"A","text":"π/4"},{"key":"B","text":"45π/180"},{"key":"C","text":"π"},{"key":"D","text":"2π"}]','A','45° = 45×π/180 = π/4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0064-1','math','高中',13,'hs-kp-0064','single_choice',0.75,'半径 3、圆心角 90° 的弧长 l = ？','[{"key":"A","text":"3×π/2"},{"key":"B","text":"3"},{"key":"C","text":"270"},{"key":"D","text":"π"}]','A','l = rθ = 3×90°(弧度) = 3×π/2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0065-1','math','高中',13,'hs-kp-0065','single_choice',0.35,'角 α 终边过点 (5,5)，sinα = ？','[{"key":"A","text":"5/7.0710678118654755"},{"key":"B","text":"5/7.0710678118654755"},{"key":"C","text":"5/5"},{"key":"D","text":"7.0710678118654755/5"}]','A','r=√(5²+5²)=7.0710678118654755，sinα=y/r=5/7.0710678118654755','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0066-1','math','高中',13,'hs-kp-0066','single_choice',0.45,'角 α 在第二象限，sinα 的符号是？','[{"key":"A","text":"正"},{"key":"B","text":"负"},{"key":"C","text":"0"},{"key":"D","text":"不确定"}]','A','第二象限 sin>0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0067-1','math','高中',13,'hs-kp-0067','single_choice',0.55,'sinα=3/5，α 为锐角，则 cosα = ？','[{"key":"A","text":"4/5"},{"key":"B","text":"3/5"},{"key":"C","text":"5/4"},{"key":"D","text":"5/3"}]','A','cosα=√(1-sin²α)=√(1-9/25)=4/5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0068-1','math','高中',13,'hs-kp-0068','single_choice',0.65,'sin(210°) = ？','[{"key":"A","text":"-1/2"},{"key":"B","text":"1/2"},{"key":"C","text":"0"},{"key":"D","text":"1"}]','A','sin(210°)=-sin30°=-1/2（诱导公式）','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0069-1','math','高中',13,'hs-kp-0069','single_choice',0.75,'函数 y=sin(2x) 的最小正周期 T = ？','[{"key":"A","text":"π"},{"key":"B","text":"π"},{"key":"C","text":"2π"},{"key":"D","text":"4π"}]','A','T=2π/ω=2π/2=π','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0070-1','math','高中',13,'hs-kp-0070','single_choice',0.35,'y=sin x 图像横坐标缩短到 1/4 → y=？','[{"key":"A","text":"y=sin(4x)"},{"key":"B","text":"y=sin(x/4)"},{"key":"C","text":"y=4sin x"},{"key":"D","text":"y=sin(x+4)"}]','A','横缩：x→4x，即 y=sin(4x)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0071-1','math','高中',13,'hs-kp-0071','single_choice',0.45,'asin x + bcos x = R·sin(x+φ)，R = ？ (a=4,b=5)','[{"key":"A","text":"√41"},{"key":"B","text":"9"},{"key":"C","text":"20"},{"key":"D","text":"1"}]','A','R=√(a²+b²)=√(16+25)=√41','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0072-1','math','高中',13,'hs-kp-0072','single_choice',0.55,'sin60°cos30°+cos60°sin30° = sin90° = ？','[{"key":"A","text":"1"},{"key":"B","text":"0.5"},{"key":"C","text":"0"},{"key":"D","text":"2"}]','A','sin60°cos30°+cos60°sin30°=sin(60°+30°)=sin90°=1','template-hs','approved','通用');