-- ============================================================
-- 第13章 圆锥曲线的方程 补题（15学期, 知识点 172-186）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0172-1','math','高中',15,'hs-kp-0172','single_choice',0.55,'下列对「椭圆、双曲线、抛物线定义」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','椭圆、双曲线、抛物线定义是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0173-1','math','高中',15,'hs-kp-0173','single_choice',0.65,'下列对「圆锥曲线标准方程」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','圆锥曲线标准方程是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0174-1','math','高中',15,'hs-kp-0174','single_choice',0.75,'下列对「a、b、c、e 关系」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','a、b、c、e 关系是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0175-1','math','高中',15,'hs-kp-0175','single_choice',0.35,'下列对「双曲线渐近线方程」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','双曲线渐近线方程是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0176-1','math','高中',15,'hs-kp-0176','single_choice',0.45,'下列对「等轴双曲线性质」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','等轴双曲线性质是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0177-1','math','高中',15,'hs-kp-0177','single_choice',0.55,'下列对「圆锥曲线通径公式」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','圆锥曲线通径公式是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0178-1','math','高中',15,'hs-kp-0178','single_choice',0.65,'下列对「焦点到渐近线距离」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','焦点到渐近线距离是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0179-1','math','高中',15,'hs-kp-0179','single_choice',0.75,'下列对「焦半径公式」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','焦半径公式是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0180-1','math','高中',15,'hs-kp-0180','single_choice',0.35,'下列对「焦点三角形面积」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','焦点三角形面积是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0181-1','math','高中',15,'hs-kp-0181','single_choice',0.45,'下列对「直线与圆锥曲线交点问题」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','直线与圆锥曲线交点问题是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0182-1','math','高中',15,'hs-kp-0182','single_choice',0.55,'下列对「抛物线焦点弦长」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','抛物线焦点弦长是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0183-1','math','高中',15,'hs-kp-0183','single_choice',0.65,'下列对「抛物线焦点弦性质」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','抛物线焦点弦性质是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0184-1','math','高中',15,'hs-kp-0184','single_choice',0.75,'下列对「圆锥曲线弦长公式」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','圆锥曲线弦长公式是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0185-1','math','高中',15,'hs-kp-0185','single_choice',0.35,'下列对「切线方程、点差法」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','切线方程、点差法是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0186-1','math','高中',15,'hs-kp-0186','single_choice',0.45,'下列对「圆锥曲线综合计算」的理解正确的是？','[{"key":"A","text":"它属于圆锥曲线的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','圆锥曲线综合计算是圆锥曲线的方程（第13章）的正式知识点','template-hs','approved','通用');