-- ============================================================
-- 第11章 空间向量与立体几何 补题（15学期, 知识点 139-156）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0139-1','math','高中',15,'hs-kp-0139','single_choice',0.75,'下列对「空间向量共面定理」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间向量共面定理是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0140-1','math','高中',15,'hs-kp-0140','single_choice',0.35,'下列对「空间向量基本定理」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间向量基本定理是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0141-1','math','高中',15,'hs-kp-0141','single_choice',0.45,'下列对「空间向量模长计算」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间向量模长计算是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0142-1','math','高中',15,'hs-kp-0142','single_choice',0.55,'下列对「空间向量数量积」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间向量数量积是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0143-1','math','高中',15,'hs-kp-0143','single_choice',0.65,'下列对「空间向量平行垂直判定」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间向量平行垂直判定是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0144-1','math','高中',15,'hs-kp-0144','single_choice',0.75,'下列对「空间向量夹角公式」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间向量夹角公式是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0145-1','math','高中',15,'hs-kp-0145','single_choice',0.35,'下列对「平面法向量求解」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','平面法向量求解是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0146-1','math','高中',15,'hs-kp-0146','single_choice',0.45,'下列对「向量法判定线面关系」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量法判定线面关系是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0147-1','math','高中',15,'hs-kp-0147','single_choice',0.55,'下列对「向量法求线线角」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量法求线线角是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0148-1','math','高中',15,'hs-kp-0148','single_choice',0.65,'下列对「向量法求线面角」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量法求线面角是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0149-1','math','高中',15,'hs-kp-0149','single_choice',0.75,'下列对「向量法求二面角」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','向量法求二面角是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0150-1','math','高中',15,'hs-kp-0150','single_choice',0.35,'下列对「点到直线距离公式」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','点到直线距离公式是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0151-1','math','高中',15,'hs-kp-0151','single_choice',0.45,'下列对「异面直线距离求解」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','异面直线距离求解是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0152-1','math','高中',15,'hs-kp-0152','single_choice',0.55,'下列对「点到平面距离公式」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','点到平面距离公式是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0153-1','math','高中',15,'hs-kp-0153','single_choice',0.65,'下列对「空间直角坐标系建系」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间直角坐标系建系是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0154-1','math','高中',15,'hs-kp-0154','single_choice',0.75,'下列对「空间向量坐标运算」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间向量坐标运算是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0155-1','math','高中',15,'hs-kp-0155','single_choice',0.35,'下列对「立体几何向量证明」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','立体几何向量证明是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0156-1','math','高中',15,'hs-kp-0156','single_choice',0.45,'下列对「空间几何最值问题」的理解正确的是？','[{"key":"A","text":"它属于空间向量与立体几何的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间几何最值问题是空间向量与立体几何（第11章）的正式知识点','template-hs','approved','通用');