-- ============================================================
-- 第18章 成对数据的统计分析 补题（16学期, 知识点 239-252）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0239-1','math','高中',16,'hs-kp-0239','single_choice',0.75,'两组数据点呈上升趋势，说明？','[{"key":"A","text":"正相关"},{"key":"B","text":"负相关"},{"key":"C","text":"无相关"},{"key":"D","text":"完全无关"}]','A','上升趋势 → 正相关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0239-2','math','高中',16,'hs-kp-0239','single_choice',0.75,'两组数据点呈上升趋势，说明？','[{"key":"A","text":"正相关"},{"key":"D","text":"完全无关"},{"key":"B","text":"负相关"},{"key":"C","text":"无相关"}]','A','上升趋势 → 正相关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0240-1','math','高中',16,'hs-kp-0240','single_choice',0.35,'散点图点群自左上向右下 → 相关方向？','[{"key":"A","text":"负相关"},{"key":"B","text":"正相关"},{"key":"C","text":"无相关"},{"key":"D","text":"非线性"}]','A','右上到左下 → 负相关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0240-2','math','高中',16,'hs-kp-0240','single_choice',0.35,'散点图点群自左上向右下 → 相关方向？','[{"key":"C","text":"无相关"},{"key":"A","text":"负相关"},{"key":"B","text":"正相关"},{"key":"D","text":"非线性"}]','A','右上到左下 → 负相关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0241-1','math','高中',16,'hs-kp-0241','single_choice',0.45,'数据 (1,2),(2,4),(3,6)，相关系数 r = ？','[{"key":"A","text":"1"},{"key":"B","text":"0"},{"key":"C","text":"-1"},{"key":"D","text":"0.5"}]','A','完全正线性 → r=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0241-2','math','高中',16,'hs-kp-0241','single_choice',0.45,'数据 (1,2),(2,4),(3,6)，相关系数 r = ？','[{"key":"C","text":"-1"},{"key":"B","text":"0"},{"key":"A","text":"1"},{"key":"D","text":"0.5"}]','A','完全正线性 → r=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0242-1','math','高中',16,'hs-kp-0242','single_choice',0.55,'|r| 越接近 1，线性相关程度？','[{"key":"A","text":"越强"},{"key":"B","text":"越弱"},{"key":"C","text":"不变"},{"key":"D","text":"无意义"}]','A','|r| 接近 1 → 强相关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0242-2','math','高中',16,'hs-kp-0242','single_choice',0.55,'|r| 越接近 1，线性相关程度？','[{"key":"B","text":"越弱"},{"key":"D","text":"无意义"},{"key":"C","text":"不变"},{"key":"A","text":"越强"}]','A','|r| 接近 1 → 强相关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0242-3','math','高中',16,'hs-kp-0242','single_choice',0.55,'|r| 越接近 1，线性相关程度？','[{"key":"D","text":"无意义"},{"key":"C","text":"不变"},{"key":"B","text":"越弱"},{"key":"A","text":"越强"}]','A','|r| 接近 1 → 强相关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0243-1','math','高中',16,'hs-kp-0243','single_choice',0.65,'回归直线 ŷ = 2x+1，x=2 时预测值 = ？','[{"key":"A","text":"5"},{"key":"B","text":"3"},{"key":"C","text":"2"},{"key":"D","text":"1"}]','A','ŷ=2×2+1=5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0243-2','math','高中',16,'hs-kp-0243','single_choice',0.65,'回归直线 ŷ = 3x+2，x=2 时预测值 = ？','[{"key":"A","text":"8"},{"key":"B","text":"5"},{"key":"C","text":"3"},{"key":"D","text":"2"}]','A','ŷ=3×2+2=8','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0243-3','math','高中',16,'hs-kp-0243','single_choice',0.65,'回归直线 ŷ = 2x+2，x=2 时预测值 = ？','[{"key":"A","text":"6"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"2"}]','A','ŷ=2×2+2=6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0244-1','math','高中',16,'hs-kp-0244','single_choice',0.75,'回归直线必过点？','[{"key":"A","text":"样本中心 (x̄,ȳ)"},{"key":"B","text":"原点"},{"key":"C","text":"(1,1)"},{"key":"D","text":"最后一个点"}]','A','回归直线过样本中心点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0244-2','math','高中',16,'hs-kp-0244','single_choice',0.75,'回归直线必过点？','[{"key":"A","text":"样本中心 (x̄,ȳ)"},{"key":"B","text":"原点"},{"key":"D","text":"最后一个点"},{"key":"C","text":"(1,1)"}]','A','回归直线过样本中心点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0244-3','math','高中',16,'hs-kp-0244','single_choice',0.75,'回归直线必过点？','[{"key":"D","text":"最后一个点"},{"key":"A","text":"样本中心 (x̄,ȳ)"},{"key":"B","text":"原点"},{"key":"C","text":"(1,1)"}]','A','回归直线过样本中心点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0245-1','math','高中',16,'hs-kp-0245','single_choice',0.35,'回归斜率 b 表示 x 每增 1 单位，y 平均变化？','[{"key":"A","text":"b 个单位"},{"key":"B","text":"1 个单位"},{"key":"C","text":"a 个单位"},{"key":"D","text":"不变"}]','A','斜率 b：x 增 1，y 平均增 b','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0245-2','math','高中',16,'hs-kp-0245','single_choice',0.35,'回归斜率 b 表示 x 每增 1 单位，y 平均变化？','[{"key":"A","text":"b 个单位"},{"key":"B","text":"1 个单位"},{"key":"D","text":"不变"},{"key":"C","text":"a 个单位"}]','A','斜率 b：x 增 1，y 平均增 b','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0245-3','math','高中',16,'hs-kp-0245','single_choice',0.35,'回归斜率 b 表示 x 每增 1 单位，y 平均变化？','[{"key":"D","text":"不变"},{"key":"C","text":"a 个单位"},{"key":"B","text":"1 个单位"},{"key":"A","text":"b 个单位"}]','A','斜率 b：x 增 1，y 平均增 b','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0246-1','math','高中',16,'hs-kp-0246','single_choice',0.45,'观测值 y=8，预测值 ŷ=3，残差 = ？','[{"key":"A","text":"5"},{"key":"B","text":"11"},{"key":"C","text":"24"},{"key":"D","text":"-5"}]','A','残差 = y-ŷ = 8-3 = 5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0246-2','math','高中',16,'hs-kp-0246','single_choice',0.45,'观测值 y=4，预测值 ŷ=2，残差 = ？','[{"key":"A","text":"2"},{"key":"B","text":"6"},{"key":"C","text":"8"},{"key":"D","text":"-2"}]','A','残差 = y-ŷ = 4-2 = 2','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0246-3','math','高中',16,'hs-kp-0246','single_choice',0.45,'观测值 y=4，预测值 ŷ=4，残差 = ？','[{"key":"A","text":"0"},{"key":"B","text":"8"},{"key":"C","text":"16"},{"key":"D","text":"0"}]','A','残差 = y-ŷ = 4-4 = 0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0247-1','math','高中',16,'hs-kp-0247','single_choice',0.55,'残差平方和越小，模型拟合？','[{"key":"A","text":"越好"},{"key":"B","text":"越差"},{"key":"C","text":"不变"},{"key":"D","text":"无关"}]','A','残差平方和 RSS 越小拟合越好','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0247-2','math','高中',16,'hs-kp-0247','single_choice',0.55,'残差平方和越小，模型拟合？','[{"key":"A","text":"越好"},{"key":"C","text":"不变"},{"key":"B","text":"越差"},{"key":"D","text":"无关"}]','A','残差平方和 RSS 越小拟合越好','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0248-1','math','高中',16,'hs-kp-0248','single_choice',0.65,'相关指数 R² 越接近 1，拟合效果？','[{"key":"A","text":"越好"},{"key":"B","text":"越差"},{"key":"C","text":"不变"},{"key":"D","text":"无意义"}]','A','R² 接近 1 → 拟合优度高','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0248-2','math','高中',16,'hs-kp-0248','single_choice',0.65,'相关指数 R² 越接近 1，拟合效果？','[{"key":"C","text":"不变"},{"key":"D","text":"无意义"},{"key":"A","text":"越好"},{"key":"B","text":"越差"}]','A','R² 接近 1 → 拟合优度高','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0248-3','math','高中',16,'hs-kp-0248','single_choice',0.65,'相关指数 R² 越接近 1，拟合效果？','[{"key":"D","text":"无意义"},{"key":"C","text":"不变"},{"key":"B","text":"越差"},{"key":"A","text":"越好"}]','A','R² 接近 1 → 拟合优度高','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0249-1','math','高中',16,'hs-kp-0249','single_choice',0.75,'r>0 且接近 1 说明？','[{"key":"A","text":"强正线性相关"},{"key":"B","text":"强负线性相关"},{"key":"C","text":"无相关"},{"key":"D","text":"非线性相关"}]','A','r>0 正相关，接近 1 强相关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0249-2','math','高中',16,'hs-kp-0249','single_choice',0.75,'r>0 且接近 1 说明？','[{"key":"A","text":"强正线性相关"},{"key":"D","text":"非线性相关"},{"key":"B","text":"强负线性相关"},{"key":"C","text":"无相关"}]','A','r>0 正相关，接近 1 强相关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0250-1','math','高中',16,'hs-kp-0250','single_choice',0.35,'2×2 列联表：甲组 24 人（含 27 达标），乙组 50 人（含 20 达标）。行合计甲 = ？','[{"key":"A","text":"24"},{"key":"B","text":"27"},{"key":"C","text":"51"},{"key":"D","text":"-3"}]','A','行合计 = 该组总人数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0250-2','math','高中',16,'hs-kp-0250','single_choice',0.35,'2×2 列联表：甲组 31 人（含 13 达标），乙组 50 人（含 20 达标）。行合计甲 = ？','[{"key":"A","text":"31"},{"key":"B","text":"13"},{"key":"C","text":"44"},{"key":"D","text":"18"}]','A','行合计 = 该组总人数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0250-3','math','高中',16,'hs-kp-0250','single_choice',0.35,'2×2 列联表：甲组 35 人（含 17 达标），乙组 50 人（含 20 达标）。行合计甲 = ？','[{"key":"A","text":"35"},{"key":"B","text":"17"},{"key":"C","text":"52"},{"key":"D","text":"18"}]','A','行合计 = 该组总人数','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0251-1','math','高中',16,'hs-kp-0251','single_choice',0.45,'独立性检验统计量 χ² = n(ad-bc)²/[(a+b)(c+d)(a+c)(b+d)]，χ² 越大说明？','[{"key":"A","text":"两变量越相关"},{"key":"B","text":"越无关"},{"key":"C","text":"样本越少"},{"key":"D","text":"无法判断"}]','A','χ² 大 → 拒绝独立假设，相关性强','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0251-2','math','高中',16,'hs-kp-0251','single_choice',0.45,'独立性检验统计量 χ² = n(ad-bc)²/[(a+b)(c+d)(a+c)(b+d)]，χ² 越大说明？','[{"key":"C","text":"样本越少"},{"key":"D","text":"无法判断"},{"key":"B","text":"越无关"},{"key":"A","text":"两变量越相关"}]','A','χ² 大 → 拒绝独立假设，相关性强','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0251-3','math','高中',16,'hs-kp-0251','single_choice',0.45,'独立性检验统计量 χ² = n(ad-bc)²/[(a+b)(c+d)(a+c)(b+d)]，χ² 越大说明？','[{"key":"D","text":"无法判断"},{"key":"C","text":"样本越少"},{"key":"B","text":"越无关"},{"key":"A","text":"两变量越相关"}]','A','χ² 大 → 拒绝独立假设，相关性强','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0252-1','math','高中',16,'hs-kp-0252','single_choice',0.55,'χ² 大于临界值 3.841（α=0.05）时，结论是？','[{"key":"A","text":"有 95% 把握认为有关"},{"key":"B","text":"无关"},{"key":"C","text":"样本无效"},{"key":"D","text":"无法判断"}]','A','χ²>3.841 → 拒绝 H₀，有 95% 把握认为有关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0252-2','math','高中',16,'hs-kp-0252','single_choice',0.55,'χ² 大于临界值 3.841（α=0.05）时，结论是？','[{"key":"D","text":"无法判断"},{"key":"C","text":"样本无效"},{"key":"B","text":"无关"},{"key":"A","text":"有 95% 把握认为有关"}]','A','χ²>3.841 → 拒绝 H₀，有 95% 把握认为有关','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0252-3','math','高中',16,'hs-kp-0252','single_choice',0.55,'χ² 大于临界值 3.841（α=0.05）时，结论是？','[{"key":"D","text":"无法判断"},{"key":"A","text":"有 95% 把握认为有关"},{"key":"C","text":"样本无效"},{"key":"B","text":"无关"}]','A','χ²>3.841 → 拒绝 H₀，有 95% 把握认为有关','template-hs','approved','通用');