-- ============================================================
-- 第14章 数列 补题（16学期, 知识点 187-198）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0187-1','math','高中',16,'hs-kp-0187','single_choice',0.55,'Sₙ=2n²+n，则 a₁ = S₁ = ？','[{"key":"A","text":"3"},{"key":"B","text":"2"},{"key":"C","text":"4"},{"key":"D","text":"1"}]','A','a₁=S₁=2×1+1=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0188-1','math','高中',16,'hs-kp-0188','single_choice',0.65,'等差数列 a₁=3，d=4，a6 = ？','[{"key":"A","text":"23"},{"key":"B","text":"27"},{"key":"C","text":"3"},{"key":"D","text":"27"}]','A','aₙ=a₁+(n-1)d=3+(6-1)×4=23','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0189-1','math','高中',16,'hs-kp-0189','single_choice',0.75,'等比数列 a₁=3，q=3，a3 = ？','[{"key":"A","text":"27"},{"key":"B","text":"81"},{"key":"C","text":"9"},{"key":"D","text":"3"}]','A','aₙ=a₁qⁿ⁻¹=3×3^2=27','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0190-1','math','高中',16,'hs-kp-0190','single_choice',0.35,'等差数列 a₁=3，d=3，S6 = ？','[{"key":"A","text":"63"},{"key":"B","text":"69"},{"key":"C","text":"18"},{"key":"D","text":"60"}]','A','Sₙ=na₁+n(n-1)d/2=6×3+6×5×3/2=63','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0191-1','math','高中',16,'hs-kp-0191','single_choice',0.45,'等比数列 a₁=3，q=2，S5 = ？','[{"key":"A","text":"93"},{"key":"B","text":"15"},{"key":"C","text":"186"},{"key":"D","text":"6"}]','A','Sₙ=a₁(1-qⁿ)/(1-q)=3×(1-2^5)/(1-2)=93','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0192-1','math','高中',16,'hs-kp-0192','single_choice',0.55,'2 与 5 的等差中项 = ？','[{"key":"A","text":"3.5"},{"key":"B","text":"7"},{"key":"C","text":"10"},{"key":"D","text":"3.1622776601683795"}]','A','等差中项=(2+5)/2=3.5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0193-1','math','高中',16,'hs-kp-0193','single_choice',0.65,'等差数列 a₁=2，d=3，a₂+a₅ = ？','[{"key":"A","text":"19"},{"key":"B","text":"4"},{"key":"C","text":"14"},{"key":"D","text":"5"}]','A','a₂=5，a₅=14，和=19','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0194-1','math','高中',16,'hs-kp-0194','single_choice',0.75,'等比数列 a₁=2，q=3，a₃ = ？','[{"key":"A","text":"18"},{"key":"B","text":"6"},{"key":"C","text":"8"},{"key":"D","text":"2"}]','A','a₃=a₁q²=2×3²=18','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0195-1','math','高中',16,'hs-kp-0195','single_choice',0.35,'数列 {n·2ⁿ} 前 n 项和常用？求和法','[{"key":"A","text":"错位相减法"},{"key":"B","text":"裂项相消法"},{"key":"C","text":"累加法"},{"key":"D","text":"累乘法"}]','A','等差×等比 → 错位相减','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0196-1','math','高中',16,'hs-kp-0196','single_choice',0.45,'1/(1×2)+1/(2×3)+...+1/(n×(n+1)) = n/(n+1)，n=3 → ？','[{"key":"A","text":"3/4"},{"key":"B","text":"1.3333333333333333"},{"key":"C","text":"3"},{"key":"D","text":"1/3"}]','A','裂项相消：1/k-1/(k+1)，和=3/4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0197-1','math','高中',16,'hs-kp-0197','single_choice',0.55,'aₙ-aₙ₋₁=n，a₁=1，则 a3 = 1+2+...+3 = ？','[{"key":"A","text":"6"},{"key":"B","text":"3"},{"key":"C","text":"9"},{"key":"D","text":"4"}]','A','累加法：aₙ=1+2+...+n=6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0198-1','math','高中',16,'hs-kp-0198','single_choice',0.65,'aₙ/aₙ₋₁=n/(n-1)，a₁=1，则 a3 = ？','[{"key":"A","text":"3"},{"key":"B","text":"2"},{"key":"C","text":"9"},{"key":"D","text":"1"}]','A','累乘法：aₙ=a₁×2/1×3/2×...×n/(n-1)=3','template-hs','approved','通用');