-- ============================================================
-- 第10章 概率 补题（14学期, 知识点 127-138）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0127-1','math','高中',14,'hs-kp-0127','single_choice',0.55,'从 1~8 随机取一个数，取到偶数的概率 = ？','[{"key":"A","text":"4/8"},{"key":"B","text":"1/2"},{"key":"C","text":"4/8"},{"key":"D","text":"1/8"}]','A','P=偶数个数/总数=4/8','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0128-1','math','高中',14,'hs-kp-0128','single_choice',0.65,'P(A)=2/4，P(B)=2/4，A、B 互斥，P(A∪B) = ？','[{"key":"A","text":"1"},{"key":"B","text":"2/4"},{"key":"C","text":"2/4"},{"key":"D","text":"0"}]','A','互斥：P(A∪B)=P(A)+P(B)=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0129-1','math','高中',14,'hs-kp-0129','single_choice',0.75,'P(A)=3/4，则 P(Ā) = ？','[{"key":"A","text":"1/4"},{"key":"B","text":"3/4"},{"key":"C","text":"0"},{"key":"D","text":"1"}]','A','对立事件：P(Ā)=1-P(A)=0.25','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0130-1','math','高中',14,'hs-kp-0130','single_choice',0.35,'A 发生不影响 B 发生的概率，则 A、B？','[{"key":"A","text":"相互独立"},{"key":"B","text":"互斥"},{"key":"C","text":"对立"},{"key":"D","text":"包含"}]','A','独立定义：一事件发生不影响另一事件概率','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0131-1','math','高中',14,'hs-kp-0131','single_choice',0.45,'P(A)=4/5，P(B)=3/4，独立，P(AB) = ？','[{"key":"A","text":"0.6"},{"key":"B","text":"0.8"},{"key":"C","text":"0.75"},{"key":"D","text":"1"}]','A','独立：P(AB)=P(A)P(B)=4/5×3/4≈0.6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0132-1','math','高中',14,'hs-kp-0132','single_choice',0.55,'A、B 互斥且 A∪B=Ω，则 A、B 是？','[{"key":"A","text":"对立事件"},{"key":"B","text":"独立事件"},{"key":"C","text":"包含事件"},{"key":"D","text":"无关事件"}]','A','对立：互斥且并集为全集','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0133-1','math','高中',14,'hs-kp-0133','single_choice',0.65,'概率的基本性质：P(Ω) = ？','[{"key":"A","text":"1"},{"key":"B","text":"0"},{"key":"C","text":"0.5"},{"key":"D","text":"∞"}]','A','必然事件概率为 1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0134-1','math','高中',14,'hs-kp-0134','single_choice',0.75,'掷两枚骰子，样本空间基本事件总数 = ？','[{"key":"A","text":"36"},{"key":"B","text":"18"},{"key":"C","text":"12"},{"key":"D","text":"6"}]','A','样本空间：6×6=36 个基本事件','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0135-1','math','高中',14,'hs-kp-0135','single_choice',0.35,'频率与概率的关系：试验次数很大时频率趋近于？','[{"key":"A","text":"概率"},{"key":"B","text":"0"},{"key":"C","text":"1"},{"key":"D","text":"样本容量"}]','A','频率的稳定值即概率','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0136-1','math','高中',14,'hs-kp-0136','single_choice',0.45,'P(A)=2/10，P(B|A)=1/2，P(AB) = ？','[{"key":"A","text":"0.1"},{"key":"B","text":"0.2"},{"key":"C","text":"0.4"},{"key":"D","text":"1/2"}]','A','P(AB)=P(A)P(B|A)=2/10×1/2=2/20','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0137-1','math','高中',14,'hs-kp-0137','single_choice',0.55,'下列是随机试验的是？','[{"key":"A","text":"掷骰子观察点数"},{"key":"B","text":"1+1=2"},{"key":"C","text":"太阳从东升起"},{"key":"D","text":"正方形的四边相等"}]','A','随机试验：结果不确定的试验','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0138-1','math','高中',14,'hs-kp-0138','single_choice',0.65,'等可能事件的概率模型是？','[{"key":"A","text":"古典概型"},{"key":"B","text":"几何概型"},{"key":"C","text":"频率概型"},{"key":"D","text":"主观概型"}]','A','古典概型：有限等可能','template-hs','approved','通用');