-- ============================================================
-- 第15章 一元函数的导数及其应用 补题（16学期, 知识点 199-212）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0199-1','math','高中',16,'hs-kp-0199','single_choice',0.75,'下列对「导数定义与表示」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','导数定义与表示是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0200-1','math','高中',16,'hs-kp-0200','single_choice',0.35,'下列对「导数几何意义（切线）」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','导数几何意义（切线）是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0201-1','math','高中',16,'hs-kp-0201','single_choice',0.45,'下列对「基本初等函数导数公式」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','基本初等函数导数公式是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0202-1','math','高中',16,'hs-kp-0202','single_choice',0.55,'下列对「导数四则运算法则」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','导数四则运算法则是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0203-1','math','高中',16,'hs-kp-0203','single_choice',0.65,'下列对「复合函数求导法则」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','复合函数求导法则是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0204-1','math','高中',16,'hs-kp-0204','single_choice',0.75,'下列对「切点在曲线上切线方程」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','切点在曲线上切线方程是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0205-1','math','高中',16,'hs-kp-0205','single_choice',0.35,'下列对「切点不在曲线上切线方程」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','切点不在曲线上切线方程是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0206-1','math','高中',16,'hs-kp-0206','single_choice',0.45,'下列对「导数判断函数单调性」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','导数判断函数单调性是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0207-1','math','高中',16,'hs-kp-0207','single_choice',0.55,'下列对「函数极值求解方法」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','函数极值求解方法是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0208-1','math','高中',16,'hs-kp-0208','single_choice',0.65,'下列对「导数构造函数技巧」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','导数构造函数技巧是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0209-1','math','高中',16,'hs-kp-0209','single_choice',0.75,'下列对「指数、对数常用不等式」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','指数、对数常用不等式是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0210-1','math','高中',16,'hs-kp-0210','single_choice',0.35,'下列对「指对综合放缩不等式」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','指对综合放缩不等式是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0211-1','math','高中',16,'hs-kp-0211','single_choice',0.45,'下列对「导数恒成立问题」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','导数恒成立问题是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0212-1','math','高中',16,'hs-kp-0212','single_choice',0.55,'下列对「导数存在性问题」的理解正确的是？','[{"key":"A","text":"它属于一元函数的导数及其应用的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','导数存在性问题是一元函数的导数及其应用（第15章）的正式知识点','template-hs','approved','通用');