-- ============================================================
-- 第12章 直线与圆的方程 补题（15学期, 知识点 157-171）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0157-1','math','高中',15,'hs-kp-0157','single_choice',0.55,'下列对「直线倾斜角与斜率」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','直线倾斜角与斜率是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0158-1','math','高中',15,'hs-kp-0158','single_choice',0.65,'下列对「五种直线方程形式」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','五种直线方程形式是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0159-1','math','高中',15,'hs-kp-0159','single_choice',0.75,'下列对「直线过定点问题」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','直线过定点问题是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0160-1','math','高中',15,'hs-kp-0160','single_choice',0.35,'下列对「两直线平行、垂直条件」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','两直线平行、垂直条件是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0161-1','math','高中',15,'hs-kp-0161','single_choice',0.45,'下列对「点点距、点线距、线线距」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','点点距、点线距、线线距是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0162-1','math','高中',15,'hs-kp-0162','single_choice',0.55,'下列对「直线系方程（平行/垂直/交点）」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','直线系方程（平行/垂直/交点）是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0163-1','math','高中',15,'hs-kp-0163','single_choice',0.65,'下列对「圆的标准方程、一般方程」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','圆的标准方程、一般方程是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0164-1','math','高中',15,'hs-kp-0164','single_choice',0.75,'下列对「圆的弦长公式」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','圆的弦长公式是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0165-1','math','高中',15,'hs-kp-0165','single_choice',0.35,'下列对「圆的切线长、切线方程」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','圆的切线长、切线方程是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0166-1','math','高中',15,'hs-kp-0166','single_choice',0.45,'下列对「直线与圆位置关系」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','直线与圆位置关系是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0167-1','math','高中',15,'hs-kp-0167','single_choice',0.55,'下列对「圆与圆位置关系」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','圆与圆位置关系是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0168-1','math','高中',15,'hs-kp-0168','single_choice',0.65,'下列对「公共弦方程」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','公共弦方程是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0169-1','math','高中',15,'hs-kp-0169','single_choice',0.75,'下列对「圆系方程应用」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','圆系方程应用是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0170-1','math','高中',15,'hs-kp-0170','single_choice',0.35,'下列对「直线圆综合最值」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','直线圆综合最值是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0171-1','math','高中',15,'hs-kp-0171','single_choice',0.45,'下列对「轨迹方程求解」的理解正确的是？','[{"key":"A","text":"它属于直线与圆的方程的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','轨迹方程求解是直线与圆的方程（第12章）的正式知识点','template-hs','approved','通用');