-- ============================================================
-- 第4章 指数函数与对数函数 补题（13学期, 知识点 49-62）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0049-1','math','高中',13,'hs-kp-0049','single_choice',0.75,'√[2]{16} = ？','[{"key":"A","text":"4"},{"key":"B","text":"8"},{"key":"C","text":"16"},{"key":"D","text":"1"}]','A','4^2=16 → √[2]{16}=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0049-2','math','高中',13,'hs-kp-0049','single_choice',0.75,'√[4]{256} = ？','[{"key":"A","text":"4"},{"key":"B","text":"16"},{"key":"C","text":"256"},{"key":"D","text":"1"}]','A','4^4=256 → √[4]{256}=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0049-3','math','高中',13,'hs-kp-0049','single_choice',0.75,'√[4]{81} = ？','[{"key":"A","text":"3"},{"key":"B","text":"12"},{"key":"C","text":"81"},{"key":"D","text":"1"}]','A','3^4=81 → √[4]{81}=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0050-1','math','高中',13,'hs-kp-0050','single_choice',0.35,'3^3 × 3^4 = ？','[{"key":"A","text":"2187"},{"key":"B","text":"531441"},{"key":"C","text":"108"},{"key":"D","text":"0.3333333333333333"}]','A','同底数幂相乘指数相加：3^7=2187','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0050-2','math','高中',13,'hs-kp-0050','single_choice',0.35,'3^4 × 3^2 = ？','[{"key":"A","text":"729"},{"key":"B","text":"6561"},{"key":"C","text":"90"},{"key":"D","text":"9"}]','A','同底数幂相乘指数相加：3^6=729','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0050-3','math','高中',13,'hs-kp-0050','single_choice',0.35,'4^2 × 4^3 = ？','[{"key":"A","text":"1024"},{"key":"B","text":"4096"},{"key":"C","text":"80"},{"key":"D","text":"0.25"}]','A','同底数幂相乘指数相加：4^5=1024','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0051-1','math','高中',13,'hs-kp-0051','single_choice',0.45,'指数函数 y=3^x 恒过点？','[{"key":"A","text":"(0,1)"},{"key":"B","text":"(1,0)"},{"key":"C","text":"(0,0)"},{"key":"D","text":"(3,1)"}]','A','a⁰=1 → 恒过 (0,1)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0051-2','math','高中',13,'hs-kp-0051','single_choice',0.45,'指数函数 y=2^x 恒过点？','[{"key":"A","text":"(0,1)"},{"key":"B","text":"(1,0)"},{"key":"C","text":"(0,0)"},{"key":"D","text":"(2,1)"}]','A','a⁰=1 → 恒过 (0,1)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0051-3','math','高中',13,'hs-kp-0051','single_choice',0.45,'指数函数 y=3^x 恒过点？','[{"key":"C","text":"(0,0)"},{"key":"A","text":"(0,1)"},{"key":"B","text":"(1,0)"},{"key":"D","text":"(3,1)"}]','A','a⁰=1 → 恒过 (0,1)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0052-1','math','高中',13,'hs-kp-0052','single_choice',0.55,'log_4 1 = ？','[{"key":"A","text":"0"},{"key":"B","text":"1"},{"key":"C","text":"4"},{"key":"D","text":"-1"}]','A','任何底 log_a 1=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0052-2','math','高中',13,'hs-kp-0052','single_choice',0.55,'log_3 1 = ？','[{"key":"A","text":"0"},{"key":"B","text":"1"},{"key":"C","text":"3"},{"key":"D","text":"-1"}]','A','任何底 log_a 1=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0052-3','math','高中',13,'hs-kp-0052','single_choice',0.55,'log_2 1 = ？','[{"key":"A","text":"0"},{"key":"B","text":"1"},{"key":"C","text":"2"},{"key":"D","text":"-1"}]','A','任何底 log_a 1=0','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0053-1','math','高中',13,'hs-kp-0053','single_choice',0.65,'log₂8 + log₂16 = ？','[{"key":"A","text":"7"},{"key":"B","text":"3"},{"key":"C","text":"4"},{"key":"D","text":"12"}]','A','log₂8=3，log₂16=4，和=7','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0053-2','math','高中',13,'hs-kp-0053','single_choice',0.65,'log₂8 + log₂8 = ？','[{"key":"A","text":"6"},{"key":"B","text":"3"},{"key":"C","text":"3"},{"key":"D","text":"9"}]','A','log₂8=3，log₂8=3，和=6','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0053-3','math','高中',13,'hs-kp-0053','single_choice',0.65,'log₂4 + log₂4 = ？','[{"key":"A","text":"4"},{"key":"B","text":"2"},{"key":"C","text":"2"},{"key":"D","text":"4"}]','A','log₂4=2，log₂4=2，和=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0054-1','math','高中',13,'hs-kp-0054','single_choice',0.75,'换底公式 log_a b = ？','[{"key":"A","text":"log_c b / log_c a"},{"key":"B","text":"log_c a / log_c b"},{"key":"C","text":"log_a c × log_c b"},{"key":"D","text":"log_b c"}]','A','换底公式：log_a b = log_c b / log_c a','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0054-2','math','高中',13,'hs-kp-0054','single_choice',0.75,'换底公式 log_a b = ？','[{"key":"C","text":"log_a c × log_c b"},{"key":"D","text":"log_b c"},{"key":"B","text":"log_c a / log_c b"},{"key":"A","text":"log_c b / log_c a"}]','A','换底公式：log_a b = log_c b / log_c a','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0054-3','math','高中',13,'hs-kp-0054','single_choice',0.75,'换底公式 log_a b = ？','[{"key":"D","text":"log_b c"},{"key":"A","text":"log_c b / log_c a"},{"key":"C","text":"log_a c × log_c b"},{"key":"B","text":"log_c a / log_c b"}]','A','换底公式：log_a b = log_c b / log_c a','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0055-1','math','高中',13,'hs-kp-0055','single_choice',0.35,'对数函数 y=log_3 x 恒过点？','[{"key":"A","text":"(1,0)"},{"key":"B","text":"(0,1)"},{"key":"C","text":"(0,0)"},{"key":"D","text":"(1,1)"}]','A','log_a 1=0 → 恒过 (1,0)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0055-2','math','高中',13,'hs-kp-0055','single_choice',0.35,'对数函数 y=log_2 x 恒过点？','[{"key":"A","text":"(1,0)"},{"key":"B","text":"(0,1)"},{"key":"C","text":"(0,0)"},{"key":"D","text":"(1,1)"}]','A','log_a 1=0 → 恒过 (1,0)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0055-3','math','高中',13,'hs-kp-0055','single_choice',0.35,'对数函数 y=log_4 x 恒过点？','[{"key":"A","text":"(1,0)"},{"key":"B","text":"(0,1)"},{"key":"C","text":"(0,0)"},{"key":"D","text":"(1,1)"}]','A','log_a 1=0 → 恒过 (1,0)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0056-1','math','高中',13,'hs-kp-0056','single_choice',0.45,'幂函数 y=x^3 恒过点？','[{"key":"A","text":"(1,1)"},{"key":"B","text":"(0,1)"},{"key":"C","text":"(1,0)"},{"key":"D","text":"(3,0)"}]','A','1 的任何次幂为 1 → 恒过 (1,1)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0056-2','math','高中',13,'hs-kp-0056','single_choice',0.45,'幂函数 y=x^4 恒过点？','[{"key":"A","text":"(1,1)"},{"key":"B","text":"(0,1)"},{"key":"C","text":"(1,0)"},{"key":"D","text":"(4,0)"}]','A','1 的任何次幂为 1 → 恒过 (1,1)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0056-3','math','高中',13,'hs-kp-0056','single_choice',0.45,'幂函数 y=x^3 恒过点？','[{"key":"A","text":"(1,1)"},{"key":"D","text":"(3,0)"},{"key":"B","text":"(0,1)"},{"key":"C","text":"(1,0)"}]','A','1 的任何次幂为 1 → 恒过 (1,1)','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0057-1','math','高中',13,'hs-kp-0057','single_choice',0.55,'f(x)=2x-2 的零点为？','[{"key":"A","text":"1"},{"key":"B","text":"-1"},{"key":"C","text":"2"},{"key":"D","text":"2"}]','A','令 f(x)=0 → x=2/2=1','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0057-2','math','高中',13,'hs-kp-0057','single_choice',0.55,'f(x)=4x-2 的零点为？','[{"key":"A","text":"0.5"},{"key":"B","text":"-0.5"},{"key":"C","text":"2"},{"key":"D","text":"4"}]','A','令 f(x)=0 → x=2/4=0.5','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0057-3','math','高中',13,'hs-kp-0057','single_choice',0.55,'f(x)=3x-5 的零点为？','[{"key":"A","text":"1.6666666666666667"},{"key":"B","text":"-1.6666666666666667"},{"key":"C","text":"5"},{"key":"D","text":"3"}]','A','令 f(x)=0 → x=5/3=1.6666666666666667','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0058-1','math','高中',13,'hs-kp-0058','single_choice',0.65,'f(x)=x³-2x-1，若 f(2)·f(2+1)<0 → 零点区间？','[{"key":"A","text":"(2,3)"},{"key":"B","text":"(1,2)"},{"key":"C","text":"(3,4)"},{"key":"D","text":"无法确定"}]','A','零点存在性定理：端点异号则零点在区间内','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0058-2','math','高中',13,'hs-kp-0058','single_choice',0.65,'f(x)=x³-3x-1，若 f(3)·f(3+1)<0 → 零点区间？','[{"key":"A","text":"(3,4)"},{"key":"B","text":"(2,3)"},{"key":"C","text":"(4,5)"},{"key":"D","text":"无法确定"}]','A','零点存在性定理：端点异号则零点在区间内','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0058-3','math','高中',13,'hs-kp-0058','single_choice',0.65,'f(x)=x³-2x-1，若 f(2)·f(2+1)<0 → 零点区间？','[{"key":"A","text":"(2,3)"},{"key":"B","text":"(1,2)"},{"key":"D","text":"无法确定"},{"key":"C","text":"(3,4)"}]','A','零点存在性定理：端点异号则零点在区间内','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0059-1','math','高中',13,'hs-kp-0059','single_choice',0.75,'x²-5x+2=0 的判别式 Δ = ？','[{"key":"A","text":"17"},{"key":"B","text":"33"},{"key":"C","text":"-3"},{"key":"D","text":"8"}]','A','Δ=b²-4ac=5²-4×1×2=17','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0059-2','math','高中',13,'hs-kp-0059','single_choice',0.75,'x²-4x+2=0 的判别式 Δ = ？','[{"key":"A","text":"8"},{"key":"B","text":"24"},{"key":"C","text":"-4"},{"key":"D","text":"8"}]','A','Δ=b²-4ac=4²-4×1×2=8','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0059-3','math','高中',13,'hs-kp-0059','single_choice',0.75,'x²-4x+1=0 的判别式 Δ = ？','[{"key":"A","text":"12"},{"key":"B","text":"20"},{"key":"C","text":"0"},{"key":"D","text":"4"}]','A','Δ=b²-4ac=4²-4×1×1=12','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0060-1','math','高中',13,'hs-kp-0060','single_choice',0.35,'比较 log₂3 与 log₂3 大小？','[{"key":"A","text":"后者大"},{"key":"B","text":"相等"},{"key":"C","text":"无法比较"},{"key":"D","text":"相等且最大"}]','A','log₂ 单调递增，3<3 → 后者大','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0060-2','math','高中',13,'hs-kp-0060','single_choice',0.35,'比较 log₂5 与 log₂2 大小？','[{"key":"A","text":"前者大"},{"key":"B","text":"相等"},{"key":"C","text":"无法比较"},{"key":"D","text":"相等且最大"}]','A','log₂ 单调递增，5>2 → 前者大','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0060-3','math','高中',13,'hs-kp-0060','single_choice',0.35,'比较 log₂7 与 log₂3 大小？','[{"key":"A","text":"前者大"},{"key":"B","text":"相等"},{"key":"C","text":"无法比较"},{"key":"D","text":"相等且最大"}]','A','log₂ 单调递增，7>3 → 前者大','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0061-1','math','高中',13,'hs-kp-0061','single_choice',0.45,'幂函数 y=x^4 在 (0,+∞) 单调？','[{"key":"A","text":"递增"},{"key":"B","text":"递减"},{"key":"C","text":"先增后减"},{"key":"D","text":"不单调"}]','A','指数 4>0 → 在 (0,+∞) 递增','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0061-2','math','高中',13,'hs-kp-0061','single_choice',0.45,'幂函数 y=x^3 在 (0,+∞) 单调？','[{"key":"A","text":"递增"},{"key":"B","text":"递减"},{"key":"C","text":"先增后减"},{"key":"D","text":"不单调"}]','A','指数 3>0 → 在 (0,+∞) 递增','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0061-3','math','高中',13,'hs-kp-0061','single_choice',0.45,'幂函数 y=x^4 在 (0,+∞) 单调？','[{"key":"D","text":"不单调"},{"key":"C","text":"先增后减"},{"key":"B","text":"递减"},{"key":"A","text":"递增"}]','A','指数 4>0 → 在 (0,+∞) 递增','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0062-1','math','高中',13,'hs-kp-0062','single_choice',0.55,'二分法求 f(x)=x²-5 零点，区间 [1,5] 第一次取中点？','[{"key":"A","text":"3"},{"key":"B","text":"2"},{"key":"C","text":"5"},{"key":"D","text":"1"}]','A','中点=(5+1)/2=3','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0062-2','math','高中',13,'hs-kp-0062','single_choice',0.55,'二分法求 f(x)=x²-6 零点，区间 [2,6] 第一次取中点？','[{"key":"A","text":"4"},{"key":"B","text":"2"},{"key":"C","text":"6"},{"key":"D","text":"2"}]','A','中点=(6+2)/2=4','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0062-3','math','高中',13,'hs-kp-0062','single_choice',0.55,'二分法求 f(x)=x²-7 零点，区间 [1,7] 第一次取中点？','[{"key":"A","text":"4"},{"key":"B","text":"3"},{"key":"C","text":"7"},{"key":"D","text":"1"}]','A','中点=(7+1)/2=4','template-hs','approved','通用');