-- ============================================================
-- 第8章 立体几何初步 补题（14学期, 知识点 97-114）
-- 参数化原创题 source='template-hs'
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0097-1','math','高中',14,'hs-kp-0097','single_choice',0.55,'下列对「斜二测画法规则」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','斜二测画法规则是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0098-1','math','高中',14,'hs-kp-0098','single_choice',0.65,'下列对「直观图面积比例关系」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','直观图面积比例关系是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0099-1','math','高中',14,'hs-kp-0099','single_choice',0.75,'下列对「平面基本事实与推论」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','平面基本事实与推论是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0100-1','math','高中',14,'hs-kp-0100','single_choice',0.35,'下列对「线线平行证明方法」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','线线平行证明方法是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0101-1','math','高中',14,'hs-kp-0101','single_choice',0.45,'下列对「线面平行判定与性质」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','线面平行判定与性质是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0102-1','math','高中',14,'hs-kp-0102','single_choice',0.55,'下列对「面面平行判定与性质」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','面面平行判定与性质是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0103-1','math','高中',14,'hs-kp-0103','single_choice',0.65,'下列对「线面垂直判定与性质」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','线面垂直判定与性质是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0104-1','math','高中',14,'hs-kp-0104','single_choice',0.75,'下列对「面面垂直判定与性质」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','面面垂直判定与性质是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0105-1','math','高中',14,'hs-kp-0105','single_choice',0.35,'下列对「线线垂直证明」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','线线垂直证明是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0106-1','math','高中',14,'hs-kp-0106','single_choice',0.45,'下列对「异面直线所成角求解」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','异面直线所成角求解是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0107-1','math','高中',14,'hs-kp-0107','single_choice',0.55,'下列对「直线与平面所成角求解」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','直线与平面所成角求解是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0108-1','math','高中',14,'hs-kp-0108','single_choice',0.65,'下列对「二面角初步求解」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','二面角初步求解是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0109-1','math','高中',14,'hs-kp-0109','single_choice',0.75,'下列对「点面距离求解」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','点面距离求解是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0110-1','math','高中',14,'hs-kp-0110','single_choice',0.35,'下列对「空间几何体表面积」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间几何体表面积是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0111-1','math','高中',14,'hs-kp-0111','single_choice',0.45,'下列对「空间几何体体积」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间几何体体积是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0112-1','math','高中',14,'hs-kp-0112','single_choice',0.55,'下列对「空间点线面位置关系」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间点线面位置关系是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0113-1','math','高中',14,'hs-kp-0113','single_choice',0.65,'下列对「平行垂直综合证明」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','平行垂直综合证明是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('hq-0114-1','math','高中',14,'hs-kp-0114','single_choice',0.75,'下列对「空间几何识图能力」的理解正确的是？','[{"key":"A","text":"它属于立体几何初步的核心内容"},{"key":"B","text":"它不属于高中数学"},{"key":"C","text":"它与本单元无关"},{"key":"D","text":"它是初中内容"}]','A','空间几何识图能力是立体几何初步（第8章）的正式知识点','template-hs','approved','通用');