-- 第24章 圆 补题（11学期, 知识点 344-367）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0344-1','math','初中',11,'jkp-0344','single_choice',0.75,'半径 4 的圆周长 C = 2πr = ？','[{"key": "A", "text": "8π"}, {"key": "B", "text": "4π"}, {"key": "C", "text": "16π"}, {"key": "D", "text": "8"}]','A','C=2π×4=8π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0344-2','math','初中',11,'jkp-0344','single_choice',0.75,'半径 3 的圆周长 C = 2πr = ？','[{"key": "A", "text": "6π"}, {"key": "B", "text": "3π"}, {"key": "C", "text": "9π"}, {"key": "D", "text": "6"}]','A','C=2π×3=6π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0344-3','math','初中',11,'jkp-0344','single_choice',0.75,'半径 5 的圆周长 C = 2πr = ？','[{"key": "A", "text": "10π"}, {"key": "B", "text": "5π"}, {"key": "C", "text": "25π"}, {"key": "D", "text": "10"}]','A','C=2π×5=10π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0345-1','math','初中',11,'jkp-0345','single_choice',0.35,'圆上两点间的部分叫？','[{"key": "A", "text": "弧"}, {"key": "B", "text": "弦"}, {"key": "C", "text": "直径"}, {"key": "D", "text": "半径"}]','A','弧定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0345-2','math','初中',11,'jkp-0345','single_choice',0.35,'圆上两点间的部分叫？','[{"key": "A", "text": "弧"}, {"key": "C", "text": "直径"}, {"key": "B", "text": "弦"}, {"key": "D", "text": "半径"}]','A','弧定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0345-3','math','初中',11,'jkp-0345','single_choice',0.35,'圆上两点间的部分叫？','[{"key": "A", "text": "弧"}, {"key": "C", "text": "直径"}, {"key": "D", "text": "半径"}, {"key": "B", "text": "弦"}]','A','弧定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0346-1','math','初中',11,'jkp-0346','single_choice',0.45,'能够完全重合的两个圆叫？','[{"key": "A", "text": "等圆"}, {"key": "B", "text": "同心圆"}, {"key": "C", "text": "相似圆"}, {"key": "D", "text": "相切圆"}]','A','等圆定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0346-2','math','初中',11,'jkp-0346','single_choice',0.45,'能够完全重合的两个圆叫？','[{"key": "D", "text": "相切圆"}, {"key": "B", "text": "同心圆"}, {"key": "C", "text": "相似圆"}, {"key": "A", "text": "等圆"}]','A','等圆定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0346-3','math','初中',11,'jkp-0346','single_choice',0.45,'能够完全重合的两个圆叫？','[{"key": "C", "text": "相似圆"}, {"key": "B", "text": "同心圆"}, {"key": "A", "text": "等圆"}, {"key": "D", "text": "相切圆"}]','A','等圆定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0347-1','math','初中',11,'jkp-0347','single_choice',0.55,'垂直于弦的直径？','[{"key": "A", "text": "平分这条弦和弦所对的两条弧"}, {"key": "B", "text": "只平分弦"}, {"key": "C", "text": "不平分"}, {"key": "D", "text": "与弦平行"}]','A','垂径定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0347-2','math','初中',11,'jkp-0347','single_choice',0.55,'垂直于弦的直径？','[{"key": "C", "text": "不平分"}, {"key": "B", "text": "只平分弦"}, {"key": "D", "text": "与弦平行"}, {"key": "A", "text": "平分这条弦和弦所对的两条弧"}]','A','垂径定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0347-3','math','初中',11,'jkp-0347','single_choice',0.55,'垂直于弦的直径？','[{"key": "A", "text": "平分这条弦和弦所对的两条弧"}, {"key": "B", "text": "只平分弦"}, {"key": "D", "text": "与弦平行"}, {"key": "C", "text": "不平分"}]','A','垂径定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0348-1','math','初中',11,'jkp-0348','single_choice',0.65,'平分弦（非直径）的直径？','[{"key": "A", "text": "垂直于弦"}, {"key": "B", "text": "平行于弦"}, {"key": "C", "text": "与弦相交但不垂直"}, {"key": "D", "text": "不经过圆心"}]','A','垂径定理推论','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0348-2','math','初中',11,'jkp-0348','single_choice',0.65,'平分弦（非直径）的直径？','[{"key": "B", "text": "平行于弦"}, {"key": "D", "text": "不经过圆心"}, {"key": "A", "text": "垂直于弦"}, {"key": "C", "text": "与弦相交但不垂直"}]','A','垂径定理推论','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0348-3','math','初中',11,'jkp-0348','single_choice',0.65,'平分弦（非直径）的直径？','[{"key": "C", "text": "与弦相交但不垂直"}, {"key": "D", "text": "不经过圆心"}, {"key": "B", "text": "平行于弦"}, {"key": "A", "text": "垂直于弦"}]','A','垂径定理推论','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0349-1','math','初中',11,'jkp-0349','single_choice',0.75,'同圆中，相等的圆心角所对的弦？','[{"key": "A", "text": "相等"}, {"key": "B", "text": "不等"}, {"key": "C", "text": "成比例"}, {"key": "D", "text": "无法确定"}]','A','弧弦圆心角关系定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0349-2','math','初中',11,'jkp-0349','single_choice',0.75,'同圆中，相等的圆心角所对的弦？','[{"key": "D", "text": "无法确定"}, {"key": "C", "text": "成比例"}, {"key": "A", "text": "相等"}, {"key": "B", "text": "不等"}]','A','弧弦圆心角关系定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0349-3','math','初中',11,'jkp-0349','single_choice',0.75,'同圆中，相等的圆心角所对的弦？','[{"key": "C", "text": "成比例"}, {"key": "A", "text": "相等"}, {"key": "D", "text": "无法确定"}, {"key": "B", "text": "不等"}]','A','弧弦圆心角关系定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0350-1','math','初中',11,'jkp-0350','single_choice',0.35,'顶点在圆上、两边都与圆相交的角叫？','[{"key": "A", "text": "圆周角"}, {"key": "B", "text": "圆心角"}, {"key": "C", "text": "平角"}, {"key": "D", "text": "周角"}]','A','圆周角定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0350-2','math','初中',11,'jkp-0350','single_choice',0.35,'顶点在圆上、两边都与圆相交的角叫？','[{"key": "A", "text": "圆周角"}, {"key": "B", "text": "圆心角"}, {"key": "D", "text": "周角"}, {"key": "C", "text": "平角"}]','A','圆周角定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0350-3','math','初中',11,'jkp-0350','single_choice',0.35,'顶点在圆上、两边都与圆相交的角叫？','[{"key": "B", "text": "圆心角"}, {"key": "D", "text": "周角"}, {"key": "C", "text": "平角"}, {"key": "A", "text": "圆周角"}]','A','圆周角定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0351-1','math','初中',11,'jkp-0351','single_choice',0.45,'同弧所对的圆心角 ∠AOB=31°，则圆周角 ∠ACB = ？','[{"key": "A", "text": "15.5°"}, {"key": "B", "text": "31°"}, {"key": "C", "text": "62°"}, {"key": "D", "text": "149°"}]','A','圆周角=圆心角一半=15.5°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0351-2','math','初中',11,'jkp-0351','single_choice',0.45,'同弧所对的圆心角 ∠AOB=69°，则圆周角 ∠ACB = ？','[{"key": "A", "text": "34.5°"}, {"key": "B", "text": "69°"}, {"key": "C", "text": "138°"}, {"key": "D", "text": "111°"}]','A','圆周角=圆心角一半=34.5°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0351-3','math','初中',11,'jkp-0351','single_choice',0.45,'同弧所对的圆心角 ∠AOB=75°，则圆周角 ∠ACB = ？','[{"key": "A", "text": "37.5°"}, {"key": "B", "text": "75°"}, {"key": "C", "text": "150°"}, {"key": "D", "text": "105°"}]','A','圆周角=圆心角一半=37.5°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0352-1','math','初中',11,'jkp-0352','single_choice',0.55,'同弧所对的圆周角？','[{"key": "A", "text": "相等"}, {"key": "B", "text": "互补"}, {"key": "C", "text": "互余"}, {"key": "D", "text": "成2倍"}]','A','同弧或等弧圆周角相等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0352-2','math','初中',11,'jkp-0352','single_choice',0.55,'同弧所对的圆周角？','[{"key": "A", "text": "相等"}, {"key": "C", "text": "互余"}, {"key": "D", "text": "成2倍"}, {"key": "B", "text": "互补"}]','A','同弧或等弧圆周角相等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0352-3','math','初中',11,'jkp-0352','single_choice',0.55,'同弧所对的圆周角？','[{"key": "A", "text": "相等"}, {"key": "C", "text": "互余"}, {"key": "B", "text": "互补"}, {"key": "D", "text": "成2倍"}]','A','同弧或等弧圆周角相等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0353-1','math','初中',11,'jkp-0353','single_choice',0.65,'直径所对的圆周角是？','[{"key": "A", "text": "直角"}, {"key": "B", "text": "锐角"}, {"key": "C", "text": "钝角"}, {"key": "D", "text": "平角"}]','A','直径所对圆周角 = 90°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0353-2','math','初中',11,'jkp-0353','single_choice',0.65,'直径所对的圆周角是？','[{"key": "B", "text": "锐角"}, {"key": "C", "text": "钝角"}, {"key": "D", "text": "平角"}, {"key": "A", "text": "直角"}]','A','直径所对圆周角 = 90°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0354-1','math','初中',11,'jkp-0354','single_choice',0.75,'圆内接四边形中 ∠A=52°，则对角 ∠C = ？','[{"key": "A", "text": "128°"}, {"key": "B", "text": "52°"}, {"key": "C", "text": "38°"}, {"key": "D", "text": "104°"}]','A','圆内接四边形对角互补：∠C=128°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0354-2','math','初中',11,'jkp-0354','single_choice',0.75,'圆内接四边形中 ∠A=89°，则对角 ∠C = ？','[{"key": "A", "text": "91°"}, {"key": "B", "text": "89°"}, {"key": "C", "text": "1°"}, {"key": "D", "text": "178°"}]','A','圆内接四边形对角互补：∠C=91°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0354-3','math','初中',11,'jkp-0354','single_choice',0.75,'圆内接四边形中 ∠A=49°，则对角 ∠C = ？','[{"key": "A", "text": "131°"}, {"key": "B", "text": "49°"}, {"key": "C", "text": "41°"}, {"key": "D", "text": "98°"}]','A','圆内接四边形对角互补：∠C=131°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0355-1','math','初中',11,'jkp-0355','single_choice',0.35,'圆 O 半径 4，点 P 到 O 距离 2，则 P 与圆的位置关系？','[{"key": "A", "text": "点在圆内"}, {"key": "B", "text": "点在圆上"}, {"key": "C", "text": "点在圆外"}, {"key": "D", "text": "无法确定"}]','A','距离 2 < 半径 4 → 点在圆内','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0355-2','math','初中',11,'jkp-0355','single_choice',0.35,'圆 O 半径 3，点 P 到 O 距离 2，则 P 与圆的位置关系？','[{"key": "A", "text": "点在圆内"}, {"key": "B", "text": "点在圆上"}, {"key": "C", "text": "点在圆外"}, {"key": "D", "text": "无法确定"}]','A','距离 2 < 半径 3 → 点在圆内','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0355-3','math','初中',11,'jkp-0355','single_choice',0.35,'圆 O 半径 4，点 P 到 O 距离 2，则 P 与圆的位置关系？','[{"key": "A", "text": "点在圆内"}, {"key": "D", "text": "无法确定"}, {"key": "B", "text": "点在圆上"}, {"key": "C", "text": "点在圆外"}]','A','距离 2 < 半径 4 → 点在圆内','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0356-1','math','初中',11,'jkp-0356','single_choice',0.45,'不在同一直线上的三个点确定？','[{"key": "A", "text": "一个圆"}, {"key": "B", "text": "一条直线"}, {"key": "C", "text": "两个圆"}, {"key": "D", "text": "一个三角形"}]','A','不共线三点确定一个圆','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0356-2','math','初中',11,'jkp-0356','single_choice',0.45,'不在同一直线上的三个点确定？','[{"key": "A", "text": "一个圆"}, {"key": "B", "text": "一条直线"}, {"key": "D", "text": "一个三角形"}, {"key": "C", "text": "两个圆"}]','A','不共线三点确定一个圆','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0356-3','math','初中',11,'jkp-0356','single_choice',0.45,'不在同一直线上的三个点确定？','[{"key": "C", "text": "两个圆"}, {"key": "B", "text": "一条直线"}, {"key": "A", "text": "一个圆"}, {"key": "D", "text": "一个三角形"}]','A','不共线三点确定一个圆','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0357-1','math','初中',11,'jkp-0357','single_choice',0.55,'三角形外接圆的圆心叫？','[{"key": "A", "text": "外心"}, {"key": "B", "text": "内心"}, {"key": "C", "text": "重心"}, {"key": "D", "text": "垂心"}]','A','外心：三边垂直平分线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0357-2','math','初中',11,'jkp-0357','single_choice',0.55,'三角形外接圆的圆心叫？','[{"key": "D", "text": "垂心"}, {"key": "B", "text": "内心"}, {"key": "C", "text": "重心"}, {"key": "A", "text": "外心"}]','A','外心：三边垂直平分线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0357-3','math','初中',11,'jkp-0357','single_choice',0.55,'三角形外接圆的圆心叫？','[{"key": "A", "text": "外心"}, {"key": "C", "text": "重心"}, {"key": "B", "text": "内心"}, {"key": "D", "text": "垂心"}]','A','外心：三边垂直平分线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0358-1','math','初中',11,'jkp-0358','single_choice',0.65,'圆心到直线距离 3，半径 3（d<r），直线与圆？','[{"key": "A", "text": "相交"}, {"key": "B", "text": "相切"}, {"key": "C", "text": "相离"}, {"key": "D", "text": "重合"}]','A','d=3<r=3 → 相交','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0358-2','math','初中',11,'jkp-0358','single_choice',0.65,'圆心到直线距离 4，半径 5（d<r），直线与圆？','[{"key": "A", "text": "相交"}, {"key": "B", "text": "相切"}, {"key": "C", "text": "相离"}, {"key": "D", "text": "重合"}]','A','d=4<r=5 → 相交','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0358-3','math','初中',11,'jkp-0358','single_choice',0.65,'圆心到直线距离 4，半径 3（d<r），直线与圆？','[{"key": "A", "text": "相交"}, {"key": "B", "text": "相切"}, {"key": "C", "text": "相离"}, {"key": "D", "text": "重合"}]','A','d=4<r=3 → 相交','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0359-1','math','初中',11,'jkp-0359','single_choice',0.75,'过半径外端且垂直于半径的直线是圆的？','[{"key": "A", "text": "切线"}, {"key": "B", "text": "弦"}, {"key": "C", "text": "直径"}, {"key": "D", "text": "割线"}]','A','切线判定定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0359-2','math','初中',11,'jkp-0359','single_choice',0.75,'过半径外端且垂直于半径的直线是圆的？','[{"key": "C", "text": "直径"}, {"key": "A", "text": "切线"}, {"key": "B", "text": "弦"}, {"key": "D", "text": "割线"}]','A','切线判定定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0359-3','math','初中',11,'jkp-0359','single_choice',0.75,'过半径外端且垂直于半径的直线是圆的？','[{"key": "A", "text": "切线"}, {"key": "B", "text": "弦"}, {"key": "D", "text": "割线"}, {"key": "C", "text": "直径"}]','A','切线判定定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0360-1','math','初中',11,'jkp-0360','single_choice',0.35,'圆的切线垂直于？','[{"key": "A", "text": "过切点的半径"}, {"key": "B", "text": "任意直径"}, {"key": "C", "text": "圆心连线"}, {"key": "D", "text": "弦"}]','A','切线性质：垂直于过切点的半径','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0360-2','math','初中',11,'jkp-0360','single_choice',0.35,'圆的切线垂直于？','[{"key": "B", "text": "任意直径"}, {"key": "D", "text": "弦"}, {"key": "A", "text": "过切点的半径"}, {"key": "C", "text": "圆心连线"}]','A','切线性质：垂直于过切点的半径','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0360-3','math','初中',11,'jkp-0360','single_choice',0.35,'圆的切线垂直于？','[{"key": "C", "text": "圆心连线"}, {"key": "B", "text": "任意直径"}, {"key": "A", "text": "过切点的半径"}, {"key": "D", "text": "弦"}]','A','切线性质：垂直于过切点的半径','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0361-1','math','初中',11,'jkp-0361','single_choice',0.45,'从圆外一点引两条切线，切线长 PA=3，则 PB = ？','[{"key": "A", "text": "3"}, {"key": "B", "text": "6"}, {"key": "C", "text": "1.5"}, {"key": "D", "text": "0"}]','A','切线长定理：两条切线长相等 = 3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0361-2','math','初中',11,'jkp-0361','single_choice',0.45,'从圆外一点引两条切线，切线长 PA=6，则 PB = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "12"}, {"key": "C", "text": "3.0"}, {"key": "D", "text": "0"}]','A','切线长定理：两条切线长相等 = 6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0361-3','math','初中',11,'jkp-0361','single_choice',0.45,'从圆外一点引两条切线，切线长 PA=5，则 PB = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "10"}, {"key": "C", "text": "2.5"}, {"key": "D", "text": "0"}]','A','切线长定理：两条切线长相等 = 5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0362-1','math','初中',11,'jkp-0362','single_choice',0.55,'三角形内切圆的圆心叫？','[{"key": "A", "text": "内心"}, {"key": "B", "text": "外心"}, {"key": "C", "text": "重心"}, {"key": "D", "text": "垂心"}]','A','内心：角平分线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0362-2','math','初中',11,'jkp-0362','single_choice',0.55,'三角形内切圆的圆心叫？','[{"key": "C", "text": "重心"}, {"key": "A", "text": "内心"}, {"key": "B", "text": "外心"}, {"key": "D", "text": "垂心"}]','A','内心：角平分线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0362-3','math','初中',11,'jkp-0362','single_choice',0.55,'三角形内切圆的圆心叫？','[{"key": "C", "text": "重心"}, {"key": "A", "text": "内心"}, {"key": "D", "text": "垂心"}, {"key": "B", "text": "外心"}]','A','内心：角平分线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0363-1','math','初中',11,'jkp-0363','single_choice',0.65,'两圆半径 3、4，圆心距 7，两圆？','[{"key": "A", "text": "外切"}, {"key": "B", "text": "外离"}, {"key": "C", "text": "内切"}, {"key": "D", "text": "内含"}]','A','圆心距=两半径和 → 外切','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0363-2','math','初中',11,'jkp-0363','single_choice',0.65,'两圆半径 3、4，圆心距 7，两圆？','[{"key": "B", "text": "外离"}, {"key": "A", "text": "外切"}, {"key": "C", "text": "内切"}, {"key": "D", "text": "内含"}]','A','圆心距=两半径和 → 外切','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0363-3','math','初中',11,'jkp-0363','single_choice',0.65,'两圆半径 3、4，圆心距 7，两圆？','[{"key": "C", "text": "内切"}, {"key": "D", "text": "内含"}, {"key": "B", "text": "外离"}, {"key": "A", "text": "外切"}]','A','圆心距=两半径和 → 外切','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0364-1','math','初中',11,'jkp-0364','single_choice',0.75,'正6边形中心角 = 360°/6 = ？','[{"key": "A", "text": "60.0°"}, {"key": "B", "text": "30.0°"}, {"key": "C", "text": "15.0°"}, {"key": "D", "text": "6°"}]','A','中心角=360°/6=60.0°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0364-2','math','初中',11,'jkp-0364','single_choice',0.75,'正5边形中心角 = 360°/5 = ？','[{"key": "A", "text": "72.0°"}, {"key": "B", "text": "36.0°"}, {"key": "C", "text": "18.0°"}, {"key": "D", "text": "5°"}]','A','中心角=360°/5=72.0°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0364-3','math','初中',11,'jkp-0364','single_choice',0.75,'正4边形中心角 = 360°/4 = ？','[{"key": "A", "text": "90.0°"}, {"key": "B", "text": "45.0°"}, {"key": "C", "text": "22.5°"}, {"key": "D", "text": "4°"}]','A','中心角=360°/4=90.0°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0365-1','math','初中',11,'jkp-0365','single_choice',0.35,'半径 3、圆心角 76° 的弧长 l = nπr/180 = ？','[{"key": "A", "text": "3.98π"}, {"key": "B", "text": "76π"}, {"key": "C", "text": "3π"}, {"key": "D", "text": "228π"}]','A','l=76π×3/180=3.98π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0365-2','math','初中',11,'jkp-0365','single_choice',0.35,'半径 3、圆心角 65° 的弧长 l = nπr/180 = ？','[{"key": "A", "text": "3.40π"}, {"key": "B", "text": "65π"}, {"key": "C", "text": "3π"}, {"key": "D", "text": "195π"}]','A','l=65π×3/180=3.40π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0365-3','math','初中',11,'jkp-0365','single_choice',0.35,'半径 2、圆心角 108° 的弧长 l = nπr/180 = ？','[{"key": "A", "text": "3.77π"}, {"key": "B", "text": "108π"}, {"key": "C", "text": "2π"}, {"key": "D", "text": "216π"}]','A','l=108π×2/180=3.77π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0366-1','math','初中',11,'jkp-0366','single_choice',0.45,'半径 4、圆心角 96° 的扇形面积 S = nπr²/360 = ？','[{"key": "A", "text": "13.40π"}, {"key": "B", "text": "96π"}, {"key": "C", "text": "16π"}, {"key": "D", "text": "384π"}]','A','S=96π×4²/360=13.40π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0366-2','math','初中',11,'jkp-0366','single_choice',0.45,'半径 2、圆心角 71° 的扇形面积 S = nπr²/360 = ？','[{"key": "A", "text": "2.48π"}, {"key": "B", "text": "71π"}, {"key": "C", "text": "4π"}, {"key": "D", "text": "142π"}]','A','S=71π×2²/360=2.48π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0366-3','math','初中',11,'jkp-0366','single_choice',0.45,'半径 2、圆心角 81° 的扇形面积 S = nπr²/360 = ？','[{"key": "A", "text": "2.83π"}, {"key": "B", "text": "81π"}, {"key": "C", "text": "4π"}, {"key": "D", "text": "162π"}]','A','S=81π×2²/360=2.83π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0367-1','math','初中',11,'jkp-0367','single_choice',0.55,'圆锥底面半径 2、母线 5，侧面积 = πrl = ？','[{"key": "A", "text": "10π"}, {"key": "B", "text": "4π"}, {"key": "C", "text": "25π"}, {"key": "D", "text": "20π"}]','A','S侧=πrl=2×5π=10π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0367-2','math','初中',11,'jkp-0367','single_choice',0.55,'圆锥底面半径 4、母线 4，侧面积 = πrl = ？','[{"key": "A", "text": "16π"}, {"key": "B", "text": "16π"}, {"key": "C", "text": "16π"}, {"key": "D", "text": "32π"}]','A','S侧=πrl=4×4π=16π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0367-3','math','初中',11,'jkp-0367','single_choice',0.55,'圆锥底面半径 3、母线 7，侧面积 = πrl = ？','[{"key": "A", "text": "21π"}, {"key": "B", "text": "9π"}, {"key": "C", "text": "49π"}, {"key": "D", "text": "42π"}]','A','S侧=πrl=3×7π=21π','template-j','approved','通用');