-- 第19章 四边形 补题（10学期, 知识点 278-299）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0278-1','math','初中',10,'jkp-0278','single_choice',0.65,'两组对边分别平行的四边形叫？','[{"key": "A", "text": "平行四边形"}, {"key": "B", "text": "梯形"}, {"key": "C", "text": "菱形"}, {"key": "D", "text": "矩形"}]','A','平行四边形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0278-2','math','初中',10,'jkp-0278','single_choice',0.65,'两组对边分别平行的四边形叫？','[{"key": "D", "text": "矩形"}, {"key": "A", "text": "平行四边形"}, {"key": "B", "text": "梯形"}, {"key": "C", "text": "菱形"}]','A','平行四边形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0278-3','math','初中',10,'jkp-0278','single_choice',0.65,'两组对边分别平行的四边形叫？','[{"key": "C", "text": "菱形"}, {"key": "A", "text": "平行四边形"}, {"key": "D", "text": "矩形"}, {"key": "B", "text": "梯形"}]','A','平行四边形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0279-1','math','初中',10,'jkp-0279','single_choice',0.75,'平行四边形对边的性质是？','[{"key": "A", "text": "对边平行且相等"}, {"key": "B", "text": "对边垂直"}, {"key": "C", "text": "对边不相等"}, {"key": "D", "text": "只有一边平行"}]','A','平行四边形对边平行且相等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0280-1','math','初中',10,'jkp-0280','single_choice',0.35,'平行四边形一个角为 71°，则相邻角 = ？','[{"key": "A", "text": "109°"}, {"key": "B", "text": "71°"}, {"key": "C", "text": "19°"}, {"key": "D", "text": "142°"}]','A','邻角互补：109°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0280-2','math','初中',10,'jkp-0280','single_choice',0.35,'平行四边形一个角为 72°，则相邻角 = ？','[{"key": "A", "text": "108°"}, {"key": "B", "text": "72°"}, {"key": "C", "text": "18°"}, {"key": "D", "text": "144°"}]','A','邻角互补：108°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0280-3','math','初中',10,'jkp-0280','single_choice',0.35,'平行四边形一个角为 61°，则相邻角 = ？','[{"key": "A", "text": "119°"}, {"key": "B", "text": "61°"}, {"key": "C", "text": "29°"}, {"key": "D", "text": "122°"}]','A','邻角互补：119°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0281-1','math','初中',10,'jkp-0281','single_choice',0.45,'平行四边形对角线？','[{"key": "A", "text": "互相平分"}, {"key": "B", "text": "相等"}, {"key": "C", "text": "垂直"}, {"key": "D", "text": "互相平分且相等"}]','A','平行四边形对角线互相平分','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0281-2','math','初中',10,'jkp-0281','single_choice',0.45,'平行四边形对角线？','[{"key": "C", "text": "垂直"}, {"key": "B", "text": "相等"}, {"key": "A", "text": "互相平分"}, {"key": "D", "text": "互相平分且相等"}]','A','平行四边形对角线互相平分','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0281-3','math','初中',10,'jkp-0281','single_choice',0.45,'平行四边形对角线？','[{"key": "D", "text": "互相平分且相等"}, {"key": "A", "text": "互相平分"}, {"key": "B", "text": "相等"}, {"key": "C", "text": "垂直"}]','A','平行四边形对角线互相平分','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0282-1','math','初中',10,'jkp-0282','single_choice',0.55,'两组对边分别平行的四边形是？判定','[{"key": "A", "text": "平行四边形"}, {"key": "B", "text": "梯形"}, {"key": "C", "text": "菱形"}, {"key": "D", "text": "矩形"}]','A','判定1：两组对边平行 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0282-2','math','初中',10,'jkp-0282','single_choice',0.55,'两组对边分别平行的四边形是？判定','[{"key": "C", "text": "菱形"}, {"key": "B", "text": "梯形"}, {"key": "D", "text": "矩形"}, {"key": "A", "text": "平行四边形"}]','A','判定1：两组对边平行 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0282-3','math','初中',10,'jkp-0282','single_choice',0.55,'两组对边分别平行的四边形是？判定','[{"key": "D", "text": "矩形"}, {"key": "A", "text": "平行四边形"}, {"key": "C", "text": "菱形"}, {"key": "B", "text": "梯形"}]','A','判定1：两组对边平行 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0283-1','math','初中',10,'jkp-0283','single_choice',0.65,'两组对边分别相等的四边形是？','[{"key": "A", "text": "平行四边形"}, {"key": "B", "text": "梯形"}, {"key": "C", "text": "等腰梯形"}, {"key": "D", "text": "任意四边形"}]','A','判定2：两组对边相等 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0283-2','math','初中',10,'jkp-0283','single_choice',0.65,'两组对边分别相等的四边形是？','[{"key": "A", "text": "平行四边形"}, {"key": "D", "text": "任意四边形"}, {"key": "C", "text": "等腰梯形"}, {"key": "B", "text": "梯形"}]','A','判定2：两组对边相等 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0283-3','math','初中',10,'jkp-0283','single_choice',0.65,'两组对边分别相等的四边形是？','[{"key": "D", "text": "任意四边形"}, {"key": "A", "text": "平行四边形"}, {"key": "B", "text": "梯形"}, {"key": "C", "text": "等腰梯形"}]','A','判定2：两组对边相等 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0284-1','math','初中',10,'jkp-0284','single_choice',0.75,'一组对边平行且相等的四边形是？','[{"key": "A", "text": "平行四边形"}, {"key": "B", "text": "梯形"}, {"key": "C", "text": "矩形"}, {"key": "D", "text": "菱形"}]','A','判定3：一组对边平行且相等 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0284-2','math','初中',10,'jkp-0284','single_choice',0.75,'一组对边平行且相等的四边形是？','[{"key": "C", "text": "矩形"}, {"key": "B", "text": "梯形"}, {"key": "A", "text": "平行四边形"}, {"key": "D", "text": "菱形"}]','A','判定3：一组对边平行且相等 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0284-3','math','初中',10,'jkp-0284','single_choice',0.75,'一组对边平行且相等的四边形是？','[{"key": "C", "text": "矩形"}, {"key": "B", "text": "梯形"}, {"key": "D", "text": "菱形"}, {"key": "A", "text": "平行四边形"}]','A','判定3：一组对边平行且相等 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0285-1','math','初中',10,'jkp-0285','single_choice',0.35,'对角线互相平分的四边形是？','[{"key": "A", "text": "平行四边形"}, {"key": "B", "text": "梯形"}, {"key": "C", "text": "等腰梯形"}, {"key": "D", "text": "不规则四边形"}]','A','判定4：对角线互相平分 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0285-2','math','初中',10,'jkp-0285','single_choice',0.35,'对角线互相平分的四边形是？','[{"key": "C", "text": "等腰梯形"}, {"key": "B", "text": "梯形"}, {"key": "D", "text": "不规则四边形"}, {"key": "A", "text": "平行四边形"}]','A','判定4：对角线互相平分 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0285-3','math','初中',10,'jkp-0285','single_choice',0.35,'对角线互相平分的四边形是？','[{"key": "A", "text": "平行四边形"}, {"key": "B", "text": "梯形"}, {"key": "D", "text": "不规则四边形"}, {"key": "C", "text": "等腰梯形"}]','A','判定4：对角线互相平分 → 平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0286-1','math','初中',10,'jkp-0286','single_choice',0.45,'△ABC 中 D、E 是 AB、AC 中点，BC=6，则 DE = ？','[{"key": "A", "text": "3.0"}, {"key": "B", "text": "6"}, {"key": "C", "text": "12"}, {"key": "D", "text": "8"}]','A','中位线=BC/2=6/2=3.0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0286-2','math','初中',10,'jkp-0286','single_choice',0.45,'△ABC 中 D、E 是 AB、AC 中点，BC=5，则 DE = ？','[{"key": "A", "text": "2.5"}, {"key": "B", "text": "5"}, {"key": "C", "text": "10"}, {"key": "D", "text": "7"}]','A','中位线=BC/2=5/2=2.5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0286-3','math','初中',10,'jkp-0286','single_choice',0.45,'△ABC 中 D、E 是 AB、AC 中点，BC=8，则 DE = ？','[{"key": "A", "text": "4.0"}, {"key": "B", "text": "8"}, {"key": "C", "text": "16"}, {"key": "D", "text": "10"}]','A','中位线=BC/2=8/2=4.0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0287-1','math','初中',10,'jkp-0287','single_choice',0.55,'有一个角是直角的平行四边形是？','[{"key": "A", "text": "矩形"}, {"key": "B", "text": "菱形"}, {"key": "C", "text": "正方形"}, {"key": "D", "text": "梯形"}]','A','矩形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0287-2','math','初中',10,'jkp-0287','single_choice',0.55,'有一个角是直角的平行四边形是？','[{"key": "C", "text": "正方形"}, {"key": "A", "text": "矩形"}, {"key": "B", "text": "菱形"}, {"key": "D", "text": "梯形"}]','A','矩形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0287-3','math','初中',10,'jkp-0287','single_choice',0.55,'有一个角是直角的平行四边形是？','[{"key": "A", "text": "矩形"}, {"key": "B", "text": "菱形"}, {"key": "D", "text": "梯形"}, {"key": "C", "text": "正方形"}]','A','矩形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0288-1','math','初中',10,'jkp-0288','single_choice',0.65,'矩形的对角线？','[{"key": "A", "text": "相等且互相平分"}, {"key": "B", "text": "互相垂直"}, {"key": "C", "text": "平分对角"}, {"key": "D", "text": "不相等"}]','A','矩形性质：对角线相等且互相平分','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0288-2','math','初中',10,'jkp-0288','single_choice',0.65,'矩形的对角线？','[{"key": "D", "text": "不相等"}, {"key": "B", "text": "互相垂直"}, {"key": "C", "text": "平分对角"}, {"key": "A", "text": "相等且互相平分"}]','A','矩形性质：对角线相等且互相平分','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0288-3','math','初中',10,'jkp-0288','single_choice',0.65,'矩形的对角线？','[{"key": "A", "text": "相等且互相平分"}, {"key": "D", "text": "不相等"}, {"key": "B", "text": "互相垂直"}, {"key": "C", "text": "平分对角"}]','A','矩形性质：对角线相等且互相平分','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0289-1','math','初中',10,'jkp-0289','single_choice',0.75,'下列能判定矩形的是？','[{"key": "A", "text": "有一个直角的平行四边形"}, {"key": "B", "text": "有一组邻边相等的平行四边形"}, {"key": "C", "text": "对角线垂直的平行四边形"}, {"key": "D", "text": "四边相等"}]','A','矩形判定：一个直角的平行四边形等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0289-2','math','初中',10,'jkp-0289','single_choice',0.75,'下列能判定矩形的是？','[{"key": "C", "text": "对角线垂直的平行四边形"}, {"key": "D", "text": "四边相等"}, {"key": "B", "text": "有一组邻边相等的平行四边形"}, {"key": "A", "text": "有一个直角的平行四边形"}]','A','矩形判定：一个直角的平行四边形等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0289-3','math','初中',10,'jkp-0289','single_choice',0.75,'下列能判定矩形的是？','[{"key": "C", "text": "对角线垂直的平行四边形"}, {"key": "A", "text": "有一个直角的平行四边形"}, {"key": "B", "text": "有一组邻边相等的平行四边形"}, {"key": "D", "text": "四边相等"}]','A','矩形判定：一个直角的平行四边形等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0290-1','math','初中',10,'jkp-0290','single_choice',0.35,'Rt△ABC 中，斜边 AB=6，斜边中线 CD = ？','[{"key": "A", "text": "3.0"}, {"key": "B", "text": "6"}, {"key": "C", "text": "12"}, {"key": "D", "text": "7"}]','A','直角三角形斜边中线=斜边一半=6/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0290-2','math','初中',10,'jkp-0290','single_choice',0.35,'Rt△ABC 中，斜边 AB=4，斜边中线 CD = ？','[{"key": "A", "text": "2.0"}, {"key": "B", "text": "4"}, {"key": "C", "text": "8"}, {"key": "D", "text": "5"}]','A','直角三角形斜边中线=斜边一半=4/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0290-3','math','初中',10,'jkp-0290','single_choice',0.35,'Rt△ABC 中，斜边 AB=8，斜边中线 CD = ？','[{"key": "A", "text": "4.0"}, {"key": "B", "text": "8"}, {"key": "C", "text": "16"}, {"key": "D", "text": "9"}]','A','直角三角形斜边中线=斜边一半=8/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0291-1','math','初中',10,'jkp-0291','single_choice',0.45,'有一组邻边相等的平行四边形是？','[{"key": "A", "text": "菱形"}, {"key": "B", "text": "矩形"}, {"key": "C", "text": "正方形"}, {"key": "D", "text": "梯形"}]','A','菱形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0291-2','math','初中',10,'jkp-0291','single_choice',0.45,'有一组邻边相等的平行四边形是？','[{"key": "B", "text": "矩形"}, {"key": "A", "text": "菱形"}, {"key": "C", "text": "正方形"}, {"key": "D", "text": "梯形"}]','A','菱形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0291-3','math','初中',10,'jkp-0291','single_choice',0.45,'有一组邻边相等的平行四边形是？','[{"key": "A", "text": "菱形"}, {"key": "C", "text": "正方形"}, {"key": "B", "text": "矩形"}, {"key": "D", "text": "梯形"}]','A','菱形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0292-1','math','初中',10,'jkp-0292','single_choice',0.55,'菱形的对角线？','[{"key": "A", "text": "垂直平分且平分对角"}, {"key": "B", "text": "相等"}, {"key": "C", "text": "互相平分且相等"}, {"key": "D", "text": "不垂直"}]','A','菱形性质：对角线垂直平分，平分内角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0292-2','math','初中',10,'jkp-0292','single_choice',0.55,'菱形的对角线？','[{"key": "D", "text": "不垂直"}, {"key": "A", "text": "垂直平分且平分对角"}, {"key": "C", "text": "互相平分且相等"}, {"key": "B", "text": "相等"}]','A','菱形性质：对角线垂直平分，平分内角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0292-3','math','初中',10,'jkp-0292','single_choice',0.55,'菱形的对角线？','[{"key": "B", "text": "相等"}, {"key": "D", "text": "不垂直"}, {"key": "A", "text": "垂直平分且平分对角"}, {"key": "C", "text": "互相平分且相等"}]','A','菱形性质：对角线垂直平分，平分内角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0293-1','math','初中',10,'jkp-0293','single_choice',0.65,'菱形面积两种算法：S = 底×高 = ？','[{"key": "A", "text": "对角线乘积的一半"}, {"key": "B", "text": "对角线乘积"}, {"key": "C", "text": "边长平方"}, {"key": "D", "text": "周长×高"}]','A','菱形面积 = ½×对角线乘积','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0293-2','math','初中',10,'jkp-0293','single_choice',0.65,'菱形面积两种算法：S = 底×高 = ？','[{"key": "B", "text": "对角线乘积"}, {"key": "A", "text": "对角线乘积的一半"}, {"key": "D", "text": "周长×高"}, {"key": "C", "text": "边长平方"}]','A','菱形面积 = ½×对角线乘积','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0293-3','math','初中',10,'jkp-0293','single_choice',0.65,'菱形面积两种算法：S = 底×高 = ？','[{"key": "C", "text": "边长平方"}, {"key": "D", "text": "周长×高"}, {"key": "B", "text": "对角线乘积"}, {"key": "A", "text": "对角线乘积的一半"}]','A','菱形面积 = ½×对角线乘积','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0294-1','math','初中',10,'jkp-0294','single_choice',0.75,'下列能判定菱形的是？','[{"key": "A", "text": "四边相等的四边形"}, {"key": "B", "text": "两组对边平行的四边形"}, {"key": "C", "text": "一个直角的平行四边形"}, {"key": "D", "text": "对角线相等的平行四边形"}]','A','菱形判定：四边相等/邻边相等的平行四边形/对角线垂直','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0294-2','math','初中',10,'jkp-0294','single_choice',0.75,'下列能判定菱形的是？','[{"key": "C", "text": "一个直角的平行四边形"}, {"key": "D", "text": "对角线相等的平行四边形"}, {"key": "B", "text": "两组对边平行的四边形"}, {"key": "A", "text": "四边相等的四边形"}]','A','菱形判定：四边相等/邻边相等的平行四边形/对角线垂直','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0294-3','math','初中',10,'jkp-0294','single_choice',0.75,'下列能判定菱形的是？','[{"key": "B", "text": "两组对边平行的四边形"}, {"key": "C", "text": "一个直角的平行四边形"}, {"key": "D", "text": "对角线相等的平行四边形"}, {"key": "A", "text": "四边相等的四边形"}]','A','菱形判定：四边相等/邻边相等的平行四边形/对角线垂直','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0295-1','math','初中',10,'jkp-0295','single_choice',0.35,'四边相等且四角都是直角的四边形是？','[{"key": "A", "text": "正方形"}, {"key": "B", "text": "矩形"}, {"key": "C", "text": "菱形"}, {"key": "D", "text": "平行四边形"}]','A','正方形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0295-2','math','初中',10,'jkp-0295','single_choice',0.35,'四边相等且四角都是直角的四边形是？','[{"key": "B", "text": "矩形"}, {"key": "C", "text": "菱形"}, {"key": "D", "text": "平行四边形"}, {"key": "A", "text": "正方形"}]','A','正方形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0295-3','math','初中',10,'jkp-0295','single_choice',0.35,'四边相等且四角都是直角的四边形是？','[{"key": "D", "text": "平行四边形"}, {"key": "B", "text": "矩形"}, {"key": "A", "text": "正方形"}, {"key": "C", "text": "菱形"}]','A','正方形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0296-1','math','初中',10,'jkp-0296','single_choice',0.45,'正方形同时具有？的性质','[{"key": "A", "text": "矩形和菱形全部"}, {"key": "B", "text": "只具有矩形"}, {"key": "C", "text": "只具有菱形"}, {"key": "D", "text": "两者都没有"}]','A','正方形兼具矩形、菱形全部性质','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0296-2','math','初中',10,'jkp-0296','single_choice',0.45,'正方形同时具有？的性质','[{"key": "B", "text": "只具有矩形"}, {"key": "D", "text": "两者都没有"}, {"key": "A", "text": "矩形和菱形全部"}, {"key": "C", "text": "只具有菱形"}]','A','正方形兼具矩形、菱形全部性质','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0296-3','math','初中',10,'jkp-0296','single_choice',0.45,'正方形同时具有？的性质','[{"key": "C", "text": "只具有菱形"}, {"key": "D", "text": "两者都没有"}, {"key": "A", "text": "矩形和菱形全部"}, {"key": "B", "text": "只具有矩形"}]','A','正方形兼具矩形、菱形全部性质','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0297-1','math','初中',10,'jkp-0297','single_choice',0.55,'判定正方形：先证矩形再证？','[{"key": "A", "text": "邻边相等（或对角线垂直）"}, {"key": "B", "text": "对边平行"}, {"key": "C", "text": "对角相等"}, {"key": "D", "text": "内角和360°"}]','A','正方形判定思路：矩形+菱形特征','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0297-2','math','初中',10,'jkp-0297','single_choice',0.55,'判定正方形：先证矩形再证？','[{"key": "D", "text": "内角和360°"}, {"key": "B", "text": "对边平行"}, {"key": "C", "text": "对角相等"}, {"key": "A", "text": "邻边相等（或对角线垂直）"}]','A','正方形判定思路：矩形+菱形特征','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0297-3','math','初中',10,'jkp-0297','single_choice',0.55,'判定正方形：先证矩形再证？','[{"key": "D", "text": "内角和360°"}, {"key": "A", "text": "邻边相等（或对角线垂直）"}, {"key": "C", "text": "对角相等"}, {"key": "B", "text": "对边平行"}]','A','正方形判定思路：矩形+菱形特征','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0298-1','math','初中',10,'jkp-0298','single_choice',0.65,'等腰梯形的两腰？','[{"key": "A", "text": "相等"}, {"key": "B", "text": "平行"}, {"key": "C", "text": "垂直"}, {"key": "D", "text": "不相等"}]','A','等腰梯形：两腰相等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0298-2','math','初中',10,'jkp-0298','single_choice',0.65,'等腰梯形的两腰？','[{"key": "C", "text": "垂直"}, {"key": "B", "text": "平行"}, {"key": "D", "text": "不相等"}, {"key": "A", "text": "相等"}]','A','等腰梯形：两腰相等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0298-3','math','初中',10,'jkp-0298','single_choice',0.65,'等腰梯形的两腰？','[{"key": "D", "text": "不相等"}, {"key": "A", "text": "相等"}, {"key": "B", "text": "平行"}, {"key": "C", "text": "垂直"}]','A','等腰梯形：两腰相等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0299-1','math','初中',10,'jkp-0299','single_choice',0.75,'顺次连接四边形各边中点得到的四边形是？','[{"key": "A", "text": "平行四边形"}, {"key": "B", "text": "矩形"}, {"key": "C", "text": "菱形"}, {"key": "D", "text": "正方形"}]','A','中点四边形一定是平行四边形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0299-2','math','初中',10,'jkp-0299','single_choice',0.75,'顺次连接四边形各边中点得到的四边形是？','[{"key": "D", "text": "正方形"}, {"key": "B", "text": "矩形"}, {"key": "A", "text": "平行四边形"}, {"key": "C", "text": "菱形"}]','A','中点四边形一定是平行四边形','template-j','approved','通用');