-- 第8章 二元一次方程组 补题（8学期, 知识点 119-130）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0119-1','math','初中',8,'jkp-0119','single_choice',0.75,'1x + 2y = 6 是？元？次方程','[{"key": "A", "text": "二 一"}, {"key": "B", "text": "一 二"}, {"key": "C", "text": "二 二"}, {"key": "D", "text": "一 一"}]','A','含两个未知数且次数为 1 → 二元一次方程','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0119-2','math','初中',8,'jkp-0119','single_choice',0.75,'1x + 4y = 1 是？元？次方程','[{"key": "A", "text": "二 一"}, {"key": "B", "text": "一 二"}, {"key": "C", "text": "二 二"}, {"key": "D", "text": "一 一"}]','A','含两个未知数且次数为 1 → 二元一次方程','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0119-3','math','初中',8,'jkp-0119','single_choice',0.75,'4x + 2y = 2 是？元？次方程','[{"key": "A", "text": "二 一"}, {"key": "B", "text": "一 二"}, {"key": "C", "text": "二 二"}, {"key": "D", "text": "一 一"}]','A','含两个未知数且次数为 1 → 二元一次方程','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0120-1','math','初中',8,'jkp-0120','single_choice',0.35,'x=3，y=1 是方程 x+y=4 的一个解吗？','[{"key": "A", "text": "是"}, {"key": "B", "text": "否"}, {"key": "C", "text": "无法判断"}, {"key": "D", "text": "不一定"}]','A','代入 3+1=4 成立 → 是解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0120-2','math','初中',8,'jkp-0120','single_choice',0.35,'x=2，y=3 是方程 x+y=5 的一个解吗？','[{"key": "A", "text": "是"}, {"key": "B", "text": "否"}, {"key": "C", "text": "无法判断"}, {"key": "D", "text": "不一定"}]','A','代入 2+3=5 成立 → 是解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0120-3','math','初中',8,'jkp-0120','single_choice',0.35,'x=3，y=2 是方程 x+y=5 的一个解吗？','[{"key": "A", "text": "是"}, {"key": "B", "text": "否"}, {"key": "C", "text": "无法判断"}, {"key": "D", "text": "不一定"}]','A','代入 3+2=5 成立 → 是解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0121-1','math','初中',8,'jkp-0121','single_choice',0.45,'两个二元一次方程合在一起叫？','[{"key": "A", "text": "二元一次方程组"}, {"key": "B", "text": "三元一次方程组"}, {"key": "C", "text": "一元一次方程"}, {"key": "D", "text": "分式方程"}]','A','二元一次方程组定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0121-2','math','初中',8,'jkp-0121','single_choice',0.45,'两个二元一次方程合在一起叫？','[{"key": "C", "text": "一元一次方程"}, {"key": "A", "text": "二元一次方程组"}, {"key": "D", "text": "分式方程"}, {"key": "B", "text": "三元一次方程组"}]','A','二元一次方程组定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0121-3','math','初中',8,'jkp-0121','single_choice',0.45,'两个二元一次方程合在一起叫？','[{"key": "A", "text": "二元一次方程组"}, {"key": "D", "text": "分式方程"}, {"key": "B", "text": "三元一次方程组"}, {"key": "C", "text": "一元一次方程"}]','A','二元一次方程组定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0122-1','math','初中',8,'jkp-0122','single_choice',0.55,'同时满足方程组中两个方程的解叫？','[{"key": "A", "text": "方程组的解"}, {"key": "B", "text": "方程的解"}, {"key": "C", "text": "未知数"}, {"key": "D", "text": "系数"}]','A','方程组解的定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0122-2','math','初中',8,'jkp-0122','single_choice',0.55,'同时满足方程组中两个方程的解叫？','[{"key": "A", "text": "方程组的解"}, {"key": "C", "text": "未知数"}, {"key": "B", "text": "方程的解"}, {"key": "D", "text": "系数"}]','A','方程组解的定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0122-3','math','初中',8,'jkp-0122','single_choice',0.55,'同时满足方程组中两个方程的解叫？','[{"key": "B", "text": "方程的解"}, {"key": "A", "text": "方程组的解"}, {"key": "D", "text": "系数"}, {"key": "C", "text": "未知数"}]','A','方程组解的定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0123-1','math','初中',8,'jkp-0123','single_choice',0.65,'方程组 {x+y=7, x-y=-3} 用代入消元，解得 x = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "5"}, {"key": "C", "text": "7"}, {"key": "D", "text": "-3"}]','A','解得 x=2，y=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0123-2','math','初中',8,'jkp-0123','single_choice',0.65,'方程组 {x+y=4, x-y=0} 用代入消元，解得 x = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "2"}, {"key": "C", "text": "4"}, {"key": "D", "text": "0"}]','A','解得 x=2，y=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0123-3','math','初中',8,'jkp-0123','single_choice',0.65,'方程组 {x+y=3, x-y=1} 用代入消元，解得 x = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "1"}, {"key": "C", "text": "3"}, {"key": "D", "text": "1"}]','A','解得 x=2，y=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0124-1','math','初中',8,'jkp-0124','single_choice',0.75,'方程组 {x+y=9, x-y=1} 用加减消元：两式相加得 2x = ？','[{"key": "A", "text": "10"}, {"key": "B", "text": "8"}, {"key": "C", "text": "9"}, {"key": "D", "text": "5"}]','A','相加消 y：2x=10，x=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0124-2','math','初中',8,'jkp-0124','single_choice',0.75,'方程组 {x+y=9, x-y=-1} 用加减消元：两式相加得 2x = ？','[{"key": "A", "text": "8"}, {"key": "B", "text": "10"}, {"key": "C", "text": "9"}, {"key": "D", "text": "4"}]','A','相加消 y：2x=8，x=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0124-3','math','初中',8,'jkp-0124','single_choice',0.75,'方程组 {x+y=7, x-y=1} 用加减消元：两式相加得 2x = ？','[{"key": "A", "text": "8"}, {"key": "B", "text": "6"}, {"key": "C", "text": "7"}, {"key": "D", "text": "4"}]','A','相加消 y：2x=8，x=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0125-1','math','初中',8,'jkp-0125','single_choice',0.35,'当两个方程中某个未知数系数相等或相反时，宜用？','[{"key": "A", "text": "加减消元法"}, {"key": "B", "text": "代入消元法"}, {"key": "C", "text": "图像法"}, {"key": "D", "text": "试值法"}]','A','系数相等/相反 → 加减消元','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0125-2','math','初中',8,'jkp-0125','single_choice',0.35,'当两个方程中某个未知数系数相等或相反时，宜用？','[{"key": "C", "text": "图像法"}, {"key": "A", "text": "加减消元法"}, {"key": "B", "text": "代入消元法"}, {"key": "D", "text": "试值法"}]','A','系数相等/相反 → 加减消元','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0125-3','math','初中',8,'jkp-0125','single_choice',0.35,'当两个方程中某个未知数系数相等或相反时，宜用？','[{"key": "C", "text": "图像法"}, {"key": "D", "text": "试值法"}, {"key": "B", "text": "代入消元法"}, {"key": "A", "text": "加减消元法"}]','A','系数相等/相反 → 加减消元','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0126-1','math','初中',8,'jkp-0126','single_choice',0.45,'甲、乙相距 12 km，相向而行 3 小时相遇，速度和 = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "12"}, {"key": "C", "text": "1.3333333333333333"}, {"key": "D", "text": "8"}]','A','速度和=路程/时间=12/3=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0126-2','math','初中',8,'jkp-0126','single_choice',0.45,'甲、乙相距 12 km，相向而行 2 小时相遇，速度和 = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "12"}, {"key": "C", "text": "3.0"}, {"key": "D", "text": "12"}]','A','速度和=路程/时间=12/2=6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0126-3','math','初中',8,'jkp-0126','single_choice',0.45,'甲、乙相距 24 km，相向而行 4 小时相遇，速度和 = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "24"}, {"key": "C", "text": "1.5"}, {"key": "D", "text": "12"}]','A','速度和=路程/时间=24/4=6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0127-1','math','初中',8,'jkp-0127','single_choice',0.55,'甲独做需 6 天，乙独做需 3 天，合做 1 天完成工程的？','[{"key": "A", "text": "1/6+1/3"}, {"key": "B", "text": "1/(6+3)"}, {"key": "C", "text": "6+3"}, {"key": "D", "text": "1/18"}]','A','合做效率=1/6+1/3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0127-2','math','初中',8,'jkp-0127','single_choice',0.55,'甲独做需 6 天，乙独做需 2 天，合做 1 天完成工程的？','[{"key": "A", "text": "1/6+1/2"}, {"key": "B", "text": "1/(6+2)"}, {"key": "C", "text": "6+2"}, {"key": "D", "text": "1/12"}]','A','合做效率=1/6+1/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0127-3','math','初中',8,'jkp-0127','single_choice',0.55,'甲独做需 3 天，乙独做需 4 天，合做 1 天完成工程的？','[{"key": "A", "text": "1/3+1/4"}, {"key": "B", "text": "1/(3+4)"}, {"key": "C", "text": "3+4"}, {"key": "D", "text": "1/12"}]','A','合做效率=1/3+1/4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0128-1','math','初中',8,'jkp-0128','single_choice',0.65,'1 个桌面配 4 条桌腿，x 桌面 y 腿配套时满足？','[{"key": "A", "text": "y = 4x"}, {"key": "B", "text": "x = 4y"}, {"key": "C", "text": "x = y"}, {"key": "D", "text": "x + y = 4"}]','A','配套：腿是桌面的 4 倍 → y=4x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0128-2','math','初中',8,'jkp-0128','single_choice',0.65,'1 个桌面配 4 条桌腿，x 桌面 y 腿配套时满足？','[{"key": "B", "text": "x = 4y"}, {"key": "D", "text": "x + y = 4"}, {"key": "C", "text": "x = y"}, {"key": "A", "text": "y = 4x"}]','A','配套：腿是桌面的 4 倍 → y=4x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0128-3','math','初中',8,'jkp-0128','single_choice',0.65,'1 个桌面配 4 条桌腿，x 桌面 y 腿配套时满足？','[{"key": "C", "text": "x = y"}, {"key": "A", "text": "y = 4x"}, {"key": "B", "text": "x = 4y"}, {"key": "D", "text": "x + y = 4"}]','A','配套：腿是桌面的 4 倍 → y=4x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0129-1','math','初中',8,'jkp-0129','single_choice',0.75,'买 2 个 A 和 3 个 B 花 21 元，买 3 个 A 和 2 个 B 花 24 元，设 A 单价 x，B 单价 y，则方程组为？','[{"key": "A", "text": "{2x+3y=21, 3x+2y=24}"}, {"key": "B", "text": "{2x+3y=24, 3x+2y=21}"}, {"key": "C", "text": "{3x+2y=21, 2x+3y=24}"}, {"key": "D", "text": "{x+y=21, x+y=24}"}]','A','按题意列方程组','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0129-2','math','初中',8,'jkp-0129','single_choice',0.75,'买 2 个 A 和 3 个 B 花 21 元，买 3 个 A 和 2 个 B 花 24 元，设 A 单价 x，B 单价 y，则方程组为？','[{"key": "C", "text": "{3x+2y=21, 2x+3y=24}"}, {"key": "B", "text": "{2x+3y=24, 3x+2y=21}"}, {"key": "A", "text": "{2x+3y=21, 3x+2y=24}"}, {"key": "D", "text": "{x+y=21, x+y=24}"}]','A','按题意列方程组','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0129-3','math','初中',8,'jkp-0129','single_choice',0.75,'买 2 个 A 和 3 个 B 花 21 元，买 3 个 A 和 2 个 B 花 24 元，设 A 单价 x，B 单价 y，则方程组为？','[{"key": "C", "text": "{3x+2y=21, 2x+3y=24}"}, {"key": "B", "text": "{2x+3y=24, 3x+2y=21}"}, {"key": "D", "text": "{x+y=21, x+y=24}"}, {"key": "A", "text": "{2x+3y=21, 3x+2y=24}"}]','A','按题意列方程组','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0130-1','math','初中',8,'jkp-0130','single_choice',0.35,'三元一次方程组用？消元成二元再解','[{"key": "A", "text": "代入或加减消元"}, {"key": "B", "text": "配方"}, {"key": "C", "text": "因式分解"}, {"key": "D", "text": "开平方"}]','A','三元 → 二元 → 一元','template-j','approved','通用');