-- 第22章 一元二次方程 补题（11学期, 知识点 321-333）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0321-1','math','初中',11,'jkp-0321','single_choice',0.45,'下列是一元二次方程的是？','[{"key": "A", "text": "x² - 3x + 2 = 0"}, {"key": "B", "text": "x + 3 = 0"}, {"key": "C", "text": "x² + y = 1"}, {"key": "D", "text": "1/x² = 2"}]','A','一元二次：一个未知数、最高次 2、整式','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0322-1','math','初中',11,'jkp-0322','single_choice',0.55,'一元二次方程 ax²+bx+c=0 中 a 必须满足？','[{"key": "A", "text": "a ≠ 0"}, {"key": "B", "text": "a = 0"}, {"key": "C", "text": "a > 0"}, {"key": "D", "text": "a < 0"}]','A','a≠0（否则不是二次）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0323-1','math','初中',11,'jkp-0323','single_choice',0.65,'直接开平方解 x² = 16，x = ？','[{"key": "A", "text": "±4"}, {"key": "B", "text": "4"}, {"key": "C", "text": "-4"}, {"key": "D", "text": "16"}]','A','x=±√16=±4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0324-1','math','初中',11,'jkp-0324','single_choice',0.75,'配方法：x² + 6x + 9 = 0，配方成 (x + 3)² = ？','[{"key": "A", "text": "0"}, {"key": "B", "text": "18"}, {"key": "C", "text": "6"}, {"key": "D", "text": "3"}]','A','(x+3)²=3²-9=0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0325-1','math','初中',11,'jkp-0325','single_choice',0.35,'x²+3x+2=0 的判别式 Δ = b²-4ac = ？','[{"key": "A", "text": "1"}, {"key": "B", "text": "17"}, {"key": "C", "text": "-5"}, {"key": "D", "text": "8"}]','A','Δ=3²-4×1×2=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0326-1','math','初中',11,'jkp-0326','single_choice',0.45,'Δ > 0 时，一元二次方程有？','[{"key": "A", "text": "两个不相等的实根"}, {"key": "B", "text": "两个相等实根"}, {"key": "C", "text": "无实数根"}, {"key": "D", "text": "一个根"}]','A','Δ>0 → 两个不等实根','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0327-1','math','初中',11,'jkp-0327','single_choice',0.55,'公式法解 x² - 4x + 4 = 0，x = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "4"}, {"key": "C", "text": "4"}, {"key": "D", "text": "0"}]','A','(x-2)²=0 → x=2（重根）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0328-1','math','初中',11,'jkp-0328','single_choice',0.65,'因式分解法解 (x-2)(x-4)=0，x = ？','[{"key": "A", "text": "2 或 4"}, {"key": "B", "text": "2 和 8"}, {"key": "C", "text": "-2 或 -4"}, {"key": "D", "text": "0"}]','A','x-2=0 或 x-4=0 → x=2 或 4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0329-1','math','初中',11,'jkp-0329','single_choice',0.75,'x²=5 用哪种方法最简便？','[{"key": "A", "text": "直接开平方法"}, {"key": "B", "text": "配方法"}, {"key": "C", "text": "公式法"}, {"key": "D", "text": "因式分解法"}]','A','x²=常数 → 直接开平方','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0330-1','math','初中',11,'jkp-0330','single_choice',0.35,'x² - 8x + 15 = 0 的两根之和 = ？','[{"key": "A", "text": "8"}, {"key": "B", "text": "15"}, {"key": "C", "text": "-8"}, {"key": "D", "text": "5"}]','A','韦达定理：x₁+x₂=8（两根 5、3）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0331-1','math','初中',11,'jkp-0331','single_choice',0.45,'某商品增长 20% 后为 120，原价 x 列方程？','[{"key": "A", "text": "x(1+20%) = 120"}, {"key": "B", "text": "x = 120×20%"}, {"key": "C", "text": "x+20% = 120"}, {"key": "D", "text": "x(1-20%) = 120"}]','A','增长率问题：x(1+20%)=120','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0332-1','math','初中',11,'jkp-0332','single_choice',0.55,'矩形长比宽多 2，宽 x，面积 15 → 列方程？','[{"key": "A", "text": "x(x+2) = 15"}, {"key": "B", "text": "x(x-2) = 15"}, {"key": "C", "text": "2(x+x+2) = 15"}, {"key": "D", "text": "x² = 15"}]','A','面积问题：长×宽=x(x+2)=15','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0333-1','math','初中',11,'jkp-0333','single_choice',0.65,'销售利润最值：利润 = 单件利润 × 销量，单件利润 = ？','[{"key": "A", "text": "售价 - 进价"}, {"key": "B", "text": "售价 + 进价"}, {"key": "C", "text": "售价 × 进价"}, {"key": "D", "text": "进价 - 售价"}]','A','利润=售价-进价','template-j','approved','通用');