-- 第4章 图形的认识初步 补题（7学期, 知识点 49-65）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0049-1','math','初中',7,'jkp-0049','single_choice',0.75,'下列是立体图形的是？','[{"key": "A", "text": "球"}, {"key": "B", "text": "三角形"}, {"key": "C", "text": "圆"}, {"key": "D", "text": "正方形"}]','A','球是立体图形，其余是平面图形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0049-2','math','初中',7,'jkp-0049','single_choice',0.75,'下列是立体图形的是？','[{"key": "B", "text": "三角形"}, {"key": "D", "text": "正方形"}, {"key": "C", "text": "圆"}, {"key": "A", "text": "球"}]','A','球是立体图形，其余是平面图形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0049-3','math','初中',7,'jkp-0049','single_choice',0.75,'下列是立体图形的是？','[{"key": "D", "text": "正方形"}, {"key": "B", "text": "三角形"}, {"key": "A", "text": "球"}, {"key": "C", "text": "圆"}]','A','球是立体图形，其余是平面图形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0050-1','math','初中',7,'jkp-0050','single_choice',0.35,'下列属于柱体的是？','[{"key": "A", "text": "圆柱"}, {"key": "B", "text": "球"}, {"key": "C", "text": "圆锥"}, {"key": "D", "text": "圆台"}]','A','圆柱是柱体（上下底面平行且全等）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0050-2','math','初中',7,'jkp-0050','single_choice',0.35,'下列属于柱体的是？','[{"key": "B", "text": "球"}, {"key": "D", "text": "圆台"}, {"key": "A", "text": "圆柱"}, {"key": "C", "text": "圆锥"}]','A','圆柱是柱体（上下底面平行且全等）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0050-3','math','初中',7,'jkp-0050','single_choice',0.35,'下列属于柱体的是？','[{"key": "B", "text": "球"}, {"key": "A", "text": "圆柱"}, {"key": "D", "text": "圆台"}, {"key": "C", "text": "圆锥"}]','A','圆柱是柱体（上下底面平行且全等）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0051-1','math','初中',7,'jkp-0051','single_choice',0.45,'圆柱的侧面展开图是？','[{"key": "A", "text": "矩形"}, {"key": "B", "text": "圆"}, {"key": "C", "text": "三角形"}, {"key": "D", "text": "梯形"}]','A','圆柱侧面展开为矩形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0051-2','math','初中',7,'jkp-0051','single_choice',0.45,'圆柱的侧面展开图是？','[{"key": "D", "text": "梯形"}, {"key": "C", "text": "三角形"}, {"key": "B", "text": "圆"}, {"key": "A", "text": "矩形"}]','A','圆柱侧面展开为矩形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0052-1','math','初中',7,'jkp-0052','single_choice',0.55,'从正面看圆柱，看到的是？','[{"key": "A", "text": "矩形"}, {"key": "B", "text": "圆"}, {"key": "C", "text": "三角形"}, {"key": "D", "text": "正方形"}]','A','圆柱主视图为矩形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0052-2','math','初中',7,'jkp-0052','single_choice',0.55,'从正面看圆柱，看到的是？','[{"key": "D", "text": "正方形"}, {"key": "A", "text": "矩形"}, {"key": "C", "text": "三角形"}, {"key": "B", "text": "圆"}]','A','圆柱主视图为矩形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0052-3','math','初中',7,'jkp-0052','single_choice',0.55,'从正面看圆柱，看到的是？','[{"key": "D", "text": "正方形"}, {"key": "C", "text": "三角形"}, {"key": "A", "text": "矩形"}, {"key": "B", "text": "圆"}]','A','圆柱主视图为矩形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0053-1','math','初中',7,'jkp-0053','single_choice',0.65,'面与面相交形成？','[{"key": "A", "text": "线"}, {"key": "B", "text": "点"}, {"key": "C", "text": "体"}, {"key": "D", "text": "面"}]','A','面面相交得线，线线相交得点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0053-2','math','初中',7,'jkp-0053','single_choice',0.65,'面与面相交形成？','[{"key": "D", "text": "面"}, {"key": "B", "text": "点"}, {"key": "C", "text": "体"}, {"key": "A", "text": "线"}]','A','面面相交得线，线线相交得点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0053-3','math','初中',7,'jkp-0053','single_choice',0.65,'面与面相交形成？','[{"key": "C", "text": "体"}, {"key": "D", "text": "面"}, {"key": "B", "text": "点"}, {"key": "A", "text": "线"}]','A','面面相交得线，线线相交得点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0054-1','math','初中',7,'jkp-0054','single_choice',0.75,'射线 AB 与射线 BA 是？','[{"key": "A", "text": "不同射线"}, {"key": "B", "text": "相同射线"}, {"key": "C", "text": "同一直线"}, {"key": "D", "text": "同一线段"}]','A','射线的端点不同，AB 与 BA 是不同射线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0054-2','math','初中',7,'jkp-0054','single_choice',0.75,'射线 AB 与射线 BA 是？','[{"key": "C", "text": "同一直线"}, {"key": "D", "text": "同一线段"}, {"key": "A", "text": "不同射线"}, {"key": "B", "text": "相同射线"}]','A','射线的端点不同，AB 与 BA 是不同射线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0054-3','math','初中',7,'jkp-0054','single_choice',0.75,'射线 AB 与射线 BA 是？','[{"key": "A", "text": "不同射线"}, {"key": "D", "text": "同一线段"}, {"key": "C", "text": "同一直线"}, {"key": "B", "text": "相同射线"}]','A','射线的端点不同，AB 与 BA 是不同射线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0055-1','math','初中',7,'jkp-0055','single_choice',0.35,'过两点可以画几条直线？','[{"key": "A", "text": "1 条"}, {"key": "B", "text": "2 条"}, {"key": "C", "text": "无数条"}, {"key": "D", "text": "0 条"}]','A','两点确定一条直线（直线基本事实）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0055-2','math','初中',7,'jkp-0055','single_choice',0.35,'过两点可以画几条直线？','[{"key": "C", "text": "无数条"}, {"key": "B", "text": "2 条"}, {"key": "D", "text": "0 条"}, {"key": "A", "text": "1 条"}]','A','两点确定一条直线（直线基本事实）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0055-3','math','初中',7,'jkp-0055','single_choice',0.35,'过两点可以画几条直线？','[{"key": "C", "text": "无数条"}, {"key": "D", "text": "0 条"}, {"key": "B", "text": "2 条"}, {"key": "A", "text": "1 条"}]','A','两点确定一条直线（直线基本事实）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0056-1','math','初中',7,'jkp-0056','single_choice',0.45,'A、B 两点间所有连线中，最短的是？','[{"key": "A", "text": "线段 AB"}, {"key": "B", "text": "折线"}, {"key": "C", "text": "曲线"}, {"key": "D", "text": "射线"}]','A','两点之间线段最短','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0056-2','math','初中',7,'jkp-0056','single_choice',0.45,'A、B 两点间所有连线中，最短的是？','[{"key": "B", "text": "折线"}, {"key": "C", "text": "曲线"}, {"key": "D", "text": "射线"}, {"key": "A", "text": "线段 AB"}]','A','两点之间线段最短','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0056-3','math','初中',7,'jkp-0056','single_choice',0.45,'A、B 两点间所有连线中，最短的是？','[{"key": "B", "text": "折线"}, {"key": "D", "text": "射线"}, {"key": "A", "text": "线段 AB"}, {"key": "C", "text": "曲线"}]','A','两点之间线段最短','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0057-1','math','初中',7,'jkp-0057','single_choice',0.55,'线段 AB=8，C 是 AB 中点，则 AC = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "8"}, {"key": "C", "text": "16"}, {"key": "D", "text": "2.0"}]','A','中点把线段平分：AC=AB/2=8/2=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0057-2','math','初中',7,'jkp-0057','single_choice',0.55,'线段 AB=4，C 是 AB 中点，则 AC = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "4"}, {"key": "C", "text": "8"}, {"key": "D", "text": "1.0"}]','A','中点把线段平分：AC=AB/2=4/2=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0057-3','math','初中',7,'jkp-0057','single_choice',0.55,'线段 AB=12，C 是 AB 中点，则 AC = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "12"}, {"key": "C", "text": "24"}, {"key": "D", "text": "3.0"}]','A','中点把线段平分：AC=AB/2=12/2=6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0058-1','math','初中',7,'jkp-0058','single_choice',0.65,'AB=6，BC=1，A、B、C 共线且 B 在中间，AC = ？','[{"key": "A", "text": "7"}, {"key": "B", "text": "5"}, {"key": "C", "text": "6"}, {"key": "D", "text": "5"}]','A','AC=AB+BC=6+1=7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0058-2','math','初中',7,'jkp-0058','single_choice',0.65,'AB=4，BC=3，A、B、C 共线且 B 在中间，AC = ？','[{"key": "A", "text": "7"}, {"key": "B", "text": "1"}, {"key": "C", "text": "12"}, {"key": "D", "text": "1"}]','A','AC=AB+BC=4+3=7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0058-3','math','初中',7,'jkp-0058','single_choice',0.65,'AB=5，BC=3，A、B、C 共线且 B 在中间，AC = ？','[{"key": "A", "text": "8"}, {"key": "B", "text": "2"}, {"key": "C", "text": "15"}, {"key": "D", "text": "2"}]','A','AC=AB+BC=5+3=8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0059-1','math','初中',7,'jkp-0059','single_choice',0.75,'下列表示角的是？','[{"key": "A", "text": "∠AOB"}, {"key": "B", "text": "△ABC"}, {"key": "C", "text": "AB"}, {"key": "D", "text": "⊥"}]','A','角用 ∠ 表示：∠AOB','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0059-2','math','初中',7,'jkp-0059','single_choice',0.75,'下列表示角的是？','[{"key": "D", "text": "⊥"}, {"key": "C", "text": "AB"}, {"key": "A", "text": "∠AOB"}, {"key": "B", "text": "△ABC"}]','A','角用 ∠ 表示：∠AOB','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0059-3','math','初中',7,'jkp-0059','single_choice',0.75,'下列表示角的是？','[{"key": "A", "text": "∠AOB"}, {"key": "B", "text": "△ABC"}, {"key": "D", "text": "⊥"}, {"key": "C", "text": "AB"}]','A','角用 ∠ 表示：∠AOB','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0060-1','math','初中',7,'jkp-0060','single_choice',0.35,'1° = ？','[{"key": "A", "text": "60′"}, {"key": "B", "text": "100′"}, {"key": "C", "text": "10′"}, {"key": "D", "text": "360′"}]','A','1°=60′，1′=60″','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0060-2','math','初中',7,'jkp-0060','single_choice',0.35,'1° = ？','[{"key": "B", "text": "100′"}, {"key": "A", "text": "60′"}, {"key": "C", "text": "10′"}, {"key": "D", "text": "360′"}]','A','1°=60′，1′=60″','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0060-3','math','初中',7,'jkp-0060','single_choice',0.35,'1° = ？','[{"key": "D", "text": "360′"}, {"key": "C", "text": "10′"}, {"key": "B", "text": "100′"}, {"key": "A", "text": "60′"}]','A','1°=60′，1′=60″','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0061-1','math','初中',7,'jkp-0061','single_choice',0.45,'30° 与 30°30′ 的大小关系是？','[{"key": "A", "text": "30° < 30°30′"}, {"key": "B", "text": "30° > 30°30′"}, {"key": "C", "text": "相等"}, {"key": "D", "text": "无法比较"}]','A','30°30′ = 30.5° > 30°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0062-1','math','初中',7,'jkp-0062','single_choice',0.55,'OC 平分 ∠AOB 且 ∠AOB=118°，则 ∠AOC = ？','[{"key": "A", "text": "59"}, {"key": "B", "text": "118"}, {"key": "C", "text": "31"}, {"key": "D", "text": "118"}]','A','角平分线平分角：∠AOC=118°/2=59°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0062-2','math','初中',7,'jkp-0062','single_choice',0.55,'OC 平分 ∠AOB 且 ∠AOB=102°，则 ∠AOC = ？','[{"key": "A", "text": "51"}, {"key": "B", "text": "102"}, {"key": "C", "text": "39"}, {"key": "D", "text": "102"}]','A','角平分线平分角：∠AOC=102°/2=51°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0062-3','math','初中',7,'jkp-0062','single_choice',0.55,'OC 平分 ∠AOB 且 ∠AOB=84°，则 ∠AOC = ？','[{"key": "A", "text": "42"}, {"key": "B", "text": "84"}, {"key": "C", "text": "48"}, {"key": "D", "text": "84"}]','A','角平分线平分角：∠AOC=84°/2=42°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0063-1','math','初中',7,'jkp-0063','single_choice',0.65,'∠A=59°，∠A 的余角 = ？','[{"key": "A", "text": "31°"}, {"key": "B", "text": "121°"}, {"key": "C", "text": "59°"}, {"key": "D", "text": "149°"}]','A','余角：90°-59°=31°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0063-2','math','初中',7,'jkp-0063','single_choice',0.65,'∠A=34°，∠A 的余角 = ？','[{"key": "A", "text": "56°"}, {"key": "B", "text": "146°"}, {"key": "C", "text": "34°"}, {"key": "D", "text": "124°"}]','A','余角：90°-34°=56°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0063-3','math','初中',7,'jkp-0063','single_choice',0.65,'∠A=55°，∠A 的余角 = ？','[{"key": "A", "text": "35°"}, {"key": "B", "text": "125°"}, {"key": "C", "text": "55°"}, {"key": "D", "text": "145°"}]','A','余角：90°-55°=35°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0064-1','math','初中',7,'jkp-0064','single_choice',0.75,'∠A=65°，∠A 的补角 = ？','[{"key": "A", "text": "115°"}, {"key": "B", "text": "25°"}, {"key": "C", "text": "65°"}, {"key": "D", "text": "245°"}]','A','补角：180°-65°=115°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0064-2','math','初中',7,'jkp-0064','single_choice',0.75,'∠A=61°，∠A 的补角 = ？','[{"key": "A", "text": "119°"}, {"key": "B", "text": "29°"}, {"key": "C", "text": "61°"}, {"key": "D", "text": "241°"}]','A','补角：180°-61°=119°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0064-3','math','初中',7,'jkp-0064','single_choice',0.75,'∠A=43°，∠A 的补角 = ？','[{"key": "A", "text": "137°"}, {"key": "B", "text": "47°"}, {"key": "C", "text": "43°"}, {"key": "D", "text": "223°"}]','A','补角：180°-43°=137°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0065-1','math','初中',7,'jkp-0065','single_choice',0.35,'北偏东 30° 表示？','[{"key": "A", "text": "以正北为基准向东偏 30°"}, {"key": "B", "text": "以正东为基准向北偏 30°"}, {"key": "C", "text": "正东方向"}, {"key": "D", "text": "正北方向"}]','A','方位角：北偏东 30° = 从正北向东转 30°','template-j','approved','通用');