-- 第13章 实数 补题（9学期, 知识点 187-200）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0187-1','math','初中',9,'jkp-0187','single_choice',0.55,'√16 = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "-4"}, {"key": "C", "text": "±4"}, {"key": "D", "text": "16"}]','A','算术平方根取正：√16=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0187-2','math','初中',9,'jkp-0187','single_choice',0.55,'√25 = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "-5"}, {"key": "C", "text": "±5"}, {"key": "D", "text": "25"}]','A','算术平方根取正：√25=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0187-3','math','初中',9,'jkp-0187','single_choice',0.55,'√81 = ？','[{"key": "A", "text": "9"}, {"key": "B", "text": "-9"}, {"key": "C", "text": "±9"}, {"key": "D", "text": "81"}]','A','算术平方根取正：√81=9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0188-1','math','初中',9,'jkp-0188','single_choice',0.65,'√a 有意义的条件是？','[{"key": "A", "text": "a ≥ 0"}, {"key": "B", "text": "a > 0"}, {"key": "C", "text": "a ≤ 0"}, {"key": "D", "text": "a ≠ 0"}]','A','算术平方根被开方数非负','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0188-2','math','初中',9,'jkp-0188','single_choice',0.65,'√a 有意义的条件是？','[{"key": "C", "text": "a ≤ 0"}, {"key": "B", "text": "a > 0"}, {"key": "A", "text": "a ≥ 0"}, {"key": "D", "text": "a ≠ 0"}]','A','算术平方根被开方数非负','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0188-3','math','初中',9,'jkp-0188','single_choice',0.65,'√a 有意义的条件是？','[{"key": "B", "text": "a > 0"}, {"key": "C", "text": "a ≤ 0"}, {"key": "A", "text": "a ≥ 0"}, {"key": "D", "text": "a ≠ 0"}]','A','算术平方根被开方数非负','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0189-1','math','初中',9,'jkp-0189','single_choice',0.75,'16 的平方根是？','[{"key": "A", "text": "±4"}, {"key": "B", "text": "4"}, {"key": "C", "text": "-4"}, {"key": "D", "text": "16"}]','A','平方根有两个：±4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0189-2','math','初中',9,'jkp-0189','single_choice',0.75,'25 的平方根是？','[{"key": "A", "text": "±5"}, {"key": "B", "text": "5"}, {"key": "C", "text": "-5"}, {"key": "D", "text": "25"}]','A','平方根有两个：±5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0189-3','math','初中',9,'jkp-0189','single_choice',0.75,'4 的平方根是？','[{"key": "A", "text": "±2"}, {"key": "B", "text": "2"}, {"key": "C", "text": "-2"}, {"key": "D", "text": "4"}]','A','平方根有两个：±2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0190-1','math','初中',9,'jkp-0190','single_choice',0.35,'下列说法正确的是？','[{"key": "A", "text": "正数有两个平方根（互为相反数）"}, {"key": "B", "text": "负数有平方根"}, {"key": "C", "text": "0 没有平方根"}, {"key": "D", "text": "正数只有一个平方根"}]','A','平方根性质：正数 2 个、0 一个、负数无','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0190-2','math','初中',9,'jkp-0190','single_choice',0.35,'下列说法正确的是？','[{"key": "B", "text": "负数有平方根"}, {"key": "D", "text": "正数只有一个平方根"}, {"key": "A", "text": "正数有两个平方根（互为相反数）"}, {"key": "C", "text": "0 没有平方根"}]','A','平方根性质：正数 2 个、0 一个、负数无','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0190-3','math','初中',9,'jkp-0190','single_choice',0.35,'下列说法正确的是？','[{"key": "D", "text": "正数只有一个平方根"}, {"key": "A", "text": "正数有两个平方根（互为相反数）"}, {"key": "B", "text": "负数有平方根"}, {"key": "C", "text": "0 没有平方根"}]','A','平方根性质：正数 2 个、0 一个、负数无','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0191-1','math','初中',9,'jkp-0191','single_choice',0.45,'开平方：√(4) = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "-2"}, {"key": "C", "text": "4"}, {"key": "D", "text": "±2"}]','A','√(4)=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0191-2','math','初中',9,'jkp-0191','single_choice',0.45,'开平方：√(64) = ？','[{"key": "A", "text": "8"}, {"key": "B", "text": "-8"}, {"key": "C", "text": "64"}, {"key": "D", "text": "±8"}]','A','√(64)=8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0191-3','math','初中',9,'jkp-0191','single_choice',0.45,'开平方：√(81) = ？','[{"key": "A", "text": "9"}, {"key": "B", "text": "-9"}, {"key": "C", "text": "81"}, {"key": "D", "text": "±9"}]','A','√(81)=9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0192-1','math','初中',9,'jkp-0192','single_choice',0.55,'³√(27) = ？','[{"key": "A", "text": "3"}, {"key": "B", "text": "-3"}, {"key": "C", "text": "27"}, {"key": "D", "text": "±3"}]','A','立方根：³√(27)=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0192-2','math','初中',9,'jkp-0192','single_choice',0.55,'³√(64) = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "-4"}, {"key": "C", "text": "64"}, {"key": "D", "text": "±4"}]','A','立方根：³√(64)=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0192-3','math','初中',9,'jkp-0192','single_choice',0.55,'³√(8) = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "-2"}, {"key": "C", "text": "8"}, {"key": "D", "text": "±2"}]','A','立方根：³√(8)=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0193-1','math','初中',9,'jkp-0193','single_choice',0.65,'³√(-125) = ？','[{"key": "A", "text": "-5"}, {"key": "B", "text": "5"}, {"key": "C", "text": "125"}, {"key": "D", "text": "无意义"}]','A','负数可开立方：³√(-125)=-5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0193-2','math','初中',9,'jkp-0193','single_choice',0.65,'³√(-64) = ？','[{"key": "A", "text": "-4"}, {"key": "B", "text": "4"}, {"key": "C", "text": "64"}, {"key": "D", "text": "无意义"}]','A','负数可开立方：³√(-64)=-4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0193-3','math','初中',9,'jkp-0193','single_choice',0.65,'³√(-8) = ？','[{"key": "A", "text": "-2"}, {"key": "B", "text": "2"}, {"key": "C", "text": "8"}, {"key": "D", "text": "无意义"}]','A','负数可开立方：³√(-8)=-2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0194-1','math','初中',9,'jkp-0194','single_choice',0.75,'开立方：³√(125) = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "125"}, {"key": "C", "text": "-5"}, {"key": "D", "text": "±5"}]','A','³√(125)=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0194-2','math','初中',9,'jkp-0194','single_choice',0.75,'开立方：³√(64) = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "64"}, {"key": "C", "text": "-4"}, {"key": "D", "text": "±4"}]','A','³√(64)=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0194-3','math','初中',9,'jkp-0194','single_choice',0.75,'开立方：³√(27) = ？','[{"key": "A", "text": "3"}, {"key": "B", "text": "27"}, {"key": "C", "text": "-3"}, {"key": "D", "text": "±3"}]','A','³√(27)=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0195-1','math','初中',9,'jkp-0195','single_choice',0.35,'下列是无理数的是？','[{"key": "A", "text": "√2"}, {"key": "B", "text": "1/3"}, {"key": "C", "text": "0.5"}, {"key": "D", "text": "-4"}]','A','√2 无限不循环 → 无理数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0195-2','math','初中',9,'jkp-0195','single_choice',0.35,'下列是无理数的是？','[{"key": "C", "text": "0.5"}, {"key": "B", "text": "1/3"}, {"key": "A", "text": "√2"}, {"key": "D", "text": "-4"}]','A','√2 无限不循环 → 无理数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0195-3','math','初中',9,'jkp-0195','single_choice',0.35,'下列是无理数的是？','[{"key": "D", "text": "-4"}, {"key": "C", "text": "0.5"}, {"key": "B", "text": "1/3"}, {"key": "A", "text": "√2"}]','A','√2 无限不循环 → 无理数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0196-1','math','初中',9,'jkp-0196','single_choice',0.45,'有理数和无理数统称为？','[{"key": "A", "text": "实数"}, {"key": "B", "text": "整数"}, {"key": "C", "text": "分数"}, {"key": "D", "text": "自然数"}]','A','实数 = 有理数 + 无理数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0196-2','math','初中',9,'jkp-0196','single_choice',0.45,'有理数和无理数统称为？','[{"key": "B", "text": "整数"}, {"key": "C", "text": "分数"}, {"key": "D", "text": "自然数"}, {"key": "A", "text": "实数"}]','A','实数 = 有理数 + 无理数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0196-3','math','初中',9,'jkp-0196','single_choice',0.45,'有理数和无理数统称为？','[{"key": "C", "text": "分数"}, {"key": "D", "text": "自然数"}, {"key": "A", "text": "实数"}, {"key": "B", "text": "整数"}]','A','实数 = 有理数 + 无理数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0197-1','math','初中',9,'jkp-0197','single_choice',0.55,'实数与数轴上的点？','[{"key": "A", "text": "一一对应"}, {"key": "B", "text": "无对应"}, {"key": "C", "text": "部分对应"}, {"key": "D", "text": "二一对应"}]','A','实数与数轴上的点一一对应','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0197-2','math','初中',9,'jkp-0197','single_choice',0.55,'实数与数轴上的点？','[{"key": "A", "text": "一一对应"}, {"key": "C", "text": "部分对应"}, {"key": "B", "text": "无对应"}, {"key": "D", "text": "二一对应"}]','A','实数与数轴上的点一一对应','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0197-3','math','初中',9,'jkp-0197','single_choice',0.55,'实数与数轴上的点？','[{"key": "C", "text": "部分对应"}, {"key": "D", "text": "二一对应"}, {"key": "B", "text": "无对应"}, {"key": "A", "text": "一一对应"}]','A','实数与数轴上的点一一对应','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0198-1','math','初中',9,'jkp-0198','single_choice',0.65,'√9 的相反数是？','[{"key": "A", "text": "-3"}, {"key": "B", "text": "3"}, {"key": "C", "text": "0"}, {"key": "D", "text": "6"}]','A','√9=3，相反数 -3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0198-2','math','初中',9,'jkp-0198','single_choice',0.65,'√36 的相反数是？','[{"key": "A", "text": "-6"}, {"key": "B", "text": "6"}, {"key": "C", "text": "0"}, {"key": "D", "text": "12"}]','A','√36=6，相反数 -6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0198-3','math','初中',9,'jkp-0198','single_choice',0.65,'√25 的相反数是？','[{"key": "A", "text": "-5"}, {"key": "B", "text": "5"}, {"key": "C", "text": "0"}, {"key": "D", "text": "10"}]','A','√25=5，相反数 -5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0199-1','math','初中',9,'jkp-0199','single_choice',0.75,'比较 √2 与 1.5 的大小？','[{"key": "A", "text": "√2 < 1.5"}, {"key": "B", "text": "√2 > 1.5"}, {"key": "C", "text": "相等"}, {"key": "D", "text": "无法比较"}]','A','√2≈1.414 < 1.5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0199-2','math','初中',9,'jkp-0199','single_choice',0.75,'比较 √2 与 1.5 的大小？','[{"key": "B", "text": "√2 > 1.5"}, {"key": "A", "text": "√2 < 1.5"}, {"key": "D", "text": "无法比较"}, {"key": "C", "text": "相等"}]','A','√2≈1.414 < 1.5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0199-3','math','初中',9,'jkp-0199','single_choice',0.75,'比较 √2 与 1.5 的大小？','[{"key": "C", "text": "相等"}, {"key": "D", "text": "无法比较"}, {"key": "A", "text": "√2 < 1.5"}, {"key": "B", "text": "√2 > 1.5"}]','A','√2≈1.414 < 1.5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0200-1','math','初中',9,'jkp-0200','single_choice',0.35,'计算：√4 + ³√8 = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "12"}, {"key": "C", "text": "4"}, {"key": "D", "text": "8"}]','A','√4=2，³√8=4，和=6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0200-2','math','初中',9,'jkp-0200','single_choice',0.35,'计算：√16 + ³√64 = ？','[{"key": "A", "text": "20"}, {"key": "B", "text": "80"}, {"key": "C", "text": "8"}, {"key": "D", "text": "32"}]','A','√16=4，³√64=16，和=20','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0200-3','math','初中',9,'jkp-0200','single_choice',0.35,'计算：√9 + ³√27 = ？','[{"key": "A", "text": "12"}, {"key": "B", "text": "36"}, {"key": "C", "text": "6"}, {"key": "D", "text": "18"}]','A','√9=3，³√27=9，和=12','template-j','approved','通用');