-- 第5章 相交线与平行线 补题（8学期, 知识点 66-87）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0066-1','math','初中',8,'jkp-0066','single_choice',0.45,'∠1 与 ∠2 互为邻补角，∠1=39°，则 ∠2 = ？','[{"key": "A", "text": "141°"}, {"key": "B", "text": "39°"}, {"key": "C", "text": "51°"}, {"key": "D", "text": "219°"}]','A','邻补角和为 180°：∠2=180°-39°=141°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0066-2','math','初中',8,'jkp-0066','single_choice',0.45,'∠1 与 ∠2 互为邻补角，∠1=118°，则 ∠2 = ？','[{"key": "A", "text": "62°"}, {"key": "B", "text": "118°"}, {"key": "C", "text": "-28°"}, {"key": "D", "text": "298°"}]','A','邻补角和为 180°：∠2=180°-118°=62°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0066-3','math','初中',8,'jkp-0066','single_choice',0.45,'∠1 与 ∠2 互为邻补角，∠1=61°，则 ∠2 = ？','[{"key": "A", "text": "119°"}, {"key": "B", "text": "61°"}, {"key": "C", "text": "29°"}, {"key": "D", "text": "241°"}]','A','邻补角和为 180°：∠2=180°-61°=119°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0067-1','math','初中',8,'jkp-0067','single_choice',0.55,'两直线相交，∠1=106°，∠1 与 ∠2 是对顶角，则 ∠2 = ？','[{"key": "A", "text": "106°"}, {"key": "B", "text": "74°"}, {"key": "C", "text": "-16°"}, {"key": "D", "text": "180°"}]','A','对顶角相等：∠2=106°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0067-2','math','初中',8,'jkp-0067','single_choice',0.55,'两直线相交，∠1=47°，∠1 与 ∠2 是对顶角，则 ∠2 = ？','[{"key": "A", "text": "47°"}, {"key": "B", "text": "133°"}, {"key": "C", "text": "43°"}, {"key": "D", "text": "180°"}]','A','对顶角相等：∠2=47°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0067-3','math','初中',8,'jkp-0067','single_choice',0.55,'两直线相交，∠1=45°，∠1 与 ∠2 是对顶角，则 ∠2 = ？','[{"key": "A", "text": "45°"}, {"key": "B", "text": "135°"}, {"key": "C", "text": "45°"}, {"key": "D", "text": "180°"}]','A','对顶角相等：∠2=45°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0068-1','math','初中',8,'jkp-0068','single_choice',0.65,'两条直线相交成直角，则这两条直线？','[{"key": "A", "text": "互相垂直"}, {"key": "B", "text": "互相平行"}, {"key": "C", "text": "重合"}, {"key": "D", "text": "斜交"}]','A','相交成 90° → 垂直','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0069-1','math','初中',8,'jkp-0069','single_choice',0.75,'过直线外一点，可以画几条直线与已知直线垂直？','[{"key": "A", "text": "1 条"}, {"key": "B", "text": "2 条"}, {"key": "C", "text": "无数条"}, {"key": "D", "text": "0 条"}]','A','垂线基本事实：过一点有且只有一条垂线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0069-2','math','初中',8,'jkp-0069','single_choice',0.75,'过直线外一点，可以画几条直线与已知直线垂直？','[{"key": "D", "text": "0 条"}, {"key": "B", "text": "2 条"}, {"key": "C", "text": "无数条"}, {"key": "A", "text": "1 条"}]','A','垂线基本事实：过一点有且只有一条垂线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0069-3','math','初中',8,'jkp-0069','single_choice',0.75,'过直线外一点，可以画几条直线与已知直线垂直？','[{"key": "D", "text": "0 条"}, {"key": "C", "text": "无数条"}, {"key": "A", "text": "1 条"}, {"key": "B", "text": "2 条"}]','A','垂线基本事实：过一点有且只有一条垂线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0070-1','math','初中',8,'jkp-0070','single_choice',0.35,'从直线外一点到这条直线的所有连线中，最短的是？','[{"key": "A", "text": "垂线段"}, {"key": "B", "text": "斜线段"}, {"key": "C", "text": "任意线段"}, {"key": "D", "text": "平行线"}]','A','垂线段最短','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0070-2','math','初中',8,'jkp-0070','single_choice',0.35,'从直线外一点到这条直线的所有连线中，最短的是？','[{"key": "A", "text": "垂线段"}, {"key": "B", "text": "斜线段"}, {"key": "D", "text": "平行线"}, {"key": "C", "text": "任意线段"}]','A','垂线段最短','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0070-3','math','初中',8,'jkp-0070','single_choice',0.35,'从直线外一点到这条直线的所有连线中，最短的是？','[{"key": "D", "text": "平行线"}, {"key": "B", "text": "斜线段"}, {"key": "A", "text": "垂线段"}, {"key": "C", "text": "任意线段"}]','A','垂线段最短','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0071-1','math','初中',8,'jkp-0071','single_choice',0.45,'点 P 到直线 l 的垂线段长为 3，则点 P 到直线 l 的距离 = ？','[{"key": "A", "text": "3"}, {"key": "B", "text": "6"}, {"key": "C", "text": "0"}, {"key": "D", "text": "1.5"}]','A','点到直线距离 = 垂线段长度 = 3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0071-2','math','初中',8,'jkp-0071','single_choice',0.45,'点 P 到直线 l 的垂线段长为 2，则点 P 到直线 l 的距离 = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "4"}, {"key": "C", "text": "0"}, {"key": "D", "text": "1.0"}]','A','点到直线距离 = 垂线段长度 = 2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0071-3','math','初中',8,'jkp-0071','single_choice',0.45,'点 P 到直线 l 的垂线段长为 5，则点 P 到直线 l 的距离 = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "10"}, {"key": "C", "text": "0"}, {"key": "D", "text": "2.5"}]','A','点到直线距离 = 垂线段长度 = 5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0072-1','math','初中',8,'jkp-0072','single_choice',0.55,'两条直线被第三条直线所截，位置相同的两个角（都在左上方）是？','[{"key": "A", "text": "同位角"}, {"key": "B", "text": "内错角"}, {"key": "C", "text": "同旁内角"}, {"key": "D", "text": "对顶角"}]','A','同位角：位置相同（左上对左上等）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0072-2','math','初中',8,'jkp-0072','single_choice',0.55,'两条直线被第三条直线所截，位置相同的两个角（都在左上方）是？','[{"key": "D", "text": "对顶角"}, {"key": "C", "text": "同旁内角"}, {"key": "B", "text": "内错角"}, {"key": "A", "text": "同位角"}]','A','同位角：位置相同（左上对左上等）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0072-3','math','初中',8,'jkp-0072','single_choice',0.55,'两条直线被第三条直线所截，位置相同的两个角（都在左上方）是？','[{"key": "B", "text": "内错角"}, {"key": "C", "text": "同旁内角"}, {"key": "A", "text": "同位角"}, {"key": "D", "text": "对顶角"}]','A','同位角：位置相同（左上对左上等）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0073-1','math','初中',8,'jkp-0073','single_choice',0.65,'两条直线被第三条直线所截，在两条直线之间且交错的两个角是？','[{"key": "A", "text": "内错角"}, {"key": "B", "text": "同位角"}, {"key": "C", "text": "同旁内角"}, {"key": "D", "text": "邻补角"}]','A','内错角：内部且交错','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0073-2','math','初中',8,'jkp-0073','single_choice',0.65,'两条直线被第三条直线所截，在两条直线之间且交错的两个角是？','[{"key": "D", "text": "邻补角"}, {"key": "A", "text": "内错角"}, {"key": "C", "text": "同旁内角"}, {"key": "B", "text": "同位角"}]','A','内错角：内部且交错','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0073-3','math','初中',8,'jkp-0073','single_choice',0.65,'两条直线被第三条直线所截，在两条直线之间且交错的两个角是？','[{"key": "B", "text": "同位角"}, {"key": "A", "text": "内错角"}, {"key": "C", "text": "同旁内角"}, {"key": "D", "text": "邻补角"}]','A','内错角：内部且交错','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0074-1','math','初中',8,'jkp-0074','single_choice',0.75,'两条直线被第三条直线所截，在两条直线之间且同侧的两个角是？','[{"key": "A", "text": "同旁内角"}, {"key": "B", "text": "内错角"}, {"key": "C", "text": "同位角"}, {"key": "D", "text": "对顶角"}]','A','同旁内角：内部且同侧','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0075-1','math','初中',8,'jkp-0075','single_choice',0.35,'在同一平面内，不相交的两条直线是？','[{"key": "A", "text": "平行线"}, {"key": "B", "text": "垂直线"}, {"key": "C", "text": "斜线"}, {"key": "D", "text": "重合线"}]','A','平行线定义：同一平面内不相交','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0075-2','math','初中',8,'jkp-0075','single_choice',0.35,'在同一平面内，不相交的两条直线是？','[{"key": "D", "text": "重合线"}, {"key": "B", "text": "垂直线"}, {"key": "C", "text": "斜线"}, {"key": "A", "text": "平行线"}]','A','平行线定义：同一平面内不相交','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0075-3','math','初中',8,'jkp-0075','single_choice',0.35,'在同一平面内，不相交的两条直线是？','[{"key": "A", "text": "平行线"}, {"key": "C", "text": "斜线"}, {"key": "D", "text": "重合线"}, {"key": "B", "text": "垂直线"}]','A','平行线定义：同一平面内不相交','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0076-1','math','初中',8,'jkp-0076','single_choice',0.45,'过直线外一点，可画几条直线与已知直线平行？','[{"key": "A", "text": "1 条"}, {"key": "B", "text": "无数条"}, {"key": "C", "text": "2 条"}, {"key": "D", "text": "0 条"}]','A','平行公理：过直线外一点有且只有一条平行线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0076-2','math','初中',8,'jkp-0076','single_choice',0.45,'过直线外一点，可画几条直线与已知直线平行？','[{"key": "C", "text": "2 条"}, {"key": "D", "text": "0 条"}, {"key": "A", "text": "1 条"}, {"key": "B", "text": "无数条"}]','A','平行公理：过直线外一点有且只有一条平行线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0076-3','math','初中',8,'jkp-0076','single_choice',0.45,'过直线外一点，可画几条直线与已知直线平行？','[{"key": "C", "text": "2 条"}, {"key": "B", "text": "无数条"}, {"key": "A", "text": "1 条"}, {"key": "D", "text": "0 条"}]','A','平行公理：过直线外一点有且只有一条平行线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0077-1','math','初中',8,'jkp-0077','single_choice',0.55,'若 a∥b 且 b∥c，则 a 与 c 的关系是？','[{"key": "A", "text": "a∥c"}, {"key": "B", "text": "a⊥c"}, {"key": "C", "text": "a 与 c 相交"}, {"key": "D", "text": "无法确定"}]','A','平行传递性：a∥c','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0077-2','math','初中',8,'jkp-0077','single_choice',0.55,'若 a∥b 且 b∥c，则 a 与 c 的关系是？','[{"key": "C", "text": "a 与 c 相交"}, {"key": "B", "text": "a⊥c"}, {"key": "D", "text": "无法确定"}, {"key": "A", "text": "a∥c"}]','A','平行传递性：a∥c','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0077-3','math','初中',8,'jkp-0077','single_choice',0.55,'若 a∥b 且 b∥c，则 a 与 c 的关系是？','[{"key": "D", "text": "无法确定"}, {"key": "A", "text": "a∥c"}, {"key": "B", "text": "a⊥c"}, {"key": "C", "text": "a 与 c 相交"}]','A','平行传递性：a∥c','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0078-1','math','初中',8,'jkp-0078','single_choice',0.65,'同位角相等，两直线？','[{"key": "A", "text": "平行"}, {"key": "B", "text": "垂直"}, {"key": "C", "text": "相交"}, {"key": "D", "text": "重合"}]','A','判定1：同位角相等 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0078-2','math','初中',8,'jkp-0078','single_choice',0.65,'同位角相等，两直线？','[{"key": "C", "text": "相交"}, {"key": "A", "text": "平行"}, {"key": "D", "text": "重合"}, {"key": "B", "text": "垂直"}]','A','判定1：同位角相等 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0078-3','math','初中',8,'jkp-0078','single_choice',0.65,'同位角相等，两直线？','[{"key": "C", "text": "相交"}, {"key": "D", "text": "重合"}, {"key": "B", "text": "垂直"}, {"key": "A", "text": "平行"}]','A','判定1：同位角相等 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0079-1','math','初中',8,'jkp-0079','single_choice',0.75,'内错角相等，两直线？','[{"key": "A", "text": "平行"}, {"key": "B", "text": "垂直"}, {"key": "C", "text": "相交"}, {"key": "D", "text": "重合"}]','A','判定2：内错角相等 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0079-2','math','初中',8,'jkp-0079','single_choice',0.75,'内错角相等，两直线？','[{"key": "B", "text": "垂直"}, {"key": "A", "text": "平行"}, {"key": "C", "text": "相交"}, {"key": "D", "text": "重合"}]','A','判定2：内错角相等 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0079-3','math','初中',8,'jkp-0079','single_choice',0.75,'内错角相等，两直线？','[{"key": "B", "text": "垂直"}, {"key": "C", "text": "相交"}, {"key": "D", "text": "重合"}, {"key": "A", "text": "平行"}]','A','判定2：内错角相等 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0080-1','math','初中',8,'jkp-0080','single_choice',0.35,'同旁内角互补，两直线？','[{"key": "A", "text": "平行"}, {"key": "B", "text": "垂直"}, {"key": "C", "text": "相交"}, {"key": "D", "text": "重合"}]','A','判定3：同旁内角互补 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0080-2','math','初中',8,'jkp-0080','single_choice',0.35,'同旁内角互补，两直线？','[{"key": "D", "text": "重合"}, {"key": "A", "text": "平行"}, {"key": "C", "text": "相交"}, {"key": "B", "text": "垂直"}]','A','判定3：同旁内角互补 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0080-3','math','初中',8,'jkp-0080','single_choice',0.35,'同旁内角互补，两直线？','[{"key": "B", "text": "垂直"}, {"key": "D", "text": "重合"}, {"key": "C", "text": "相交"}, {"key": "A", "text": "平行"}]','A','判定3：同旁内角互补 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0081-1','math','初中',8,'jkp-0081','single_choice',0.45,'两直线平行，∠1=71°（∠1 与 ∠2 是同位角），则 ∠2 = ？','[{"key": "A", "text": "71°"}, {"key": "B", "text": "109°"}, {"key": "C", "text": "19°"}, {"key": "D", "text": "0°"}]','A','性质1：两直线平行，同位角相等 → ∠2=71°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0081-2','math','初中',8,'jkp-0081','single_choice',0.45,'两直线平行，∠1=76°（∠1 与 ∠2 是同位角），则 ∠2 = ？','[{"key": "A", "text": "76°"}, {"key": "B", "text": "104°"}, {"key": "C", "text": "14°"}, {"key": "D", "text": "0°"}]','A','性质1：两直线平行，同位角相等 → ∠2=76°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0081-3','math','初中',8,'jkp-0081','single_choice',0.45,'两直线平行，∠1=73°（∠1 与 ∠2 是同位角），则 ∠2 = ？','[{"key": "A", "text": "73°"}, {"key": "B", "text": "107°"}, {"key": "C", "text": "17°"}, {"key": "D", "text": "0°"}]','A','性质1：两直线平行，同位角相等 → ∠2=73°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0082-1','math','初中',8,'jkp-0082','single_choice',0.55,'两直线平行，∠1=43°（内错角关系），则其内错角 ∠2 = ？','[{"key": "A", "text": "43°"}, {"key": "B", "text": "137°"}, {"key": "C", "text": "47°"}, {"key": "D", "text": "180°"}]','A','性质2：内错角相等 → ∠2=43°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0082-2','math','初中',8,'jkp-0082','single_choice',0.55,'两直线平行，∠1=82°（内错角关系），则其内错角 ∠2 = ？','[{"key": "A", "text": "82°"}, {"key": "B", "text": "98°"}, {"key": "C", "text": "8°"}, {"key": "D", "text": "180°"}]','A','性质2：内错角相等 → ∠2=82°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0082-3','math','初中',8,'jkp-0082','single_choice',0.55,'两直线平行，∠1=32°（内错角关系），则其内错角 ∠2 = ？','[{"key": "A", "text": "32°"}, {"key": "B", "text": "148°"}, {"key": "C", "text": "58°"}, {"key": "D", "text": "180°"}]','A','性质2：内错角相等 → ∠2=32°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0083-1','math','初中',8,'jkp-0083','single_choice',0.65,'两直线平行，∠1=30°（同旁内角关系），则其同旁内角 ∠2 = ？','[{"key": "A", "text": "150°"}, {"key": "B", "text": "30°"}, {"key": "C", "text": "60°"}, {"key": "D", "text": "0°"}]','A','性质3：同旁内角互补 → ∠2=180°-30°=150°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0083-2','math','初中',8,'jkp-0083','single_choice',0.65,'两直线平行，∠1=50°（同旁内角关系），则其同旁内角 ∠2 = ？','[{"key": "A", "text": "130°"}, {"key": "B", "text": "50°"}, {"key": "C", "text": "40°"}, {"key": "D", "text": "0°"}]','A','性质3：同旁内角互补 → ∠2=180°-50°=130°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0083-3','math','初中',8,'jkp-0083','single_choice',0.65,'两直线平行，∠1=82°（同旁内角关系），则其同旁内角 ∠2 = ？','[{"key": "A", "text": "98°"}, {"key": "B", "text": "82°"}, {"key": "C", "text": "8°"}, {"key": "D", "text": "0°"}]','A','性质3：同旁内角互补 → ∠2=180°-82°=98°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0084-1','math','初中',8,'jkp-0084','single_choice',0.75,'下列是命题的是？','[{"key": "A", "text": "如果 a=b，那么 a²=b²"}, {"key": "B", "text": "画线段 AB"}, {"key": "C", "text": "延长 AB"}, {"key": "D", "text": "过点 P 作直线"}]','A','命题：判断一件事情的语句','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0084-2','math','初中',8,'jkp-0084','single_choice',0.75,'下列是命题的是？','[{"key": "A", "text": "如果 a=b，那么 a²=b²"}, {"key": "D", "text": "过点 P 作直线"}, {"key": "B", "text": "画线段 AB"}, {"key": "C", "text": "延长 AB"}]','A','命题：判断一件事情的语句','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0084-3','math','初中',8,'jkp-0084','single_choice',0.75,'下列是命题的是？','[{"key": "C", "text": "延长 AB"}, {"key": "B", "text": "画线段 AB"}, {"key": "A", "text": "如果 a=b，那么 a²=b²"}, {"key": "D", "text": "过点 P 作直线"}]','A','命题：判断一件事情的语句','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0085-1','math','初中',8,'jkp-0085','single_choice',0.35,'经过推理证实的真命题叫？','[{"key": "A", "text": "定理"}, {"key": "B", "text": "公理"}, {"key": "C", "text": "猜想"}, {"key": "D", "text": "定义"}]','A','定理：经过证明的真命题','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0085-2','math','初中',8,'jkp-0085','single_choice',0.35,'经过推理证实的真命题叫？','[{"key": "A", "text": "定理"}, {"key": "D", "text": "定义"}, {"key": "C", "text": "猜想"}, {"key": "B", "text": "公理"}]','A','定理：经过证明的真命题','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0085-3','math','初中',8,'jkp-0085','single_choice',0.35,'经过推理证实的真命题叫？','[{"key": "C", "text": "猜想"}, {"key": "D", "text": "定义"}, {"key": "A", "text": "定理"}, {"key": "B", "text": "公理"}]','A','定理：经过证明的真命题','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0086-1','math','初中',8,'jkp-0086','single_choice',0.45,'平移不改变图形的？','[{"key": "A", "text": "形状和大小"}, {"key": "B", "text": "位置"}, {"key": "C", "text": "方向"}, {"key": "D", "text": "面积"}]','A','平移只改变位置，不改变形状大小方向','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0086-2','math','初中',8,'jkp-0086','single_choice',0.45,'平移不改变图形的？','[{"key": "A", "text": "形状和大小"}, {"key": "D", "text": "面积"}, {"key": "B", "text": "位置"}, {"key": "C", "text": "方向"}]','A','平移只改变位置，不改变形状大小方向','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0086-3','math','初中',8,'jkp-0086','single_choice',0.45,'平移不改变图形的？','[{"key": "C", "text": "方向"}, {"key": "D", "text": "面积"}, {"key": "A", "text": "形状和大小"}, {"key": "B", "text": "位置"}]','A','平移只改变位置，不改变形状大小方向','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0087-1','math','初中',8,'jkp-0087','single_choice',0.55,'点 A 向右平移 5 个单位，对应点 A′，则 AA′ = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "10"}, {"key": "C", "text": "0"}, {"key": "D", "text": "2.5"}]','A','平移距离 = 对应点连线长度 = 5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0087-2','math','初中',8,'jkp-0087','single_choice',0.55,'点 A 向右平移 2 个单位，对应点 A′，则 AA′ = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "4"}, {"key": "C", "text": "0"}, {"key": "D", "text": "1.0"}]','A','平移距离 = 对应点连线长度 = 2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0087-3','math','初中',8,'jkp-0087','single_choice',0.55,'点 A 向右平移 4 个单位，对应点 A′，则 AA′ = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "8"}, {"key": "C", "text": "0"}, {"key": "D", "text": "2.0"}]','A','平移距离 = 对应点连线长度 = 4','template-j','approved','通用');