-- 第24章 圆 补题（11学期, 知识点 344-367）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0344-1','math','初中',11,'jkp-0344','single_choice',0.75,'半径 4 的圆周长 C = 2πr = ？','[{"key": "A", "text": "8π"}, {"key": "B", "text": "4π"}, {"key": "C", "text": "16π"}, {"key": "D", "text": "8"}]','A','C=2π×4=8π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0345-1','math','初中',11,'jkp-0345','single_choice',0.35,'圆上两点间的部分叫？','[{"key": "A", "text": "弧"}, {"key": "B", "text": "弦"}, {"key": "C", "text": "直径"}, {"key": "D", "text": "半径"}]','A','弧定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0346-1','math','初中',11,'jkp-0346','single_choice',0.45,'能够完全重合的两个圆叫？','[{"key": "A", "text": "等圆"}, {"key": "B", "text": "同心圆"}, {"key": "C", "text": "相似圆"}, {"key": "D", "text": "相切圆"}]','A','等圆定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0347-1','math','初中',11,'jkp-0347','single_choice',0.55,'垂直于弦的直径？','[{"key": "A", "text": "平分这条弦和弦所对的两条弧"}, {"key": "B", "text": "只平分弦"}, {"key": "C", "text": "不平分"}, {"key": "D", "text": "与弦平行"}]','A','垂径定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0348-1','math','初中',11,'jkp-0348','single_choice',0.65,'平分弦（非直径）的直径？','[{"key": "A", "text": "垂直于弦"}, {"key": "B", "text": "平行于弦"}, {"key": "C", "text": "与弦相交但不垂直"}, {"key": "D", "text": "不经过圆心"}]','A','垂径定理推论','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0349-1','math','初中',11,'jkp-0349','single_choice',0.75,'同圆中，相等的圆心角所对的弦？','[{"key": "A", "text": "相等"}, {"key": "B", "text": "不等"}, {"key": "C", "text": "成比例"}, {"key": "D", "text": "无法确定"}]','A','弧弦圆心角关系定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0350-1','math','初中',11,'jkp-0350','single_choice',0.35,'顶点在圆上、两边都与圆相交的角叫？','[{"key": "A", "text": "圆周角"}, {"key": "B", "text": "圆心角"}, {"key": "C", "text": "平角"}, {"key": "D", "text": "周角"}]','A','圆周角定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0351-1','math','初中',11,'jkp-0351','single_choice',0.45,'同弧所对的圆心角 ∠AOB=75°，则圆周角 ∠ACB = ？','[{"key": "A", "text": "37.5°"}, {"key": "B", "text": "75°"}, {"key": "C", "text": "150°"}, {"key": "D", "text": "105°"}]','A','圆周角=圆心角一半=37.5°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0352-1','math','初中',11,'jkp-0352','single_choice',0.55,'同弧所对的圆周角？','[{"key": "A", "text": "相等"}, {"key": "B", "text": "互补"}, {"key": "C", "text": "互余"}, {"key": "D", "text": "成2倍"}]','A','同弧或等弧圆周角相等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0353-1','math','初中',11,'jkp-0353','single_choice',0.65,'直径所对的圆周角是？','[{"key": "A", "text": "直角"}, {"key": "B", "text": "锐角"}, {"key": "C", "text": "钝角"}, {"key": "D", "text": "平角"}]','A','直径所对圆周角 = 90°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0354-1','math','初中',11,'jkp-0354','single_choice',0.75,'圆内接四边形中 ∠A=78°，则对角 ∠C = ？','[{"key": "A", "text": "102°"}, {"key": "B", "text": "78°"}, {"key": "C", "text": "12°"}, {"key": "D", "text": "156°"}]','A','圆内接四边形对角互补：∠C=102°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0355-1','math','初中',11,'jkp-0355','single_choice',0.35,'圆 O 半径 4，点 P 到 O 距离 2，则 P 与圆的位置关系？','[{"key": "A", "text": "点在圆内"}, {"key": "B", "text": "点在圆上"}, {"key": "C", "text": "点在圆外"}, {"key": "D", "text": "无法确定"}]','A','距离 2 < 半径 4 → 点在圆内','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0356-1','math','初中',11,'jkp-0356','single_choice',0.45,'不在同一直线上的三个点确定？','[{"key": "A", "text": "一个圆"}, {"key": "B", "text": "一条直线"}, {"key": "C", "text": "两个圆"}, {"key": "D", "text": "一个三角形"}]','A','不共线三点确定一个圆','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0357-1','math','初中',11,'jkp-0357','single_choice',0.55,'三角形外接圆的圆心叫？','[{"key": "A", "text": "外心"}, {"key": "B", "text": "内心"}, {"key": "C", "text": "重心"}, {"key": "D", "text": "垂心"}]','A','外心：三边垂直平分线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0358-1','math','初中',11,'jkp-0358','single_choice',0.65,'圆心到直线距离 4，半径 3（d<r），直线与圆？','[{"key": "A", "text": "相交"}, {"key": "B", "text": "相切"}, {"key": "C", "text": "相离"}, {"key": "D", "text": "重合"}]','A','d=4<r=3 → 相交','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0359-1','math','初中',11,'jkp-0359','single_choice',0.75,'过半径外端且垂直于半径的直线是圆的？','[{"key": "A", "text": "切线"}, {"key": "B", "text": "弦"}, {"key": "C", "text": "直径"}, {"key": "D", "text": "割线"}]','A','切线判定定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0360-1','math','初中',11,'jkp-0360','single_choice',0.35,'圆的切线垂直于？','[{"key": "A", "text": "过切点的半径"}, {"key": "B", "text": "任意直径"}, {"key": "C", "text": "圆心连线"}, {"key": "D", "text": "弦"}]','A','切线性质：垂直于过切点的半径','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0361-1','math','初中',11,'jkp-0361','single_choice',0.45,'从圆外一点引两条切线，切线长 PA=6，则 PB = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "12"}, {"key": "C", "text": "3.0"}, {"key": "D", "text": "0"}]','A','切线长定理：两条切线长相等 = 6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0362-1','math','初中',11,'jkp-0362','single_choice',0.55,'三角形内切圆的圆心叫？','[{"key": "A", "text": "内心"}, {"key": "B", "text": "外心"}, {"key": "C", "text": "重心"}, {"key": "D", "text": "垂心"}]','A','内心：角平分线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0363-1','math','初中',11,'jkp-0363','single_choice',0.65,'两圆半径 3、4，圆心距 7，两圆？','[{"key": "A", "text": "外切"}, {"key": "B", "text": "外离"}, {"key": "C", "text": "内切"}, {"key": "D", "text": "内含"}]','A','圆心距=两半径和 → 外切','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0364-1','math','初中',11,'jkp-0364','single_choice',0.75,'正5边形中心角 = 360°/5 = ？','[{"key": "A", "text": "72.0°"}, {"key": "B", "text": "36.0°"}, {"key": "C", "text": "18.0°"}, {"key": "D", "text": "5°"}]','A','中心角=360°/5=72.0°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0365-1','math','初中',11,'jkp-0365','single_choice',0.35,'半径 2、圆心角 74° 的弧长 l = nπr/180 = ？','[{"key": "A", "text": "2.58π"}, {"key": "B", "text": "74π"}, {"key": "C", "text": "2π"}, {"key": "D", "text": "148π"}]','A','l=74π×2/180=2.58π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0366-1','math','初中',11,'jkp-0366','single_choice',0.45,'半径 4、圆心角 73° 的扇形面积 S = nπr²/360 = ？','[{"key": "A", "text": "10.19π"}, {"key": "B", "text": "73π"}, {"key": "C", "text": "16π"}, {"key": "D", "text": "292π"}]','A','S=73π×4²/360=10.19π','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0367-1','math','初中',11,'jkp-0367','single_choice',0.55,'圆锥底面半径 2、母线 5，侧面积 = πrl = ？','[{"key": "A", "text": "10π"}, {"key": "B", "text": "4π"}, {"key": "C", "text": "25π"}, {"key": "D", "text": "20π"}]','A','S侧=πrl=2×5π=10π','template-j','approved','通用');