-- 第6章 平面直角坐标系 补题（8学期, 知识点 88-99）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0088-1','math','初中',8,'jkp-0088','single_choice',0.65,'(3,5) 与 (5,3) 表示的位置？','[{"key": "A", "text": "不同位置"}, {"key": "B", "text": "相同位置"}, {"key": "C", "text": "互为相反数"}, {"key": "D", "text": "无法确定"}]','A','有序数对：顺序不同位置不同','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0088-2','math','初中',8,'jkp-0088','single_choice',0.65,'(3,5) 与 (5,3) 表示的位置？','[{"key": "C", "text": "互为相反数"}, {"key": "D", "text": "无法确定"}, {"key": "A", "text": "不同位置"}, {"key": "B", "text": "相同位置"}]','A','有序数对：顺序不同位置不同','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0088-3','math','初中',8,'jkp-0088','single_choice',0.65,'(3,5) 与 (5,3) 表示的位置？','[{"key": "B", "text": "相同位置"}, {"key": "A", "text": "不同位置"}, {"key": "C", "text": "互为相反数"}, {"key": "D", "text": "无法确定"}]','A','有序数对：顺序不同位置不同','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0089-1','math','初中',8,'jkp-0089','single_choice',0.75,'平面直角坐标系由 x 轴、y 轴和？组成','[{"key": "A", "text": "原点"}, {"key": "B", "text": "单位圆"}, {"key": "C", "text": "象限角"}, {"key": "D", "text": "刻度"}]','A','坐标系三要素：x 轴、y 轴、原点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0089-2','math','初中',8,'jkp-0089','single_choice',0.75,'平面直角坐标系由 x 轴、y 轴和？组成','[{"key": "A", "text": "原点"}, {"key": "D", "text": "刻度"}, {"key": "C", "text": "象限角"}, {"key": "B", "text": "单位圆"}]','A','坐标系三要素：x 轴、y 轴、原点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0089-3','math','初中',8,'jkp-0089','single_choice',0.75,'平面直角坐标系由 x 轴、y 轴和？组成','[{"key": "B", "text": "单位圆"}, {"key": "C", "text": "象限角"}, {"key": "A", "text": "原点"}, {"key": "D", "text": "刻度"}]','A','坐标系三要素：x 轴、y 轴、原点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0090-1','math','初中',8,'jkp-0090','single_choice',0.35,'平面直角坐标系把平面分成几个象限？','[{"key": "A", "text": "4 个"}, {"key": "B", "text": "2 个"}, {"key": "C", "text": "3 个"}, {"key": "D", "text": "8 个"}]','A','四个象限（逆时针 I、II、III、IV）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0090-2','math','初中',8,'jkp-0090','single_choice',0.35,'平面直角坐标系把平面分成几个象限？','[{"key": "B", "text": "2 个"}, {"key": "D", "text": "8 个"}, {"key": "A", "text": "4 个"}, {"key": "C", "text": "3 个"}]','A','四个象限（逆时针 I、II、III、IV）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0090-3','math','初中',8,'jkp-0090','single_choice',0.35,'平面直角坐标系把平面分成几个象限？','[{"key": "C", "text": "3 个"}, {"key": "D", "text": "8 个"}, {"key": "B", "text": "2 个"}, {"key": "A", "text": "4 个"}]','A','四个象限（逆时针 I、II、III、IV）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0091-1','math','初中',8,'jkp-0091','single_choice',0.45,'点 P 的横坐标 3，纵坐标 1，则 P 的坐标写作？','[{"key": "A", "text": "(3,1)"}, {"key": "B", "text": "(1,3)"}, {"key": "C", "text": "x=3 y=1"}, {"key": "D", "text": "3，1"}]','A','坐标写法 (横, 纵) = (3,1)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0091-2','math','初中',8,'jkp-0091','single_choice',0.45,'点 P 的横坐标 3，纵坐标 4，则 P 的坐标写作？','[{"key": "A", "text": "(3,4)"}, {"key": "B", "text": "(4,3)"}, {"key": "C", "text": "x=3 y=4"}, {"key": "D", "text": "3，4"}]','A','坐标写法 (横, 纵) = (3,4)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0091-3','math','初中',8,'jkp-0091','single_choice',0.45,'点 P 的横坐标 5，纵坐标 2，则 P 的坐标写作？','[{"key": "A", "text": "(5,2)"}, {"key": "B", "text": "(2,5)"}, {"key": "C", "text": "x=5 y=2"}, {"key": "D", "text": "5，2"}]','A','坐标写法 (横, 纵) = (5,2)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0092-1','math','初中',8,'jkp-0092','single_choice',0.55,'点 (-3, 2) 在第几象限？','[{"key": "A", "text": "第二象限"}, {"key": "B", "text": "第一象限"}, {"key": "C", "text": "第三象限"}, {"key": "D", "text": "第四象限"}]','A','(-,+) → 第二象限','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0092-2','math','初中',8,'jkp-0092','single_choice',0.55,'点 (-3, 2) 在第几象限？','[{"key": "C", "text": "第三象限"}, {"key": "B", "text": "第一象限"}, {"key": "D", "text": "第四象限"}, {"key": "A", "text": "第二象限"}]','A','(-,+) → 第二象限','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0092-3','math','初中',8,'jkp-0092','single_choice',0.55,'点 (-3, 2) 在第几象限？','[{"key": "B", "text": "第一象限"}, {"key": "C", "text": "第三象限"}, {"key": "D", "text": "第四象限"}, {"key": "A", "text": "第二象限"}]','A','(-,+) → 第二象限','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0093-1','math','初中',8,'jkp-0093','single_choice',0.65,'点 (5, 0) 在？','[{"key": "A", "text": "x 轴上"}, {"key": "B", "text": "y 轴上"}, {"key": "C", "text": "第一象限"}, {"key": "D", "text": "原点"}]','A','纵坐标为 0 → 在 x 轴上','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0093-2','math','初中',8,'jkp-0093','single_choice',0.65,'点 (2, 0) 在？','[{"key": "A", "text": "x 轴上"}, {"key": "B", "text": "y 轴上"}, {"key": "C", "text": "第一象限"}, {"key": "D", "text": "原点"}]','A','纵坐标为 0 → 在 x 轴上','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0093-3','math','初中',8,'jkp-0093','single_choice',0.65,'点 (3, 0) 在？','[{"key": "A", "text": "x 轴上"}, {"key": "B", "text": "y 轴上"}, {"key": "C", "text": "第一象限"}, {"key": "D", "text": "原点"}]','A','纵坐标为 0 → 在 x 轴上','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0094-1','math','初中',8,'jkp-0094','single_choice',0.75,'点 (1,1) 关于 x 轴对称的点的坐标是？','[{"key": "A", "text": "(1,-1)"}, {"key": "B", "text": "(-1,1)"}, {"key": "C", "text": "(-1,-1)"}, {"key": "D", "text": "(1,1)"}]','A','关于 x 轴对称：横坐标不变，纵坐标变号 → (1,-1)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0094-2','math','初中',8,'jkp-0094','single_choice',0.75,'点 (1,3) 关于 x 轴对称的点的坐标是？','[{"key": "A", "text": "(1,-3)"}, {"key": "B", "text": "(-1,3)"}, {"key": "C", "text": "(-1,-3)"}, {"key": "D", "text": "(3,1)"}]','A','关于 x 轴对称：横坐标不变，纵坐标变号 → (1,-3)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0094-3','math','初中',8,'jkp-0094','single_choice',0.75,'点 (5,1) 关于 x 轴对称的点的坐标是？','[{"key": "A", "text": "(5,-1)"}, {"key": "B", "text": "(-5,1)"}, {"key": "C", "text": "(-5,-1)"}, {"key": "D", "text": "(1,5)"}]','A','关于 x 轴对称：横坐标不变，纵坐标变号 → (5,-1)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0095-1','math','初中',8,'jkp-0095','single_choice',0.35,'点 (3,3) 关于 y 轴对称的点的坐标是？','[{"key": "A", "text": "(-3,3)"}, {"key": "B", "text": "(3,-3)"}, {"key": "C", "text": "(-3,-3)"}, {"key": "D", "text": "(3,3)"}]','A','关于 y 轴对称：横坐标变号，纵坐标不变 → (-3,3)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0095-2','math','初中',8,'jkp-0095','single_choice',0.35,'点 (1,2) 关于 y 轴对称的点的坐标是？','[{"key": "A", "text": "(-1,2)"}, {"key": "B", "text": "(1,-2)"}, {"key": "C", "text": "(-1,-2)"}, {"key": "D", "text": "(2,1)"}]','A','关于 y 轴对称：横坐标变号，纵坐标不变 → (-1,2)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0095-3','math','初中',8,'jkp-0095','single_choice',0.35,'点 (2,4) 关于 y 轴对称的点的坐标是？','[{"key": "A", "text": "(-2,4)"}, {"key": "B", "text": "(2,-4)"}, {"key": "C", "text": "(-2,-4)"}, {"key": "D", "text": "(4,2)"}]','A','关于 y 轴对称：横坐标变号，纵坐标不变 → (-2,4)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0096-1','math','初中',8,'jkp-0096','single_choice',0.45,'点 (4,2) 关于原点对称的点的坐标是？','[{"key": "A", "text": "(-4,-2)"}, {"key": "B", "text": "(4,-2)"}, {"key": "C", "text": "(-4,2)"}, {"key": "D", "text": "(2,4)"}]','A','关于原点对称：横纵都变号 → (-4,-2)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0096-2','math','初中',8,'jkp-0096','single_choice',0.45,'点 (5,5) 关于原点对称的点的坐标是？','[{"key": "A", "text": "(-5,-5)"}, {"key": "B", "text": "(5,-5)"}, {"key": "C", "text": "(-5,5)"}, {"key": "D", "text": "(5,5)"}]','A','关于原点对称：横纵都变号 → (-5,-5)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0096-3','math','初中',8,'jkp-0096','single_choice',0.45,'点 (4,5) 关于原点对称的点的坐标是？','[{"key": "A", "text": "(-4,-5)"}, {"key": "B", "text": "(4,-5)"}, {"key": "C", "text": "(-4,5)"}, {"key": "D", "text": "(5,4)"}]','A','关于原点对称：横纵都变号 → (-4,-5)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0097-1','math','初中',8,'jkp-0097','single_choice',0.55,'点 (1,1) 向右平移 5 个单位，再向上平移 4 个单位，得到？','[{"key": "A", "text": "(6,5)"}, {"key": "B", "text": "(-4,-3)"}, {"key": "C", "text": "(6,-3)"}, {"key": "D", "text": "(-4,5)"}]','A','右加左减 x，上加下减 y → (6,5)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0097-2','math','初中',8,'jkp-0097','single_choice',0.55,'点 (1,1) 向右平移 4 个单位，再向上平移 3 个单位，得到？','[{"key": "A", "text": "(5,4)"}, {"key": "B", "text": "(-3,-2)"}, {"key": "C", "text": "(5,-2)"}, {"key": "D", "text": "(-3,4)"}]','A','右加左减 x，上加下减 y → (5,4)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0097-3','math','初中',8,'jkp-0097','single_choice',0.55,'点 (1,1) 向右平移 5 个单位，再向上平移 3 个单位，得到？','[{"key": "A", "text": "(6,4)"}, {"key": "B", "text": "(-4,-2)"}, {"key": "C", "text": "(6,-2)"}, {"key": "D", "text": "(-4,4)"}]','A','右加左减 x，上加下减 y → (6,4)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0098-1','math','初中',8,'jkp-0098','single_choice',0.65,'三点 (0,0)、(4,0)、(4,4) 围成三角形面积 = ？','[{"key": "A", "text": "8.0"}, {"key": "B", "text": "16"}, {"key": "C", "text": "8"}, {"key": "D", "text": "4"}]','A','直角三角形：S=½×4×4=8.0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0098-2','math','初中',8,'jkp-0098','single_choice',0.65,'三点 (0,0)、(3,0)、(3,3) 围成三角形面积 = ？','[{"key": "A", "text": "4.5"}, {"key": "B", "text": "9"}, {"key": "C", "text": "6"}, {"key": "D", "text": "3"}]','A','直角三角形：S=½×3×3=4.5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0098-3','math','初中',8,'jkp-0098','single_choice',0.65,'三点 (0,0)、(2,0)、(2,2) 围成三角形面积 = ？','[{"key": "A", "text": "2.0"}, {"key": "B", "text": "4"}, {"key": "C", "text": "4"}, {"key": "D", "text": "2"}]','A','直角三角形：S=½×2×2=2.0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0099-1','math','初中',8,'jkp-0099','single_choice',0.75,'用坐标表示地理位置，先要建立？','[{"key": "A", "text": "平面直角坐标系"}, {"key": "B", "text": "比例尺"}, {"key": "C", "text": "方位角"}, {"key": "D", "text": "地图"}]','A','先建坐标系，再定原点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0099-2','math','初中',8,'jkp-0099','single_choice',0.75,'用坐标表示地理位置，先要建立？','[{"key": "A", "text": "平面直角坐标系"}, {"key": "B", "text": "比例尺"}, {"key": "D", "text": "地图"}, {"key": "C", "text": "方位角"}]','A','先建坐标系，再定原点','template-j','approved','通用');