-- 第15章 整式的乘除与分解因式 补题（9学期, 知识点 220-240）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0220-1','math','初中',9,'jkp-0220','single_choice',0.35,'3^4 × 3^2 = ？','[{"key": "A", "text": "729"}, {"key": "B", "text": "6561"}, {"key": "C", "text": "90"}, {"key": "D", "text": "9"}]','A','同底数幂相乘指数相加：3^6=729','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0221-1','math','初中',9,'jkp-0221','single_choice',0.45,'(2^2)^2 = 2^2×2 = ？','[{"key": "A", "text": "16"}, {"key": "B", "text": "16"}, {"key": "C", "text": "16"}, {"key": "D", "text": "32"}]','A','幂的乘方指数相乘：2^4=16','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0222-1','math','初中',9,'jkp-0222','single_choice',0.55,'(2x)^2 = ？','[{"key": "A", "text": "4x^2"}, {"key": "B", "text": "4x^2"}, {"key": "C", "text": "2x^2"}, {"key": "D", "text": "4x^3"}]','A','积的乘方：4x^2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0223-1','math','初中',9,'jkp-0223','single_choice',0.65,'3^2 ÷ 3^2 = ？','[{"key": "A", "text": "1"}, {"key": "B", "text": "81"}, {"key": "C", "text": "81"}, {"key": "D", "text": "3.0"}]','A','同底数幂相除指数相减：3^0=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0224-1','math','初中',9,'jkp-0224','single_choice',0.75,'3⁰ = ？(a≠0)','[{"key": "A", "text": "1"}, {"key": "B", "text": "0"}, {"key": "C", "text": "3"}, {"key": "D", "text": "-3"}]','A','零指数幂：任何非零数的 0 次幂 = 1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0225-1','math','初中',9,'jkp-0225','single_choice',0.35,'3⁻¹ = ？','[{"key": "A", "text": "1/3"}, {"key": "B", "text": "-3"}, {"key": "C", "text": "3"}, {"key": "D", "text": "-1/3"}]','A','负整数指数：3⁻¹=1/3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0226-1','math','初中',9,'jkp-0226','single_choice',0.45,'计算：3x² · 4x³ = ？','[{"key": "A", "text": "12x⁵"}, {"key": "B", "text": "12x⁶"}, {"key": "C", "text": "7x⁵"}, {"key": "D", "text": "12x^5"}]','A','系数相乘、指数相加：12x⁵','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0227-1','math','初中',9,'jkp-0227','single_choice',0.55,'计算：4x(4x + 1) = ？','[{"key": "A", "text": "16x² + 4x"}, {"key": "B", "text": "16x² + 1"}, {"key": "C", "text": "4x² + 4x"}, {"key": "D", "text": "16x + 4"}]','A','分配律：16x² + 4x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0228-1','math','初中',9,'jkp-0228','single_choice',0.65,'(x + 2)(x + 4) = ？','[{"key": "A", "text": "x² + 6x + 8"}, {"key": "B", "text": "x² + 8x + 6"}, {"key": "C", "text": "x² + 6x + 6"}, {"key": "D", "text": "x² + -2x + 8"}]','A','多项式乘多项式：x²+(2+4)x+2×4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0229-1','math','初中',9,'jkp-0229','single_choice',0.75,'计算：(2x + 3)(2x - 3) = ？','[{"key": "A", "text": "4x² - 9"}, {"key": "B", "text": "4x² + 9"}, {"key": "C", "text": "4x² + 12x + 9"}, {"key": "D", "text": "4x² - 12x + 9"}]','A','平方差公式：(2x)²-3²=4x²-9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0230-1','math','初中',9,'jkp-0230','single_choice',0.35,'(2 + 5)² = ？','[{"key": "A", "text": "4+20+25"}, {"key": "B", "text": "4+25"}, {"key": "C", "text": "4-20+25"}, {"key": "D", "text": "4+10"}]','A','完全平方和：2²+2×2×5+5²=4+20+25','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0231-1','math','初中',9,'jkp-0231','single_choice',0.45,'(5 - 3)² = ？','[{"key": "A", "text": "25-30+9"}, {"key": "B", "text": "25+9"}, {"key": "C", "text": "25+30+9"}, {"key": "D", "text": "10-6"}]','A','完全平方差：5²-2×5×3+3²=25-30+9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0232-1','math','初中',9,'jkp-0232','single_choice',0.55,'(x + 3)² = x² + 2·3·x + 3²，则 x² + 6x + 9 = (x + ?)²','[{"key": "A", "text": "3"}, {"key": "B", "text": "6"}, {"key": "C", "text": "9"}, {"key": "D", "text": "4"}]','A','完全平方逆用：(x+3)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0233-1','math','初中',9,'jkp-0233','single_choice',0.65,'8x⁴ ÷ 2x² = ？','[{"key": "A", "text": "4x²"}, {"key": "B", "text": "8x²"}, {"key": "C", "text": "4x⁴"}, {"key": "D", "text": "4x^2"}]','A','系数相除、指数相减：4x²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0234-1','math','初中',9,'jkp-0234','single_choice',0.75,'(4x² + 8x) ÷ 4x = ？','[{"key": "A", "text": "x + 2"}, {"key": "B", "text": "4x + 2"}, {"key": "C", "text": "x + 8"}, {"key": "D", "text": "4x + 8"}]','A','逐项除以：4x²÷4x + 8x÷4x = x+2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0235-1','math','初中',9,'jkp-0235','single_choice',0.35,'把一个多项式化成几个整式的积的形式叫？','[{"key": "A", "text": "因式分解"}, {"key": "B", "text": "整式乘法"}, {"key": "C", "text": "合并同类项"}, {"key": "D", "text": "去括号"}]','A','因式分解定义（和变积）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0236-1','math','初中',9,'jkp-0236','single_choice',0.45,'因式分解与整式乘法的关系是？','[{"key": "A", "text": "互逆"}, {"key": "B", "text": "相同"}, {"key": "C", "text": "无关"}, {"key": "D", "text": "包含"}]','A','因式分解与整式乘法互为逆运算','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0237-1','math','初中',9,'jkp-0237','single_choice',0.55,'分解因式：4x + 8 = ？','[{"key": "A", "text": "4(x + 2)"}, {"key": "B", "text": "4(x + 8)"}, {"key": "C", "text": "x(4 + 2)"}, {"key": "D", "text": "4x(1 + 2)"}]','A','提公因式 4：4(x+2)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0238-1','math','初中',9,'jkp-0238','single_choice',0.65,'分解因式：4x² - 16 = ？','[{"key": "A", "text": "(2x+4)(2x-4)"}, {"key": "B", "text": "(2x+4)²"}, {"key": "C", "text": "(2x-4)²"}, {"key": "D", "text": "(2x+4)(2x+4)"}]','A','平方差公式：(2x)²-4²=(2x+4)(2x-4)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0239-1','math','初中',9,'jkp-0239','single_choice',0.75,'分解因式：x² + 8x + 16 = ？','[{"key": "A", "text": "(x+4)²"}, {"key": "B", "text": "(x-4)²"}, {"key": "C", "text": "(x+4)(x-4)"}, {"key": "D", "text": "(x+8)²"}]','A','完全平方：x²+2×4x+4²=(x+4)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0240-1','math','初中',9,'jkp-0240','single_choice',0.35,'分解因式 10x² - 10 的第一步是？','[{"key": "A", "text": "提公因式 10"}, {"key": "B", "text": "直接套公式"}, {"key": "C", "text": "合并同类项"}, {"key": "D", "text": "去括号"}]','A','先提公因式 10：10(x²-1)','template-j','approved','通用');