-- 第29章 投影与视图 补题（12学期, 知识点 431-437）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0431-1','math','初中',12,'jkp-0431','single_choice',0.45,'平行光线照射形成的投影叫？','[{"key": "A", "text": "平行投影"}, {"key": "B", "text": "中心投影"}, {"key": "C", "text": "正投影"}, {"key": "D", "text": "斜投影"}]','A','平行投影（如太阳光）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0431-2','math','初中',12,'jkp-0431','single_choice',0.45,'平行光线照射形成的投影叫？','[{"key": "B", "text": "中心投影"}, {"key": "A", "text": "平行投影"}, {"key": "D", "text": "斜投影"}, {"key": "C", "text": "正投影"}]','A','平行投影（如太阳光）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0431-3','math','初中',12,'jkp-0431','single_choice',0.45,'平行光线照射形成的投影叫？','[{"key": "B", "text": "中心投影"}, {"key": "A", "text": "平行投影"}, {"key": "C", "text": "正投影"}, {"key": "D", "text": "斜投影"}]','A','平行投影（如太阳光）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0432-1','math','初中',12,'jkp-0432','single_choice',0.55,'投影线垂直于投影面时的投影叫？','[{"key": "A", "text": "正投影"}, {"key": "B", "text": "平行投影"}, {"key": "C", "text": "中心投影"}, {"key": "D", "text": "斜投影"}]','A','正投影定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0432-2','math','初中',12,'jkp-0432','single_choice',0.55,'投影线垂直于投影面时的投影叫？','[{"key": "A", "text": "正投影"}, {"key": "C", "text": "中心投影"}, {"key": "D", "text": "斜投影"}, {"key": "B", "text": "平行投影"}]','A','正投影定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0432-3','math','初中',12,'jkp-0432','single_choice',0.55,'投影线垂直于投影面时的投影叫？','[{"key": "C", "text": "中心投影"}, {"key": "D", "text": "斜投影"}, {"key": "A", "text": "正投影"}, {"key": "B", "text": "平行投影"}]','A','正投影定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0433-1','math','初中',12,'jkp-0433','single_choice',0.65,'三视图是指？','[{"key": "A", "text": "主视图、左视图、俯视图"}, {"key": "B", "text": "正视图、侧视图、背视图"}, {"key": "C", "text": "顶视图、底视图、侧视图"}, {"key": "D", "text": "前视图、后视图、左视图"}]','A','三视图定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0433-2','math','初中',12,'jkp-0433','single_choice',0.65,'三视图是指？','[{"key": "C", "text": "顶视图、底视图、侧视图"}, {"key": "A", "text": "主视图、左视图、俯视图"}, {"key": "B", "text": "正视图、侧视图、背视图"}, {"key": "D", "text": "前视图、后视图、左视图"}]','A','三视图定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0433-3','math','初中',12,'jkp-0433','single_choice',0.65,'三视图是指？','[{"key": "B", "text": "正视图、侧视图、背视图"}, {"key": "C", "text": "顶视图、底视图、侧视图"}, {"key": "A", "text": "主视图、左视图、俯视图"}, {"key": "D", "text": "前视图、后视图、左视图"}]','A','三视图定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0434-1','math','初中',12,'jkp-0434','single_choice',0.75,'三视图中，主视图与俯视图？','[{"key": "A", "text": "长对正"}, {"key": "B", "text": "高平齐"}, {"key": "C", "text": "宽相等"}, {"key": "D", "text": "无关"}]','A','主俯长对正','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0434-2','math','初中',12,'jkp-0434','single_choice',0.75,'三视图中，主视图与俯视图？','[{"key": "C", "text": "宽相等"}, {"key": "D", "text": "无关"}, {"key": "A", "text": "长对正"}, {"key": "B", "text": "高平齐"}]','A','主俯长对正','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0434-3','math','初中',12,'jkp-0434','single_choice',0.75,'三视图中，主视图与俯视图？','[{"key": "A", "text": "长对正"}, {"key": "D", "text": "无关"}, {"key": "C", "text": "宽相等"}, {"key": "B", "text": "高平齐"}]','A','主俯长对正','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0435-1','math','初中',12,'jkp-0435','single_choice',0.35,'球的三视图都是？','[{"key": "A", "text": "圆"}, {"key": "B", "text": "矩形"}, {"key": "C", "text": "三角形"}, {"key": "D", "text": "正方形"}]','A','球三视图都是圆','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0435-2','math','初中',12,'jkp-0435','single_choice',0.35,'球的三视图都是？','[{"key": "C", "text": "三角形"}, {"key": "B", "text": "矩形"}, {"key": "D", "text": "正方形"}, {"key": "A", "text": "圆"}]','A','球三视图都是圆','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0435-3','math','初中',12,'jkp-0435','single_choice',0.35,'球的三视图都是？','[{"key": "A", "text": "圆"}, {"key": "D", "text": "正方形"}, {"key": "C", "text": "三角形"}, {"key": "B", "text": "矩形"}]','A','球三视图都是圆','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0436-1','math','初中',12,'jkp-0436','single_choice',0.45,'三视图都是矩形的几何体是？','[{"key": "A", "text": "长方体"}, {"key": "B", "text": "球"}, {"key": "C", "text": "圆锥"}, {"key": "D", "text": "三棱锥"}]','A','长方体三视图为矩形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0436-2','math','初中',12,'jkp-0436','single_choice',0.45,'三视图都是矩形的几何体是？','[{"key": "A", "text": "长方体"}, {"key": "D", "text": "三棱锥"}, {"key": "B", "text": "球"}, {"key": "C", "text": "圆锥"}]','A','长方体三视图为矩形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0436-3','math','初中',12,'jkp-0436','single_choice',0.45,'三视图都是矩形的几何体是？','[{"key": "B", "text": "球"}, {"key": "A", "text": "长方体"}, {"key": "C", "text": "圆锥"}, {"key": "D", "text": "三棱锥"}]','A','长方体三视图为矩形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0437-1','math','初中',12,'jkp-0437','single_choice',0.55,'由三视图还原：主视图和俯视图都是正方形、左视图也是正方形，几何体棱长 2，体积 = ？','[{"key": "A", "text": "8"}, {"key": "B", "text": "4"}, {"key": "C", "text": "24"}, {"key": "D", "text": "6"}]','A','正方体 V=a³=2³=8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0437-2','math','初中',12,'jkp-0437','single_choice',0.55,'由三视图还原：主视图和俯视图都是正方形、左视图也是正方形，几何体棱长 4，体积 = ？','[{"key": "A", "text": "64"}, {"key": "B", "text": "16"}, {"key": "C", "text": "96"}, {"key": "D", "text": "12"}]','A','正方体 V=a³=4³=64','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0437-3','math','初中',12,'jkp-0437','single_choice',0.55,'由三视图还原：主视图和俯视图都是正方形、左视图也是正方形，几何体棱长 5，体积 = ？','[{"key": "A", "text": "125"}, {"key": "B", "text": "25"}, {"key": "C", "text": "150"}, {"key": "D", "text": "15"}]','A','正方体 V=a³=5³=125','template-j','approved','通用');