-- 第21章 二次根式 补题（11学期, 知识点 310-320）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0310-1','math','初中',11,'jkp-0310','single_choice',0.35,'下列是二次根式的是？','[{"key": "A", "text": "√3"}, {"key": "B", "text": "³√2"}, {"key": "C", "text": "√-1"}, {"key": "D", "text": "2"}]','A','二次根式：√a(a≥0)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0310-2','math','初中',11,'jkp-0310','single_choice',0.35,'下列是二次根式的是？','[{"key": "A", "text": "√3"}, {"key": "D", "text": "2"}, {"key": "B", "text": "³√2"}, {"key": "C", "text": "√-1"}]','A','二次根式：√a(a≥0)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0310-3','math','初中',11,'jkp-0310','single_choice',0.35,'下列是二次根式的是？','[{"key": "D", "text": "2"}, {"key": "C", "text": "√-1"}, {"key": "B", "text": "³√2"}, {"key": "A", "text": "√3"}]','A','二次根式：√a(a≥0)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0311-1','math','初中',11,'jkp-0311','single_choice',0.45,'√(x-5) 有意义的条件是？','[{"key": "A", "text": "x ≥ 5"}, {"key": "B", "text": "x > 5"}, {"key": "C", "text": "x ≤ 5"}, {"key": "D", "text": "x ≠ 5"}]','A','被开方数非负：x-5≥0 → x≥5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0311-2','math','初中',11,'jkp-0311','single_choice',0.45,'√(x-2) 有意义的条件是？','[{"key": "A", "text": "x ≥ 2"}, {"key": "B", "text": "x > 2"}, {"key": "C", "text": "x ≤ 2"}, {"key": "D", "text": "x ≠ 2"}]','A','被开方数非负：x-2≥0 → x≥2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0311-3','math','初中',11,'jkp-0311','single_choice',0.45,'√(x-4) 有意义的条件是？','[{"key": "A", "text": "x ≥ 4"}, {"key": "B", "text": "x > 4"}, {"key": "C", "text": "x ≤ 4"}, {"key": "D", "text": "x ≠ 4"}]','A','被开方数非负：x-4≥0 → x≥4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0312-1','math','初中',11,'jkp-0312','single_choice',0.55,'(√5)² = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "25"}, {"key": "C", "text": "1"}, {"key": "D", "text": "-5"}]','A','(√a)²=a=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0312-2','math','初中',11,'jkp-0312','single_choice',0.55,'(√3)² = ？','[{"key": "A", "text": "3"}, {"key": "B", "text": "9"}, {"key": "C", "text": "1"}, {"key": "D", "text": "-3"}]','A','(√a)²=a=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0312-3','math','初中',11,'jkp-0312','single_choice',0.55,'(√4)² = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "16"}, {"key": "C", "text": "1"}, {"key": "D", "text": "-4"}]','A','(√a)²=a=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0313-1','math','初中',11,'jkp-0313','single_choice',0.65,'√(25) = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "-5"}, {"key": "C", "text": "25"}, {"key": "D", "text": "±5"}]','A','√(a²)=|a|=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0313-2','math','初中',11,'jkp-0313','single_choice',0.65,'√(4) = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "-2"}, {"key": "C", "text": "4"}, {"key": "D", "text": "±2"}]','A','√(a²)=|a|=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0313-3','math','初中',11,'jkp-0313','single_choice',0.65,'√(9) = ？','[{"key": "A", "text": "3"}, {"key": "B", "text": "-3"}, {"key": "C", "text": "9"}, {"key": "D", "text": "±3"}]','A','√(a²)=|a|=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0314-1','math','初中',11,'jkp-0314','single_choice',0.75,'√9 × √4 = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "5"}, {"key": "C", "text": "36"}, {"key": "D", "text": "12"}]','A','√a×√b=√(ab)=3×2=6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0314-2','math','初中',11,'jkp-0314','single_choice',0.75,'√16 × √4 = ？','[{"key": "A", "text": "8"}, {"key": "B", "text": "6"}, {"key": "C", "text": "64"}, {"key": "D", "text": "16"}]','A','√a×√b=√(ab)=4×2=8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0314-3','math','初中',11,'jkp-0314','single_choice',0.75,'√16 × √9 = ？','[{"key": "A", "text": "12"}, {"key": "B", "text": "7"}, {"key": "C", "text": "144"}, {"key": "D", "text": "24"}]','A','√a×√b=√(ab)=4×3=12','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0315-1','math','初中',11,'jkp-0315','single_choice',0.35,'√81 ÷ √9 = ？','[{"key": "A", "text": "3"}, {"key": "B", "text": "9"}, {"key": "C", "text": "3"}, {"key": "D", "text": "6"}]','A','√81=9，÷3=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0315-2','math','初中',11,'jkp-0315','single_choice',0.35,'√64 ÷ √4 = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "8"}, {"key": "C", "text": "2"}, {"key": "D", "text": "6"}]','A','√64=8，÷2=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0315-3','math','初中',11,'jkp-0315','single_choice',0.35,'√64 ÷ √16 = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "8"}, {"key": "C", "text": "4"}, {"key": "D", "text": "6"}]','A','√64=8，÷4=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0316-1','math','初中',11,'jkp-0316','single_choice',0.45,'最简二次根式的要求是？','[{"key": "A", "text": "被开方数不含分母和开得尽的因数"}, {"key": "B", "text": "被开方数含分母"}, {"key": "C", "text": "被开方数是分数"}, {"key": "D", "text": "系数是分数"}]','A','最简二次根式：被开方数不含分母、不含能开得尽的因数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0316-2','math','初中',11,'jkp-0316','single_choice',0.45,'最简二次根式的要求是？','[{"key": "D", "text": "系数是分数"}, {"key": "A", "text": "被开方数不含分母和开得尽的因数"}, {"key": "B", "text": "被开方数含分母"}, {"key": "C", "text": "被开方数是分数"}]','A','最简二次根式：被开方数不含分母、不含能开得尽的因数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0316-3','math','初中',11,'jkp-0316','single_choice',0.45,'最简二次根式的要求是？','[{"key": "D", "text": "系数是分数"}, {"key": "C", "text": "被开方数是分数"}, {"key": "B", "text": "被开方数含分母"}, {"key": "A", "text": "被开方数不含分母和开得尽的因数"}]','A','最简二次根式：被开方数不含分母、不含能开得尽的因数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0317-1','math','初中',11,'jkp-0317','single_choice',0.55,'化简 √(4×2) = ？','[{"key": "A", "text": "2√2"}, {"key": "B", "text": "4√2"}, {"key": "C", "text": "√8"}, {"key": "D", "text": "4"}]','A','√(4×2)=2√2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0317-2','math','初中',11,'jkp-0317','single_choice',0.55,'化简 √(16×2) = ？','[{"key": "A", "text": "4√2"}, {"key": "B", "text": "16√2"}, {"key": "C", "text": "√32"}, {"key": "D", "text": "8"}]','A','√(16×2)=4√2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0317-3','math','初中',11,'jkp-0317','single_choice',0.55,'化简 √(4×2) = ？','[{"key": "D", "text": "4"}, {"key": "B", "text": "4√2"}, {"key": "C", "text": "√8"}, {"key": "A", "text": "2√2"}]','A','√(4×2)=2√2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0318-1','math','初中',11,'jkp-0318','single_choice',0.65,'√8 与 √2 是同类二次根式吗？','[{"key": "A", "text": "是"}, {"key": "B", "text": "否"}, {"key": "C", "text": "无法判断"}, {"key": "D", "text": "不一定"}]','A','√8=2√2，与 √2 是同类','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0318-2','math','初中',11,'jkp-0318','single_choice',0.65,'√32 与 √2 是同类二次根式吗？','[{"key": "A", "text": "是"}, {"key": "B", "text": "否"}, {"key": "C", "text": "无法判断"}, {"key": "D", "text": "不一定"}]','A','√32=4√2，与 √2 是同类','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0318-3','math','初中',11,'jkp-0318','single_choice',0.65,'√8 与 √2 是同类二次根式吗？','[{"key": "D", "text": "不一定"}, {"key": "C", "text": "无法判断"}, {"key": "B", "text": "否"}, {"key": "A", "text": "是"}]','A','√8=2√2，与 √2 是同类','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0319-1','math','初中',11,'jkp-0319','single_choice',0.75,'√32 + √32 = ？','[{"key": "A", "text": "(4+4)√2"}, {"key": "B", "text": "8√2"}, {"key": "C", "text": "16√2"}, {"key": "D", "text": "(4×4)√2"}]','A','√32=4√2，√32=4√2，和=(4+4)√2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0319-2','math','初中',11,'jkp-0319','single_choice',0.75,'√32 + √8 = ？','[{"key": "A", "text": "(4+2)√2"}, {"key": "B", "text": "6√2"}, {"key": "C", "text": "8√2"}, {"key": "D", "text": "(4×2)√2"}]','A','√32=4√2，√8=2√2，和=(4+2)√2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0319-3','math','初中',11,'jkp-0319','single_choice',0.75,'√18 + √8 = ？','[{"key": "A", "text": "(3+2)√2"}, {"key": "B", "text": "5√2"}, {"key": "C", "text": "6√2"}, {"key": "D", "text": "(3×2)√2"}]','A','√18=3√2，√8=2√2，和=(3+2)√2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0320-1','math','初中',11,'jkp-0320','single_choice',0.35,'化简 1/√9 = ？','[{"key": "A", "text": "1/3"}, {"key": "B", "text": "3"}, {"key": "C", "text": "√9"}, {"key": "D", "text": "-1/3"}]','A','1/√9=1/3（分母有理化）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0320-2','math','初中',11,'jkp-0320','single_choice',0.35,'化简 1/√4 = ？','[{"key": "A", "text": "1/2"}, {"key": "B", "text": "2"}, {"key": "C", "text": "√4"}, {"key": "D", "text": "-1/2"}]','A','1/√4=1/2（分母有理化）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0320-3','math','初中',11,'jkp-0320','single_choice',0.35,'化简 1/√16 = ？','[{"key": "A", "text": "1/4"}, {"key": "B", "text": "4"}, {"key": "C", "text": "√16"}, {"key": "D", "text": "-1/4"}]','A','1/√16=1/4（分母有理化）','template-j','approved','通用');