-- 第14章 一次函数 补题（9学期, 知识点 201-219）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0201-1','math','初中',9,'jkp-0201','single_choice',0.45,'在某一变化过程中，数值发生变化的量叫？','[{"key": "A", "text": "变量"}, {"key": "B", "text": "常量"}, {"key": "C", "text": "参数"}, {"key": "D", "text": "系数"}]','A','变量定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0202-1','math','初中',9,'jkp-0202','single_choice',0.55,'函数 y=2x 中，自变量是？','[{"key": "A", "text": "x"}, {"key": "B", "text": "y"}, {"key": "C", "text": "2"}, {"key": "D", "text": "0"}]','A','自变量 x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0203-1','math','初中',9,'jkp-0203','single_choice',0.65,'函数 y = 1/(x-2) 的自变量取值范围是？','[{"key": "A", "text": "x ≠ 2"}, {"key": "B", "text": "x > 2"}, {"key": "C", "text": "x ≥ 2"}, {"key": "D", "text": "x ≠ 0"}]','A','分式分母不为 0：x≠2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0204-1','math','初中',9,'jkp-0204','single_choice',0.75,'下列不是函数表示方法的是？','[{"key": "A", "text": "解方程法"}, {"key": "B", "text": "解析式法"}, {"key": "C", "text": "列表法"}, {"key": "D", "text": "图像法"}]','A','函数三种表示：解析式、列表、图像','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0205-1','math','初中',9,'jkp-0205','single_choice',0.35,'画函数图像的步骤是？','[{"key": "A", "text": "列表、描点、连线"}, {"key": "B", "text": "连线、描点、列表"}, {"key": "C", "text": "描点、列表、连线"}, {"key": "D", "text": "列表、连线、描点"}]','A','画图三步：列表、描点、连线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0206-1','math','初中',9,'jkp-0206','single_choice',0.45,'y = 4x (k≠0) 是？函数','[{"key": "A", "text": "正比例函数"}, {"key": "B", "text": "反比例函数"}, {"key": "C", "text": "二次函数"}, {"key": "D", "text": "常量函数"}]','A','y=kx 是正比例函数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0207-1','math','初中',9,'jkp-0207','single_choice',0.55,'正比例函数 y=kx 的图像是？','[{"key": "A", "text": "过原点的直线"}, {"key": "B", "text": "不过原点的直线"}, {"key": "C", "text": "抛物线"}, {"key": "D", "text": "双曲线"}]','A','正比例函数图像过原点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0208-1','math','初中',9,'jkp-0208','single_choice',0.65,'正比例函数 y=5x，y 随 x 增大而？','[{"key": "A", "text": "增大"}, {"key": "B", "text": "减小"}, {"key": "C", "text": "不变"}, {"key": "D", "text": "先增后减"}]','A','k=5>0，y 随 x 增大而增大','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0209-1','math','初中',9,'jkp-0209','single_choice',0.75,'y = 2x + 1 是？函数','[{"key": "A", "text": "一次函数"}, {"key": "B", "text": "正比例函数"}, {"key": "C", "text": "二次函数"}, {"key": "D", "text": "反比例函数"}]','A','y=kx+b(k≠0) 是一次函数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0210-1','math','初中',9,'jkp-0210','single_choice',0.35,'一次函数 y=3x+5 与 y 轴交于点？','[{"key": "A", "text": "(0,5)"}, {"key": "B", "text": "(5,0)"}, {"key": "C", "text": "(0,0)"}, {"key": "D", "text": "(1,8)"}]','A','令 x=0，y=5 → (0,5)（截距 5）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0211-1','math','初中',9,'jkp-0211','single_choice',0.45,'一次函数 y=3x+1，y 随 x 增大而？','[{"key": "A", "text": "增大"}, {"key": "B", "text": "减小"}, {"key": "C", "text": "不变"}, {"key": "D", "text": "无法确定"}]','A','k=3>0 → y 随 x 增大而增大','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0212-1','math','初中',9,'jkp-0212','single_choice',0.55,'一次函数 y=2x+3 的图像经过哪些象限？','[{"key": "A", "text": "一、二、三"}, {"key": "B", "text": "一、二、四"}, {"key": "C", "text": "一、三、四"}, {"key": "D", "text": "二、三、四"}]','A','k>0、b>0 → 过一、二、三象限','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0213-1','math','初中',9,'jkp-0213','single_choice',0.65,'已知直线过 (0,3) 和 (1,5)，用待定系数法：y=kx+3，代入 (1,5) 得 k=？','[{"key": "A", "text": "2"}, {"key": "B", "text": "3"}, {"key": "C", "text": "5"}, {"key": "D", "text": "1"}]','A','5=k+3 → k=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0214-1','math','初中',9,'jkp-0214','single_choice',0.75,'一次函数 y=5x+3 与 x 轴交点横坐标 = ？','[{"key": "A", "text": "-3/5"}, {"key": "B", "text": "3/5"}, {"key": "C", "text": "3"}, {"key": "D", "text": "-3"}]','A','令 y=0：x=-3/5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0215-1','math','初中',9,'jkp-0215','single_choice',0.35,'与 y=5x+1 平行的直线是？','[{"key": "A", "text": "y=5x+3"}, {"key": "B", "text": "y=-5x+1"}, {"key": "C", "text": "y=6x+1"}, {"key": "D", "text": "y=5x²"}]','A','平行条件：k 相同、b 不同 → y=5x+3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0216-1','math','初中',9,'jkp-0216','single_choice',0.45,'一次函数 y=2x-4 与 x 轴交点的横坐标即方程？的解','[{"key": "A", "text": "2x-4=0"}, {"key": "B", "text": "2x+4=0"}, {"key": "C", "text": "x-4=0"}, {"key": "D", "text": "2x=4"}]','A','y=0 → 2x-4=0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0217-1','math','初中',9,'jkp-0217','single_choice',0.55,'一次函数 y=2x-4，y>0 时即 2x-4>0 → x 的取值范围？','[{"key": "A", "text": "x > 2"}, {"key": "B", "text": "x < 2"}, {"key": "C", "text": "x > 4"}, {"key": "D", "text": "x < 4"}]','A','2x-4>0 → x>2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0218-1','math','初中',9,'jkp-0218','single_choice',0.65,'两条一次函数图像的交点坐标是？的解','[{"key": "A", "text": "对应二元一次方程组"}, {"key": "B", "text": "一元一次方程"}, {"key": "C", "text": "一元二次方程"}, {"key": "D", "text": "不等式"}]','A','交点坐标 = 方程组解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0219-1','math','初中',9,'jkp-0219','single_choice',0.75,'一次函数应用：y=3x+2 表示每月固定 2 元 + 每件 3 元，买 5 件费用 = ？','[{"key": "A", "text": "17"}, {"key": "B", "text": "15"}, {"key": "C", "text": "10"}, {"key": "D", "text": "20"}]','A','y=3×5+2=17','template-j','approved','通用');