-- 第11章 全等三角形 补题（9学期, 知识点 158-170）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0158-1','math','初中',9,'jkp-0158','single_choice',0.65,'能够完全重合的两个图形叫？','[{"key": "A", "text": "全等形"}, {"key": "B", "text": "相似形"}, {"key": "C", "text": "等积形"}, {"key": "D", "text": "对称形"}]','A','全等形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0158-2','math','初中',9,'jkp-0158','single_choice',0.65,'能够完全重合的两个图形叫？','[{"key": "B", "text": "相似形"}, {"key": "D", "text": "对称形"}, {"key": "A", "text": "全等形"}, {"key": "C", "text": "等积形"}]','A','全等形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0158-3','math','初中',9,'jkp-0158','single_choice',0.65,'能够完全重合的两个图形叫？','[{"key": "B", "text": "相似形"}, {"key": "A", "text": "全等形"}, {"key": "D", "text": "对称形"}, {"key": "C", "text": "等积形"}]','A','全等形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0159-1','math','初中',9,'jkp-0159','single_choice',0.75,'全等三角形中，互相重合的顶点叫？','[{"key": "A", "text": "对应顶点"}, {"key": "B", "text": "重心"}, {"key": "C", "text": "外心"}, {"key": "D", "text": "内心"}]','A','对应顶点定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0159-2','math','初中',9,'jkp-0159','single_choice',0.75,'全等三角形中，互相重合的顶点叫？','[{"key": "A", "text": "对应顶点"}, {"key": "D", "text": "内心"}, {"key": "C", "text": "外心"}, {"key": "B", "text": "重心"}]','A','对应顶点定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0159-3','math','初中',9,'jkp-0159','single_choice',0.75,'全等三角形中，互相重合的顶点叫？','[{"key": "A", "text": "对应顶点"}, {"key": "C", "text": "外心"}, {"key": "D", "text": "内心"}, {"key": "B", "text": "重心"}]','A','对应顶点定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0160-1','math','初中',9,'jkp-0160','single_choice',0.35,'△ABC≌△DEF，AB=8，则 DE = ？','[{"key": "A", "text": "8"}, {"key": "B", "text": "16"}, {"key": "C", "text": "4.0"}, {"key": "D", "text": "无法确定"}]','A','全等三角形对应边相等：DE=AB=8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0160-2','math','初中',9,'jkp-0160','single_choice',0.35,'△ABC≌△DEF，AB=9，则 DE = ？','[{"key": "A", "text": "9"}, {"key": "B", "text": "18"}, {"key": "C", "text": "4.5"}, {"key": "D", "text": "无法确定"}]','A','全等三角形对应边相等：DE=AB=9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0160-3','math','初中',9,'jkp-0160','single_choice',0.35,'△ABC≌△DEF，AB=7，则 DE = ？','[{"key": "A", "text": "7"}, {"key": "B", "text": "14"}, {"key": "C", "text": "3.5"}, {"key": "D", "text": "无法确定"}]','A','全等三角形对应边相等：DE=AB=7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0161-1','math','初中',9,'jkp-0161','single_choice',0.45,'三边对应相等的两个三角形全等，简称？','[{"key": "A", "text": "SSS"}, {"key": "B", "text": "SAS"}, {"key": "C", "text": "ASA"}, {"key": "D", "text": "HL"}]','A','SSS：边边边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0161-2','math','初中',9,'jkp-0161','single_choice',0.45,'三边对应相等的两个三角形全等，简称？','[{"key": "A", "text": "SSS"}, {"key": "D", "text": "HL"}, {"key": "B", "text": "SAS"}, {"key": "C", "text": "ASA"}]','A','SSS：边边边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0161-3','math','初中',9,'jkp-0161','single_choice',0.45,'三边对应相等的两个三角形全等，简称？','[{"key": "A", "text": "SSS"}, {"key": "C", "text": "ASA"}, {"key": "D", "text": "HL"}, {"key": "B", "text": "SAS"}]','A','SSS：边边边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0162-1','math','初中',9,'jkp-0162','single_choice',0.55,'两边及夹角对应相等的两个三角形全等，简称？','[{"key": "A", "text": "SAS"}, {"key": "B", "text": "SSS"}, {"key": "C", "text": "AAS"}, {"key": "D", "text": "AAA"}]','A','SAS：边角边（注意夹角）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0162-2','math','初中',9,'jkp-0162','single_choice',0.55,'两边及夹角对应相等的两个三角形全等，简称？','[{"key": "B", "text": "SSS"}, {"key": "A", "text": "SAS"}, {"key": "D", "text": "AAA"}, {"key": "C", "text": "AAS"}]','A','SAS：边角边（注意夹角）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0162-3','math','初中',9,'jkp-0162','single_choice',0.55,'两边及夹角对应相等的两个三角形全等，简称？','[{"key": "B", "text": "SSS"}, {"key": "D", "text": "AAA"}, {"key": "C", "text": "AAS"}, {"key": "A", "text": "SAS"}]','A','SAS：边角边（注意夹角）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0163-1','math','初中',9,'jkp-0163','single_choice',0.65,'两角及夹边对应相等 → 全等，简称？','[{"key": "A", "text": "ASA"}, {"key": "B", "text": "SAS"}, {"key": "C", "text": "SSS"}, {"key": "D", "text": "HL"}]','A','ASA：角边角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0163-2','math','初中',9,'jkp-0163','single_choice',0.65,'两角及夹边对应相等 → 全等，简称？','[{"key": "C", "text": "SSS"}, {"key": "D", "text": "HL"}, {"key": "A", "text": "ASA"}, {"key": "B", "text": "SAS"}]','A','ASA：角边角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0163-3','math','初中',9,'jkp-0163','single_choice',0.65,'两角及夹边对应相等 → 全等，简称？','[{"key": "C", "text": "SSS"}, {"key": "B", "text": "SAS"}, {"key": "A", "text": "ASA"}, {"key": "D", "text": "HL"}]','A','ASA：角边角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0164-1','math','初中',9,'jkp-0164','single_choice',0.75,'两角及其中一角的对边对应相等 → 全等，简称？','[{"key": "A", "text": "AAS"}, {"key": "B", "text": "ASA"}, {"key": "C", "text": "SAS"}, {"key": "D", "text": "SSS"}]','A','AAS：角角边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0164-2','math','初中',9,'jkp-0164','single_choice',0.75,'两角及其中一角的对边对应相等 → 全等，简称？','[{"key": "D", "text": "SSS"}, {"key": "B", "text": "ASA"}, {"key": "C", "text": "SAS"}, {"key": "A", "text": "AAS"}]','A','AAS：角角边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0165-1','math','初中',9,'jkp-0165','single_choice',0.35,'直角三角形斜边和一条直角边对应相等 → 全等，简称？','[{"key": "A", "text": "HL"}, {"key": "B", "text": "SSA"}, {"key": "C", "text": "AAA"}, {"key": "D", "text": "SSS"}]','A','HL：斜边直角边（只适用于直角三角形）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0165-2','math','初中',9,'jkp-0165','single_choice',0.35,'直角三角形斜边和一条直角边对应相等 → 全等，简称？','[{"key": "B", "text": "SSA"}, {"key": "A", "text": "HL"}, {"key": "D", "text": "SSS"}, {"key": "C", "text": "AAA"}]','A','HL：斜边直角边（只适用于直角三角形）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0165-3','math','初中',9,'jkp-0165','single_choice',0.35,'直角三角形斜边和一条直角边对应相等 → 全等，简称？','[{"key": "C", "text": "AAA"}, {"key": "B", "text": "SSA"}, {"key": "A", "text": "HL"}, {"key": "D", "text": "SSS"}]','A','HL：斜边直角边（只适用于直角三角形）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0166-1','math','初中',9,'jkp-0166','single_choice',0.45,'下列不能判定三角形全等的是？','[{"key": "A", "text": "SSA"}, {"key": "B", "text": "SSS"}, {"key": "C", "text": "AAS"}, {"key": "D", "text": "HL"}]','A','SSA 不能判定全等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0166-2','math','初中',9,'jkp-0166','single_choice',0.45,'下列不能判定三角形全等的是？','[{"key": "D", "text": "HL"}, {"key": "A", "text": "SSA"}, {"key": "C", "text": "AAS"}, {"key": "B", "text": "SSS"}]','A','SSA 不能判定全等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0166-3','math','初中',9,'jkp-0166','single_choice',0.45,'下列不能判定三角形全等的是？','[{"key": "C", "text": "AAS"}, {"key": "A", "text": "SSA"}, {"key": "B", "text": "SSS"}, {"key": "D", "text": "HL"}]','A','SSA 不能判定全等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0167-1','math','初中',9,'jkp-0167','single_choice',0.55,'证明三角形全等的一般书写顺序是？','[{"key": "A", "text": "先写已知和条件，再写判定依据"}, {"key": "B", "text": "直接写结论"}, {"key": "C", "text": "只写图形"}, {"key": "D", "text": "随意写"}]','A','规范书写：已知 → 推导 → 判定 → 结论','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0167-2','math','初中',9,'jkp-0167','single_choice',0.55,'证明三角形全等的一般书写顺序是？','[{"key": "B", "text": "直接写结论"}, {"key": "A", "text": "先写已知和条件，再写判定依据"}, {"key": "D", "text": "随意写"}, {"key": "C", "text": "只写图形"}]','A','规范书写：已知 → 推导 → 判定 → 结论','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0167-3','math','初中',9,'jkp-0167','single_choice',0.55,'证明三角形全等的一般书写顺序是？','[{"key": "D", "text": "随意写"}, {"key": "B", "text": "直接写结论"}, {"key": "A", "text": "先写已知和条件，再写判定依据"}, {"key": "C", "text": "只写图形"}]','A','规范书写：已知 → 推导 → 判定 → 结论','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0168-1','math','初中',9,'jkp-0168','single_choice',0.65,'OC 平分 ∠AOB，PC⊥OA 于 C，PC=5，则 P 到 OB 的距离 = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "10"}, {"key": "C", "text": "2.5"}, {"key": "D", "text": "0"}]','A','角平分线上点到角两边距离相等 = 5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0168-2','math','初中',9,'jkp-0168','single_choice',0.65,'OC 平分 ∠AOB，PC⊥OA 于 C，PC=4，则 P 到 OB 的距离 = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "8"}, {"key": "C", "text": "2.0"}, {"key": "D", "text": "0"}]','A','角平分线上点到角两边距离相等 = 4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0168-3','math','初中',9,'jkp-0168','single_choice',0.65,'OC 平分 ∠AOB，PC⊥OA 于 C，PC=8，则 P 到 OB 的距离 = ？','[{"key": "A", "text": "8"}, {"key": "B", "text": "16"}, {"key": "C", "text": "4.0"}, {"key": "D", "text": "0"}]','A','角平分线上点到角两边距离相等 = 8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0169-1','math','初中',9,'jkp-0169','single_choice',0.75,'到角两边距离相等的点在？上','[{"key": "A", "text": "角的平分线"}, {"key": "B", "text": "角的内部"}, {"key": "C", "text": "角的边上"}, {"key": "D", "text": "三角形外"}]','A','角平分线判定定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0169-2','math','初中',9,'jkp-0169','single_choice',0.75,'到角两边距离相等的点在？上','[{"key": "D", "text": "三角形外"}, {"key": "B", "text": "角的内部"}, {"key": "A", "text": "角的平分线"}, {"key": "C", "text": "角的边上"}]','A','角平分线判定定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0169-3','math','初中',9,'jkp-0169','single_choice',0.75,'到角两边距离相等的点在？上','[{"key": "B", "text": "角的内部"}, {"key": "A", "text": "角的平分线"}, {"key": "D", "text": "三角形外"}, {"key": "C", "text": "角的边上"}]','A','角平分线判定定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0170-1','math','初中',9,'jkp-0170','single_choice',0.35,'尺规作角平分线的依据是？','[{"key": "A", "text": "SSS（构造全等）"}, {"key": "B", "text": "SAS"}, {"key": "C", "text": "ASA"}, {"key": "D", "text": "HL"}]','A','尺规作角平分线用 SSS 证全等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0170-2','math','初中',9,'jkp-0170','single_choice',0.35,'尺规作角平分线的依据是？','[{"key": "B", "text": "SAS"}, {"key": "C", "text": "ASA"}, {"key": "A", "text": "SSS（构造全等）"}, {"key": "D", "text": "HL"}]','A','尺规作角平分线用 SSS 证全等','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0170-3','math','初中',9,'jkp-0170','single_choice',0.35,'尺规作角平分线的依据是？','[{"key": "D", "text": "HL"}, {"key": "A", "text": "SSS（构造全等）"}, {"key": "B", "text": "SAS"}, {"key": "C", "text": "ASA"}]','A','尺规作角平分线用 SSS 证全等','template-j','approved','通用');