-- 第26章 二次函数 补题（12学期, 知识点 375-396）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0375-1','math','初中',12,'jkp-0375','single_choice',0.35,'下列是二次函数的是？','[{"key": "A", "text": "y = x² + 2x + 1"}, {"key": "B", "text": "y = 2x + 1"}, {"key": "C", "text": "y = 2/x"}, {"key": "D", "text": "y = x³"}]','A','y=ax²+bx+c(a≠0) 是二次函数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0375-2','math','初中',12,'jkp-0375','single_choice',0.35,'下列是二次函数的是？','[{"key": "C", "text": "y = 2/x"}, {"key": "A", "text": "y = x² + 2x + 1"}, {"key": "D", "text": "y = x³"}, {"key": "B", "text": "y = 2x + 1"}]','A','y=ax²+bx+c(a≠0) 是二次函数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0375-3','math','初中',12,'jkp-0375','single_choice',0.35,'下列是二次函数的是？','[{"key": "D", "text": "y = x³"}, {"key": "B", "text": "y = 2x + 1"}, {"key": "C", "text": "y = 2/x"}, {"key": "A", "text": "y = x² + 2x + 1"}]','A','y=ax²+bx+c(a≠0) 是二次函数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0376-1','math','初中',12,'jkp-0376','single_choice',0.45,'y = 1x² 的图像开口？','[{"key": "A", "text": "向上"}, {"key": "B", "text": "向下"}, {"key": "C", "text": "向左"}, {"key": "D", "text": "向右"}]','A','a=1>0 → 开口向上','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0376-2','math','初中',12,'jkp-0376','single_choice',0.45,'y = 3x² 的图像开口？','[{"key": "A", "text": "向上"}, {"key": "B", "text": "向下"}, {"key": "C", "text": "向左"}, {"key": "D", "text": "向右"}]','A','a=3>0 → 开口向上','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0376-3','math','初中',12,'jkp-0376','single_choice',0.45,'y = 1x² 的图像开口？','[{"key": "A", "text": "向上"}, {"key": "D", "text": "向右"}, {"key": "C", "text": "向左"}, {"key": "B", "text": "向下"}]','A','a=1>0 → 开口向上','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0377-1','math','初中',12,'jkp-0377','single_choice',0.55,'y = x² 向上平移 4 个单位 → y = ？','[{"key": "A", "text": "x² + 4"}, {"key": "B", "text": "x² - 4"}, {"key": "C", "text": "(x+4)²"}, {"key": "D", "text": "(x-4)²"}]','A','上加下减：y=x²+4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0377-2','math','初中',12,'jkp-0377','single_choice',0.55,'y = x² 向上平移 2 个单位 → y = ？','[{"key": "A", "text": "x² + 2"}, {"key": "B", "text": "x² - 2"}, {"key": "C", "text": "(x+2)²"}, {"key": "D", "text": "(x-2)²"}]','A','上加下减：y=x²+2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0377-3','math','初中',12,'jkp-0377','single_choice',0.55,'y = x² 向上平移 3 个单位 → y = ？','[{"key": "A", "text": "x² + 3"}, {"key": "B", "text": "x² - 3"}, {"key": "C", "text": "(x+3)²"}, {"key": "D", "text": "(x-3)²"}]','A','上加下减：y=x²+3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0378-1','math','初中',12,'jkp-0378','single_choice',0.65,'y = x² 向右平移 4 个单位 → y = ？','[{"key": "A", "text": "(x-4)²"}, {"key": "B", "text": "(x+4)²"}, {"key": "C", "text": "x² + 4"}, {"key": "D", "text": "x² - 4"}]','A','左加右减：y=(x-4)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0378-2','math','初中',12,'jkp-0378','single_choice',0.65,'y = x² 向右平移 3 个单位 → y = ？','[{"key": "A", "text": "(x-3)²"}, {"key": "B", "text": "(x+3)²"}, {"key": "C", "text": "x² + 3"}, {"key": "D", "text": "x² - 3"}]','A','左加右减：y=(x-3)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0378-3','math','初中',12,'jkp-0378','single_choice',0.65,'y = x² 向右平移 5 个单位 → y = ？','[{"key": "A", "text": "(x-5)²"}, {"key": "B", "text": "(x+5)²"}, {"key": "C", "text": "x² + 5"}, {"key": "D", "text": "x² - 5"}]','A','左加右减：y=(x-5)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0379-1','math','初中',12,'jkp-0379','single_choice',0.75,'y = (x-2)² + 5 的顶点坐标是？','[{"key": "A", "text": "(2,5)"}, {"key": "B", "text": "(-2,5)"}, {"key": "C", "text": "(2,-5)"}, {"key": "D", "text": "(-2,-5)"}]','A','顶点式 y=(x-h)²+k 顶点(h,k)=(2,5)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0379-2','math','初中',12,'jkp-0379','single_choice',0.75,'y = (x-5)² + 2 的顶点坐标是？','[{"key": "A", "text": "(5,2)"}, {"key": "B", "text": "(-5,2)"}, {"key": "C", "text": "(5,-2)"}, {"key": "D", "text": "(-5,-2)"}]','A','顶点式 y=(x-h)²+k 顶点(h,k)=(5,2)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0379-3','math','初中',12,'jkp-0379','single_choice',0.75,'y = (x-4)² + 3 的顶点坐标是？','[{"key": "A", "text": "(4,3)"}, {"key": "B", "text": "(-4,3)"}, {"key": "C", "text": "(4,-3)"}, {"key": "D", "text": "(-4,-3)"}]','A','顶点式 y=(x-h)²+k 顶点(h,k)=(4,3)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0380-1','math','初中',12,'jkp-0380','single_choice',0.35,'y = x² + 8x + 3 配方成 (x+4)² + (3-16) → 常数项 = ？','[{"key": "A", "text": "-13"}, {"key": "B", "text": "16"}, {"key": "C", "text": "19"}, {"key": "D", "text": "3"}]','A','配方：(x+4)²+-13','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0380-2','math','初中',12,'jkp-0380','single_choice',0.35,'y = x² + 6x + 3 配方成 (x+3)² + (3-9) → 常数项 = ？','[{"key": "A", "text": "-6"}, {"key": "B", "text": "9"}, {"key": "C", "text": "12"}, {"key": "D", "text": "3"}]','A','配方：(x+3)²+-6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0380-3','math','初中',12,'jkp-0380','single_choice',0.35,'y = x² + 4x + 3 配方成 (x+2)² + (3-4) → 常数项 = ？','[{"key": "A", "text": "-1"}, {"key": "B", "text": "4"}, {"key": "C", "text": "7"}, {"key": "D", "text": "3"}]','A','配方：(x+2)²+-1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0381-1','math','初中',12,'jkp-0381','single_choice',0.45,'y = x² + 8x + 1 的对称轴 x = -b/2a = ？','[{"key": "A", "text": "-4"}, {"key": "B", "text": "4"}, {"key": "C", "text": "-8"}, {"key": "D", "text": "8"}]','A','对称轴 x=-8/(2×1)=-4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0381-2','math','初中',12,'jkp-0381','single_choice',0.45,'y = x² + 4x + 1 的对称轴 x = -b/2a = ？','[{"key": "A", "text": "-2"}, {"key": "B", "text": "2"}, {"key": "C", "text": "-4"}, {"key": "D", "text": "4"}]','A','对称轴 x=-4/(2×1)=-2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0381-3','math','初中',12,'jkp-0381','single_choice',0.45,'y = x² + 8x + 1 的对称轴 x = -b/2a = ？','[{"key": "C", "text": "-8"}, {"key": "A", "text": "-4"}, {"key": "D", "text": "8"}, {"key": "B", "text": "4"}]','A','对称轴 x=-8/(2×1)=-4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0382-1','math','初中',12,'jkp-0382','single_choice',0.55,'y = x² - 6x + 9 的顶点纵坐标 = (4ac-b²)/4a = ？','[{"key": "A", "text": "0"}, {"key": "B", "text": "3"}, {"key": "C", "text": "-3"}, {"key": "D", "text": "9"}]','A','y=(x-3)² → 顶点纵坐标 0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0382-2','math','初中',12,'jkp-0382','single_choice',0.55,'y = x² - 8x + 16 的顶点纵坐标 = (4ac-b²)/4a = ？','[{"key": "A", "text": "0"}, {"key": "B", "text": "4"}, {"key": "C", "text": "-4"}, {"key": "D", "text": "16"}]','A','y=(x-4)² → 顶点纵坐标 0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0382-3','math','初中',12,'jkp-0382','single_choice',0.55,'y = x² - 4x + 4 的顶点纵坐标 = (4ac-b²)/4a = ？','[{"key": "A", "text": "0"}, {"key": "B", "text": "2"}, {"key": "C", "text": "-2"}, {"key": "D", "text": "4"}]','A','y=(x-2)² → 顶点纵坐标 0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0383-1','math','初中',12,'jkp-0383','single_choice',0.65,'二次函数 y = -2x² 的开口方向和大小？','[{"key": "A", "text": "开口向下，比 y=x² 窄"}, {"key": "B", "text": "开口向上，比 y=x² 窄"}, {"key": "C", "text": "开口向下，比 y=x² 宽"}, {"key": "D", "text": "开口向上"}]','A','a=-2<0 开口向下，|a|>1 更窄','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0383-2','math','初中',12,'jkp-0383','single_choice',0.65,'二次函数 y = -2x² 的开口方向和大小？','[{"key": "A", "text": "开口向下，比 y=x² 窄"}, {"key": "D", "text": "开口向上"}, {"key": "B", "text": "开口向上，比 y=x² 窄"}, {"key": "C", "text": "开口向下，比 y=x² 宽"}]','A','a=-2<0 开口向下，|a|>1 更窄','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0384-1','math','初中',12,'jkp-0384','single_choice',0.75,'y = ax²+bx+c 中 a、b 同号，对称轴在 y 轴？','[{"key": "A", "text": "左侧"}, {"key": "B", "text": "右侧"}, {"key": "C", "text": "上"}, {"key": "D", "text": "下"}]','A','左同右异：a、b 同号 → 对称轴在左','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0384-2','math','初中',12,'jkp-0384','single_choice',0.75,'y = ax²+bx+c 中 a、b 同号，对称轴在 y 轴？','[{"key": "B", "text": "右侧"}, {"key": "D", "text": "下"}, {"key": "C", "text": "上"}, {"key": "A", "text": "左侧"}]','A','左同右异：a、b 同号 → 对称轴在左','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0384-3','math','初中',12,'jkp-0384','single_choice',0.75,'y = ax²+bx+c 中 a、b 同号，对称轴在 y 轴？','[{"key": "A", "text": "左侧"}, {"key": "D", "text": "下"}, {"key": "B", "text": "右侧"}, {"key": "C", "text": "上"}]','A','左同右异：a、b 同号 → 对称轴在左','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0385-1','math','初中',12,'jkp-0385','single_choice',0.35,'y = x² + 2x + 5 与 y 轴交点纵坐标 = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "2"}, {"key": "C", "text": "1"}, {"key": "D", "text": "0"}]','A','c=5 → 与 y 轴交点 (0,5)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0385-2','math','初中',12,'jkp-0385','single_choice',0.35,'y = x² + 2x + 5 与 y 轴交点纵坐标 = ？','[{"key": "B", "text": "2"}, {"key": "D", "text": "0"}, {"key": "C", "text": "1"}, {"key": "A", "text": "5"}]','A','c=5 → 与 y 轴交点 (0,5)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0385-3','math','初中',12,'jkp-0385','single_choice',0.35,'y = x² + 2x + 5 与 y 轴交点纵坐标 = ？','[{"key": "A", "text": "5"}, {"key": "C", "text": "1"}, {"key": "D", "text": "0"}, {"key": "B", "text": "2"}]','A','c=5 → 与 y 轴交点 (0,5)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0386-1','math','初中',12,'jkp-0386','single_choice',0.45,'y = x² - 4x + 3，Δ = 16-12 = 4 > 0，与 x 轴交点个数？','[{"key": "A", "text": "2 个"}, {"key": "B", "text": "1 个"}, {"key": "C", "text": "0 个"}, {"key": "D", "text": "3 个"}]','A','Δ>0 → 两个交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0386-2','math','初中',12,'jkp-0386','single_choice',0.45,'y = x² - 4x + 3，Δ = 16-12 = 4 > 0，与 x 轴交点个数？','[{"key": "B", "text": "1 个"}, {"key": "A", "text": "2 个"}, {"key": "D", "text": "3 个"}, {"key": "C", "text": "0 个"}]','A','Δ>0 → 两个交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0387-1','math','初中',12,'jkp-0387','single_choice',0.55,'抛物线与 x 轴交于 (4,0)、(4,0)，交点式 y = a(x-4)(x-4)，顶点横坐标 = ？','[{"key": "A", "text": "4.0"}, {"key": "B", "text": "4"}, {"key": "C", "text": "4"}, {"key": "D", "text": "16"}]','A','顶点横坐标 = 两根中点 = (4+4)/2 = 4.0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0387-2','math','初中',12,'jkp-0387','single_choice',0.55,'抛物线与 x 轴交于 (2,0)、(3,0)，交点式 y = a(x-2)(x-3)，顶点横坐标 = ？','[{"key": "A", "text": "2.5"}, {"key": "B", "text": "2"}, {"key": "C", "text": "3"}, {"key": "D", "text": "6"}]','A','顶点横坐标 = 两根中点 = (2+3)/2 = 2.5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0387-3','math','初中',12,'jkp-0387','single_choice',0.55,'抛物线与 x 轴交于 (3,0)、(3,0)，交点式 y = a(x-3)(x-3)，顶点横坐标 = ？','[{"key": "A", "text": "3.0"}, {"key": "B", "text": "3"}, {"key": "C", "text": "3"}, {"key": "D", "text": "9"}]','A','顶点横坐标 = 两根中点 = (3+3)/2 = 3.0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0388-1','math','初中',12,'jkp-0388','single_choice',0.65,'已知抛物线上三点坐标求解析式，用？','[{"key": "A", "text": "一般式（待定系数法）"}, {"key": "B", "text": "直接看"}, {"key": "C", "text": "求导"}, {"key": "D", "text": "积分"}]','A','三点 → 一般式待定系数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0388-2','math','初中',12,'jkp-0388','single_choice',0.65,'已知抛物线上三点坐标求解析式，用？','[{"key": "C", "text": "求导"}, {"key": "B", "text": "直接看"}, {"key": "A", "text": "一般式（待定系数法）"}, {"key": "D", "text": "积分"}]','A','三点 → 一般式待定系数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0388-3','math','初中',12,'jkp-0388','single_choice',0.65,'已知抛物线上三点坐标求解析式，用？','[{"key": "D", "text": "积分"}, {"key": "C", "text": "求导"}, {"key": "A", "text": "一般式（待定系数法）"}, {"key": "B", "text": "直接看"}]','A','三点 → 一般式待定系数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0389-1','math','初中',12,'jkp-0389','single_choice',0.75,'y = x² - 4x，x > 2 时 y 随 x 增大而？','[{"key": "A", "text": "增大"}, {"key": "B", "text": "减小"}, {"key": "C", "text": "不变"}, {"key": "D", "text": "无法确定"}]','A','对称轴 x=2，开口向上，x>2 递增','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0389-2','math','初中',12,'jkp-0389','single_choice',0.75,'y = x² - 4x，x > 2 时 y 随 x 增大而？','[{"key": "D", "text": "无法确定"}, {"key": "B", "text": "减小"}, {"key": "C", "text": "不变"}, {"key": "A", "text": "增大"}]','A','对称轴 x=2，开口向上，x>2 递增','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0389-3','math','初中',12,'jkp-0389','single_choice',0.75,'y = x² - 4x，x > 2 时 y 随 x 增大而？','[{"key": "A", "text": "增大"}, {"key": "D", "text": "无法确定"}, {"key": "C", "text": "不变"}, {"key": "B", "text": "减小"}]','A','对称轴 x=2，开口向上，x>2 递增','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0390-1','math','初中',12,'jkp-0390','single_choice',0.35,'y = x² - 4x + 5 = (x-2)² + 1，最小值 = ？','[{"key": "A", "text": "1"}, {"key": "B", "text": "2"}, {"key": "C", "text": "5"}, {"key": "D", "text": "-1"}]','A','顶点 (2,1)，开口向上 → 最小值 1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0390-2','math','初中',12,'jkp-0390','single_choice',0.35,'y = x² - 4x + 5 = (x-2)² + 1，最小值 = ？','[{"key": "B", "text": "2"}, {"key": "D", "text": "-1"}, {"key": "A", "text": "1"}, {"key": "C", "text": "5"}]','A','顶点 (2,1)，开口向上 → 最小值 1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0390-3','math','初中',12,'jkp-0390','single_choice',0.35,'y = x² - 4x + 5 = (x-2)² + 1，最小值 = ？','[{"key": "C", "text": "5"}, {"key": "A", "text": "1"}, {"key": "B", "text": "2"}, {"key": "D", "text": "-1"}]','A','顶点 (2,1)，开口向上 → 最小值 1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0391-1','math','初中',12,'jkp-0391','single_choice',0.45,'y = x² 在区间 [1,3] 上最大值 = ？','[{"key": "A", "text": "9"}, {"key": "B", "text": "1"}, {"key": "C", "text": "3"}, {"key": "D", "text": "6"}]','A','x=3 时最大 y=9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0391-2','math','初中',12,'jkp-0391','single_choice',0.45,'y = x² 在区间 [1,3] 上最大值 = ？','[{"key": "D", "text": "6"}, {"key": "B", "text": "1"}, {"key": "C", "text": "3"}, {"key": "A", "text": "9"}]','A','x=3 时最大 y=9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0391-3','math','初中',12,'jkp-0391','single_choice',0.45,'y = x² 在区间 [1,3] 上最大值 = ？','[{"key": "A", "text": "9"}, {"key": "D", "text": "6"}, {"key": "C", "text": "3"}, {"key": "B", "text": "1"}]','A','x=3 时最大 y=9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0392-1','math','初中',12,'jkp-0392','single_choice',0.55,'抛物线 y = x² - 4x + 3 与 x 轴交点即方程？的根','[{"key": "A", "text": "x²-4x+3=0"}, {"key": "B", "text": "x²+4x+3=0"}, {"key": "C", "text": "x²-4x=0"}, {"key": "D", "text": "x-4=0"}]','A','y=0 → x²-4x+3=0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0392-2','math','初中',12,'jkp-0392','single_choice',0.55,'抛物线 y = x² - 4x + 3 与 x 轴交点即方程？的根','[{"key": "C", "text": "x²-4x=0"}, {"key": "A", "text": "x²-4x+3=0"}, {"key": "D", "text": "x-4=0"}, {"key": "B", "text": "x²+4x+3=0"}]','A','y=0 → x²-4x+3=0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0392-3','math','初中',12,'jkp-0392','single_choice',0.55,'抛物线 y = x² - 4x + 3 与 x 轴交点即方程？的根','[{"key": "D", "text": "x-4=0"}, {"key": "C", "text": "x²-4x=0"}, {"key": "B", "text": "x²+4x+3=0"}, {"key": "A", "text": "x²-4x+3=0"}]','A','y=0 → x²-4x+3=0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0393-1','math','初中',12,'jkp-0393','single_choice',0.65,'抛物线 y = x² - 4x + 3 在 x 轴下方 ⇔ 不等式？','[{"key": "A", "text": "x²-4x+3 < 0"}, {"key": "B", "text": "x²-4x+3 > 0"}, {"key": "C", "text": "x²-4x+3 = 0"}, {"key": "D", "text": "x²-4x+3 ≥ 0"}]','A','图像在 x 轴下方 → y<0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0393-2','math','初中',12,'jkp-0393','single_choice',0.65,'抛物线 y = x² - 4x + 3 在 x 轴下方 ⇔ 不等式？','[{"key": "C", "text": "x²-4x+3 = 0"}, {"key": "D", "text": "x²-4x+3 ≥ 0"}, {"key": "B", "text": "x²-4x+3 > 0"}, {"key": "A", "text": "x²-4x+3 < 0"}]','A','图像在 x 轴下方 → y<0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0393-3','math','初中',12,'jkp-0393','single_choice',0.65,'抛物线 y = x² - 4x + 3 在 x 轴下方 ⇔ 不等式？','[{"key": "B", "text": "x²-4x+3 > 0"}, {"key": "D", "text": "x²-4x+3 ≥ 0"}, {"key": "C", "text": "x²-4x+3 = 0"}, {"key": "A", "text": "x²-4x+3 < 0"}]','A','图像在 x 轴下方 → y<0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0394-1','math','初中',12,'jkp-0394','single_choice',0.75,'利润最大化问题：利润 = 单件利润 × 销量，用二次函数求最值的方法是？','[{"key": "A", "text": "求顶点（配方法/公式）"}, {"key": "B", "text": "求根"}, {"key": "C", "text": "求交点"}, {"key": "D", "text": "求渐近线"}]','A','最大利润 → 二次函数顶点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0395-1','math','初中',12,'jkp-0395','single_choice',0.35,'下列对「二次函数实际应用：最大面积」的理解正确的是？','[{"key": "A", "text": "属于初中数学核心内容"}, {"key": "B", "text": "不属于初中数学"}, {"key": "C", "text": "与本单元无关"}, {"key": "D", "text": "是超纲内容"}]','A','二次函数实际应用：最大面积 是人教版初中数学的正式知识点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0395-2','math','初中',12,'jkp-0395','single_choice',0.35,'下列对「二次函数实际应用：最大面积」的理解正确的是？','[{"key": "B", "text": "不属于初中数学"}, {"key": "D", "text": "是超纲内容"}, {"key": "C", "text": "与本单元无关"}, {"key": "A", "text": "属于初中数学核心内容"}]','A','二次函数实际应用：最大面积 是人教版初中数学的正式知识点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0395-3','math','初中',12,'jkp-0395','single_choice',0.35,'下列对「二次函数实际应用：最大面积」的理解正确的是？','[{"key": "C", "text": "与本单元无关"}, {"key": "D", "text": "是超纲内容"}, {"key": "B", "text": "不属于初中数学"}, {"key": "A", "text": "属于初中数学核心内容"}]','A','二次函数实际应用：最大面积 是人教版初中数学的正式知识点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0396-1','math','初中',12,'jkp-0396','single_choice',0.45,'抛物线存在性综合题，判断等腰三角形常用？','[{"key": "A", "text": "分类讨论（三边两两相等）"}, {"key": "B", "text": "只查一个"}, {"key": "C", "text": "画图猜"}, {"key": "D", "text": "不用验证"}]','A','等腰存在性：三边两两相等分类讨论','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0396-2','math','初中',12,'jkp-0396','single_choice',0.45,'抛物线存在性综合题，判断等腰三角形常用？','[{"key": "B", "text": "只查一个"}, {"key": "C", "text": "画图猜"}, {"key": "A", "text": "分类讨论（三边两两相等）"}, {"key": "D", "text": "不用验证"}]','A','等腰存在性：三边两两相等分类讨论','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0396-3','math','初中',12,'jkp-0396','single_choice',0.45,'抛物线存在性综合题，判断等腰三角形常用？','[{"key": "C", "text": "画图猜"}, {"key": "D", "text": "不用验证"}, {"key": "A", "text": "分类讨论（三边两两相等）"}, {"key": "B", "text": "只查一个"}]','A','等腰存在性：三边两两相等分类讨论','template-j','approved','通用');