-- 第15章 整式的乘除与分解因式 补题（9学期, 知识点 220-240）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0220-1','math','初中',9,'jkp-0220','single_choice',0.35,'4^3 × 4^3 = ？','[{"key": "A", "text": "4096"}, {"key": "B", "text": "262144"}, {"key": "C", "text": "128"}, {"key": "D", "text": "1"}]','A','同底数幂相乘指数相加：4^6=4096','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0220-2','math','初中',9,'jkp-0220','single_choice',0.35,'3^4 × 3^4 = ？','[{"key": "A", "text": "6561"}, {"key": "B", "text": "43046721"}, {"key": "C", "text": "162"}, {"key": "D", "text": "1"}]','A','同底数幂相乘指数相加：3^8=6561','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0220-3','math','初中',9,'jkp-0220','single_choice',0.35,'4^2 × 4^3 = ？','[{"key": "A", "text": "1024"}, {"key": "B", "text": "4096"}, {"key": "C", "text": "80"}, {"key": "D", "text": "0.25"}]','A','同底数幂相乘指数相加：4^5=1024','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0221-1','math','初中',9,'jkp-0221','single_choice',0.45,'(2^3)^3 = 2^3×3 = ？','[{"key": "A", "text": "512"}, {"key": "B", "text": "64"}, {"key": "C", "text": "64"}, {"key": "D", "text": "128"}]','A','幂的乘方指数相乘：2^9=512','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0221-2','math','初中',9,'jkp-0221','single_choice',0.45,'(3^3)^2 = 3^3×2 = ？','[{"key": "A", "text": "729"}, {"key": "B", "text": "243"}, {"key": "C", "text": "243"}, {"key": "D", "text": "729"}]','A','幂的乘方指数相乘：3^6=729','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0221-3','math','初中',9,'jkp-0221','single_choice',0.45,'(2^2)^3 = 2^2×3 = ？','[{"key": "A", "text": "64"}, {"key": "B", "text": "32"}, {"key": "C", "text": "32"}, {"key": "D", "text": "64"}]','A','幂的乘方指数相乘：2^6=64','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0222-1','math','初中',9,'jkp-0222','single_choice',0.55,'(2x)^3 = ？','[{"key": "A", "text": "8x^3"}, {"key": "B", "text": "6x^3"}, {"key": "C", "text": "2x^3"}, {"key": "D", "text": "8x^4"}]','A','积的乘方：8x^3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0222-2','math','初中',9,'jkp-0222','single_choice',0.55,'(3x)^3 = ？','[{"key": "A", "text": "27x^3"}, {"key": "B", "text": "9x^3"}, {"key": "C", "text": "3x^3"}, {"key": "D", "text": "27x^4"}]','A','积的乘方：27x^3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0222-3','math','初中',9,'jkp-0222','single_choice',0.55,'(2x)^2 = ？','[{"key": "A", "text": "4x^2"}, {"key": "B", "text": "4x^2"}, {"key": "C", "text": "2x^2"}, {"key": "D", "text": "4x^3"}]','A','积的乘方：4x^2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0223-1','math','初中',9,'jkp-0223','single_choice',0.65,'3^2 ÷ 3^3 = ？','[{"key": "A", "text": "0.3333333333333333"}, {"key": "B", "text": "243"}, {"key": "C", "text": "729"}, {"key": "D", "text": "2.080083823051904"}]','A','同底数幂相除指数相减：3^-1=0.3333333333333333','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0223-2','math','初中',9,'jkp-0223','single_choice',0.65,'2^2 ÷ 2^2 = ？','[{"key": "A", "text": "1"}, {"key": "B", "text": "16"}, {"key": "C", "text": "16"}, {"key": "D", "text": "2.0"}]','A','同底数幂相除指数相减：2^0=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0223-3','math','初中',9,'jkp-0223','single_choice',0.65,'4^4 ÷ 4^1 = ？','[{"key": "A", "text": "64"}, {"key": "B", "text": "1024"}, {"key": "C", "text": "256"}, {"key": "D", "text": "256.0"}]','A','同底数幂相除指数相减：4^3=64','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0224-1','math','初中',9,'jkp-0224','single_choice',0.75,'2⁰ = ？(a≠0)','[{"key": "A", "text": "1"}, {"key": "B", "text": "0"}, {"key": "C", "text": "2"}, {"key": "D", "text": "-2"}]','A','零指数幂：任何非零数的 0 次幂 = 1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0224-2','math','初中',9,'jkp-0224','single_choice',0.75,'5⁰ = ？(a≠0)','[{"key": "A", "text": "1"}, {"key": "B", "text": "0"}, {"key": "C", "text": "5"}, {"key": "D", "text": "-5"}]','A','零指数幂：任何非零数的 0 次幂 = 1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0224-3','math','初中',9,'jkp-0224','single_choice',0.75,'6⁰ = ？(a≠0)','[{"key": "A", "text": "1"}, {"key": "B", "text": "0"}, {"key": "C", "text": "6"}, {"key": "D", "text": "-6"}]','A','零指数幂：任何非零数的 0 次幂 = 1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0225-1','math','初中',9,'jkp-0225','single_choice',0.35,'3⁻¹ = ？','[{"key": "A", "text": "1/3"}, {"key": "B", "text": "-3"}, {"key": "C", "text": "3"}, {"key": "D", "text": "-1/3"}]','A','负整数指数：3⁻¹=1/3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0225-2','math','初中',9,'jkp-0225','single_choice',0.35,'2⁻¹ = ？','[{"key": "A", "text": "1/2"}, {"key": "B", "text": "-2"}, {"key": "C", "text": "2"}, {"key": "D", "text": "-1/2"}]','A','负整数指数：2⁻¹=1/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0225-3','math','初中',9,'jkp-0225','single_choice',0.35,'3⁻¹ = ？','[{"key": "D", "text": "-1/3"}, {"key": "B", "text": "-3"}, {"key": "A", "text": "1/3"}, {"key": "C", "text": "3"}]','A','负整数指数：3⁻¹=1/3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0226-1','math','初中',9,'jkp-0226','single_choice',0.45,'计算：2x² · 2x³ = ？','[{"key": "A", "text": "4x⁵"}, {"key": "B", "text": "4x⁶"}, {"key": "C", "text": "4x⁵"}, {"key": "D", "text": "4x^5"}]','A','系数相乘、指数相加：4x⁵','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0226-2','math','初中',9,'jkp-0226','single_choice',0.45,'计算：4x² · 2x³ = ？','[{"key": "A", "text": "8x⁵"}, {"key": "B", "text": "8x⁶"}, {"key": "C", "text": "6x⁵"}, {"key": "D", "text": "8x^5"}]','A','系数相乘、指数相加：8x⁵','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0226-3','math','初中',9,'jkp-0226','single_choice',0.45,'计算：4x² · 3x³ = ？','[{"key": "A", "text": "12x⁵"}, {"key": "B", "text": "12x⁶"}, {"key": "C", "text": "7x⁵"}, {"key": "D", "text": "12x^5"}]','A','系数相乘、指数相加：12x⁵','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0227-1','math','初中',9,'jkp-0227','single_choice',0.55,'计算：2x(4x + 1) = ？','[{"key": "A", "text": "8x² + 2x"}, {"key": "B", "text": "8x² + 1"}, {"key": "C", "text": "2x² + 2x"}, {"key": "D", "text": "8x + 2"}]','A','分配律：8x² + 2x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0227-2','math','初中',9,'jkp-0227','single_choice',0.55,'计算：4x(2x + 1) = ？','[{"key": "A", "text": "8x² + 4x"}, {"key": "B", "text": "8x² + 1"}, {"key": "C", "text": "4x² + 4x"}, {"key": "D", "text": "8x + 4"}]','A','分配律：8x² + 4x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0227-3','math','初中',9,'jkp-0227','single_choice',0.55,'计算：3x(3x + 1) = ？','[{"key": "A", "text": "9x² + 3x"}, {"key": "B", "text": "9x² + 1"}, {"key": "C", "text": "3x² + 3x"}, {"key": "D", "text": "9x + 3"}]','A','分配律：9x² + 3x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0228-1','math','初中',9,'jkp-0228','single_choice',0.65,'(x + 2)(x + 4) = ？','[{"key": "A", "text": "x² + 6x + 8"}, {"key": "B", "text": "x² + 8x + 6"}, {"key": "C", "text": "x² + 6x + 6"}, {"key": "D", "text": "x² + -2x + 8"}]','A','多项式乘多项式：x²+(2+4)x+2×4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0228-2','math','初中',9,'jkp-0228','single_choice',0.65,'(x + 2)(x + 2) = ？','[{"key": "A", "text": "x² + 4x + 4"}, {"key": "B", "text": "x² + 4x + 4"}, {"key": "C", "text": "x² + 4x + 4"}, {"key": "D", "text": "x² + 0x + 4"}]','A','多项式乘多项式：x²+(2+2)x+2×2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0228-3','math','初中',9,'jkp-0228','single_choice',0.65,'(x + 4)(x + 2) = ？','[{"key": "A", "text": "x² + 6x + 8"}, {"key": "B", "text": "x² + 8x + 6"}, {"key": "C", "text": "x² + 6x + 6"}, {"key": "D", "text": "x² + 2x + 8"}]','A','多项式乘多项式：x²+(4+2)x+4×2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0229-1','math','初中',9,'jkp-0229','single_choice',0.75,'计算：(5x + 4)(5x - 4) = ？','[{"key": "A", "text": "25x² - 16"}, {"key": "B", "text": "25x² + 16"}, {"key": "C", "text": "25x² + 40x + 16"}, {"key": "D", "text": "25x² - 40x + 16"}]','A','平方差公式：(5x)²-4²=25x²-16','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0229-2','math','初中',9,'jkp-0229','single_choice',0.75,'计算：(5x + 5)(5x - 5) = ？','[{"key": "A", "text": "25x² - 25"}, {"key": "B", "text": "25x² + 25"}, {"key": "C", "text": "25x² + 50x + 25"}, {"key": "D", "text": "25x² - 50x + 25"}]','A','平方差公式：(5x)²-5²=25x²-25','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0229-3','math','初中',9,'jkp-0229','single_choice',0.75,'计算：(5x + 4)(5x - 4) = ？','[{"key": "A", "text": "25x² - 16"}, {"key": "B", "text": "25x² + 16"}, {"key": "D", "text": "25x² - 40x + 16"}, {"key": "C", "text": "25x² + 40x + 16"}]','A','平方差公式：(5x)²-4²=25x²-16','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0230-1','math','初中',9,'jkp-0230','single_choice',0.35,'(3 + 4)² = ？','[{"key": "A", "text": "9+24+16"}, {"key": "B", "text": "9+16"}, {"key": "C", "text": "9-24+16"}, {"key": "D", "text": "6+8"}]','A','完全平方和：3²+2×3×4+4²=9+24+16','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0230-2','math','初中',9,'jkp-0230','single_choice',0.35,'(2 + 4)² = ？','[{"key": "A", "text": "4+16+16"}, {"key": "B", "text": "4+16"}, {"key": "C", "text": "4-16+16"}, {"key": "D", "text": "4+8"}]','A','完全平方和：2²+2×2×4+4²=4+16+16','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0230-3','math','初中',9,'jkp-0230','single_choice',0.35,'(4 + 3)² = ？','[{"key": "A", "text": "16+24+9"}, {"key": "B", "text": "16+9"}, {"key": "C", "text": "16-24+9"}, {"key": "D", "text": "8+6"}]','A','完全平方和：4²+2×4×3+3²=16+24+9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0231-1','math','初中',9,'jkp-0231','single_choice',0.45,'(5 - 2)² = ？','[{"key": "A", "text": "25-20+4"}, {"key": "B", "text": "25+4"}, {"key": "C", "text": "25+20+4"}, {"key": "D", "text": "10-4"}]','A','完全平方差：5²-2×5×2+2²=25-20+4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0231-2','math','初中',9,'jkp-0231','single_choice',0.45,'(5 - 3)² = ？','[{"key": "A", "text": "25-30+9"}, {"key": "B", "text": "25+9"}, {"key": "C", "text": "25+30+9"}, {"key": "D", "text": "10-6"}]','A','完全平方差：5²-2×5×3+3²=25-30+9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0231-3','math','初中',9,'jkp-0231','single_choice',0.45,'(4 - 2)² = ？','[{"key": "A", "text": "16-16+4"}, {"key": "B", "text": "16+4"}, {"key": "C", "text": "16+16+4"}, {"key": "D", "text": "8-4"}]','A','完全平方差：4²-2×4×2+2²=16-16+4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0232-1','math','初中',9,'jkp-0232','single_choice',0.55,'(x + 5)² = x² + 2·5·x + 5²，则 x² + 10x + 25 = (x + ?)²','[{"key": "A", "text": "5"}, {"key": "B", "text": "10"}, {"key": "C", "text": "25"}, {"key": "D", "text": "6"}]','A','完全平方逆用：(x+5)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0232-2','math','初中',9,'jkp-0232','single_choice',0.55,'(x + 2)² = x² + 2·2·x + 2²，则 x² + 4x + 4 = (x + ?)²','[{"key": "A", "text": "2"}, {"key": "B", "text": "4"}, {"key": "C", "text": "4"}, {"key": "D", "text": "3"}]','A','完全平方逆用：(x+2)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0232-3','math','初中',9,'jkp-0232','single_choice',0.55,'(x + 4)² = x² + 2·4·x + 4²，则 x² + 8x + 16 = (x + ?)²','[{"key": "A", "text": "4"}, {"key": "B", "text": "8"}, {"key": "C", "text": "16"}, {"key": "D", "text": "5"}]','A','完全平方逆用：(x+4)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0233-1','math','初中',9,'jkp-0233','single_choice',0.65,'4x⁴ ÷ 2x² = ？','[{"key": "A", "text": "2x²"}, {"key": "B", "text": "4x²"}, {"key": "C", "text": "2x⁴"}, {"key": "D", "text": "2x^2"}]','A','系数相除、指数相减：2x²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0233-2','math','初中',9,'jkp-0233','single_choice',0.65,'8x⁴ ÷ 4x² = ？','[{"key": "A", "text": "2x²"}, {"key": "B", "text": "8x²"}, {"key": "C", "text": "2x⁴"}, {"key": "D", "text": "2x^4"}]','A','系数相除、指数相减：2x²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0233-3','math','初中',9,'jkp-0233','single_choice',0.65,'6x⁴ ÷ 2x² = ？','[{"key": "A", "text": "3x²"}, {"key": "B", "text": "6x²"}, {"key": "C", "text": "3x⁴"}, {"key": "D", "text": "3x^2"}]','A','系数相除、指数相减：3x²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0234-1','math','初中',9,'jkp-0234','single_choice',0.75,'(2x² + 4x) ÷ 2x = ？','[{"key": "A", "text": "x + 2"}, {"key": "B", "text": "2x + 2"}, {"key": "C", "text": "x + 4"}, {"key": "D", "text": "2x + 4"}]','A','逐项除以：2x²÷2x + 4x÷2x = x+2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0234-2','math','初中',9,'jkp-0234','single_choice',0.75,'(2x² + 8x) ÷ 2x = ？','[{"key": "A", "text": "x + 4"}, {"key": "B", "text": "2x + 4"}, {"key": "C", "text": "x + 8"}, {"key": "D", "text": "2x + 8"}]','A','逐项除以：2x²÷2x + 8x÷2x = x+4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0234-3','math','初中',9,'jkp-0234','single_choice',0.75,'(4x² + 16x) ÷ 4x = ？','[{"key": "A", "text": "x + 4"}, {"key": "B", "text": "4x + 4"}, {"key": "C", "text": "x + 16"}, {"key": "D", "text": "4x + 16"}]','A','逐项除以：4x²÷4x + 16x÷4x = x+4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0235-1','math','初中',9,'jkp-0235','single_choice',0.35,'把一个多项式化成几个整式的积的形式叫？','[{"key": "A", "text": "因式分解"}, {"key": "B", "text": "整式乘法"}, {"key": "C", "text": "合并同类项"}, {"key": "D", "text": "去括号"}]','A','因式分解定义（和变积）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0235-2','math','初中',9,'jkp-0235','single_choice',0.35,'把一个多项式化成几个整式的积的形式叫？','[{"key": "C", "text": "合并同类项"}, {"key": "D", "text": "去括号"}, {"key": "B", "text": "整式乘法"}, {"key": "A", "text": "因式分解"}]','A','因式分解定义（和变积）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0235-3','math','初中',9,'jkp-0235','single_choice',0.35,'把一个多项式化成几个整式的积的形式叫？','[{"key": "C", "text": "合并同类项"}, {"key": "B", "text": "整式乘法"}, {"key": "D", "text": "去括号"}, {"key": "A", "text": "因式分解"}]','A','因式分解定义（和变积）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0236-1','math','初中',9,'jkp-0236','single_choice',0.45,'因式分解与整式乘法的关系是？','[{"key": "A", "text": "互逆"}, {"key": "B", "text": "相同"}, {"key": "C", "text": "无关"}, {"key": "D", "text": "包含"}]','A','因式分解与整式乘法互为逆运算','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0236-2','math','初中',9,'jkp-0236','single_choice',0.45,'因式分解与整式乘法的关系是？','[{"key": "B", "text": "相同"}, {"key": "A", "text": "互逆"}, {"key": "D", "text": "包含"}, {"key": "C", "text": "无关"}]','A','因式分解与整式乘法互为逆运算','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0236-3','math','初中',9,'jkp-0236','single_choice',0.45,'因式分解与整式乘法的关系是？','[{"key": "C", "text": "无关"}, {"key": "A", "text": "互逆"}, {"key": "D", "text": "包含"}, {"key": "B", "text": "相同"}]','A','因式分解与整式乘法互为逆运算','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0237-1','math','初中',9,'jkp-0237','single_choice',0.55,'分解因式：3x + 9 = ？','[{"key": "A", "text": "3(x + 3)"}, {"key": "B", "text": "3(x + 9)"}, {"key": "C", "text": "x(3 + 3)"}, {"key": "D", "text": "3x(1 + 3)"}]','A','提公因式 3：3(x+3)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0237-2','math','初中',9,'jkp-0237','single_choice',0.55,'分解因式：4x + 16 = ？','[{"key": "A", "text": "4(x + 4)"}, {"key": "B", "text": "4(x + 16)"}, {"key": "C", "text": "x(4 + 4)"}, {"key": "D", "text": "4x(1 + 4)"}]','A','提公因式 4：4(x+4)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0237-3','math','初中',9,'jkp-0237','single_choice',0.55,'分解因式：5x + 15 = ？','[{"key": "A", "text": "5(x + 3)"}, {"key": "B", "text": "5(x + 15)"}, {"key": "C", "text": "x(5 + 3)"}, {"key": "D", "text": "5x(1 + 3)"}]','A','提公因式 5：5(x+3)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0238-1','math','初中',9,'jkp-0238','single_choice',0.65,'分解因式：4x² - 16 = ？','[{"key": "A", "text": "(2x+4)(2x-4)"}, {"key": "B", "text": "(2x+4)²"}, {"key": "C", "text": "(2x-4)²"}, {"key": "D", "text": "(2x+4)(2x+4)"}]','A','平方差公式：(2x)²-4²=(2x+4)(2x-4)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0238-2','math','初中',9,'jkp-0238','single_choice',0.65,'分解因式：16x² - 4 = ？','[{"key": "A", "text": "(4x+2)(4x-2)"}, {"key": "B", "text": "(4x+2)²"}, {"key": "C", "text": "(4x-2)²"}, {"key": "D", "text": "(4x+2)(4x+2)"}]','A','平方差公式：(4x)²-2²=(4x+2)(4x-2)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0238-3','math','初中',9,'jkp-0238','single_choice',0.65,'分解因式：25x² - 25 = ？','[{"key": "A", "text": "(5x+5)(5x-5)"}, {"key": "B", "text": "(5x+5)²"}, {"key": "C", "text": "(5x-5)²"}, {"key": "D", "text": "(5x+5)(5x+5)"}]','A','平方差公式：(5x)²-5²=(5x+5)(5x-5)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0239-1','math','初中',9,'jkp-0239','single_choice',0.75,'分解因式：x² + 10x + 25 = ？','[{"key": "A", "text": "(x+5)²"}, {"key": "B", "text": "(x-5)²"}, {"key": "C", "text": "(x+5)(x-5)"}, {"key": "D", "text": "(x+10)²"}]','A','完全平方：x²+2×5x+5²=(x+5)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0239-2','math','初中',9,'jkp-0239','single_choice',0.75,'分解因式：x² + 6x + 9 = ？','[{"key": "A", "text": "(x+3)²"}, {"key": "B", "text": "(x-3)²"}, {"key": "C", "text": "(x+3)(x-3)"}, {"key": "D", "text": "(x+6)²"}]','A','完全平方：x²+2×3x+3²=(x+3)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0239-3','math','初中',9,'jkp-0239','single_choice',0.75,'分解因式：x² + 8x + 16 = ？','[{"key": "A", "text": "(x+4)²"}, {"key": "B", "text": "(x-4)²"}, {"key": "C", "text": "(x+4)(x-4)"}, {"key": "D", "text": "(x+8)²"}]','A','完全平方：x²+2×4x+4²=(x+4)²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0240-1','math','初中',9,'jkp-0240','single_choice',0.35,'分解因式 6x² - 6 的第一步是？','[{"key": "A", "text": "提公因式 6"}, {"key": "B", "text": "直接套公式"}, {"key": "C", "text": "合并同类项"}, {"key": "D", "text": "去括号"}]','A','先提公因式 6：6(x²-1)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0240-2','math','初中',9,'jkp-0240','single_choice',0.35,'分解因式 10x² - 10 的第一步是？','[{"key": "A", "text": "提公因式 10"}, {"key": "B", "text": "直接套公式"}, {"key": "C", "text": "合并同类项"}, {"key": "D", "text": "去括号"}]','A','先提公因式 10：10(x²-1)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0240-3','math','初中',9,'jkp-0240','single_choice',0.35,'分解因式 8x² - 8 的第一步是？','[{"key": "A", "text": "提公因式 8"}, {"key": "B", "text": "直接套公式"}, {"key": "C", "text": "合并同类项"}, {"key": "D", "text": "去括号"}]','A','先提公因式 8：8(x²-1)','template-j','approved','通用');