-- 第27章 相似 补题（12学期, 知识点 397-417）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0397-1','math','初中',12,'jkp-0397','single_choice',0.55,'线段 a=3、b=4，a 与 b 的比 = ？','[{"key": "A", "text": "3:4"}, {"key": "B", "text": "4:3"}, {"key": "C", "text": "12"}, {"key": "D", "text": "7"}]','A','比 = 3:4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0397-2','math','初中',12,'jkp-0397','single_choice',0.55,'线段 a=4、b=7，a 与 b 的比 = ？','[{"key": "A", "text": "4:7"}, {"key": "B", "text": "7:4"}, {"key": "C", "text": "28"}, {"key": "D", "text": "11"}]','A','比 = 4:7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0397-3','math','初中',12,'jkp-0397','single_choice',0.55,'线段 a=4、b=6，a 与 b 的比 = ？','[{"key": "A", "text": "4:6"}, {"key": "B", "text": "6:4"}, {"key": "C", "text": "24"}, {"key": "D", "text": "10"}]','A','比 = 4:6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0398-1','math','初中',12,'jkp-0398','single_choice',0.65,'若 a/b = 4/3，则 a:b = ？','[{"key": "A", "text": "4:3"}, {"key": "B", "text": "3:4"}, {"key": "C", "text": "7:4"}, {"key": "D", "text": "1:1"}]','A','比例式 a:b=4:3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0398-2','math','初中',12,'jkp-0398','single_choice',0.65,'若 a/b = 5/3，则 a:b = ？','[{"key": "A", "text": "5:3"}, {"key": "B", "text": "3:5"}, {"key": "C", "text": "8:5"}, {"key": "D", "text": "1:1"}]','A','比例式 a:b=5:3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0398-3','math','初中',12,'jkp-0398','single_choice',0.65,'若 a/b = 3/4，则 a:b = ？','[{"key": "A", "text": "3:4"}, {"key": "B", "text": "4:3"}, {"key": "C", "text": "7:3"}, {"key": "D", "text": "1:1"}]','A','比例式 a:b=3:4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0399-1','math','初中',12,'jkp-0399','single_choice',0.75,'黄金分割比 ≈ ？','[{"key": "A", "text": "0.618"}, {"key": "B", "text": "0.5"}, {"key": "C", "text": "1"}, {"key": "D", "text": "0.707"}]','A','黄金比 (√5-1)/2 ≈ 0.618','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0399-2','math','初中',12,'jkp-0399','single_choice',0.75,'黄金分割比 ≈ ？','[{"key": "C", "text": "1"}, {"key": "B", "text": "0.5"}, {"key": "D", "text": "0.707"}, {"key": "A", "text": "0.618"}]','A','黄金比 (√5-1)/2 ≈ 0.618','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0399-3','math','初中',12,'jkp-0399','single_choice',0.75,'黄金分割比 ≈ ？','[{"key": "C", "text": "1"}, {"key": "D", "text": "0.707"}, {"key": "B", "text": "0.5"}, {"key": "A", "text": "0.618"}]','A','黄金比 (√5-1)/2 ≈ 0.618','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0400-1','math','初中',12,'jkp-0400','single_choice',0.35,'形状相同、大小不一定相同的图形叫？','[{"key": "A", "text": "相似图形"}, {"key": "B", "text": "全等图形"}, {"key": "C", "text": "对称图形"}, {"key": "D", "text": "平移图形"}]','A','相似图形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0400-2','math','初中',12,'jkp-0400','single_choice',0.35,'形状相同、大小不一定相同的图形叫？','[{"key": "A", "text": "相似图形"}, {"key": "C", "text": "对称图形"}, {"key": "B", "text": "全等图形"}, {"key": "D", "text": "平移图形"}]','A','相似图形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0400-3','math','初中',12,'jkp-0400','single_choice',0.35,'形状相同、大小不一定相同的图形叫？','[{"key": "B", "text": "全等图形"}, {"key": "A", "text": "相似图形"}, {"key": "C", "text": "对称图形"}, {"key": "D", "text": "平移图形"}]','A','相似图形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0401-1','math','初中',12,'jkp-0401','single_choice',0.45,'相似多边形的性质：对应角？对应边？','[{"key": "A", "text": "相等、成比例"}, {"key": "B", "text": "成比例、相等"}, {"key": "C", "text": "相等、相等"}, {"key": "D", "text": "成比例、成比例"}]','A','相似多边形：对应角相等，对应边成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0401-2','math','初中',12,'jkp-0401','single_choice',0.45,'相似多边形的性质：对应角？对应边？','[{"key": "C", "text": "相等、相等"}, {"key": "A", "text": "相等、成比例"}, {"key": "D", "text": "成比例、成比例"}, {"key": "B", "text": "成比例、相等"}]','A','相似多边形：对应角相等，对应边成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0401-3','math','初中',12,'jkp-0401','single_choice',0.45,'相似多边形的性质：对应角？对应边？','[{"key": "D", "text": "成比例、成比例"}, {"key": "C", "text": "相等、相等"}, {"key": "B", "text": "成比例、相等"}, {"key": "A", "text": "相等、成比例"}]','A','相似多边形：对应角相等，对应边成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0402-1','math','初中',12,'jkp-0402','single_choice',0.55,'相似多边形对应边 3 与 2，相似比 = ？','[{"key": "A", "text": "3:2"}, {"key": "B", "text": "2:3"}, {"key": "C", "text": "6"}, {"key": "D", "text": "5"}]','A','相似比 = 对应边比 = 3:2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0402-2','math','初中',12,'jkp-0402','single_choice',0.55,'相似多边形对应边 4 与 4，相似比 = ？','[{"key": "A", "text": "4:4"}, {"key": "B", "text": "4:4"}, {"key": "C", "text": "16"}, {"key": "D", "text": "8"}]','A','相似比 = 对应边比 = 4:4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0402-3','math','初中',12,'jkp-0402','single_choice',0.55,'相似多边形对应边 2 与 4，相似比 = ？','[{"key": "A", "text": "2:4"}, {"key": "B", "text": "4:2"}, {"key": "C", "text": "8"}, {"key": "D", "text": "6"}]','A','相似比 = 对应边比 = 2:4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0403-1','math','初中',12,'jkp-0403','single_choice',0.65,'平行线分线段成比例：两条平行线截两条直线，对应线段？','[{"key": "A", "text": "成比例"}, {"key": "B", "text": "相等"}, {"key": "C", "text": "互补"}, {"key": "D", "text": "无关"}]','A','平行线分线段成比例定理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0404-1','math','初中',12,'jkp-0404','single_choice',0.75,'平行于三角形一边的直线截其他两边，所得线段？','[{"key": "A", "text": "成比例"}, {"key": "B", "text": "相等"}, {"key": "C", "text": "加倍"}, {"key": "D", "text": "减半"}]','A','A 字型：平行 → 对应线段成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0404-2','math','初中',12,'jkp-0404','single_choice',0.75,'平行于三角形一边的直线截其他两边，所得线段？','[{"key": "D", "text": "减半"}, {"key": "A", "text": "成比例"}, {"key": "B", "text": "相等"}, {"key": "C", "text": "加倍"}]','A','A 字型：平行 → 对应线段成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0404-3','math','初中',12,'jkp-0404','single_choice',0.75,'平行于三角形一边的直线截其他两边，所得线段？','[{"key": "C", "text": "加倍"}, {"key": "D", "text": "减半"}, {"key": "B", "text": "相等"}, {"key": "A", "text": "成比例"}]','A','A 字型：平行 → 对应线段成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0405-1','math','初中',12,'jkp-0405','single_choice',0.35,'对应角相等、对应边成比例的三角形叫？','[{"key": "A", "text": "相似三角形"}, {"key": "B", "text": "全等三角形"}, {"key": "C", "text": "等腰三角形"}, {"key": "D", "text": "直角三角形"}]','A','相似三角形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0405-2','math','初中',12,'jkp-0405','single_choice',0.35,'对应角相等、对应边成比例的三角形叫？','[{"key": "C", "text": "等腰三角形"}, {"key": "A", "text": "相似三角形"}, {"key": "D", "text": "直角三角形"}, {"key": "B", "text": "全等三角形"}]','A','相似三角形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0405-3','math','初中',12,'jkp-0405','single_choice',0.35,'对应角相等、对应边成比例的三角形叫？','[{"key": "A", "text": "相似三角形"}, {"key": "D", "text": "直角三角形"}, {"key": "C", "text": "等腰三角形"}, {"key": "B", "text": "全等三角形"}]','A','相似三角形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0406-1','math','初中',12,'jkp-0406','single_choice',0.45,'平行于三角形一边的直线与三角形其他两边相交，所得的三角形与原三角形？','[{"key": "A", "text": "相似"}, {"key": "B", "text": "全等"}, {"key": "C", "text": "不相似"}, {"key": "D", "text": "无关"}]','A','相似判定1：平行 → 相似','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0406-2','math','初中',12,'jkp-0406','single_choice',0.45,'平行于三角形一边的直线与三角形其他两边相交，所得的三角形与原三角形？','[{"key": "A", "text": "相似"}, {"key": "D", "text": "无关"}, {"key": "C", "text": "不相似"}, {"key": "B", "text": "全等"}]','A','相似判定1：平行 → 相似','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0406-3','math','初中',12,'jkp-0406','single_choice',0.45,'平行于三角形一边的直线与三角形其他两边相交，所得的三角形与原三角形？','[{"key": "D", "text": "无关"}, {"key": "B", "text": "全等"}, {"key": "A", "text": "相似"}, {"key": "C", "text": "不相似"}]','A','相似判定1：平行 → 相似','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0407-1','math','初中',12,'jkp-0407','single_choice',0.55,'三边对应成比例的三角形？','[{"key": "A", "text": "相似"}, {"key": "B", "text": "全等"}, {"key": "C", "text": "不一定"}, {"key": "D", "text": "无关"}]','A','相似判定2：SSS（三边成比例）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0407-2','math','初中',12,'jkp-0407','single_choice',0.55,'三边对应成比例的三角形？','[{"key": "C", "text": "不一定"}, {"key": "D", "text": "无关"}, {"key": "A", "text": "相似"}, {"key": "B", "text": "全等"}]','A','相似判定2：SSS（三边成比例）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0407-3','math','初中',12,'jkp-0407','single_choice',0.55,'三边对应成比例的三角形？','[{"key": "B", "text": "全等"}, {"key": "D", "text": "无关"}, {"key": "A", "text": "相似"}, {"key": "C", "text": "不一定"}]','A','相似判定2：SSS（三边成比例）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0408-1','math','初中',12,'jkp-0408','single_choice',0.65,'两边成比例且夹角相等的三角形？','[{"key": "A", "text": "相似"}, {"key": "B", "text": "全等"}, {"key": "C", "text": "不一定"}, {"key": "D", "text": "无关"}]','A','相似判定3：SAS','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0408-2','math','初中',12,'jkp-0408','single_choice',0.65,'两边成比例且夹角相等的三角形？','[{"key": "B", "text": "全等"}, {"key": "D", "text": "无关"}, {"key": "C", "text": "不一定"}, {"key": "A", "text": "相似"}]','A','相似判定3：SAS','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0408-3','math','初中',12,'jkp-0408','single_choice',0.65,'两边成比例且夹角相等的三角形？','[{"key": "C", "text": "不一定"}, {"key": "B", "text": "全等"}, {"key": "A", "text": "相似"}, {"key": "D", "text": "无关"}]','A','相似判定3：SAS','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0409-1','math','初中',12,'jkp-0409','single_choice',0.75,'两角对应相等的三角形？','[{"key": "A", "text": "相似"}, {"key": "B", "text": "全等"}, {"key": "C", "text": "不一定"}, {"key": "D", "text": "无关"}]','A','相似判定4：AA','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0409-2','math','初中',12,'jkp-0409','single_choice',0.75,'两角对应相等的三角形？','[{"key": "A", "text": "相似"}, {"key": "B", "text": "全等"}, {"key": "D", "text": "无关"}, {"key": "C", "text": "不一定"}]','A','相似判定4：AA','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0409-3','math','初中',12,'jkp-0409','single_choice',0.75,'两角对应相等的三角形？','[{"key": "C", "text": "不一定"}, {"key": "B", "text": "全等"}, {"key": "A", "text": "相似"}, {"key": "D", "text": "无关"}]','A','相似判定4：AA','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0410-1','math','初中',12,'jkp-0410','single_choice',0.35,'直角三角形相似的特殊判定：一条直角边和斜边成比例？','[{"key": "A", "text": "相似"}, {"key": "B", "text": "全等"}, {"key": "C", "text": "不一定"}, {"key": "D", "text": "无关"}]','A','直角三角形相似：HL 成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0410-2','math','初中',12,'jkp-0410','single_choice',0.35,'直角三角形相似的特殊判定：一条直角边和斜边成比例？','[{"key": "D", "text": "无关"}, {"key": "B", "text": "全等"}, {"key": "C", "text": "不一定"}, {"key": "A", "text": "相似"}]','A','直角三角形相似：HL 成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0410-3','math','初中',12,'jkp-0410','single_choice',0.35,'直角三角形相似的特殊判定：一条直角边和斜边成比例？','[{"key": "D", "text": "无关"}, {"key": "C", "text": "不一定"}, {"key": "B", "text": "全等"}, {"key": "A", "text": "相似"}]','A','直角三角形相似：HL 成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0411-1','math','初中',12,'jkp-0411','single_choice',0.45,'相似比 3:1，对应高之比 = ？','[{"key": "A", "text": "3:1"}, {"key": "B", "text": "9:1"}, {"key": "C", "text": "1:3"}, {"key": "D", "text": "3:3"}]','A','相似三角形对应高比 = 相似比 = 3:1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0411-2','math','初中',12,'jkp-0411','single_choice',0.45,'相似比 4:1，对应高之比 = ？','[{"key": "A", "text": "4:1"}, {"key": "B", "text": "16:1"}, {"key": "C", "text": "1:4"}, {"key": "D", "text": "4:4"}]','A','相似三角形对应高比 = 相似比 = 4:1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0411-3','math','初中',12,'jkp-0411','single_choice',0.45,'相似比 2:1，对应高之比 = ？','[{"key": "A", "text": "2:1"}, {"key": "B", "text": "4:1"}, {"key": "C", "text": "1:2"}, {"key": "D", "text": "2:2"}]','A','相似三角形对应高比 = 相似比 = 2:1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0412-1','math','初中',12,'jkp-0412','single_choice',0.55,'相似比 3:1，周长之比 = ？','[{"key": "A", "text": "3:1"}, {"key": "B", "text": "9:1"}, {"key": "C", "text": "1:3"}, {"key": "D", "text": "3:9"}]','A','周长比 = 相似比 = 3:1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0412-2','math','初中',12,'jkp-0412','single_choice',0.55,'相似比 4:1，周长之比 = ？','[{"key": "A", "text": "4:1"}, {"key": "B", "text": "16:1"}, {"key": "C", "text": "1:4"}, {"key": "D", "text": "4:16"}]','A','周长比 = 相似比 = 4:1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0412-3','math','初中',12,'jkp-0412','single_choice',0.55,'相似比 3:1，周长之比 = ？','[{"key": "D", "text": "3:9"}, {"key": "A", "text": "3:1"}, {"key": "C", "text": "1:3"}, {"key": "B", "text": "9:1"}]','A','周长比 = 相似比 = 3:1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0413-1','math','初中',12,'jkp-0413','single_choice',0.65,'相似比 3:1，面积之比 = ？','[{"key": "A", "text": "9:1"}, {"key": "B", "text": "3:1"}, {"key": "C", "text": "1:9"}, {"key": "D", "text": "3:3"}]','A','面积比 = 相似比平方 = 9:1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0413-2','math','初中',12,'jkp-0413','single_choice',0.65,'相似比 2:1，面积之比 = ？','[{"key": "A", "text": "4:1"}, {"key": "B", "text": "2:1"}, {"key": "C", "text": "1:4"}, {"key": "D", "text": "2:2"}]','A','面积比 = 相似比平方 = 4:1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0413-3','math','初中',12,'jkp-0413','single_choice',0.65,'相似比 4:1，面积之比 = ？','[{"key": "A", "text": "16:1"}, {"key": "B", "text": "4:1"}, {"key": "C", "text": "1:16"}, {"key": "D", "text": "4:4"}]','A','面积比 = 相似比平方 = 16:1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0414-1','math','初中',12,'jkp-0414','single_choice',0.75,'两个相似图形对应点连线交于一点的变换叫？','[{"key": "A", "text": "位似变换"}, {"key": "B", "text": "平移"}, {"key": "C", "text": "旋转"}, {"key": "D", "text": "轴对称"}]','A','位似定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0415-1','math','初中',12,'jkp-0415','single_choice',0.35,'位似图形是特殊的？','[{"key": "A", "text": "相似图形"}, {"key": "B", "text": "全等图形"}, {"key": "C", "text": "对称图形"}, {"key": "D", "text": "平移图形"}]','A','位似是特殊相似','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0415-2','math','初中',12,'jkp-0415','single_choice',0.35,'位似图形是特殊的？','[{"key": "C", "text": "对称图形"}, {"key": "A", "text": "相似图形"}, {"key": "D", "text": "平移图形"}, {"key": "B", "text": "全等图形"}]','A','位似是特殊相似','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0415-3','math','初中',12,'jkp-0415','single_choice',0.35,'位似图形是特殊的？','[{"key": "C", "text": "对称图形"}, {"key": "B", "text": "全等图形"}, {"key": "A", "text": "相似图形"}, {"key": "D", "text": "平移图形"}]','A','位似是特殊相似','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0416-1','math','初中',12,'jkp-0416','single_choice',0.45,'位似比 2，点 (2,3) 对应点坐标 = ？','[{"key": "A", "text": "(4,6)"}, {"key": "B", "text": "(1.0,1.5)"}, {"key": "C", "text": "(4,5)"}, {"key": "D", "text": "(0,1)"}]','A','位似比 2：坐标×2 → (4,6)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0416-2','math','初中',12,'jkp-0416','single_choice',0.45,'位似比 2，点 (1,3) 对应点坐标 = ？','[{"key": "A", "text": "(2,6)"}, {"key": "B", "text": "(0.5,1.5)"}, {"key": "C", "text": "(3,5)"}, {"key": "D", "text": "(-1,1)"}]','A','位似比 2：坐标×2 → (2,6)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0416-3','math','初中',12,'jkp-0416','single_choice',0.45,'位似比 2，点 (1,1) 对应点坐标 = ？','[{"key": "A", "text": "(2,2)"}, {"key": "B", "text": "(0.5,0.5)"}, {"key": "C", "text": "(3,3)"}, {"key": "D", "text": "(-1,-1)"}]','A','位似比 2：坐标×2 → (2,2)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0417-1','math','初中',12,'jkp-0417','single_choice',0.55,'测高常用方法：利用？构造相似三角形','[{"key": "A", "text": "同一时刻影长比（相似）"}, {"key": "B", "text": "测量"}, {"key": "C", "text": "目测"}, {"key": "D", "text": "猜测"}]','A','相似测高：物高/影长成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0417-2','math','初中',12,'jkp-0417','single_choice',0.55,'测高常用方法：利用？构造相似三角形','[{"key": "A", "text": "同一时刻影长比（相似）"}, {"key": "C", "text": "目测"}, {"key": "B", "text": "测量"}, {"key": "D", "text": "猜测"}]','A','相似测高：物高/影长成比例','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0417-3','math','初中',12,'jkp-0417','single_choice',0.55,'测高常用方法：利用？构造相似三角形','[{"key": "B", "text": "测量"}, {"key": "C", "text": "目测"}, {"key": "A", "text": "同一时刻影长比（相似）"}, {"key": "D", "text": "猜测"}]','A','相似测高：物高/影长成比例','template-j','approved','通用');