-- 第2章 整式的加减 补题（7学期, 知识点 26-35）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0026-1','math','初中',7,'jkp-0026','single_choice',0.45,'边长为 8 的正方形周长用字母表示：C = 4a，当 a=8 时 C=？','[{"key": "A", "text": "32"}, {"key": "B", "text": "8"}, {"key": "C", "text": "64"}, {"key": "D", "text": "16"}]','A','C=4a=4×8=32','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0027-1','math','初中',7,'jkp-0027','single_choice',0.55,'用代数式表示：2 与 7 的和是？','[{"key": "A", "text": "2+7"}, {"key": "B", "text": "2-7"}, {"key": "C", "text": "2×7"}, {"key": "D", "text": "2÷7"}]','A','和为 2+7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0028-1','math','初中',7,'jkp-0028','single_choice',0.65,'单项式 5x³ 的系数和次数分别是？','[{"key": "A", "text": "系数 5，次数 3"}, {"key": "B", "text": "系数 3，次数 5"}, {"key": "C", "text": "系数 1，次数 3"}, {"key": "D", "text": "系数 5，次数 1"}]','A','系数是数字因数 5，次数是字母指数和 3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0029-1','math','初中',7,'jkp-0029','single_choice',0.75,'多项式 5x² + 3x - 1 的次数和常数项是？','[{"key": "A", "text": "次数 2，常数项 -1"}, {"key": "B", "text": "次数 3，常数项 -1"}, {"key": "C", "text": "次数 2，常数项 1"}, {"key": "D", "text": "次数 5，常数项 -1"}]','A','最高次项是 2 次，常数项是 -1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0030-1','math','初中',7,'jkp-0030','single_choice',0.35,'下列代数式中是整式的是？','[{"key": "A", "text": "3x²+2x"}, {"key": "B", "text": "1/x"}, {"key": "C", "text": "√x"}, {"key": "D", "text": "2/x"}]','A','整式：不含分母含字母的项；3x²+2x 是整式（多项式）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0031-1','math','初中',7,'jkp-0031','single_choice',0.45,'下列与 6x²y 是同类项的是？','[{"key": "A", "text": "5x²y"}, {"key": "B", "text": "5xy²"}, {"key": "C", "text": "6xy"}, {"key": "D", "text": "6x²y²"}]','A','同类项：字母相同且次数相同，5x²y 符合','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0032-1','math','初中',7,'jkp-0032','single_choice',0.55,'合并同类项：2x + 2x = ？','[{"key": "A", "text": "4x"}, {"key": "B", "text": "(4)x²"}, {"key": "C", "text": "2x²2x"}, {"key": "D", "text": "4x"}]','A','系数相加：(2+2)x=4x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0033-1','math','初中',7,'jkp-0033','single_choice',0.65,'去括号：-(3x + 2) = ？','[{"key": "A", "text": "-3x - 2"}, {"key": "B", "text": "-3x + 2"}, {"key": "C", "text": "3x - 2"}, {"key": "D", "text": "3x + 2"}]','A','括号前负号：各项变号，-3x-2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0034-1','math','初中',7,'jkp-0034','single_choice',0.75,'计算：(5x + 5) + (5x - 5) = ？','[{"key": "A", "text": "10x"}, {"key": "B", "text": "10"}, {"key": "C", "text": "5x"}, {"key": "D", "text": "5x+5x"}]','A','去括号合并：5x+5+5x-5=10x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0035-1','math','初中',7,'jkp-0035','single_choice',0.35,'化简求值：当 x=4 时，2x² + x² = ？','[{"key": "A", "text": "48"}, {"key": "B", "text": "32"}, {"key": "C", "text": "12"}, {"key": "D", "text": "20"}]','A','2x²+x²=3x²，x=4 时 3×4²=48','template-j','approved','通用');