-- 第5章 相交线与平行线 补题（8学期, 知识点 66-87）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0066-1','math','初中',8,'jkp-0066','single_choice',0.45,'∠1 与 ∠2 互为邻补角，∠1=72°，则 ∠2 = ？','[{"key": "A", "text": "108°"}, {"key": "B", "text": "72°"}, {"key": "C", "text": "18°"}, {"key": "D", "text": "252°"}]','A','邻补角和为 180°：∠2=180°-72°=108°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0067-1','math','初中',8,'jkp-0067','single_choice',0.55,'两直线相交，∠1=43°，∠1 与 ∠2 是对顶角，则 ∠2 = ？','[{"key": "A", "text": "43°"}, {"key": "B", "text": "137°"}, {"key": "C", "text": "47°"}, {"key": "D", "text": "180°"}]','A','对顶角相等：∠2=43°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0068-1','math','初中',8,'jkp-0068','single_choice',0.65,'两条直线相交成直角，则这两条直线？','[{"key": "A", "text": "互相垂直"}, {"key": "B", "text": "互相平行"}, {"key": "C", "text": "重合"}, {"key": "D", "text": "斜交"}]','A','相交成 90° → 垂直','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0069-1','math','初中',8,'jkp-0069','single_choice',0.75,'过直线外一点，可以画几条直线与已知直线垂直？','[{"key": "A", "text": "1 条"}, {"key": "B", "text": "2 条"}, {"key": "C", "text": "无数条"}, {"key": "D", "text": "0 条"}]','A','垂线基本事实：过一点有且只有一条垂线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0070-1','math','初中',8,'jkp-0070','single_choice',0.35,'从直线外一点到这条直线的所有连线中，最短的是？','[{"key": "A", "text": "垂线段"}, {"key": "B", "text": "斜线段"}, {"key": "C", "text": "任意线段"}, {"key": "D", "text": "平行线"}]','A','垂线段最短','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0071-1','math','初中',8,'jkp-0071','single_choice',0.45,'点 P 到直线 l 的垂线段长为 6，则点 P 到直线 l 的距离 = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "12"}, {"key": "C", "text": "0"}, {"key": "D", "text": "3.0"}]','A','点到直线距离 = 垂线段长度 = 6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0072-1','math','初中',8,'jkp-0072','single_choice',0.55,'两条直线被第三条直线所截，位置相同的两个角（都在左上方）是？','[{"key": "A", "text": "同位角"}, {"key": "B", "text": "内错角"}, {"key": "C", "text": "同旁内角"}, {"key": "D", "text": "对顶角"}]','A','同位角：位置相同（左上对左上等）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0073-1','math','初中',8,'jkp-0073','single_choice',0.65,'两条直线被第三条直线所截，在两条直线之间且交错的两个角是？','[{"key": "A", "text": "内错角"}, {"key": "B", "text": "同位角"}, {"key": "C", "text": "同旁内角"}, {"key": "D", "text": "邻补角"}]','A','内错角：内部且交错','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0074-1','math','初中',8,'jkp-0074','single_choice',0.75,'两条直线被第三条直线所截，在两条直线之间且同侧的两个角是？','[{"key": "A", "text": "同旁内角"}, {"key": "B", "text": "内错角"}, {"key": "C", "text": "同位角"}, {"key": "D", "text": "对顶角"}]','A','同旁内角：内部且同侧','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0075-1','math','初中',8,'jkp-0075','single_choice',0.35,'在同一平面内，不相交的两条直线是？','[{"key": "A", "text": "平行线"}, {"key": "B", "text": "垂直线"}, {"key": "C", "text": "斜线"}, {"key": "D", "text": "重合线"}]','A','平行线定义：同一平面内不相交','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0076-1','math','初中',8,'jkp-0076','single_choice',0.45,'过直线外一点，可画几条直线与已知直线平行？','[{"key": "A", "text": "1 条"}, {"key": "B", "text": "无数条"}, {"key": "C", "text": "2 条"}, {"key": "D", "text": "0 条"}]','A','平行公理：过直线外一点有且只有一条平行线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0077-1','math','初中',8,'jkp-0077','single_choice',0.55,'若 a∥b 且 b∥c，则 a 与 c 的关系是？','[{"key": "A", "text": "a∥c"}, {"key": "B", "text": "a⊥c"}, {"key": "C", "text": "a 与 c 相交"}, {"key": "D", "text": "无法确定"}]','A','平行传递性：a∥c','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0078-1','math','初中',8,'jkp-0078','single_choice',0.65,'同位角相等，两直线？','[{"key": "A", "text": "平行"}, {"key": "B", "text": "垂直"}, {"key": "C", "text": "相交"}, {"key": "D", "text": "重合"}]','A','判定1：同位角相等 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0079-1','math','初中',8,'jkp-0079','single_choice',0.75,'内错角相等，两直线？','[{"key": "A", "text": "平行"}, {"key": "B", "text": "垂直"}, {"key": "C", "text": "相交"}, {"key": "D", "text": "重合"}]','A','判定2：内错角相等 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0080-1','math','初中',8,'jkp-0080','single_choice',0.35,'同旁内角互补，两直线？','[{"key": "A", "text": "平行"}, {"key": "B", "text": "垂直"}, {"key": "C", "text": "相交"}, {"key": "D", "text": "重合"}]','A','判定3：同旁内角互补 → 平行','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0081-1','math','初中',8,'jkp-0081','single_choice',0.45,'两直线平行，∠1=87°（∠1 与 ∠2 是同位角），则 ∠2 = ？','[{"key": "A", "text": "87°"}, {"key": "B", "text": "93°"}, {"key": "C", "text": "3°"}, {"key": "D", "text": "0°"}]','A','性质1：两直线平行，同位角相等 → ∠2=87°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0082-1','math','初中',8,'jkp-0082','single_choice',0.55,'两直线平行，∠1=59°（内错角关系），则其内错角 ∠2 = ？','[{"key": "A", "text": "59°"}, {"key": "B", "text": "121°"}, {"key": "C", "text": "31°"}, {"key": "D", "text": "180°"}]','A','性质2：内错角相等 → ∠2=59°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0083-1','math','初中',8,'jkp-0083','single_choice',0.65,'两直线平行，∠1=57°（同旁内角关系），则其同旁内角 ∠2 = ？','[{"key": "A", "text": "123°"}, {"key": "B", "text": "57°"}, {"key": "C", "text": "33°"}, {"key": "D", "text": "0°"}]','A','性质3：同旁内角互补 → ∠2=180°-57°=123°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0084-1','math','初中',8,'jkp-0084','single_choice',0.75,'下列是命题的是？','[{"key": "A", "text": "如果 a=b，那么 a²=b²"}, {"key": "B", "text": "画线段 AB"}, {"key": "C", "text": "延长 AB"}, {"key": "D", "text": "过点 P 作直线"}]','A','命题：判断一件事情的语句','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0085-1','math','初中',8,'jkp-0085','single_choice',0.35,'经过推理证实的真命题叫？','[{"key": "A", "text": "定理"}, {"key": "B", "text": "公理"}, {"key": "C", "text": "猜想"}, {"key": "D", "text": "定义"}]','A','定理：经过证明的真命题','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0086-1','math','初中',8,'jkp-0086','single_choice',0.45,'平移不改变图形的？','[{"key": "A", "text": "形状和大小"}, {"key": "B", "text": "位置"}, {"key": "C", "text": "方向"}, {"key": "D", "text": "面积"}]','A','平移只改变位置，不改变形状大小方向','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0087-1','math','初中',8,'jkp-0087','single_choice',0.55,'点 A 向右平移 4 个单位，对应点 A′，则 AA′ = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "8"}, {"key": "C", "text": "0"}, {"key": "D", "text": "2.0"}]','A','平移距离 = 对应点连线长度 = 4','template-j','approved','通用');