-- 第3章 一元一次方程 补题（7学期, 知识点 36-48）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0036-1','math','初中',7,'jkp-0036','single_choice',0.45,'下列是方程的是？','[{"key": "A", "text": "3x + 2 = 8"}, {"key": "B", "text": "3x + 2"}, {"key": "C", "text": "3 + 2"}, {"key": "D", "text": "x > 1"}]','A','方程：含未知数的等式','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0036-2','math','初中',7,'jkp-0036','single_choice',0.45,'下列是方程的是？','[{"key": "B", "text": "3x + 2"}, {"key": "C", "text": "3 + 2"}, {"key": "A", "text": "3x + 2 = 8"}, {"key": "D", "text": "x > 1"}]','A','方程：含未知数的等式','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0036-3','math','初中',7,'jkp-0036','single_choice',0.45,'下列是方程的是？','[{"key": "A", "text": "3x + 2 = 8"}, {"key": "C", "text": "3 + 2"}, {"key": "D", "text": "x > 1"}, {"key": "B", "text": "3x + 2"}]','A','方程：含未知数的等式','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0037-1','math','初中',7,'jkp-0037','single_choice',0.55,'下列是一元一次方程的是？','[{"key": "A", "text": "5x + 3 = 0"}, {"key": "B", "text": "x² + x = 0"}, {"key": "C", "text": "x + y = 1"}, {"key": "D", "text": "1/x = 2"}]','A','一元一次：一个未知数、一次、整式方程','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0037-2','math','初中',7,'jkp-0037','single_choice',0.55,'下列是一元一次方程的是？','[{"key": "C", "text": "x + y = 1"}, {"key": "B", "text": "x² + x = 0"}, {"key": "A", "text": "5x + 3 = 0"}, {"key": "D", "text": "1/x = 2"}]','A','一元一次：一个未知数、一次、整式方程','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0037-3','math','初中',7,'jkp-0037','single_choice',0.55,'下列是一元一次方程的是？','[{"key": "C", "text": "x + y = 1"}, {"key": "A", "text": "5x + 3 = 0"}, {"key": "D", "text": "1/x = 2"}, {"key": "B", "text": "x² + x = 0"}]','A','一元一次：一个未知数、一次、整式方程','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0038-1','math','初中',7,'jkp-0038','single_choice',0.65,'检验：x=3 是方程 4x = 12 的解吗？','[{"key": "A", "text": "是"}, {"key": "B", "text": "否"}, {"key": "C", "text": "无法判断"}, {"key": "D", "text": "不一定"}]','A','代入 4×3=12 成立，x=3 是解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0038-2','math','初中',7,'jkp-0038','single_choice',0.65,'检验：x=3 是方程 2x = 6 的解吗？','[{"key": "A", "text": "是"}, {"key": "B", "text": "否"}, {"key": "C", "text": "无法判断"}, {"key": "D", "text": "不一定"}]','A','代入 2×3=6 成立，x=3 是解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0038-3','math','初中',7,'jkp-0038','single_choice',0.65,'检验：x=1 是方程 1x = 1 的解吗？','[{"key": "A", "text": "是"}, {"key": "B", "text": "否"}, {"key": "C", "text": "无法判断"}, {"key": "D", "text": "不一定"}]','A','代入 1×1=1 成立，x=1 是解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0039-1','math','初中',7,'jkp-0039','single_choice',0.75,'若 5x = 15，两边同除以 5 得 x = ？（等式性质2）','[{"key": "A", "text": "3"}, {"key": "B", "text": "5"}, {"key": "C", "text": "15"}, {"key": "D", "text": "1"}]','A','等式两边同除以 5：x=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0039-2','math','初中',7,'jkp-0039','single_choice',0.75,'若 3x = 9，两边同除以 3 得 x = ？（等式性质2）','[{"key": "A", "text": "3"}, {"key": "B", "text": "3"}, {"key": "C", "text": "9"}, {"key": "D", "text": "1"}]','A','等式两边同除以 3：x=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0039-3','math','初中',7,'jkp-0039','single_choice',0.75,'若 5x = 15，两边同除以 5 得 x = ？（等式性质2）','[{"key": "D", "text": "1"}, {"key": "C", "text": "15"}, {"key": "A", "text": "3"}, {"key": "B", "text": "5"}]','A','等式两边同除以 5：x=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0040-1','math','初中',7,'jkp-0040','single_choice',0.35,'解方程 5x + 2 = 0，移项得？','[{"key": "A", "text": "5x = -2"}, {"key": "B", "text": "5x = 2"}, {"key": "C", "text": "5x = 0"}, {"key": "D", "text": "x = 2"}]','A','移项变号：{b} 移到右边变 -{b}','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0040-2','math','初中',7,'jkp-0040','single_choice',0.35,'解方程 4x + 2 = 0，移项得？','[{"key": "A", "text": "4x = -2"}, {"key": "B", "text": "4x = 2"}, {"key": "C", "text": "4x = 0"}, {"key": "D", "text": "x = 2"}]','A','移项变号：{b} 移到右边变 -{b}','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0040-3','math','初中',7,'jkp-0040','single_choice',0.35,'解方程 4x + 3 = 0，移项得？','[{"key": "A", "text": "4x = -3"}, {"key": "B", "text": "4x = 3"}, {"key": "C", "text": "4x = 0"}, {"key": "D", "text": "x = 3"}]','A','移项变号：{b} 移到右边变 -{b}','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0041-1','math','初中',7,'jkp-0041','single_choice',0.45,'解方程 x/2 + 4 = 2，去分母（两边乘 2）得？','[{"key": "A", "text": "x + 8 = 4"}, {"key": "B", "text": "x + 4 = 4"}, {"key": "C", "text": "x + 8 = 2"}, {"key": "D", "text": "2x + 4 = 2"}]','A','两边乘 2：x + 2×{a} = 2×{b}','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0041-2','math','初中',7,'jkp-0041','single_choice',0.45,'解方程 x/2 + 2 = 2，去分母（两边乘 2）得？','[{"key": "A", "text": "x + 4 = 4"}, {"key": "B", "text": "x + 2 = 4"}, {"key": "C", "text": "x + 4 = 2"}, {"key": "D", "text": "2x + 2 = 2"}]','A','两边乘 2：x + 2×{a} = 2×{b}','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0041-3','math','初中',7,'jkp-0041','single_choice',0.45,'解方程 x/2 + 4 = 4，去分母（两边乘 2）得？','[{"key": "A", "text": "x + 8 = 8"}, {"key": "B", "text": "x + 4 = 8"}, {"key": "C", "text": "x + 8 = 4"}, {"key": "D", "text": "2x + 4 = 4"}]','A','两边乘 2：x + 2×{a} = 2×{b}','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0042-1','math','初中',7,'jkp-0042','single_choice',0.55,'解方程 3(x - 1) = 2，去括号得？','[{"key": "A", "text": "3x - 3 = 2"}, {"key": "B", "text": "3x - 1 = 2"}, {"key": "C", "text": "3x + 3 = 2"}, {"key": "D", "text": "x - 3 = 2"}]','A','分配律：3x - 3×1 = 2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0042-2','math','初中',7,'jkp-0042','single_choice',0.55,'解方程 2(x - 1) = 5，去括号得？','[{"key": "A", "text": "2x - 2 = 5"}, {"key": "B", "text": "2x - 1 = 5"}, {"key": "C", "text": "2x + 2 = 5"}, {"key": "D", "text": "x - 2 = 5"}]','A','分配律：2x - 2×1 = 5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0042-3','math','初中',7,'jkp-0042','single_choice',0.55,'解方程 5(x - 1) = 5，去括号得？','[{"key": "A", "text": "5x - 5 = 5"}, {"key": "B", "text": "5x - 1 = 5"}, {"key": "C", "text": "5x + 5 = 5"}, {"key": "D", "text": "x - 5 = 5"}]','A','分配律：5x - 5×1 = 5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0043-1','math','初中',7,'jkp-0043','single_choice',0.65,'解方程 4x = 12，系数化为 1 得 x = ？','[{"key": "A", "text": "3"}, {"key": "B", "text": "12"}, {"key": "C", "text": "4"}, {"key": "D", "text": "1"}]','A','两边同除以 4：x=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0043-2','math','初中',7,'jkp-0043','single_choice',0.65,'解方程 4x = 16，系数化为 1 得 x = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "16"}, {"key": "C", "text": "4"}, {"key": "D", "text": "1"}]','A','两边同除以 4：x=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0043-3','math','初中',7,'jkp-0043','single_choice',0.65,'解方程 2x = 6，系数化为 1 得 x = ？','[{"key": "A", "text": "3"}, {"key": "B", "text": "6"}, {"key": "C", "text": "2"}, {"key": "D", "text": "1"}]','A','两边同除以 2：x=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0044-1','math','初中',7,'jkp-0044','single_choice',0.75,'每台机器生产 2 个零件，需 4 台机器凑 8 个零件：列方程？','[{"key": "A", "text": "2x = 8"}, {"key": "B", "text": "x = 2"}, {"key": "C", "text": "4x = 2"}, {"key": "D", "text": "2x = 4"}]','A','每台 2 个，x 台共 2x 个，凑 8 个：2x=8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0044-2','math','初中',7,'jkp-0044','single_choice',0.75,'每台机器生产 4 个零件，需 2 台机器凑 8 个零件：列方程？','[{"key": "A", "text": "4x = 8"}, {"key": "B", "text": "x = 4"}, {"key": "C", "text": "2x = 4"}, {"key": "D", "text": "4x = 2"}]','A','每台 4 个，x 台共 4x 个，凑 8 个：4x=8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0044-3','math','初中',7,'jkp-0044','single_choice',0.75,'每台机器生产 3 个零件，需 4 台机器凑 12 个零件：列方程？','[{"key": "A", "text": "3x = 12"}, {"key": "B", "text": "x = 3"}, {"key": "C", "text": "4x = 3"}, {"key": "D", "text": "3x = 4"}]','A','每台 3 个，x 台共 3x 个，凑 12 个：3x=12','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0045-1','math','初中',7,'jkp-0045','single_choice',0.35,'甲单独做需 5 天完成，则甲每天完成工程的？','[{"key": "A", "text": "1/5"}, {"key": "B", "text": "5"}, {"key": "C", "text": "1/4"}, {"key": "D", "text": "5/1"}]','A','工作效率=1/时间=1/5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0045-2','math','初中',7,'jkp-0045','single_choice',0.35,'甲单独做需 4 天完成，则甲每天完成工程的？','[{"key": "A", "text": "1/4"}, {"key": "B", "text": "4"}, {"key": "C", "text": "1/3"}, {"key": "D", "text": "4/1"}]','A','工作效率=1/时间=1/4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0045-3','math','初中',7,'jkp-0045','single_choice',0.35,'甲单独做需 3 天完成，则甲每天完成工程的？','[{"key": "A", "text": "1/3"}, {"key": "B", "text": "3"}, {"key": "C", "text": "1/3"}, {"key": "D", "text": "3/1"}]','A','工作效率=1/时间=1/3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0046-1','math','初中',7,'jkp-0046','single_choice',0.45,'速度 3 km/h，行驶 3 小时，路程 s = vt = ？','[{"key": "A", "text": "9"}, {"key": "B", "text": "6"}, {"key": "C", "text": "0"}, {"key": "D", "text": "1.0"}]','A','s=vt=3×3=9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0046-2','math','初中',7,'jkp-0046','single_choice',0.45,'速度 6 km/h，行驶 2 小时，路程 s = vt = ？','[{"key": "A", "text": "12"}, {"key": "B", "text": "8"}, {"key": "C", "text": "4"}, {"key": "D", "text": "3.0"}]','A','s=vt=6×2=12','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0046-3','math','初中',7,'jkp-0046','single_choice',0.45,'速度 4 km/h，行驶 2 小时，路程 s = vt = ？','[{"key": "A", "text": "8"}, {"key": "B", "text": "6"}, {"key": "C", "text": "2"}, {"key": "D", "text": "2.0"}]','A','s=vt=4×2=8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0047-1','math','初中',7,'jkp-0047','single_choice',0.55,'进价 6 元，售价 7 元，利润 = ？','[{"key": "A", "text": "1"}, {"key": "B", "text": "6"}, {"key": "C", "text": "7"}, {"key": "D", "text": "5"}]','A','利润=售价-进价=7-6=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0047-2','math','初中',7,'jkp-0047','single_choice',0.55,'进价 3 元，售价 5 元，利润 = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "3"}, {"key": "C", "text": "5"}, {"key": "D", "text": "1"}]','A','利润=售价-进价=5-3=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0047-3','math','初中',7,'jkp-0047','single_choice',0.55,'进价 5 元，售价 6 元，利润 = ？','[{"key": "A", "text": "1"}, {"key": "B", "text": "5"}, {"key": "C", "text": "6"}, {"key": "D", "text": "4"}]','A','利润=售价-进价=6-5=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0048-1','math','初中',7,'jkp-0048','single_choice',0.65,'月用水不超过 3 吨每吨 3 元，超过部分每吨 4 元。用 4 吨费用 = ？','[{"key": "A", "text": "13"}, {"key": "B", "text": "12"}, {"key": "C", "text": "9"}, {"key": "D", "text": "16"}]','A','前 3 吨 3×3=9，超 1 吨 4，共 13','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0048-2','math','初中',7,'jkp-0048','single_choice',0.65,'月用水不超过 4 吨每吨 2 元，超过部分每吨 3 元。用 5 吨费用 = ？','[{"key": "A", "text": "11"}, {"key": "B", "text": "10"}, {"key": "C", "text": "8"}, {"key": "D", "text": "15"}]','A','前 4 吨 4×2=8，超 1 吨 3，共 11','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0048-3','math','初中',7,'jkp-0048','single_choice',0.65,'月用水不超过 3 吨每吨 4 元，超过部分每吨 5 元。用 4 吨费用 = ？','[{"key": "A", "text": "17"}, {"key": "B", "text": "16"}, {"key": "C", "text": "12"}, {"key": "D", "text": "20"}]','A','前 3 吨 3×4=12，超 1 吨 5，共 17','template-j','approved','通用');