-- 第16章 分式 补题（10学期, 知识点 241-258）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0241-1','math','初中',10,'jkp-0241','single_choice',0.45,'下列是分式的是？','[{"key": "A", "text": "1/x"}, {"key": "B", "text": "x/2"}, {"key": "C", "text": "3"}, {"key": "D", "text": "x+1"}]','A','分式：分母含字母','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0241-2','math','初中',10,'jkp-0241','single_choice',0.45,'下列是分式的是？','[{"key": "A", "text": "1/x"}, {"key": "C", "text": "3"}, {"key": "D", "text": "x+1"}, {"key": "B", "text": "x/2"}]','A','分式：分母含字母','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0241-3','math','初中',10,'jkp-0241','single_choice',0.45,'下列是分式的是？','[{"key": "A", "text": "1/x"}, {"key": "D", "text": "x+1"}, {"key": "B", "text": "x/2"}, {"key": "C", "text": "3"}]','A','分式：分母含字母','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0242-1','math','初中',10,'jkp-0242','single_choice',0.55,'分式 1/(x-4) 有意义的条件是？','[{"key": "A", "text": "x≠4"}, {"key": "B", "text": "x>4"}, {"key": "C", "text": "x≥4"}, {"key": "D", "text": "x≠0"}]','A','分母不为 0：x-4≠0 → x≠4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0242-2','math','初中',10,'jkp-0242','single_choice',0.55,'分式 1/(x-5) 有意义的条件是？','[{"key": "A", "text": "x≠5"}, {"key": "B", "text": "x>5"}, {"key": "C", "text": "x≥5"}, {"key": "D", "text": "x≠0"}]','A','分母不为 0：x-5≠0 → x≠5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0242-3','math','初中',10,'jkp-0242','single_choice',0.55,'分式 1/(x-3) 有意义的条件是？','[{"key": "A", "text": "x≠3"}, {"key": "B", "text": "x>3"}, {"key": "C", "text": "x≥3"}, {"key": "D", "text": "x≠0"}]','A','分母不为 0：x-3≠0 → x≠3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0243-1','math','初中',10,'jkp-0243','single_choice',0.65,'分式 (x-5)/(x+1) 的值为 0 的条件是？','[{"key": "A", "text": "x=5（且分母不为0）"}, {"key": "B", "text": "x=-5"}, {"key": "C", "text": "x=0"}, {"key": "D", "text": "x=1"}]','A','分子=0 且分母≠0：x=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0243-2','math','初中',10,'jkp-0243','single_choice',0.65,'分式 (x-2)/(x+1) 的值为 0 的条件是？','[{"key": "A", "text": "x=2（且分母不为0）"}, {"key": "B", "text": "x=-2"}, {"key": "C", "text": "x=0"}, {"key": "D", "text": "x=1"}]','A','分子=0 且分母≠0：x=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0243-3','math','初中',10,'jkp-0243','single_choice',0.65,'分式 (x-5)/(x+1) 的值为 0 的条件是？','[{"key": "A", "text": "x=5（且分母不为0）"}, {"key": "D", "text": "x=1"}, {"key": "B", "text": "x=-5"}, {"key": "C", "text": "x=0"}]','A','分子=0 且分母≠0：x=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0244-1','math','初中',10,'jkp-0244','single_choice',0.75,'分式 a/b 分子分母同乘 2，值？','[{"key": "A", "text": "不变"}, {"key": "B", "text": "变为 2 倍"}, {"key": "C", "text": "变为 1/2"}, {"key": "D", "text": "无法确定"}]','A','分式基本性质：分子分母同乘（除）同一个非零数，值不变','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0244-2','math','初中',10,'jkp-0244','single_choice',0.75,'分式 a/b 分子分母同乘 3，值？','[{"key": "A", "text": "不变"}, {"key": "B", "text": "变为 3 倍"}, {"key": "C", "text": "变为 1/3"}, {"key": "D", "text": "无法确定"}]','A','分式基本性质：分子分母同乘（除）同一个非零数，值不变','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0244-3','math','初中',10,'jkp-0244','single_choice',0.75,'分式 a/b 分子分母同乘 5，值？','[{"key": "A", "text": "不变"}, {"key": "B", "text": "变为 5 倍"}, {"key": "C", "text": "变为 1/5"}, {"key": "D", "text": "无法确定"}]','A','分式基本性质：分子分母同乘（除）同一个非零数，值不变','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0245-1','math','初中',10,'jkp-0245','single_choice',0.35,'约分：(4x)/(2x²) = ？','[{"key": "A", "text": "2/x"}, {"key": "B", "text": "4/x"}, {"key": "C", "text": "2x"}, {"key": "D", "text": "2/x²"}]','A','约去公因式 2x：2/x（最简分式）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0245-2','math','初中',10,'jkp-0245','single_choice',0.35,'约分：(6x)/(3x²) = ？','[{"key": "A", "text": "2/x"}, {"key": "B", "text": "6/x"}, {"key": "C", "text": "2x"}, {"key": "D", "text": "2/x²"}]','A','约去公因式 3x：2/x（最简分式）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0245-3','math','初中',10,'jkp-0245','single_choice',0.35,'约分：(6x)/(2x²) = ？','[{"key": "A", "text": "3/x"}, {"key": "B", "text": "6/x"}, {"key": "C", "text": "3x"}, {"key": "D", "text": "3/x²"}]','A','约去公因式 2x：3/x（最简分式）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0246-1','math','初中',10,'jkp-0246','single_choice',0.45,'分式 1/x 与 1/(2x) 的最简公分母是？','[{"key": "A", "text": "2x"}, {"key": "B", "text": "x"}, {"key": "C", "text": "2x²"}, {"key": "D", "text": "3x"}]','A','最简公分母：2x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0246-2','math','初中',10,'jkp-0246','single_choice',0.45,'分式 1/x 与 1/(2x) 的最简公分母是？','[{"key": "D", "text": "3x"}, {"key": "B", "text": "x"}, {"key": "A", "text": "2x"}, {"key": "C", "text": "2x²"}]','A','最简公分母：2x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0246-3','math','初中',10,'jkp-0246','single_choice',0.45,'分式 1/x 与 1/(2x) 的最简公分母是？','[{"key": "C", "text": "2x²"}, {"key": "A", "text": "2x"}, {"key": "B", "text": "x"}, {"key": "D", "text": "3x"}]','A','最简公分母：2x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0247-1','math','初中',10,'jkp-0247','single_choice',0.55,'计算：(2/x) × (x/4) = ？','[{"key": "A", "text": "2/4"}, {"key": "B", "text": "8/x"}, {"key": "C", "text": "2/x²"}, {"key": "D", "text": "8/x²"}]','A','分式乘法：分子乘分子、分母乘分母，约分后 2/4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0247-2','math','初中',10,'jkp-0247','single_choice',0.55,'计算：(2/x) × (x/3) = ？','[{"key": "A", "text": "2/3"}, {"key": "B", "text": "6/x"}, {"key": "C", "text": "2/x²"}, {"key": "D", "text": "6/x²"}]','A','分式乘法：分子乘分子、分母乘分母，约分后 2/3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0247-3','math','初中',10,'jkp-0247','single_choice',0.55,'计算：(2/x) × (x/2) = ？','[{"key": "A", "text": "2/2"}, {"key": "B", "text": "4/x"}, {"key": "C", "text": "2/x²"}, {"key": "D", "text": "4/x²"}]','A','分式乘法：分子乘分子、分母乘分母，约分后 2/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0248-1','math','初中',10,'jkp-0248','single_choice',0.65,'计算：(2/x) ÷ (2/x) = ？','[{"key": "A", "text": "2/2"}, {"key": "B", "text": "4/x"}, {"key": "C", "text": "2/x"}, {"key": "D", "text": "2/2"}]','A','除以分式 = 乘其倒数：2/x × x/2=2/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0248-2','math','初中',10,'jkp-0248','single_choice',0.65,'计算：(4/x) ÷ (3/x) = ？','[{"key": "A", "text": "4/3"}, {"key": "B", "text": "12/x"}, {"key": "C", "text": "4/x"}, {"key": "D", "text": "3/4"}]','A','除以分式 = 乘其倒数：4/x × x/3=4/3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0248-3','math','初中',10,'jkp-0248','single_choice',0.65,'计算：(2/x) ÷ (3/x) = ？','[{"key": "A", "text": "2/3"}, {"key": "B", "text": "6/x"}, {"key": "C", "text": "2/x"}, {"key": "D", "text": "3/2"}]','A','除以分式 = 乘其倒数：2/x × x/3=2/3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0249-1','math','初中',10,'jkp-0249','single_choice',0.75,'计算：(x/2)² = ？','[{"key": "A", "text": "x²/4"}, {"key": "B", "text": "x²/2"}, {"key": "C", "text": "x/4"}, {"key": "D", "text": "x²/4"}]','A','分式乘方：分子分母分别乘方 = x²/4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0249-2','math','初中',10,'jkp-0249','single_choice',0.75,'计算：(x/4)² = ？','[{"key": "A", "text": "x²/16"}, {"key": "B", "text": "x²/4"}, {"key": "C", "text": "x/16"}, {"key": "D", "text": "x²/8"}]','A','分式乘方：分子分母分别乘方 = x²/16','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0249-3','math','初中',10,'jkp-0249','single_choice',0.75,'计算：(x/3)² = ？','[{"key": "A", "text": "x²/9"}, {"key": "B", "text": "x²/3"}, {"key": "C", "text": "x/9"}, {"key": "D", "text": "x²/6"}]','A','分式乘方：分子分母分别乘方 = x²/9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0250-1','math','初中',10,'jkp-0250','single_choice',0.35,'计算：(3/x) + (3/x) = ？','[{"key": "A", "text": "6/x"}, {"key": "B", "text": "3/x"}, {"key": "C", "text": "6/x²"}, {"key": "D", "text": "9/x"}]','A','同分母分式相加：分母不变分子相加 = 6/x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0250-2','math','初中',10,'jkp-0250','single_choice',0.35,'计算：(5/x) + (5/x) = ？','[{"key": "A", "text": "10/x"}, {"key": "B", "text": "5/x"}, {"key": "C", "text": "10/x²"}, {"key": "D", "text": "25/x"}]','A','同分母分式相加：分母不变分子相加 = 10/x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0250-3','math','初中',10,'jkp-0250','single_choice',0.35,'计算：(4/x) + (4/x) = ？','[{"key": "A", "text": "8/x"}, {"key": "B", "text": "4/x"}, {"key": "C", "text": "8/x²"}, {"key": "D", "text": "16/x"}]','A','同分母分式相加：分母不变分子相加 = 8/x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0251-1','math','初中',10,'jkp-0251','single_choice',0.45,'计算：1/x + 1/(2x) = ？','[{"key": "A", "text": "(2+1)/(2x)"}, {"key": "B", "text": "2/(2x)"}, {"key": "C", "text": "1/(2x)"}, {"key": "D", "text": "2/x"}]','A','通分：2/(2x)+1/(2x)=(2+1)/(2x)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0251-2','math','初中',10,'jkp-0251','single_choice',0.45,'计算：1/x + 1/(3x) = ？','[{"key": "A", "text": "(3+1)/(3x)"}, {"key": "B", "text": "2/(3x)"}, {"key": "C", "text": "1/(3x)"}, {"key": "D", "text": "2/x"}]','A','通分：3/(3x)+1/(3x)=(3+1)/(3x)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0251-3','math','初中',10,'jkp-0251','single_choice',0.45,'计算：1/x + 1/(4x) = ？','[{"key": "A", "text": "(4+1)/(4x)"}, {"key": "B", "text": "2/(4x)"}, {"key": "C", "text": "1/(4x)"}, {"key": "D", "text": "2/x"}]','A','通分：4/(4x)+1/(4x)=(4+1)/(4x)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0252-1','math','初中',10,'jkp-0252','single_choice',0.55,'分式混合运算的顺序是？','[{"key": "A", "text": "先乘方再乘除后加减，有括号先算括号"}, {"key": "B", "text": "从左到右"}, {"key": "C", "text": "先加减后乘除"}, {"key": "D", "text": "随意"}]','A','分式混合运算：乘方→乘除→加减，括号优先','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0253-1','math','初中',10,'jkp-0253','single_choice',0.65,'5x⁻¹ 用分式表示为？','[{"key": "A", "text": "5/x"}, {"key": "B", "text": "x/5"}, {"key": "C", "text": "1/(5x)"}, {"key": "D", "text": "5x"}]','A','负指数转分式：5x⁻¹=5/x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0253-2','math','初中',10,'jkp-0253','single_choice',0.65,'3x⁻¹ 用分式表示为？','[{"key": "A", "text": "3/x"}, {"key": "B", "text": "x/3"}, {"key": "C", "text": "1/(3x)"}, {"key": "D", "text": "3x"}]','A','负指数转分式：3x⁻¹=3/x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0253-3','math','初中',10,'jkp-0253','single_choice',0.65,'2x⁻¹ 用分式表示为？','[{"key": "A", "text": "2/x"}, {"key": "B", "text": "x/2"}, {"key": "C", "text": "1/(2x)"}, {"key": "D", "text": "2x"}]','A','负指数转分式：2x⁻¹=2/x','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0254-1','math','初中',10,'jkp-0254','single_choice',0.75,'分母中含未知数的方程叫？','[{"key": "A", "text": "分式方程"}, {"key": "B", "text": "整式方程"}, {"key": "C", "text": "一元一次方程"}, {"key": "D", "text": "二元一次方程"}]','A','分式方程定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0254-2','math','初中',10,'jkp-0254','single_choice',0.75,'分母中含未知数的方程叫？','[{"key": "C", "text": "一元一次方程"}, {"key": "D", "text": "二元一次方程"}, {"key": "A", "text": "分式方程"}, {"key": "B", "text": "整式方程"}]','A','分式方程定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0254-3','math','初中',10,'jkp-0254','single_choice',0.75,'分母中含未知数的方程叫？','[{"key": "C", "text": "一元一次方程"}, {"key": "B", "text": "整式方程"}, {"key": "D", "text": "二元一次方程"}, {"key": "A", "text": "分式方程"}]','A','分式方程定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0255-1','math','初中',10,'jkp-0255','single_choice',0.35,'解分式方程 1/x = 3，去分母（两边乘 x）得？','[{"key": "A", "text": "1 = 3x"}, {"key": "B", "text": "x = 3"}, {"key": "C", "text": "1 = x"}, {"key": "D", "text": "3 = x"}]','A','两边乘 x：1=3x → x=1/3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0255-2','math','初中',10,'jkp-0255','single_choice',0.35,'解分式方程 1/x = 2，去分母（两边乘 x）得？','[{"key": "A", "text": "1 = 2x"}, {"key": "B", "text": "x = 2"}, {"key": "C", "text": "1 = x"}, {"key": "D", "text": "2 = x"}]','A','两边乘 x：1=2x → x=1/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0255-3','math','初中',10,'jkp-0255','single_choice',0.35,'解分式方程 1/x = 3，去分母（两边乘 x）得？','[{"key": "D", "text": "3 = x"}, {"key": "C", "text": "1 = x"}, {"key": "A", "text": "1 = 3x"}, {"key": "B", "text": "x = 3"}]','A','两边乘 x：1=3x → x=1/3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0256-1','math','初中',10,'jkp-0256','single_choice',0.45,'解分式方程后必须？','[{"key": "A", "text": "检验（是否增根）"}, {"key": "B", "text": "不需要检验"}, {"key": "C", "text": "只验正数"}, {"key": "D", "text": "只验整数"}]','A','分式方程必须检验增根','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0256-2','math','初中',10,'jkp-0256','single_choice',0.45,'解分式方程后必须？','[{"key": "A", "text": "检验（是否增根）"}, {"key": "C", "text": "只验正数"}, {"key": "D", "text": "只验整数"}, {"key": "B", "text": "不需要检验"}]','A','分式方程必须检验增根','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0256-3','math','初中',10,'jkp-0256','single_choice',0.45,'解分式方程后必须？','[{"key": "D", "text": "只验整数"}, {"key": "C", "text": "只验正数"}, {"key": "A", "text": "检验（是否增根）"}, {"key": "B", "text": "不需要检验"}]','A','分式方程必须检验增根','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0257-1','math','初中',10,'jkp-0257','single_choice',0.55,'分式方程产生增根的原因是？','[{"key": "A", "text": "去分母时乘了含未知数的式子，可能使分母为0"}, {"key": "B", "text": "计算错误"}, {"key": "C", "text": "题目错误"}, {"key": "D", "text": "解错了"}]','A','增根：去分母引入的使分母为 0 的根','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0257-2','math','初中',10,'jkp-0257','single_choice',0.55,'分式方程产生增根的原因是？','[{"key": "C", "text": "题目错误"}, {"key": "B", "text": "计算错误"}, {"key": "A", "text": "去分母时乘了含未知数的式子，可能使分母为0"}, {"key": "D", "text": "解错了"}]','A','增根：去分母引入的使分母为 0 的根','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0257-3','math','初中',10,'jkp-0257','single_choice',0.55,'分式方程产生增根的原因是？','[{"key": "A", "text": "去分母时乘了含未知数的式子，可能使分母为0"}, {"key": "B", "text": "计算错误"}, {"key": "D", "text": "解错了"}, {"key": "C", "text": "题目错误"}]','A','增根：去分母引入的使分母为 0 的根','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0258-1','math','初中',10,'jkp-0258','single_choice',0.65,'一项工程甲独做需 5 天，乙独做需 4 天，合做 x 天完成 → 列分式方程？','[{"key": "A", "text": "x/5 + x/4 = 1"}, {"key": "B", "text": "x/(5+4) = 1"}, {"key": "C", "text": "5/x + 4/x = 1"}, {"key": "D", "text": "x/5 = 1"}]','A','效率乘时间：x/5+x/4=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0258-2','math','初中',10,'jkp-0258','single_choice',0.65,'一项工程甲独做需 3 天，乙独做需 3 天，合做 x 天完成 → 列分式方程？','[{"key": "A", "text": "x/3 + x/3 = 1"}, {"key": "B", "text": "x/(3+3) = 1"}, {"key": "C", "text": "3/x + 3/x = 1"}, {"key": "D", "text": "x/3 = 1"}]','A','效率乘时间：x/3+x/3=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0258-3','math','初中',10,'jkp-0258','single_choice',0.65,'一项工程甲独做需 3 天，乙独做需 2 天，合做 x 天完成 → 列分式方程？','[{"key": "A", "text": "x/3 + x/2 = 1"}, {"key": "B", "text": "x/(3+2) = 1"}, {"key": "C", "text": "3/x + 2/x = 1"}, {"key": "D", "text": "x/3 = 1"}]','A','效率乘时间：x/3+x/2=1','template-j','approved','通用');