-- 第9章 不等式与不等式组 补题（8学期, 知识点 131-145）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0131-1','math','初中',8,'jkp-0131','single_choice',0.45,'下列是不等式的是？','[{"key": "A", "text": "x + 3 > 5"}, {"key": "B", "text": "x + 3 = 5"}, {"key": "C", "text": "x + 3"}, {"key": "D", "text": "3 + 5"}]','A','用不等号连接的是不等式','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0131-2','math','初中',8,'jkp-0131','single_choice',0.45,'下列是不等式的是？','[{"key": "D", "text": "3 + 5"}, {"key": "B", "text": "x + 3 = 5"}, {"key": "C", "text": "x + 3"}, {"key": "A", "text": "x + 3 > 5"}]','A','用不等号连接的是不等式','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0131-3','math','初中',8,'jkp-0131','single_choice',0.45,'下列是不等式的是？','[{"key": "D", "text": "3 + 5"}, {"key": "B", "text": "x + 3 = 5"}, {"key": "A", "text": "x + 3 > 5"}, {"key": "C", "text": "x + 3"}]','A','用不等号连接的是不等式','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0132-1','math','初中',8,'jkp-0132','single_choice',0.55,'不等式 x > 2 的解集是？','[{"key": "A", "text": "x > 2"}, {"key": "B", "text": "x < 2"}, {"key": "C", "text": "x = 2"}, {"key": "D", "text": "x ≥ {a}"}]','A','解集为 x>2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0132-2','math','初中',8,'jkp-0132','single_choice',0.55,'不等式 x > 8 的解集是？','[{"key": "A", "text": "x > 8"}, {"key": "B", "text": "x < 8"}, {"key": "C", "text": "x = 8"}, {"key": "D", "text": "x ≥ {a}"}]','A','解集为 x>8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0132-3','math','初中',8,'jkp-0132','single_choice',0.55,'不等式 x > 6 的解集是？','[{"key": "A", "text": "x > 6"}, {"key": "B", "text": "x < 6"}, {"key": "C", "text": "x = 6"}, {"key": "D", "text": "x ≥ {a}"}]','A','解集为 x>6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0133-1','math','初中',8,'jkp-0133','single_choice',0.65,'不等式 x ≥ 2 的解集在数轴上表示为？','[{"key": "A", "text": "从 {a} 向右，实心点"}, {"key": "B", "text": "从 {a} 向左，实心点"}, {"key": "C", "text": "从 {a} 向右，空心点"}, {"key": "D", "text": "从 {a} 向左，空心点"}]','A','x≥2：实心点，向右','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0133-2','math','初中',8,'jkp-0133','single_choice',0.65,'不等式 x ≥ 8 的解集在数轴上表示为？','[{"key": "A", "text": "从 {a} 向右，实心点"}, {"key": "B", "text": "从 {a} 向左，实心点"}, {"key": "C", "text": "从 {a} 向右，空心点"}, {"key": "D", "text": "从 {a} 向左，空心点"}]','A','x≥8：实心点，向右','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0133-3','math','初中',8,'jkp-0133','single_choice',0.65,'不等式 x ≥ 6 的解集在数轴上表示为？','[{"key": "A", "text": "从 {a} 向右，实心点"}, {"key": "B", "text": "从 {a} 向左，实心点"}, {"key": "C", "text": "从 {a} 向右，空心点"}, {"key": "D", "text": "从 {a} 向左，空心点"}]','A','x≥6：实心点，向右','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0134-1','math','初中',8,'jkp-0134','single_choice',0.75,'若 a > 4，则 a+1 > 5 依据不等式性质？','[{"key": "A", "text": "性质1（两边同加）"}, {"key": "B", "text": "性质2（同乘正数）"}, {"key": "C", "text": "性质3（同乘负数）"}, {"key": "D", "text": "无依据"}]','A','不等式两边同加一个数，不等号方向不变（性质1）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0134-2','math','初中',8,'jkp-0134','single_choice',0.75,'若 a > 2，则 a+1 > 3 依据不等式性质？','[{"key": "A", "text": "性质1（两边同加）"}, {"key": "B", "text": "性质2（同乘正数）"}, {"key": "C", "text": "性质3（同乘负数）"}, {"key": "D", "text": "无依据"}]','A','不等式两边同加一个数，不等号方向不变（性质1）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0134-3','math','初中',8,'jkp-0134','single_choice',0.75,'若 a > 8，则 a+1 > 9 依据不等式性质？','[{"key": "A", "text": "性质1（两边同加）"}, {"key": "B", "text": "性质2（同乘正数）"}, {"key": "C", "text": "性质3（同乘负数）"}, {"key": "D", "text": "无依据"}]','A','不等式两边同加一个数，不等号方向不变（性质1）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0135-1','math','初中',8,'jkp-0135','single_choice',0.35,'若 x > 2，则 3x > 6 依据不等式性质？','[{"key": "A", "text": "性质2（同乘正数）"}, {"key": "B", "text": "性质1"}, {"key": "C", "text": "性质3"}, {"key": "D", "text": "无依据"}]','A','两边同乘正数 3，不等号不变：3x>6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0135-2','math','初中',8,'jkp-0135','single_choice',0.35,'若 x > 5，则 3x > 15 依据不等式性质？','[{"key": "A", "text": "性质2（同乘正数）"}, {"key": "B", "text": "性质1"}, {"key": "C", "text": "性质3"}, {"key": "D", "text": "无依据"}]','A','两边同乘正数 3，不等号不变：3x>15','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0135-3','math','初中',8,'jkp-0135','single_choice',0.35,'若 x > 2，则 3x > 6 依据不等式性质？','[{"key": "A", "text": "性质2（同乘正数）"}, {"key": "C", "text": "性质3"}, {"key": "D", "text": "无依据"}, {"key": "B", "text": "性质1"}]','A','两边同乘正数 3，不等号不变：3x>6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0136-1','math','初中',8,'jkp-0136','single_choice',0.45,'若 x > 2，则 -x < -2 依据不等式性质？','[{"key": "A", "text": "性质3（同乘负数变号）"}, {"key": "B", "text": "性质2"}, {"key": "C", "text": "性质1"}, {"key": "D", "text": "无依据"}]','A','两边同乘 -1，不等号方向改变：-x<-2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0136-2','math','初中',8,'jkp-0136','single_choice',0.45,'若 x > 4，则 -x < -4 依据不等式性质？','[{"key": "A", "text": "性质3（同乘负数变号）"}, {"key": "B", "text": "性质2"}, {"key": "C", "text": "性质1"}, {"key": "D", "text": "无依据"}]','A','两边同乘 -1，不等号方向改变：-x<-4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0136-3','math','初中',8,'jkp-0136','single_choice',0.45,'若 x > 2，则 -x < -2 依据不等式性质？','[{"key": "B", "text": "性质2"}, {"key": "C", "text": "性质1"}, {"key": "A", "text": "性质3（同乘负数变号）"}, {"key": "D", "text": "无依据"}]','A','两边同乘 -1，不等号方向改变：-x<-2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0137-1','math','初中',8,'jkp-0137','single_choice',0.55,'下列是一元一次不等式的是？','[{"key": "A", "text": "2x - 3 > 1"}, {"key": "B", "text": "x² > 1"}, {"key": "C", "text": "2x + y > 1"}, {"key": "D", "text": "1/x > 2"}]','A','一个未知数、一次、整式不等式','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0137-2','math','初中',8,'jkp-0137','single_choice',0.55,'下列是一元一次不等式的是？','[{"key": "D", "text": "1/x > 2"}, {"key": "A", "text": "2x - 3 > 1"}, {"key": "B", "text": "x² > 1"}, {"key": "C", "text": "2x + y > 1"}]','A','一个未知数、一次、整式不等式','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0138-1','math','初中',8,'jkp-0138','single_choice',0.65,'解不等式 5x > 30，两边除以 5 得 x = ？','[{"key": "A", "text": "x > 6"}, {"key": "B", "text": "x < 6"}, {"key": "C", "text": "x > 30"}, {"key": "D", "text": "x > 5"}]','A','两边除以正数 5：x > 6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0138-2','math','初中',8,'jkp-0138','single_choice',0.65,'解不等式 5x > 25，两边除以 5 得 x = ？','[{"key": "A", "text": "x > 5"}, {"key": "B", "text": "x < 5"}, {"key": "C", "text": "x > 25"}, {"key": "D", "text": "x > 5"}]','A','两边除以正数 5：x > 5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0138-3','math','初中',8,'jkp-0138','single_choice',0.65,'解不等式 2x > 6，两边除以 2 得 x = ？','[{"key": "A", "text": "x > 3"}, {"key": "B", "text": "x < 3"}, {"key": "C", "text": "x > 6"}, {"key": "D", "text": "x > 2"}]','A','两边除以正数 2：x > 3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0139-1','math','初中',8,'jkp-0139','single_choice',0.75,'不等式 x < 4 的整数解有？个','[{"key": "A", "text": "4"}, {"key": "B", "text": "3"}, {"key": "C", "text": "5"}, {"key": "D", "text": "无数"}]','A','x 取 1,2,...,3 共 3 个正整数解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0139-2','math','初中',8,'jkp-0139','single_choice',0.75,'不等式 x < 6 的整数解有？个','[{"key": "A", "text": "6"}, {"key": "B", "text": "5"}, {"key": "C", "text": "7"}, {"key": "D", "text": "无数"}]','A','x 取 1,2,...,5 共 5 个正整数解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0139-3','math','初中',8,'jkp-0139','single_choice',0.75,'不等式 x < 5 的整数解有？个','[{"key": "A", "text": "5"}, {"key": "B", "text": "4"}, {"key": "C", "text": "6"}, {"key": "D", "text": "无数"}]','A','x 取 1,2,...,4 共 4 个正整数解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0140-1','math','初中',8,'jkp-0140','single_choice',0.35,'至少需要 4 个苹果才能满足每人 1 个（有 5 人）→ 设苹果 x，列不等式？','[{"key": "A", "text": "x ≥ 4"}, {"key": "B", "text": "x > 4"}, {"key": "C", "text": "x ≤ 4"}, {"key": "D", "text": "x < 4"}]','A','至少 → x ≥ 4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0140-2','math','初中',8,'jkp-0140','single_choice',0.35,'至少需要 6 个苹果才能满足每人 1 个（有 5 人）→ 设苹果 x，列不等式？','[{"key": "A", "text": "x ≥ 6"}, {"key": "B", "text": "x > 6"}, {"key": "C", "text": "x ≤ 6"}, {"key": "D", "text": "x < 6"}]','A','至少 → x ≥ 6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0140-3','math','初中',8,'jkp-0140','single_choice',0.35,'至少需要 7 个苹果才能满足每人 1 个（有 5 人）→ 设苹果 x，列不等式？','[{"key": "A", "text": "x ≥ 7"}, {"key": "B", "text": "x > 7"}, {"key": "C", "text": "x ≤ 7"}, {"key": "D", "text": "x < 7"}]','A','至少 → x ≥ 7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0141-1','math','初中',8,'jkp-0141','single_choice',0.45,'几个一元一次不等式合在一起组成？','[{"key": "A", "text": "一元一次不等式组"}, {"key": "B", "text": "方程组"}, {"key": "C", "text": "分式方程"}, {"key": "D", "text": "不等式"}]','A','不等式组定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0141-2','math','初中',8,'jkp-0141','single_choice',0.45,'几个一元一次不等式合在一起组成？','[{"key": "B", "text": "方程组"}, {"key": "D", "text": "不等式"}, {"key": "A", "text": "一元一次不等式组"}, {"key": "C", "text": "分式方程"}]','A','不等式组定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0141-3','math','初中',8,'jkp-0141','single_choice',0.45,'几个一元一次不等式合在一起组成？','[{"key": "D", "text": "不等式"}, {"key": "A", "text": "一元一次不等式组"}, {"key": "C", "text": "分式方程"}, {"key": "B", "text": "方程组"}]','A','不等式组定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0142-1','math','初中',8,'jkp-0142','single_choice',0.55,'不等式组中所有不等式解集的公共部分叫？','[{"key": "A", "text": "不等式组的解集"}, {"key": "B", "text": "不等式的解"}, {"key": "C", "text": "方程的解"}, {"key": "D", "text": "定义域"}]','A','不等式组解集 = 各不等式解集的交集','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0142-2','math','初中',8,'jkp-0142','single_choice',0.55,'不等式组中所有不等式解集的公共部分叫？','[{"key": "B", "text": "不等式的解"}, {"key": "A", "text": "不等式组的解集"}, {"key": "D", "text": "定义域"}, {"key": "C", "text": "方程的解"}]','A','不等式组解集 = 各不等式解集的交集','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0142-3','math','初中',8,'jkp-0142','single_choice',0.55,'不等式组中所有不等式解集的公共部分叫？','[{"key": "A", "text": "不等式组的解集"}, {"key": "D", "text": "定义域"}, {"key": "B", "text": "不等式的解"}, {"key": "C", "text": "方程的解"}]','A','不等式组解集 = 各不等式解集的交集','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0143-1','math','初中',8,'jkp-0143','single_choice',0.65,'不等式组 {x>2, x<5} 的解集是？','[{"key": "A", "text": "2 < x < 5"}, {"key": "B", "text": "x > 5"}, {"key": "C", "text": "x < 2"}, {"key": "D", "text": "无解"}]','A','大小小大取中间：2<x<5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0143-2','math','初中',8,'jkp-0143','single_choice',0.65,'不等式组 {x>2, x<5} 的解集是？','[{"key": "B", "text": "x > 5"}, {"key": "A", "text": "2 < x < 5"}, {"key": "D", "text": "无解"}, {"key": "C", "text": "x < 2"}]','A','大小小大取中间：2<x<5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0143-3','math','初中',8,'jkp-0143','single_choice',0.65,'不等式组 {x>2, x<5} 的解集是？','[{"key": "D", "text": "无解"}, {"key": "C", "text": "x < 2"}, {"key": "B", "text": "x > 5"}, {"key": "A", "text": "2 < x < 5"}]','A','大小小大取中间：2<x<5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0144-1','math','初中',8,'jkp-0144','single_choice',0.75,'解不等式组 {x > 2, x < 7}，解集为？','[{"key": "A", "text": "2 < x < 7"}, {"key": "B", "text": "x > 7"}, {"key": "C", "text": "x < 2"}, {"key": "D", "text": "无解"}]','A','解集：2<x<7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0144-2','math','初中',8,'jkp-0144','single_choice',0.75,'解不等式组 {x > 5, x < 9}，解集为？','[{"key": "A", "text": "5 < x < 9"}, {"key": "B", "text": "x > 9"}, {"key": "C", "text": "x < 5"}, {"key": "D", "text": "无解"}]','A','解集：5<x<9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0144-3','math','初中',8,'jkp-0144','single_choice',0.75,'解不等式组 {x > 3, x < 8}，解集为？','[{"key": "A", "text": "3 < x < 8"}, {"key": "B", "text": "x > 8"}, {"key": "C", "text": "x < 3"}, {"key": "D", "text": "无解"}]','A','解集：3<x<8','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0145-1','math','初中',8,'jkp-0145','single_choice',0.35,'不等式组 {x>a, x<2} 无解，则 a 满足？','[{"key": "A", "text": "a ≥ 2"}, {"key": "B", "text": "a < 2"}, {"key": "C", "text": "a = 2"}, {"key": "D", "text": "a ≤ 2"}]','A','无解：a ≥ 2（比 2 大或相等时无交集）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0145-2','math','初中',8,'jkp-0145','single_choice',0.35,'不等式组 {x>a, x<2} 无解，则 a 满足？','[{"key": "A", "text": "a ≥ 2"}, {"key": "C", "text": "a = 2"}, {"key": "B", "text": "a < 2"}, {"key": "D", "text": "a ≤ 2"}]','A','无解：a ≥ 2（比 2 大或相等时无交集）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0145-3','math','初中',8,'jkp-0145','single_choice',0.35,'不等式组 {x>a, x<2} 无解，则 a 满足？','[{"key": "C", "text": "a = 2"}, {"key": "B", "text": "a < 2"}, {"key": "A", "text": "a ≥ 2"}, {"key": "D", "text": "a ≤ 2"}]','A','无解：a ≥ 2（比 2 大或相等时无交集）','template-j','approved','通用');