-- 第3章 一元一次方程 补题（7学期, 知识点 36-48）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0036-1','math','初中',7,'jkp-0036','single_choice',0.45,'下列是方程的是？','[{"key": "A", "text": "3x + 2 = 8"}, {"key": "B", "text": "3x + 2"}, {"key": "C", "text": "3 + 2"}, {"key": "D", "text": "x > 1"}]','A','方程：含未知数的等式','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0037-1','math','初中',7,'jkp-0037','single_choice',0.55,'下列是一元一次方程的是？','[{"key": "A", "text": "4x + 2 = 0"}, {"key": "B", "text": "x² + x = 0"}, {"key": "C", "text": "x + y = 1"}, {"key": "D", "text": "1/x = 2"}]','A','一元一次：一个未知数、一次、整式方程','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0038-1','math','初中',7,'jkp-0038','single_choice',0.65,'检验：x=5 是方程 4x = 20 的解吗？','[{"key": "A", "text": "是"}, {"key": "B", "text": "否"}, {"key": "C", "text": "无法判断"}, {"key": "D", "text": "不一定"}]','A','代入 4×5=20 成立，x=5 是解','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0039-1','math','初中',7,'jkp-0039','single_choice',0.75,'若 3x = 9，两边同除以 3 得 x = ？（等式性质2）','[{"key": "A", "text": "3"}, {"key": "B", "text": "3"}, {"key": "C", "text": "9"}, {"key": "D", "text": "1"}]','A','等式两边同除以 3：x=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0040-1','math','初中',7,'jkp-0040','single_choice',0.35,'解方程 3x + 4 = 0，移项得？','[{"key": "A", "text": "3x = -4"}, {"key": "B", "text": "3x = 4"}, {"key": "C", "text": "3x = 0"}, {"key": "D", "text": "x = 4"}]','A','移项变号：{b} 移到右边变 -{b}','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0041-1','math','初中',7,'jkp-0041','single_choice',0.45,'解方程 x/2 + 5 = 4，去分母（两边乘 2）得？','[{"key": "A", "text": "x + 10 = 8"}, {"key": "B", "text": "x + 5 = 8"}, {"key": "C", "text": "x + 10 = 4"}, {"key": "D", "text": "2x + 5 = 4"}]','A','两边乘 2：x + 2×{a} = 2×{b}','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0042-1','math','初中',7,'jkp-0042','single_choice',0.55,'解方程 3(x - 1) = 4，去括号得？','[{"key": "A", "text": "3x - 3 = 4"}, {"key": "B", "text": "3x - 1 = 4"}, {"key": "C", "text": "3x + 3 = 4"}, {"key": "D", "text": "x - 3 = 4"}]','A','分配律：3x - 3×1 = 4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0043-1','math','初中',7,'jkp-0043','single_choice',0.65,'解方程 4x = 12，系数化为 1 得 x = ？','[{"key": "A", "text": "3"}, {"key": "B", "text": "12"}, {"key": "C", "text": "4"}, {"key": "D", "text": "1"}]','A','两边同除以 4：x=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0044-1','math','初中',7,'jkp-0044','single_choice',0.75,'每台机器生产 2 个零件，需 2 台机器凑 4 个零件：列方程？','[{"key": "A", "text": "2x = 4"}, {"key": "B", "text": "x = 2"}, {"key": "C", "text": "2x = 2"}, {"key": "D", "text": "2x = 2"}]','A','每台 2 个，x 台共 2x 个，凑 4 个：2x=4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0045-1','math','初中',7,'jkp-0045','single_choice',0.35,'甲单独做需 5 天完成，则甲每天完成工程的？','[{"key": "A", "text": "1/5"}, {"key": "B", "text": "5"}, {"key": "C", "text": "1/3"}, {"key": "D", "text": "5/1"}]','A','工作效率=1/时间=1/5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0046-1','math','初中',7,'jkp-0046','single_choice',0.45,'速度 3 km/h，行驶 4 小时，路程 s = vt = ？','[{"key": "A", "text": "12"}, {"key": "B", "text": "7"}, {"key": "C", "text": "-1"}, {"key": "D", "text": "0.75"}]','A','s=vt=3×4=12','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0047-1','math','初中',7,'jkp-0047','single_choice',0.55,'进价 3 元，售价 4 元，利润 = ？','[{"key": "A", "text": "1"}, {"key": "B", "text": "3"}, {"key": "C", "text": "4"}, {"key": "D", "text": "2"}]','A','利润=售价-进价=4-3=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0048-1','math','初中',7,'jkp-0048','single_choice',0.65,'月用水不超过 3 吨每吨 2 元，超过部分每吨 3 元。用 4 吨费用 = ？','[{"key": "A", "text": "9"}, {"key": "B", "text": "8"}, {"key": "C", "text": "6"}, {"key": "D", "text": "12"}]','A','前 3 吨 3×2=6，超 1 吨 3，共 9','template-j','approved','通用');