-- 第12章 轴对称 补题（9学期, 知识点 171-186）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0171-1','math','初中',9,'jkp-0171','single_choice',0.45,'下列是轴对称图形的是？','[{"key": "A", "text": "等边三角形"}, {"key": "B", "text": "任意四边形"}, {"key": "C", "text": "平行四边形"}, {"key": "D", "text": "三角形"}]','A','等边三角形有对称轴（3 条）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0171-2','math','初中',9,'jkp-0171','single_choice',0.45,'下列是轴对称图形的是？','[{"key": "C", "text": "平行四边形"}, {"key": "B", "text": "任意四边形"}, {"key": "D", "text": "三角形"}, {"key": "A", "text": "等边三角形"}]','A','等边三角形有对称轴（3 条）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0171-3','math','初中',9,'jkp-0171','single_choice',0.45,'下列是轴对称图形的是？','[{"key": "C", "text": "平行四边形"}, {"key": "A", "text": "等边三角形"}, {"key": "B", "text": "任意四边形"}, {"key": "D", "text": "三角形"}]','A','等边三角形有对称轴（3 条）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0172-1','math','初中',9,'jkp-0172','single_choice',0.55,'关于某直线对称的两个图形，对称轴是？','[{"key": "A", "text": "对应点连线的垂直平分线"}, {"key": "B", "text": "任意直线"}, {"key": "C", "text": "对应点连线"}, {"key": "D", "text": "图形的边"}]','A','对称轴垂直平分对应点连线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0172-2','math','初中',9,'jkp-0172','single_choice',0.55,'关于某直线对称的两个图形，对称轴是？','[{"key": "D", "text": "图形的边"}, {"key": "C", "text": "对应点连线"}, {"key": "B", "text": "任意直线"}, {"key": "A", "text": "对应点连线的垂直平分线"}]','A','对称轴垂直平分对应点连线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0172-3','math','初中',9,'jkp-0172','single_choice',0.55,'关于某直线对称的两个图形，对称轴是？','[{"key": "A", "text": "对应点连线的垂直平分线"}, {"key": "C", "text": "对应点连线"}, {"key": "D", "text": "图形的边"}, {"key": "B", "text": "任意直线"}]','A','对称轴垂直平分对应点连线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0173-1','math','初中',9,'jkp-0173','single_choice',0.65,'轴对称图形的对称轴垂直平分？','[{"key": "A", "text": "对应点连线"}, {"key": "B", "text": "对应边"}, {"key": "C", "text": "对应角"}, {"key": "D", "text": "高线"}]','A','对称轴是任意一对对应点连线的垂直平分线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0173-2','math','初中',9,'jkp-0173','single_choice',0.65,'轴对称图形的对称轴垂直平分？','[{"key": "C", "text": "对应角"}, {"key": "D", "text": "高线"}, {"key": "B", "text": "对应边"}, {"key": "A", "text": "对应点连线"}]','A','对称轴是任意一对对应点连线的垂直平分线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0173-3','math','初中',9,'jkp-0173','single_choice',0.65,'轴对称图形的对称轴垂直平分？','[{"key": "D", "text": "高线"}, {"key": "B", "text": "对应边"}, {"key": "C", "text": "对应角"}, {"key": "A", "text": "对应点连线"}]','A','对称轴是任意一对对应点连线的垂直平分线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0174-1','math','初中',9,'jkp-0174','single_choice',0.75,'经过线段中点且垂直于这条线段的直线叫？','[{"key": "A", "text": "线段垂直平分线"}, {"key": "B", "text": "角平分线"}, {"key": "C", "text": "中线"}, {"key": "D", "text": "高线"}]','A','垂直平分线定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0174-2','math','初中',9,'jkp-0174','single_choice',0.75,'经过线段中点且垂直于这条线段的直线叫？','[{"key": "A", "text": "线段垂直平分线"}, {"key": "C", "text": "中线"}, {"key": "D", "text": "高线"}, {"key": "B", "text": "角平分线"}]','A','垂直平分线定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0174-3','math','初中',9,'jkp-0174','single_choice',0.75,'经过线段中点且垂直于这条线段的直线叫？','[{"key": "A", "text": "线段垂直平分线"}, {"key": "D", "text": "高线"}, {"key": "B", "text": "角平分线"}, {"key": "C", "text": "中线"}]','A','垂直平分线定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0175-1','math','初中',9,'jkp-0175','single_choice',0.35,'P 在线段 AB 的垂直平分线上，PA=6，则 PB = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "12"}, {"key": "C", "text": "3.0"}, {"key": "D", "text": "无法确定"}]','A','垂直平分线上点到两端点距离相等：PB=6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0175-2','math','初中',9,'jkp-0175','single_choice',0.35,'P 在线段 AB 的垂直平分线上，PA=5，则 PB = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "10"}, {"key": "C", "text": "2.5"}, {"key": "D", "text": "无法确定"}]','A','垂直平分线上点到两端点距离相等：PB=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0175-3','math','初中',9,'jkp-0175','single_choice',0.35,'P 在线段 AB 的垂直平分线上，PA=6，则 PB = ？','[{"key": "A", "text": "6"}, {"key": "C", "text": "3.0"}, {"key": "B", "text": "12"}, {"key": "D", "text": "无法确定"}]','A','垂直平分线上点到两端点距离相等：PB=6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0176-1','math','初中',9,'jkp-0176','single_choice',0.45,'到线段两端点距离相等的点，在？上','[{"key": "A", "text": "线段的垂直平分线"}, {"key": "B", "text": "线段上"}, {"key": "C", "text": "线段外"}, {"key": "D", "text": "角平分线"}]','A','垂直平分线判定','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0176-2','math','初中',9,'jkp-0176','single_choice',0.45,'到线段两端点距离相等的点，在？上','[{"key": "D", "text": "角平分线"}, {"key": "A", "text": "线段的垂直平分线"}, {"key": "B", "text": "线段上"}, {"key": "C", "text": "线段外"}]','A','垂直平分线判定','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0176-3','math','初中',9,'jkp-0176','single_choice',0.45,'到线段两端点距离相等的点，在？上','[{"key": "B", "text": "线段上"}, {"key": "C", "text": "线段外"}, {"key": "D", "text": "角平分线"}, {"key": "A", "text": "线段的垂直平分线"}]','A','垂直平分线判定','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0177-1','math','初中',9,'jkp-0177','single_choice',0.55,'尺规作垂直平分线，作图的依据是？','[{"key": "A", "text": "到两端点距离相等的点在垂直平分线上"}, {"key": "B", "text": "SSS"}, {"key": "C", "text": "角平分线"}, {"key": "D", "text": "中位线"}]','A','作垂直平分线的原理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0177-2','math','初中',9,'jkp-0177','single_choice',0.55,'尺规作垂直平分线，作图的依据是？','[{"key": "B", "text": "SSS"}, {"key": "C", "text": "角平分线"}, {"key": "D", "text": "中位线"}, {"key": "A", "text": "到两端点距离相等的点在垂直平分线上"}]','A','作垂直平分线的原理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0177-3','math','初中',9,'jkp-0177','single_choice',0.55,'尺规作垂直平分线，作图的依据是？','[{"key": "C", "text": "角平分线"}, {"key": "B", "text": "SSS"}, {"key": "A", "text": "到两端点距离相等的点在垂直平分线上"}, {"key": "D", "text": "中位线"}]','A','作垂直平分线的原理','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0178-1','math','初中',9,'jkp-0178','single_choice',0.65,'点 (2,5) 关于 x 轴对称的点是？','[{"key": "A", "text": "(2,-5)"}, {"key": "B", "text": "(-2,5)"}, {"key": "C", "text": "(-2,-5)"}, {"key": "D", "text": "(5,2)"}]','A','关于 x 轴对称：纵坐标变号 → (2,-5)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0178-2','math','初中',9,'jkp-0178','single_choice',0.65,'点 (3,4) 关于 x 轴对称的点是？','[{"key": "A", "text": "(3,-4)"}, {"key": "B", "text": "(-3,4)"}, {"key": "C", "text": "(-3,-4)"}, {"key": "D", "text": "(4,3)"}]','A','关于 x 轴对称：纵坐标变号 → (3,-4)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0178-3','math','初中',9,'jkp-0178','single_choice',0.65,'点 (4,4) 关于 x 轴对称的点是？','[{"key": "A", "text": "(4,-4)"}, {"key": "B", "text": "(-4,4)"}, {"key": "C", "text": "(-4,-4)"}, {"key": "D", "text": "(4,4)"}]','A','关于 x 轴对称：纵坐标变号 → (4,-4)','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0179-1','math','初中',9,'jkp-0179','single_choice',0.75,'有两边相等的三角形叫？','[{"key": "A", "text": "等腰三角形"}, {"key": "B", "text": "等边三角形"}, {"key": "C", "text": "直角三角形"}, {"key": "D", "text": "钝角三角形"}]','A','等腰三角形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0179-2','math','初中',9,'jkp-0179','single_choice',0.75,'有两边相等的三角形叫？','[{"key": "C", "text": "直角三角形"}, {"key": "D", "text": "钝角三角形"}, {"key": "B", "text": "等边三角形"}, {"key": "A", "text": "等腰三角形"}]','A','等腰三角形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0179-3','math','初中',9,'jkp-0179','single_choice',0.75,'有两边相等的三角形叫？','[{"key": "B", "text": "等边三角形"}, {"key": "D", "text": "钝角三角形"}, {"key": "A", "text": "等腰三角形"}, {"key": "C", "text": "直角三角形"}]','A','等腰三角形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0180-1','math','初中',9,'jkp-0180','single_choice',0.35,'等腰三角形顶角为 60°，则底角 = ？','[{"key": "A", "text": "60°"}, {"key": "B", "text": "120°"}, {"key": "C", "text": "30°"}, {"key": "D", "text": "120°"}]','A','等边对等角：底角=(120)°/2=60°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0180-2','math','初中',9,'jkp-0180','single_choice',0.35,'等腰三角形顶角为 102°，则底角 = ？','[{"key": "A", "text": "39°"}, {"key": "B", "text": "78°"}, {"key": "C", "text": "51°"}, {"key": "D", "text": "141°"}]','A','等边对等角：底角=(78)°/2=39°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0180-3','math','初中',9,'jkp-0180','single_choice',0.35,'等腰三角形顶角为 62°，则底角 = ？','[{"key": "A", "text": "59°"}, {"key": "B", "text": "118°"}, {"key": "C", "text": "31°"}, {"key": "D", "text": "121°"}]','A','等边对等角：底角=(118)°/2=59°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0181-1','math','初中',9,'jkp-0181','single_choice',0.45,'等腰三角形顶角平分线、底边中线、底边高线？','[{"key": "A", "text": "三线合一"}, {"key": "B", "text": "互相平行"}, {"key": "C", "text": "互相垂直"}, {"key": "D", "text": "互相平分"}]','A','等腰三角形三线合一','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0181-2','math','初中',9,'jkp-0181','single_choice',0.45,'等腰三角形顶角平分线、底边中线、底边高线？','[{"key": "C", "text": "互相垂直"}, {"key": "D", "text": "互相平分"}, {"key": "A", "text": "三线合一"}, {"key": "B", "text": "互相平行"}]','A','等腰三角形三线合一','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0181-3','math','初中',9,'jkp-0181','single_choice',0.45,'等腰三角形顶角平分线、底边中线、底边高线？','[{"key": "C", "text": "互相垂直"}, {"key": "B", "text": "互相平行"}, {"key": "D", "text": "互相平分"}, {"key": "A", "text": "三线合一"}]','A','等腰三角形三线合一','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0182-1','math','初中',9,'jkp-0182','single_choice',0.55,'有两个角相等的三角形是？','[{"key": "A", "text": "等腰三角形"}, {"key": "B", "text": "等边三角形"}, {"key": "C", "text": "直角三角形"}, {"key": "D", "text": "钝角三角形"}]','A','等角对等边 → 等腰','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0182-2','math','初中',9,'jkp-0182','single_choice',0.55,'有两个角相等的三角形是？','[{"key": "D", "text": "钝角三角形"}, {"key": "C", "text": "直角三角形"}, {"key": "A", "text": "等腰三角形"}, {"key": "B", "text": "等边三角形"}]','A','等角对等边 → 等腰','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0182-3','math','初中',9,'jkp-0182','single_choice',0.55,'有两个角相等的三角形是？','[{"key": "D", "text": "钝角三角形"}, {"key": "B", "text": "等边三角形"}, {"key": "A", "text": "等腰三角形"}, {"key": "C", "text": "直角三角形"}]','A','等角对等边 → 等腰','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0183-1','math','初中',9,'jkp-0183','single_choice',0.65,'等边三角形的每个内角都是？','[{"key": "A", "text": "60°"}, {"key": "B", "text": "45°"}, {"key": "C", "text": "90°"}, {"key": "D", "text": "30°"}]','A','等边三角形三角都是 60°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0183-2','math','初中',9,'jkp-0183','single_choice',0.65,'等边三角形的每个内角都是？','[{"key": "C", "text": "90°"}, {"key": "A", "text": "60°"}, {"key": "B", "text": "45°"}, {"key": "D", "text": "30°"}]','A','等边三角形三角都是 60°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0183-3','math','初中',9,'jkp-0183','single_choice',0.65,'等边三角形的每个内角都是？','[{"key": "C", "text": "90°"}, {"key": "A", "text": "60°"}, {"key": "D", "text": "30°"}, {"key": "B", "text": "45°"}]','A','等边三角形三角都是 60°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0184-1','math','初中',9,'jkp-0184','single_choice',0.75,'下列能判定等边三角形的是？','[{"key": "A", "text": "三边相等"}, {"key": "B", "text": "两边相等"}, {"key": "C", "text": "一个角 60° 的普通三角形"}, {"key": "D", "text": "一个角 90°"}]','A','等边判定：三边相等/三角相等/一角 60° 的等腰','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0184-2','math','初中',9,'jkp-0184','single_choice',0.75,'下列能判定等边三角形的是？','[{"key": "A", "text": "三边相等"}, {"key": "D", "text": "一个角 90°"}, {"key": "C", "text": "一个角 60° 的普通三角形"}, {"key": "B", "text": "两边相等"}]','A','等边判定：三边相等/三角相等/一角 60° 的等腰','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0184-3','math','初中',9,'jkp-0184','single_choice',0.75,'下列能判定等边三角形的是？','[{"key": "D", "text": "一个角 90°"}, {"key": "B", "text": "两边相等"}, {"key": "C", "text": "一个角 60° 的普通三角形"}, {"key": "A", "text": "三边相等"}]','A','等边判定：三边相等/三角相等/一角 60° 的等腰','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0185-1','math','初中',9,'jkp-0185','single_choice',0.35,'含 30° 角的直角三角形中，30° 角所对直角边 = 2，则斜边 = ？','[{"key": "A", "text": "4"}, {"key": "B", "text": "2"}, {"key": "C", "text": "1.0"}, {"key": "D", "text": "6"}]','A','30° 对边 = 斜边的一半 → 斜边 = 4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0185-2','math','初中',9,'jkp-0185','single_choice',0.35,'含 30° 角的直角三角形中，30° 角所对直角边 = 3，则斜边 = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "3"}, {"key": "C", "text": "1.5"}, {"key": "D", "text": "9"}]','A','30° 对边 = 斜边的一半 → 斜边 = 6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0185-3','math','初中',9,'jkp-0185','single_choice',0.35,'含 30° 角的直角三角形中，30° 角所对直角边 = 2，则斜边 = ？','[{"key": "A", "text": "4"}, {"key": "D", "text": "6"}, {"key": "C", "text": "1.0"}, {"key": "B", "text": "2"}]','A','30° 对边 = 斜边的一半 → 斜边 = 4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0186-1','math','初中',9,'jkp-0186','single_choice',0.45,'将军饮马问题的核心是作？','[{"key": "A", "text": "对称点再连线（两点之间线段最短）"}, {"key": "B", "text": "垂线段"}, {"key": "C", "text": "角平分线"}, {"key": "D", "text": "中线"}]','A','将军饮马：对称 → 共线最短','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0186-2','math','初中',9,'jkp-0186','single_choice',0.45,'将军饮马问题的核心是作？','[{"key": "A", "text": "对称点再连线（两点之间线段最短）"}, {"key": "D", "text": "中线"}, {"key": "B", "text": "垂线段"}, {"key": "C", "text": "角平分线"}]','A','将军饮马：对称 → 共线最短','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0186-3','math','初中',9,'jkp-0186','single_choice',0.45,'将军饮马问题的核心是作？','[{"key": "C", "text": "角平分线"}, {"key": "D", "text": "中线"}, {"key": "B", "text": "垂线段"}, {"key": "A", "text": "对称点再连线（两点之间线段最短）"}]','A','将军饮马：对称 → 共线最短','template-j','approved','通用');