-- 第7章 三角形 补题（8学期, 知识点 100-118）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0100-1','math','初中',8,'jkp-0100','single_choice',0.35,'三角形有？条边、？个顶点、？个内角','[{"key": "A", "text": "3、3、3"}, {"key": "B", "text": "3、3、4"}, {"key": "C", "text": "4、4、3"}, {"key": "D", "text": "3、4、3"}]','A','三角形：3 边 3 顶点 3 内角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0100-2','math','初中',8,'jkp-0100','single_choice',0.35,'三角形有？条边、？个顶点、？个内角','[{"key": "A", "text": "3、3、3"}, {"key": "D", "text": "3、4、3"}, {"key": "B", "text": "3、3、4"}, {"key": "C", "text": "4、4、3"}]','A','三角形：3 边 3 顶点 3 内角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0101-1','math','初中',8,'jkp-0101','single_choice',0.45,'三边都不相等的三角形叫？','[{"key": "A", "text": "不等边三角形"}, {"key": "B", "text": "等腰三角形"}, {"key": "C", "text": "等边三角形"}, {"key": "D", "text": "直角三角形"}]','A','按边分类：不等边、等腰（含等边）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0101-2','math','初中',8,'jkp-0101','single_choice',0.45,'三边都不相等的三角形叫？','[{"key": "C", "text": "等边三角形"}, {"key": "B", "text": "等腰三角形"}, {"key": "A", "text": "不等边三角形"}, {"key": "D", "text": "直角三角形"}]','A','按边分类：不等边、等腰（含等边）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0101-3','math','初中',8,'jkp-0101','single_choice',0.45,'三边都不相等的三角形叫？','[{"key": "A", "text": "不等边三角形"}, {"key": "B", "text": "等腰三角形"}, {"key": "D", "text": "直角三角形"}, {"key": "C", "text": "等边三角形"}]','A','按边分类：不等边、等腰（含等边）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0102-1','math','初中',8,'jkp-0102','single_choice',0.55,'有一个角是 90° 的三角形是？','[{"key": "A", "text": "直角三角形"}, {"key": "B", "text": "锐角三角形"}, {"key": "C", "text": "钝角三角形"}, {"key": "D", "text": "等腰三角形"}]','A','按角分类：锐角、直角、钝角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0102-2','math','初中',8,'jkp-0102','single_choice',0.55,'有一个角是 90° 的三角形是？','[{"key": "B", "text": "锐角三角形"}, {"key": "D", "text": "等腰三角形"}, {"key": "A", "text": "直角三角形"}, {"key": "C", "text": "钝角三角形"}]','A','按角分类：锐角、直角、钝角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0102-3','math','初中',8,'jkp-0102','single_choice',0.55,'有一个角是 90° 的三角形是？','[{"key": "B", "text": "锐角三角形"}, {"key": "A", "text": "直角三角形"}, {"key": "D", "text": "等腰三角形"}, {"key": "C", "text": "钝角三角形"}]','A','按角分类：锐角、直角、钝角','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0103-1','math','初中',8,'jkp-0103','single_choice',0.65,'三角形三边关系定理是？','[{"key": "A", "text": "任意两边之和大于第三边"}, {"key": "B", "text": "任意两边之差大于第三边"}, {"key": "C", "text": "两边之和等于第三边"}, {"key": "D", "text": "任意两边之和小于第三边"}]','A','三角形两边之和大于第三边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0103-2','math','初中',8,'jkp-0103','single_choice',0.65,'三角形三边关系定理是？','[{"key": "C", "text": "两边之和等于第三边"}, {"key": "A", "text": "任意两边之和大于第三边"}, {"key": "D", "text": "任意两边之和小于第三边"}, {"key": "B", "text": "任意两边之差大于第三边"}]','A','三角形两边之和大于第三边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0103-3','math','初中',8,'jkp-0103','single_choice',0.65,'三角形三边关系定理是？','[{"key": "A", "text": "任意两边之和大于第三边"}, {"key": "D", "text": "任意两边之和小于第三边"}, {"key": "B", "text": "任意两边之差大于第三边"}, {"key": "C", "text": "两边之和等于第三边"}]','A','三角形两边之和大于第三边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0104-1','math','初中',8,'jkp-0104','single_choice',0.75,'3、5、7 三条线段能构成三角形吗？','[{"key": "A", "text": "能"}, {"key": "B", "text": "不能"}, {"key": "C", "text": "不一定"}, {"key": "D", "text": "无法判断"}]','A','3+5=8>7，且其他两边之和也满足 → 能','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0104-2','math','初中',8,'jkp-0104','single_choice',0.75,'5、6、10 三条线段能构成三角形吗？','[{"key": "A", "text": "能"}, {"key": "B", "text": "不能"}, {"key": "C", "text": "不一定"}, {"key": "D", "text": "无法判断"}]','A','5+6=11>10，且其他两边之和也满足 → 能','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0104-3','math','初中',8,'jkp-0104','single_choice',0.75,'5、3、7 三条线段能构成三角形吗？','[{"key": "A", "text": "能"}, {"key": "B", "text": "不能"}, {"key": "C", "text": "不一定"}, {"key": "D", "text": "无法判断"}]','A','5+3=8>7，且其他两边之和也满足 → 能','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0105-1','math','初中',8,'jkp-0105','single_choice',0.35,'从三角形一个顶点向对边作垂线，顶点到垂足的线段叫？','[{"key": "A", "text": "高"}, {"key": "B", "text": "中线"}, {"key": "C", "text": "角平分线"}, {"key": "D", "text": "中位线"}]','A','三角形的高','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0105-2','math','初中',8,'jkp-0105','single_choice',0.35,'从三角形一个顶点向对边作垂线，顶点到垂足的线段叫？','[{"key": "C", "text": "角平分线"}, {"key": "D", "text": "中位线"}, {"key": "B", "text": "中线"}, {"key": "A", "text": "高"}]','A','三角形的高','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0105-3','math','初中',8,'jkp-0105','single_choice',0.35,'从三角形一个顶点向对边作垂线，顶点到垂足的线段叫？','[{"key": "A", "text": "高"}, {"key": "D", "text": "中位线"}, {"key": "B", "text": "中线"}, {"key": "C", "text": "角平分线"}]','A','三角形的高','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0106-1','math','初中',8,'jkp-0106','single_choice',0.45,'三角形三条中线交于一点，该点是？','[{"key": "A", "text": "重心"}, {"key": "B", "text": "外心"}, {"key": "C", "text": "内心"}, {"key": "D", "text": "垂心"}]','A','重心：三条中线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0106-2','math','初中',8,'jkp-0106','single_choice',0.45,'三角形三条中线交于一点，该点是？','[{"key": "C", "text": "内心"}, {"key": "D", "text": "垂心"}, {"key": "B", "text": "外心"}, {"key": "A", "text": "重心"}]','A','重心：三条中线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0106-3','math','初中',8,'jkp-0106','single_choice',0.45,'三角形三条中线交于一点，该点是？','[{"key": "B", "text": "外心"}, {"key": "D", "text": "垂心"}, {"key": "C", "text": "内心"}, {"key": "A", "text": "重心"}]','A','重心：三条中线交点','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0107-1','math','初中',8,'jkp-0107','single_choice',0.55,'三角形一个角的平分线交对边于一点，顶点到交点的线段叫？','[{"key": "A", "text": "角平分线"}, {"key": "B", "text": "中线"}, {"key": "C", "text": "高"}, {"key": "D", "text": "中位线"}]','A','三角形角平分线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0107-2','math','初中',8,'jkp-0107','single_choice',0.55,'三角形一个角的平分线交对边于一点，顶点到交点的线段叫？','[{"key": "D", "text": "中位线"}, {"key": "A", "text": "角平分线"}, {"key": "C", "text": "高"}, {"key": "B", "text": "中线"}]','A','三角形角平分线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0107-3','math','初中',8,'jkp-0107','single_choice',0.55,'三角形一个角的平分线交对边于一点，顶点到交点的线段叫？','[{"key": "C", "text": "高"}, {"key": "A", "text": "角平分线"}, {"key": "B", "text": "中线"}, {"key": "D", "text": "中位线"}]','A','三角形角平分线','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0108-1','math','初中',8,'jkp-0108','single_choice',0.65,'△ABC 中 ∠A=57°，∠B=59°，则 ∠C = ？','[{"key": "A", "text": "64°"}, {"key": "B", "text": "116°"}, {"key": "C", "text": "-26°"}, {"key": "D", "text": "90°"}]','A','内角和 180°：∠C=180°-57°-59°=64°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0108-2','math','初中',8,'jkp-0108','single_choice',0.65,'△ABC 中 ∠A=48°，∠B=57°，则 ∠C = ？','[{"key": "A", "text": "75°"}, {"key": "B", "text": "105°"}, {"key": "C", "text": "-15°"}, {"key": "D", "text": "90°"}]','A','内角和 180°：∠C=180°-48°-57°=75°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0108-3','math','初中',8,'jkp-0108','single_choice',0.65,'△ABC 中 ∠A=33°，∠B=57°，则 ∠C = ？','[{"key": "A", "text": "90°"}, {"key": "B", "text": "90°"}, {"key": "C", "text": "0°"}, {"key": "D", "text": "90°"}]','A','内角和 180°：∠C=180°-33°-57°=90°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0109-1','math','初中',8,'jkp-0109','single_choice',0.75,'三角形内角和定理的证明常用？','[{"key": "A", "text": "过顶点作对边平行线（平角转化）"}, {"key": "B", "text": "测量三个角"}, {"key": "C", "text": "剪拼"}, {"key": "D", "text": "外角定理"}]','A','作平行线，将三个角移到同一平角上','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0109-2','math','初中',8,'jkp-0109','single_choice',0.75,'三角形内角和定理的证明常用？','[{"key": "D", "text": "外角定理"}, {"key": "B", "text": "测量三个角"}, {"key": "A", "text": "过顶点作对边平行线（平角转化）"}, {"key": "C", "text": "剪拼"}]','A','作平行线，将三个角移到同一平角上','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0109-3','math','初中',8,'jkp-0109','single_choice',0.75,'三角形内角和定理的证明常用？','[{"key": "C", "text": "剪拼"}, {"key": "B", "text": "测量三个角"}, {"key": "D", "text": "外角定理"}, {"key": "A", "text": "过顶点作对边平行线（平角转化）"}]','A','作平行线，将三个角移到同一平角上','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0110-1','math','初中',8,'jkp-0110','single_choice',0.35,'直角三角形两锐角的关系是？','[{"key": "A", "text": "互余（和为90°）"}, {"key": "B", "text": "互补（和为180°）"}, {"key": "C", "text": "相等"}, {"key": "D", "text": "无关"}]','A','直角三角形两锐角互余','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0110-2','math','初中',8,'jkp-0110','single_choice',0.35,'直角三角形两锐角的关系是？','[{"key": "B", "text": "互补（和为180°）"}, {"key": "A", "text": "互余（和为90°）"}, {"key": "D", "text": "无关"}, {"key": "C", "text": "相等"}]','A','直角三角形两锐角互余','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0110-3','math','初中',8,'jkp-0110','single_choice',0.35,'直角三角形两锐角的关系是？','[{"key": "D", "text": "无关"}, {"key": "B", "text": "互补（和为180°）"}, {"key": "A", "text": "互余（和为90°）"}, {"key": "C", "text": "相等"}]','A','直角三角形两锐角互余','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0111-1','math','初中',8,'jkp-0111','single_choice',0.45,'三角形的一边与另一边的延长线组成的角叫？','[{"key": "A", "text": "外角"}, {"key": "B", "text": "内角"}, {"key": "C", "text": "对顶角"}, {"key": "D", "text": "邻补角"}]','A','三角形外角定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0111-2','math','初中',8,'jkp-0111','single_choice',0.45,'三角形的一边与另一边的延长线组成的角叫？','[{"key": "C", "text": "对顶角"}, {"key": "D", "text": "邻补角"}, {"key": "B", "text": "内角"}, {"key": "A", "text": "外角"}]','A','三角形外角定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0112-1','math','初中',8,'jkp-0112','single_choice',0.55,'△ABC 中 ∠A=41°，∠B=58°，则外角 ∠ACD（∠C 的外角）= ？','[{"key": "A", "text": "99°"}, {"key": "B", "text": "81°"}, {"key": "C", "text": "-17°"}, {"key": "D", "text": "180°"}]','A','外角=不相邻两内角和=41°+58°=99°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0112-2','math','初中',8,'jkp-0112','single_choice',0.55,'△ABC 中 ∠A=45°，∠B=45°，则外角 ∠ACD（∠C 的外角）= ？','[{"key": "A", "text": "90°"}, {"key": "B", "text": "90°"}, {"key": "C", "text": "0°"}, {"key": "D", "text": "180°"}]','A','外角=不相邻两内角和=45°+45°=90°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0112-3','math','初中',8,'jkp-0112','single_choice',0.55,'△ABC 中 ∠A=37°，∠B=45°，则外角 ∠ACD（∠C 的外角）= ？','[{"key": "A", "text": "82°"}, {"key": "B", "text": "98°"}, {"key": "C", "text": "-8°"}, {"key": "D", "text": "180°"}]','A','外角=不相邻两内角和=37°+45°=82°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0113-1','math','初中',8,'jkp-0113','single_choice',0.65,'∠A=60°，∠B=36°，则 ∠A 与外角 ∠ACD 的关系？','[{"key": "A", "text": "∠ACD > ∠A"}, {"key": "B", "text": "∠ACD < ∠A"}, {"key": "C", "text": "相等"}, {"key": "D", "text": "无关"}]','A','外角大于任意不相邻内角：96° > 60°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0113-2','math','初中',8,'jkp-0113','single_choice',0.65,'∠A=32°，∠B=39°，则 ∠A 与外角 ∠ACD 的关系？','[{"key": "A", "text": "∠ACD > ∠A"}, {"key": "B", "text": "∠ACD < ∠A"}, {"key": "C", "text": "相等"}, {"key": "D", "text": "无关"}]','A','外角大于任意不相邻内角：71° > 32°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0113-3','math','初中',8,'jkp-0113','single_choice',0.65,'∠A=49°，∠B=56°，则 ∠A 与外角 ∠ACD 的关系？','[{"key": "A", "text": "∠ACD > ∠A"}, {"key": "B", "text": "∠ACD < ∠A"}, {"key": "C", "text": "相等"}, {"key": "D", "text": "无关"}]','A','外角大于任意不相邻内角：105° > 49°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0114-1','math','初中',8,'jkp-0114','single_choice',0.75,'6 边形有 6 条边、6 个顶点，从一个顶点引对角线可作？条','[{"key": "A", "text": "3"}, {"key": "B", "text": "6"}, {"key": "C", "text": "5"}, {"key": "D", "text": "4"}]','A','从一顶点引对角线：n-3=3 条','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0114-2','math','初中',8,'jkp-0114','single_choice',0.75,'5 边形有 5 条边、5 个顶点，从一个顶点引对角线可作？条','[{"key": "A", "text": "2"}, {"key": "B", "text": "5"}, {"key": "C", "text": "4"}, {"key": "D", "text": "3"}]','A','从一顶点引对角线：n-3=2 条','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0115-1','math','初中',8,'jkp-0115','single_choice',0.35,'4 边形共有对角线条数 = n(n-3)/2 = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "4"}, {"key": "C", "text": "1"}, {"key": "D", "text": "6"}]','A','对角线条数=4×(4-3)/2=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0115-2','math','初中',8,'jkp-0115','single_choice',0.35,'7 边形共有对角线条数 = n(n-3)/2 = ？','[{"key": "A", "text": "14"}, {"key": "B", "text": "7"}, {"key": "C", "text": "4"}, {"key": "D", "text": "21"}]','A','对角线条数=7×(7-3)/2=14','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0115-3','math','初中',8,'jkp-0115','single_choice',0.35,'6 边形共有对角线条数 = n(n-3)/2 = ？','[{"key": "A", "text": "9"}, {"key": "B", "text": "6"}, {"key": "C", "text": "3"}, {"key": "D", "text": "15"}]','A','对角线条数=6×(6-3)/2=9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0116-1','math','初中',8,'jkp-0116','single_choice',0.45,'5 边形内角和 = (n-2)×180° = ？','[{"key": "A", "text": "540"}, {"key": "B", "text": "900"}, {"key": "C", "text": "270"}, {"key": "D", "text": "180"}]','A','内角和=(5-2)×180°=540°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0116-2','math','初中',8,'jkp-0116','single_choice',0.45,'8 边形内角和 = (n-2)×180° = ？','[{"key": "A", "text": "1080"}, {"key": "B", "text": "1440"}, {"key": "C", "text": "540"}, {"key": "D", "text": "180"}]','A','内角和=(8-2)×180°=1080°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0116-3','math','初中',8,'jkp-0116','single_choice',0.45,'7 边形内角和 = (n-2)×180° = ？','[{"key": "A", "text": "900"}, {"key": "B", "text": "1260"}, {"key": "C", "text": "450"}, {"key": "D", "text": "180"}]','A','内角和=(7-2)×180°=900°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0117-1','math','初中',8,'jkp-0117','single_choice',0.55,'任意多边形外角和恒等于？','[{"key": "A", "text": "360°"}, {"key": "B", "text": "180°"}, {"key": "C", "text": "540°"}, {"key": "D", "text": "720°"}]','A','多边形外角和恒为 360°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0117-2','math','初中',8,'jkp-0117','single_choice',0.55,'任意多边形外角和恒等于？','[{"key": "D", "text": "720°"}, {"key": "A", "text": "360°"}, {"key": "C", "text": "540°"}, {"key": "B", "text": "180°"}]','A','多边形外角和恒为 360°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0117-3','math','初中',8,'jkp-0117','single_choice',0.55,'任意多边形外角和恒等于？','[{"key": "B", "text": "180°"}, {"key": "D", "text": "720°"}, {"key": "A", "text": "360°"}, {"key": "C", "text": "540°"}]','A','多边形外角和恒为 360°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0118-1','math','初中',8,'jkp-0118','single_choice',0.65,'各边相等、各角也相等的多边形叫？','[{"key": "A", "text": "正多边形"}, {"key": "B", "text": "等边多边形"}, {"key": "C", "text": "凸多边形"}, {"key": "D", "text": "凹多边形"}]','A','正多边形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0118-2','math','初中',8,'jkp-0118','single_choice',0.65,'各边相等、各角也相等的多边形叫？','[{"key": "B", "text": "等边多边形"}, {"key": "D", "text": "凹多边形"}, {"key": "A", "text": "正多边形"}, {"key": "C", "text": "凸多边形"}]','A','正多边形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0118-3','math','初中',8,'jkp-0118','single_choice',0.65,'各边相等、各角也相等的多边形叫？','[{"key": "A", "text": "正多边形"}, {"key": "D", "text": "凹多边形"}, {"key": "B", "text": "等边多边形"}, {"key": "C", "text": "凸多边形"}]','A','正多边形定义','template-j','approved','通用');