-- 第28章 锐角三角函数 补题（12学期, 知识点 418-430）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0418-1','math','初中',12,'jkp-0418','single_choice',0.65,'Rt△ 中 sinA = ？','[{"key": "A", "text": "∠A 的对边/斜边"}, {"key": "B", "text": "∠A 的邻边/斜边"}, {"key": "C", "text": "∠A 的对边/邻边"}, {"key": "D", "text": "斜边/对边"}]','A','sinA = 对边/斜边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0418-2','math','初中',12,'jkp-0418','single_choice',0.65,'Rt△ 中 sinA = ？','[{"key": "A", "text": "∠A 的对边/斜边"}, {"key": "C", "text": "∠A 的对边/邻边"}, {"key": "D", "text": "斜边/对边"}, {"key": "B", "text": "∠A 的邻边/斜边"}]','A','sinA = 对边/斜边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0419-1','math','初中',12,'jkp-0419','single_choice',0.75,'Rt△ 中 cosA = ？','[{"key": "A", "text": "∠A 的邻边/斜边"}, {"key": "B", "text": "∠A 的对边/斜边"}, {"key": "C", "text": "∠A 的对边/邻边"}, {"key": "D", "text": "斜边/邻边"}]','A','cosA = 邻边/斜边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0419-2','math','初中',12,'jkp-0419','single_choice',0.75,'Rt△ 中 cosA = ？','[{"key": "D", "text": "斜边/邻边"}, {"key": "C", "text": "∠A 的对边/邻边"}, {"key": "A", "text": "∠A 的邻边/斜边"}, {"key": "B", "text": "∠A 的对边/斜边"}]','A','cosA = 邻边/斜边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0420-1','math','初中',12,'jkp-0420','single_choice',0.35,'Rt△ 中 tanA = ？','[{"key": "A", "text": "∠A 的对边/邻边"}, {"key": "B", "text": "∠A 的邻边/斜边"}, {"key": "C", "text": "∠A 的对边/斜边"}, {"key": "D", "text": "斜边/对边"}]','A','tanA = 对边/邻边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0420-2','math','初中',12,'jkp-0420','single_choice',0.35,'Rt△ 中 tanA = ？','[{"key": "A", "text": "∠A 的对边/邻边"}, {"key": "C", "text": "∠A 的对边/斜边"}, {"key": "B", "text": "∠A 的邻边/斜边"}, {"key": "D", "text": "斜边/对边"}]','A','tanA = 对边/邻边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0420-3','math','初中',12,'jkp-0420','single_choice',0.35,'Rt△ 中 tanA = ？','[{"key": "B", "text": "∠A 的邻边/斜边"}, {"key": "D", "text": "斜边/对边"}, {"key": "C", "text": "∠A 的对边/斜边"}, {"key": "A", "text": "∠A 的对边/邻边"}]','A','tanA = 对边/邻边','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0421-1','math','初中',12,'jkp-0421','single_choice',0.45,'锐角三角函数值的范围是？','[{"key": "A", "text": "sin、cos 在 (0,1)，tan > 0"}, {"key": "B", "text": "都大于 1"}, {"key": "C", "text": "都小于 0"}, {"key": "D", "text": "sin 大于 1"}]','A','锐角三角：sin、cos∈(0,1)，tan>0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0421-2','math','初中',12,'jkp-0421','single_choice',0.45,'锐角三角函数值的范围是？','[{"key": "A", "text": "sin、cos 在 (0,1)，tan > 0"}, {"key": "D", "text": "sin 大于 1"}, {"key": "B", "text": "都大于 1"}, {"key": "C", "text": "都小于 0"}]','A','锐角三角：sin、cos∈(0,1)，tan>0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0421-3','math','初中',12,'jkp-0421','single_choice',0.45,'锐角三角函数值的范围是？','[{"key": "C", "text": "都小于 0"}, {"key": "B", "text": "都大于 1"}, {"key": "A", "text": "sin、cos 在 (0,1)，tan > 0"}, {"key": "D", "text": "sin 大于 1"}]','A','锐角三角：sin、cos∈(0,1)，tan>0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0422-1','math','初中',12,'jkp-0422','single_choice',0.55,'sin30° = ？','[{"key": "A", "text": "1/2"}, {"key": "B", "text": "√2/2"}, {"key": "C", "text": "√3/2"}, {"key": "D", "text": "1"}]','A','特殊角：sin30°=1/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0422-2','math','初中',12,'jkp-0422','single_choice',0.55,'sin30° = ？','[{"key": "C", "text": "√3/2"}, {"key": "A", "text": "1/2"}, {"key": "B", "text": "√2/2"}, {"key": "D", "text": "1"}]','A','特殊角：sin30°=1/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0422-3','math','初中',12,'jkp-0422','single_choice',0.55,'sin30° = ？','[{"key": "D", "text": "1"}, {"key": "C", "text": "√3/2"}, {"key": "B", "text": "√2/2"}, {"key": "A", "text": "1/2"}]','A','特殊角：sin30°=1/2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0423-1','math','初中',12,'jkp-0423','single_choice',0.65,'同角关系：sin²A + cos²A = ？','[{"key": "A", "text": "1"}, {"key": "B", "text": "0"}, {"key": "C", "text": "tanA"}, {"key": "D", "text": "2"}]','A','sin²A+cos²A=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0423-2','math','初中',12,'jkp-0423','single_choice',0.65,'同角关系：sin²A + cos²A = ？','[{"key": "B", "text": "0"}, {"key": "C", "text": "tanA"}, {"key": "D", "text": "2"}, {"key": "A", "text": "1"}]','A','sin²A+cos²A=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0423-3','math','初中',12,'jkp-0423','single_choice',0.65,'同角关系：sin²A + cos²A = ？','[{"key": "D", "text": "2"}, {"key": "A", "text": "1"}, {"key": "B", "text": "0"}, {"key": "C", "text": "tanA"}]','A','sin²A+cos²A=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0424-1','math','初中',12,'jkp-0424','single_choice',0.75,'互余两角：sinA = cos(90°-A)，则 sin30° = cos？','[{"key": "A", "text": "60°"}, {"key": "B", "text": "30°"}, {"key": "C", "text": "45°"}, {"key": "D", "text": "90°"}]','A','sin30°=cos60°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0424-2','math','初中',12,'jkp-0424','single_choice',0.75,'互余两角：sinA = cos(90°-A)，则 sin30° = cos？','[{"key": "B", "text": "30°"}, {"key": "C", "text": "45°"}, {"key": "D", "text": "90°"}, {"key": "A", "text": "60°"}]','A','sin30°=cos60°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0424-3','math','初中',12,'jkp-0424','single_choice',0.75,'互余两角：sinA = cos(90°-A)，则 sin30° = cos？','[{"key": "A", "text": "60°"}, {"key": "C", "text": "45°"}, {"key": "D", "text": "90°"}, {"key": "B", "text": "30°"}]','A','sin30°=cos60°','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0425-1','math','初中',12,'jkp-0425','single_choice',0.35,'tanA = 1，A 为锐角，则 A = ？','[{"key": "A", "text": "45°"}, {"key": "B", "text": "30°"}, {"key": "C", "text": "60°"}, {"key": "D", "text": "90°"}]','A','tan45°=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0425-2','math','初中',12,'jkp-0425','single_choice',0.35,'tanA = 1，A 为锐角，则 A = ？','[{"key": "C", "text": "60°"}, {"key": "D", "text": "90°"}, {"key": "A", "text": "45°"}, {"key": "B", "text": "30°"}]','A','tan45°=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0425-3','math','初中',12,'jkp-0425','single_choice',0.35,'tanA = 1，A 为锐角，则 A = ？','[{"key": "D", "text": "90°"}, {"key": "A", "text": "45°"}, {"key": "C", "text": "60°"}, {"key": "B", "text": "30°"}]','A','tan45°=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0426-1','math','初中',12,'jkp-0426','single_choice',0.45,'由直角三角形已知元素求其余元素的过程叫？','[{"key": "A", "text": "解直角三角形"}, {"key": "B", "text": "画三角形"}, {"key": "C", "text": "测三角形"}, {"key": "D", "text": "拼三角形"}]','A','解直角三角形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0426-2','math','初中',12,'jkp-0426','single_choice',0.45,'由直角三角形已知元素求其余元素的过程叫？','[{"key": "D", "text": "拼三角形"}, {"key": "A", "text": "解直角三角形"}, {"key": "B", "text": "画三角形"}, {"key": "C", "text": "测三角形"}]','A','解直角三角形定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0427-1','math','初中',12,'jkp-0427','single_choice',0.55,'解直角三角形的依据是？','[{"key": "A", "text": "三边关系（勾股）、两锐角互余、边角关系（三角）"}, {"key": "B", "text": "只靠勾股"}, {"key": "C", "text": "只靠内角和"}, {"key": "D", "text": "只靠测量"}]','A','解直角三角形三大依据','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0427-2','math','初中',12,'jkp-0427','single_choice',0.55,'解直角三角形的依据是？','[{"key": "D", "text": "只靠测量"}, {"key": "C", "text": "只靠内角和"}, {"key": "B", "text": "只靠勾股"}, {"key": "A", "text": "三边关系（勾股）、两锐角互余、边角关系（三角）"}]','A','解直角三角形三大依据','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0427-3','math','初中',12,'jkp-0427','single_choice',0.55,'解直角三角形的依据是？','[{"key": "B", "text": "只靠勾股"}, {"key": "C", "text": "只靠内角和"}, {"key": "A", "text": "三边关系（勾股）、两锐角互余、边角关系（三角）"}, {"key": "D", "text": "只靠测量"}]','A','解直角三角形三大依据','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0428-1','math','初中',12,'jkp-0428','single_choice',0.65,'从下往上看，视线与水平线的夹角叫？','[{"key": "A", "text": "仰角"}, {"key": "B", "text": "俯角"}, {"key": "C", "text": "坡角"}, {"key": "D", "text": "方位角"}]','A','仰角定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0428-2','math','初中',12,'jkp-0428','single_choice',0.65,'从下往上看，视线与水平线的夹角叫？','[{"key": "C", "text": "坡角"}, {"key": "A", "text": "仰角"}, {"key": "D", "text": "方位角"}, {"key": "B", "text": "俯角"}]','A','仰角定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0428-3','math','初中',12,'jkp-0428','single_choice',0.65,'从下往上看，视线与水平线的夹角叫？','[{"key": "B", "text": "俯角"}, {"key": "D", "text": "方位角"}, {"key": "A", "text": "仰角"}, {"key": "C", "text": "坡角"}]','A','仰角定义','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0429-1','math','初中',12,'jkp-0429','single_choice',0.75,'坡度（坡比）i = ？','[{"key": "A", "text": "铅直高度/水平宽度"}, {"key": "B", "text": "水平宽度/铅直高度"}, {"key": "C", "text": "坡长/高度"}, {"key": "D", "text": "高度×宽度"}]','A','坡度 = 铅直高度/水平宽度','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0429-2','math','初中',12,'jkp-0429','single_choice',0.75,'坡度（坡比）i = ？','[{"key": "D", "text": "高度×宽度"}, {"key": "A", "text": "铅直高度/水平宽度"}, {"key": "B", "text": "水平宽度/铅直高度"}, {"key": "C", "text": "坡长/高度"}]','A','坡度 = 铅直高度/水平宽度','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0430-1','math','初中',12,'jkp-0430','single_choice',0.35,'解直角三角形的方位角应用：北偏东 30°，实际是？','[{"key": "A", "text": "从正北向东转 30°"}, {"key": "B", "text": "从正东向北转 30°"}, {"key": "C", "text": "正东"}, {"key": "D", "text": "正北"}]','A','方位角约定','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0430-2','math','初中',12,'jkp-0430','single_choice',0.35,'解直角三角形的方位角应用：北偏东 30°，实际是？','[{"key": "B", "text": "从正东向北转 30°"}, {"key": "A", "text": "从正北向东转 30°"}, {"key": "C", "text": "正东"}, {"key": "D", "text": "正北"}]','A','方位角约定','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0430-3','math','初中',12,'jkp-0430','single_choice',0.35,'解直角三角形的方位角应用：北偏东 30°，实际是？','[{"key": "A", "text": "从正北向东转 30°"}, {"key": "C", "text": "正东"}, {"key": "B", "text": "从正东向北转 30°"}, {"key": "D", "text": "正北"}]','A','方位角约定','template-j','approved','通用');