-- 第18章 勾股定理 补题（10学期, 知识点 268-277）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0268-1','math','初中',10,'jkp-0268','single_choice',0.65,'勾股定理：直角三角形两直角边 a、b，斜边 c 满足？','[{"key": "A", "text": "a² + b² = c²"}, {"key": "B", "text": "a + b = c"}, {"key": "C", "text": "a² - b² = c²"}, {"key": "D", "text": "ab = c"}]','A','勾股定理：a²+b²=c²','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0269-1','math','初中',10,'jkp-0269','single_choice',0.75,'勾股定理的证明常用？','[{"key": "A", "text": "面积法（拼图）"}, {"key": "B", "text": "测量"}, {"key": "C", "text": "相似"}, {"key": "D", "text": "三角函数"}]','A','勾股定理证明：面积法','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0270-1','math','初中',10,'jkp-0270','single_choice',0.35,'直角三角形两直角边 3、4，斜边 = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "7"}, {"key": "C", "text": "12"}, {"key": "D", "text": "6"}]','A','c=√(3²+4²)=√25=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0271-1','math','初中',10,'jkp-0271','single_choice',0.45,'下列是勾股数的是？','[{"key": "A", "text": "3、4、5"}, {"key": "B", "text": "2、3、4"}, {"key": "C", "text": "1、2、3"}, {"key": "D", "text": "4、5、6"}]','A','3²+4²=5² → 勾股数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0272-1','math','初中',10,'jkp-0272','single_choice',0.55,'勾股定理逆定理：a²+b²=c² → 三角形是？','[{"key": "A", "text": "直角三角形"}, {"key": "B", "text": "锐角三角形"}, {"key": "C", "text": "钝角三角形"}, {"key": "D", "text": "等腰三角形"}]','A','逆定理：满足 a²+b²=c² → 直角三角形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0273-1','math','初中',10,'jkp-0273','single_choice',0.65,'三角形三边 5、12、13，它是？','[{"key": "A", "text": "直角三角形"}, {"key": "B", "text": "锐角三角形"}, {"key": "C", "text": "钝角三角形"}, {"key": "D", "text": "无法判断"}]','A','5²+12²=25+144=169=13² → 直角三角形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0274-1','math','初中',10,'jkp-0274','single_choice',0.75,'命题''若 a=b，则 a²=b²''的逆命题是？','[{"key": "A", "text": "若 a²=b²，则 a=b"}, {"key": "B", "text": "若 a≠b，则 a²≠b²"}, {"key": "C", "text": "若 a=b，则 a³=b³"}, {"key": "D", "text": "若 a²=b²，则 a²=b²"}]','A','逆命题：条件和结论互换','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0275-1','math','初中',10,'jkp-0275','single_choice',0.35,'边长 1、1、√2 的三角形是？','[{"key": "A", "text": "直角三角形"}, {"key": "B", "text": "等边三角形"}, {"key": "C", "text": "钝角三角形"}, {"key": "D", "text": "等腰直角三角形"}]','A','1²+1²=2=(√2)² → 等腰直角三角形','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0276-1','math','初中',10,'jkp-0276','single_choice',0.45,'矩形折叠问题常构造？用勾股定理','[{"key": "A", "text": "直角三角形"}, {"key": "B", "text": "等边三角形"}, {"key": "C", "text": "平行四边形"}, {"key": "D", "text": "梯形"}]','A','折叠 → 构造直角三角形用勾股','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0277-1','math','初中',10,'jkp-0277','single_choice',0.55,'长方体长 4、宽 4、高 4，体对角线 = √(4²+4²+4²) = ？','[{"key": "A", "text": "4√3"}, {"key": "B", "text": "4√2"}, {"key": "C", "text": "12"}, {"key": "D", "text": "8"}]','A','体对角线=√(48)=4√3','template-j','approved','通用');