-- 第1章 有理数 补题（7学期, 知识点 1-25）
-- 参数化原创题 source='template-j'
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0001-1','math','初中',7,'jkp-0001','single_choice',0.45,'下列各数中是正数的是？','[{"key": "A", "text": "3"}, {"key": "B", "text": "-2"}, {"key": "C", "text": "0"}, {"key": "D", "text": "-0.5"}]','A','大于 0 的数是正数，3 是正数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0001-2','math','初中',7,'jkp-0001','single_choice',0.45,'下列各数中是正数的是？','[{"key": "D", "text": "-0.5"}, {"key": "A", "text": "3"}, {"key": "B", "text": "-2"}, {"key": "C", "text": "0"}]','A','大于 0 的数是正数，3 是正数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0002-1','math','初中',7,'jkp-0002','single_choice',0.55,'若收入 500 元记作 +500，则支出 200 元记作？','[{"key": "A", "text": "-200"}, {"key": "B", "text": "+200"}, {"key": "C", "text": "200"}, {"key": "D", "text": "0"}]','A','支出用负数表示：-200','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0002-2','math','初中',7,'jkp-0002','single_choice',0.55,'若收入 500 元记作 +500，则支出 200 元记作？','[{"key": "B", "text": "+200"}, {"key": "D", "text": "0"}, {"key": "C", "text": "200"}, {"key": "A", "text": "-200"}]','A','支出用负数表示：-200','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0002-3','math','初中',7,'jkp-0002','single_choice',0.55,'若收入 500 元记作 +500，则支出 200 元记作？','[{"key": "D", "text": "0"}, {"key": "C", "text": "200"}, {"key": "A", "text": "-200"}, {"key": "B", "text": "+200"}]','A','支出用负数表示：-200','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0003-1','math','初中',7,'jkp-0003','single_choice',0.65,'下列各数中是有理数的是？','[{"key": "A", "text": "3.14"}, {"key": "B", "text": "π"}, {"key": "C", "text": "√2"}, {"key": "D", "text": "0.1010010001…(无限不循环)"}]','A','有限小数 3.14 是有理数；π、√2 等是无理数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0003-2','math','初中',7,'jkp-0003','single_choice',0.65,'下列各数中是有理数的是？','[{"key": "B", "text": "π"}, {"key": "A", "text": "3.14"}, {"key": "D", "text": "0.1010010001…(无限不循环)"}, {"key": "C", "text": "√2"}]','A','有限小数 3.14 是有理数；π、√2 等是无理数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0003-3','math','初中',7,'jkp-0003','single_choice',0.65,'下列各数中是有理数的是？','[{"key": "B", "text": "π"}, {"key": "C", "text": "√2"}, {"key": "A", "text": "3.14"}, {"key": "D", "text": "0.1010010001…(无限不循环)"}]','A','有限小数 3.14 是有理数；π、√2 等是无理数','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0004-1','math','初中',7,'jkp-0004','single_choice',0.75,'下列各数中是负分数的是？','[{"key": "A", "text": "-1/2"}, {"key": "B", "text": "-3"}, {"key": "C", "text": "0"}, {"key": "D", "text": "1/2"}]','A','负分数：既是负数又是分数，-1/2 符合','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0004-2','math','初中',7,'jkp-0004','single_choice',0.75,'下列各数中是负分数的是？','[{"key": "A", "text": "-1/2"}, {"key": "C", "text": "0"}, {"key": "B", "text": "-3"}, {"key": "D", "text": "1/2"}]','A','负分数：既是负数又是分数，-1/2 符合','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0004-3','math','初中',7,'jkp-0004','single_choice',0.75,'下列各数中是负分数的是？','[{"key": "C", "text": "0"}, {"key": "D", "text": "1/2"}, {"key": "A", "text": "-1/2"}, {"key": "B", "text": "-3"}]','A','负分数：既是负数又是分数，-1/2 符合','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0005-1','math','初中',7,'jkp-0005','single_choice',0.35,'数轴的三要素是？','[{"key": "A", "text": "原点、正方向、单位长度"}, {"key": "B", "text": "原点、刻度、长度"}, {"key": "C", "text": "方向、刻度、单位"}, {"key": "D", "text": "原点、终点、单位"}]','A','数轴三要素：原点、正方向、单位长度','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0005-2','math','初中',7,'jkp-0005','single_choice',0.35,'数轴的三要素是？','[{"key": "D", "text": "原点、终点、单位"}, {"key": "B", "text": "原点、刻度、长度"}, {"key": "A", "text": "原点、正方向、单位长度"}, {"key": "C", "text": "方向、刻度、单位"}]','A','数轴三要素：原点、正方向、单位长度','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0005-3','math','初中',7,'jkp-0005','single_choice',0.35,'数轴的三要素是？','[{"key": "C", "text": "方向、刻度、单位"}, {"key": "D", "text": "原点、终点、单位"}, {"key": "A", "text": "原点、正方向、单位长度"}, {"key": "B", "text": "原点、刻度、长度"}]','A','数轴三要素：原点、正方向、单位长度','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0006-1','math','初中',7,'jkp-0006','single_choice',0.45,'数轴上表示 -3 的点到原点的距离是？','[{"key": "A", "text": "3"}, {"key": "B", "text": "-3"}, {"key": "C", "text": "0"}, {"key": "D", "text": "6"}]','A','数轴上点的对应值到原点距离即绝对值 |-3|=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0006-2','math','初中',7,'jkp-0006','single_choice',0.45,'数轴上表示 -3 的点到原点的距离是？','[{"key": "C", "text": "0"}, {"key": "D", "text": "6"}, {"key": "B", "text": "-3"}, {"key": "A", "text": "3"}]','A','数轴上点的对应值到原点距离即绝对值 |-3|=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0006-3','math','初中',7,'jkp-0006','single_choice',0.45,'数轴上表示 -3 的点到原点的距离是？','[{"key": "C", "text": "0"}, {"key": "B", "text": "-3"}, {"key": "A", "text": "3"}, {"key": "D", "text": "6"}]','A','数轴上点的对应值到原点距离即绝对值 |-3|=3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0007-1','math','初中',7,'jkp-0007','single_choice',0.55,'7 的相反数是？','[{"key": "A", "text": "-7"}, {"key": "B", "text": "7"}, {"key": "C", "text": "0"}, {"key": "D", "text": "14"}]','A','相反数：只有符号不同，7 的相反数是 -7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0007-2','math','初中',7,'jkp-0007','single_choice',0.55,'3 的相反数是？','[{"key": "A", "text": "-3"}, {"key": "B", "text": "3"}, {"key": "C", "text": "0"}, {"key": "D", "text": "6"}]','A','相反数：只有符号不同，3 的相反数是 -3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0007-3','math','初中',7,'jkp-0007','single_choice',0.55,'9 的相反数是？','[{"key": "A", "text": "-9"}, {"key": "B", "text": "9"}, {"key": "C", "text": "0"}, {"key": "D", "text": "18"}]','A','相反数：只有符号不同，9 的相反数是 -9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0008-1','math','初中',7,'jkp-0008','single_choice',0.65,'化简：-(-5) = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "-5"}, {"key": "C", "text": "0"}, {"key": "D", "text": "10"}]','A','双重负号化简为正：-(-5)=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0008-2','math','初中',7,'jkp-0008','single_choice',0.65,'化简：-(-6) = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "-6"}, {"key": "C", "text": "0"}, {"key": "D", "text": "12"}]','A','双重负号化简为正：-(-6)=6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0008-3','math','初中',7,'jkp-0008','single_choice',0.65,'化简：-(-9) = ？','[{"key": "A", "text": "9"}, {"key": "B", "text": "-9"}, {"key": "C", "text": "0"}, {"key": "D", "text": "18"}]','A','双重负号化简为正：-(-9)=9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0009-1','math','初中',7,'jkp-0009','single_choice',0.75,'|−7| = ？','[{"key": "A", "text": "7"}, {"key": "B", "text": "-7"}, {"key": "C", "text": "0"}, {"key": "D", "text": "14"}]','A','绝对值非负：|−7|=7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0009-2','math','初中',7,'jkp-0009','single_choice',0.75,'|−5| = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "-5"}, {"key": "C", "text": "0"}, {"key": "D", "text": "10"}]','A','绝对值非负：|−5|=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0009-3','math','初中',7,'jkp-0009','single_choice',0.75,'|−6| = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "-6"}, {"key": "C", "text": "0"}, {"key": "D", "text": "12"}]','A','绝对值非负：|−6|=6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0010-1','math','初中',7,'jkp-0010','single_choice',0.35,'若 |a| = 0，则 a = ？','[{"key": "A", "text": "0"}, {"key": "B", "text": "1"}, {"key": "C", "text": "-1"}, {"key": "D", "text": "不存在"}]','A','绝对值为 0 的数只有 0 本身','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0010-2','math','初中',7,'jkp-0010','single_choice',0.35,'若 |a| = 0，则 a = ？','[{"key": "A", "text": "0"}, {"key": "D", "text": "不存在"}, {"key": "C", "text": "-1"}, {"key": "B", "text": "1"}]','A','绝对值为 0 的数只有 0 本身','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0011-1','math','初中',7,'jkp-0011','single_choice',0.45,'比较 -5 与 -3 的大小（5≠3）','[{"key": "A", "text": "-3 > -5"}, {"key": "B", "text": "-5 > -3"}, {"key": "C", "text": "相等"}, {"key": "D", "text": "无法比较"}]','A','负数比较：绝对值大的反而小，-3 > -5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0011-2','math','初中',7,'jkp-0011','single_choice',0.45,'比较 -2 与 -6 的大小（2≠6）','[{"key": "A", "text": "-2 > -6"}, {"key": "B", "text": "-2 > -6"}, {"key": "C", "text": "相等"}, {"key": "D", "text": "无法比较"}]','A','负数比较：绝对值大的反而小，-2 > -6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0011-3','math','初中',7,'jkp-0011','single_choice',0.45,'比较 -9 与 -3 的大小（9≠3）','[{"key": "A", "text": "-3 > -9"}, {"key": "B", "text": "-9 > -3"}, {"key": "C", "text": "相等"}, {"key": "D", "text": "无法比较"}]','A','负数比较：绝对值大的反而小，-3 > -9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0012-1','math','初中',7,'jkp-0012','single_choice',0.55,'计算：(-3) + (-4) = ？','[{"key": "A", "text": "-7"}, {"key": "B", "text": "7"}, {"key": "C", "text": "-1"}, {"key": "D", "text": "1"}]','A','同号相加取相同符号，绝对值相加：-(3+4)=-7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0012-2','math','初中',7,'jkp-0012','single_choice',0.55,'计算：(-8) + (-5) = ？','[{"key": "A", "text": "-13"}, {"key": "B", "text": "13"}, {"key": "C", "text": "3"}, {"key": "D", "text": "-3"}]','A','同号相加取相同符号，绝对值相加：-(8+5)=-13','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0012-3','math','初中',7,'jkp-0012','single_choice',0.55,'计算：(-9) + (-5) = ？','[{"key": "A", "text": "-14"}, {"key": "B", "text": "14"}, {"key": "C", "text": "4"}, {"key": "D", "text": "-4"}]','A','同号相加取相同符号，绝对值相加：-(9+5)=-14','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0013-1','math','初中',7,'jkp-0013','single_choice',0.65,'计算：(1+5)+2 = 1+(5+2) 运用了？','[{"key": "A", "text": "加法结合律"}, {"key": "B", "text": "加法交换律"}, {"key": "C", "text": "分配律"}, {"key": "D", "text": "乘法结合律"}]','A','先加后两个数再与第一个数相加 → 结合律','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0013-2','math','初中',7,'jkp-0013','single_choice',0.65,'计算：(1+3)+2 = 1+(3+2) 运用了？','[{"key": "A", "text": "加法结合律"}, {"key": "B", "text": "加法交换律"}, {"key": "C", "text": "分配律"}, {"key": "D", "text": "乘法结合律"}]','A','先加后两个数再与第一个数相加 → 结合律','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0013-3','math','初中',7,'jkp-0013','single_choice',0.65,'计算：(1+3)+5 = 1+(3+5) 运用了？','[{"key": "A", "text": "加法结合律"}, {"key": "B", "text": "加法交换律"}, {"key": "C", "text": "分配律"}, {"key": "D", "text": "乘法结合律"}]','A','先加后两个数再与第一个数相加 → 结合律','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0014-1','math','初中',7,'jkp-0014','single_choice',0.75,'计算：5 - 3 = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "8"}, {"key": "C", "text": "-2"}, {"key": "D", "text": "-8"}]','A','减法化加法：5-3=5+(-3)=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0014-2','math','初中',7,'jkp-0014','single_choice',0.75,'计算：6 - 4 = ？','[{"key": "A", "text": "2"}, {"key": "B", "text": "10"}, {"key": "C", "text": "-2"}, {"key": "D", "text": "-10"}]','A','减法化加法：6-4=6+(-4)=2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0014-3','math','初中',7,'jkp-0014','single_choice',0.75,'计算：7 - 1 = ？','[{"key": "A", "text": "6"}, {"key": "B", "text": "8"}, {"key": "C", "text": "-6"}, {"key": "D", "text": "-8"}]','A','减法化加法：7-1=7+(-1)=6','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0015-1','math','初中',7,'jkp-0015','single_choice',0.35,'计算：2 - 3 + 1 = ？','[{"key": "A", "text": "0"}, {"key": "B", "text": "6"}, {"key": "C", "text": "-2"}, {"key": "D", "text": "2"}]','A','从左到右依次计算：2-3+1=0','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0015-2','math','初中',7,'jkp-0015','single_choice',0.35,'计算：5 - 5 + 1 = ？','[{"key": "A", "text": "1"}, {"key": "B", "text": "11"}, {"key": "C", "text": "-1"}, {"key": "D", "text": "1"}]','A','从左到右依次计算：5-5+1=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0015-3','math','初中',7,'jkp-0015','single_choice',0.35,'计算：3 - 5 + 3 = ？','[{"key": "A", "text": "1"}, {"key": "B", "text": "11"}, {"key": "C", "text": "-5"}, {"key": "D", "text": "5"}]','A','从左到右依次计算：3-5+3=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0016-1','math','初中',7,'jkp-0016','single_choice',0.45,'计算：(-2) × 2 = ？','[{"key": "A", "text": "-4"}, {"key": "B", "text": "4"}, {"key": "C", "text": "-4"}, {"key": "D", "text": "0"}]','A','异号相乘得负：-2×2=-4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0016-2','math','初中',7,'jkp-0016','single_choice',0.45,'计算：(-7) × 3 = ？','[{"key": "A", "text": "-21"}, {"key": "B", "text": "21"}, {"key": "C", "text": "-10"}, {"key": "D", "text": "4"}]','A','异号相乘得负：-7×3=-21','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0016-3','math','初中',7,'jkp-0016','single_choice',0.45,'计算：(-3) × 6 = ？','[{"key": "A", "text": "-18"}, {"key": "B", "text": "18"}, {"key": "C", "text": "-9"}, {"key": "D", "text": "-3"}]','A','异号相乘得负：-3×6=-18','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0017-1','math','初中',7,'jkp-0017','single_choice',0.55,'计算：(-1) × 4 × (-5) 的符号是？','[{"key": "A", "text": "正"}, {"key": "B", "text": "负"}, {"key": "C", "text": "0"}, {"key": "D", "text": "无法确定"}]','A','两个负因数的个数为偶数（2个），积为正','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0017-2','math','初中',7,'jkp-0017','single_choice',0.55,'计算：(-1) × 5 × (-2) 的符号是？','[{"key": "A", "text": "正"}, {"key": "B", "text": "负"}, {"key": "C", "text": "0"}, {"key": "D", "text": "无法确定"}]','A','两个负因数的个数为偶数（2个），积为正','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0017-3','math','初中',7,'jkp-0017','single_choice',0.55,'计算：(-1) × 2 × (-3) 的符号是？','[{"key": "A", "text": "正"}, {"key": "B", "text": "负"}, {"key": "C", "text": "0"}, {"key": "D", "text": "无法确定"}]','A','两个负因数的个数为偶数（2个），积为正','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0018-1','math','初中',7,'jkp-0018','single_choice',0.65,'计算：4 × (5 + 3) = 4×5 + 4×3 运用了？','[{"key": "A", "text": "分配律"}, {"key": "B", "text": "交换律"}, {"key": "C", "text": "结合律"}, {"key": "D", "text": "分配律逆用"}]','A','乘法对加法的分配律','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0018-2','math','初中',7,'jkp-0018','single_choice',0.65,'计算：2 × (2 + 5) = 2×2 + 2×5 运用了？','[{"key": "A", "text": "分配律"}, {"key": "B", "text": "交换律"}, {"key": "C", "text": "结合律"}, {"key": "D", "text": "分配律逆用"}]','A','乘法对加法的分配律','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0018-3','math','初中',7,'jkp-0018','single_choice',0.65,'计算：3 × (4 + 3) = 3×4 + 3×3 运用了？','[{"key": "A", "text": "分配律"}, {"key": "B", "text": "交换律"}, {"key": "C", "text": "结合律"}, {"key": "D", "text": "分配律逆用"}]','A','乘法对加法的分配律','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0019-1','math','初中',7,'jkp-0019','single_choice',0.75,'计算：(-10) ÷ 2 = ？','[{"key": "A", "text": "-5"}, {"key": "B", "text": "5"}, {"key": "C", "text": "-10"}, {"key": "D", "text": "2"}]','A','异号相除得负：-10÷2=-5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0019-2','math','初中',7,'jkp-0019','single_choice',0.75,'计算：(-20) ÷ 5 = ？','[{"key": "A", "text": "-4"}, {"key": "B", "text": "4"}, {"key": "C", "text": "-20"}, {"key": "D", "text": "5"}]','A','异号相除得负：-20÷5=-4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0019-3','math','初中',7,'jkp-0019','single_choice',0.75,'计算：(-12) ÷ 3 = ？','[{"key": "A", "text": "-4"}, {"key": "B", "text": "4"}, {"key": "C", "text": "-12"}, {"key": "D", "text": "3"}]','A','异号相除得负：-12÷3=-4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0020-1','math','初中',7,'jkp-0020','single_choice',0.35,'计算：12 ÷ 3 × (-1) = ？','[{"key": "A", "text": "-4"}, {"key": "B", "text": "4"}, {"key": "C", "text": "-12"}, {"key": "D", "text": "12"}]','A','从左到右：12÷3=4，4×(-1)=-4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0020-2','math','初中',7,'jkp-0020','single_choice',0.35,'计算：9 ÷ 3 × (-1) = ？','[{"key": "A", "text": "-3"}, {"key": "B", "text": "3"}, {"key": "C", "text": "-9"}, {"key": "D", "text": "9"}]','A','从左到右：9÷3=3，3×(-1)=-3','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0020-3','math','初中',7,'jkp-0020','single_choice',0.35,'计算：4 ÷ 2 × (-1) = ？','[{"key": "A", "text": "-2"}, {"key": "B", "text": "2"}, {"key": "C", "text": "-4"}, {"key": "D", "text": "4"}]','A','从左到右：4÷2=2，2×(-1)=-2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0021-1','math','初中',7,'jkp-0021','single_choice',0.45,'4 的 2 次幂（4^2）等于？','[{"key": "A", "text": "16"}, {"key": "B", "text": "8"}, {"key": "C", "text": "6"}, {"key": "D", "text": "4"}]','A','4^2=16（2 个 4 相乘）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0021-2','math','初中',7,'jkp-0021','single_choice',0.45,'3 的 4 次幂（3^4）等于？','[{"key": "A", "text": "81"}, {"key": "B", "text": "12"}, {"key": "C", "text": "7"}, {"key": "D", "text": "3"}]','A','3^4=81（4 个 3 相乘）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0021-3','math','初中',7,'jkp-0021','single_choice',0.45,'4 的 4 次幂（4^4）等于？','[{"key": "A", "text": "256"}, {"key": "B", "text": "16"}, {"key": "C", "text": "8"}, {"key": "D", "text": "4"}]','A','4^4=256（4 个 4 相乘）','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0022-1','math','初中',7,'jkp-0022','single_choice',0.55,'(-1)^4 = ？（n=4）','[{"key": "A", "text": "1"}, {"key": "B", "text": "1"}, {"key": "C", "text": "4"}, {"key": "D", "text": "-4"}]','A','负数的奇次幂为负：(-1)^4=1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0022-2','math','初中',7,'jkp-0022','single_choice',0.55,'(-1)^5 = ？（n=5）','[{"key": "A", "text": "-1"}, {"key": "B", "text": "1"}, {"key": "C", "text": "5"}, {"key": "D", "text": "-5"}]','A','负数的奇次幂为负：(-1)^5=-1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0022-3','math','初中',7,'jkp-0022','single_choice',0.55,'(-1)^3 = ？（n=3）','[{"key": "A", "text": "-1"}, {"key": "B", "text": "1"}, {"key": "C", "text": "3"}, {"key": "D", "text": "-3"}]','A','负数的奇次幂为负：(-1)^3=-1','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0023-1','math','初中',7,'jkp-0023','single_choice',0.65,'计算：-1² + 3 × 2 = ？','[{"key": "A", "text": "5"}, {"key": "B", "text": "7"}, {"key": "C", "text": "-7"}, {"key": "D", "text": "6"}]','A','先乘方再乘法再加减：-1+6=5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0023-2','math','初中',7,'jkp-0023','single_choice',0.65,'计算：-1² + 4 × 2 = ？','[{"key": "A", "text": "7"}, {"key": "B", "text": "9"}, {"key": "C", "text": "-9"}, {"key": "D", "text": "8"}]','A','先乘方再乘法再加减：-1+8=7','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0023-3','math','初中',7,'jkp-0023','single_choice',0.65,'计算：-1² + 5 × 2 = ？','[{"key": "A", "text": "9"}, {"key": "B", "text": "11"}, {"key": "C", "text": "-11"}, {"key": "D", "text": "10"}]','A','先乘方再乘法再加减：-1+10=9','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0024-1','math','初中',7,'jkp-0024','single_choice',0.75,'用科学记数法表示 100000 = ？','[{"key": "A", "text": "1×10^5"}, {"key": "B", "text": "10×10^4"}, {"key": "C", "text": "1×10^6"}, {"key": "D", "text": "100000"}]','A','100000=1×10^5','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0024-2','math','初中',7,'jkp-0024','single_choice',0.75,'用科学记数法表示 100 = ？','[{"key": "A", "text": "1×10^2"}, {"key": "B", "text": "10×10^1"}, {"key": "C", "text": "1×10^3"}, {"key": "D", "text": "100"}]','A','100=1×10^2','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0024-3','math','初中',7,'jkp-0024','single_choice',0.75,'用科学记数法表示 10000 = ？','[{"key": "A", "text": "1×10^4"}, {"key": "B", "text": "10×10^3"}, {"key": "C", "text": "1×10^5"}, {"key": "D", "text": "10000"}]','A','10000=1×10^4','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0025-1','math','初中',7,'jkp-0025','single_choice',0.35,'3.14159 精确到百分位是？','[{"key": "A", "text": "3.14"}, {"key": "B", "text": "3.15"}, {"key": "C", "text": "3.1"}, {"key": "D", "text": "3.142"}]','A','精确到百分位看千分位 1，舍去：3.14','template-j','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('jq-0025-2','math','初中',7,'jkp-0025','single_choice',0.35,'3.14159 精确到百分位是？','[{"key": "A", "text": "3.14"}, {"key": "B", "text": "3.15"}, {"key": "D", "text": "3.142"}, {"key": "C", "text": "3.1"}]','A','精确到百分位看千分位 1，舍去：3.14','template-j','approved','通用');