-- ============================================================
-- 参数化模板生成的原创题（每知识点多道变体，确保题量充足）
-- 生成时间: 2026-08-17T08:02:08
-- 幂等：INSERT OR IGNORE
-- ============================================================
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-rational-b4-1','math','初中',7,'kp-math-rational','single_choice',0.30,'计算：-4 - 8 = ？','[{"key":"A","text":"-12"},{"key":"B","text":"-10"},{"key":"C","text":"-15"},{"key":"D","text":"-11"}]','A','有理数减法：-4 - 8 = -4 + (-8) = -12','template','approved','通用'),
('qt-rational-b4-2','math','初中',7,'kp-math-rational','single_choice',0.38,'计算：-4 - 6 = ？','[{"key":"A","text":"-10"},{"key":"B","text":"-8"},{"key":"C","text":"-13"},{"key":"D","text":"-9"}]','A','有理数减法：-4 - 6 = -4 + (-6) = -10','template','approved','通用'),
('qt-rational-b4-3','math','初中',7,'kp-math-rational','single_choice',0.46,'计算：-4 - 9 = ？','[{"key":"A","text":"-13"},{"key":"B","text":"-11"},{"key":"C","text":"-16"},{"key":"D","text":"-12"}]','A','有理数减法：-4 - 9 = -4 + (-9) = -13','template','approved','通用'),
('qt-rational-b4-4','math','初中',7,'kp-math-rational','single_choice',0.54,'计算：1 - 9 = ？','[{"key":"A","text":"-8"},{"key":"B","text":"-6"},{"key":"C","text":"-11"},{"key":"D","text":"-7"}]','A','有理数减法：1 - 9 = 1 + (-9) = -8','template','approved','通用'),
('qt-rational-b4-5','math','初中',7,'kp-math-rational','single_choice',0.62,'计算：-3 - 7 = ？','[{"key":"A","text":"-10"},{"key":"B","text":"-8"},{"key":"C","text":"-13"},{"key":"D","text":"-9"}]','A','有理数减法：-3 - 7 = -3 + (-7) = -10','template','approved','通用'),
('qt-rational-b4-6','math','初中',7,'kp-math-rational','single_choice',0.70,'计算：0 - 2 = ？','[{"key":"A","text":"-2"},{"key":"B","text":"0"},{"key":"C","text":"-5"},{"key":"D","text":"-1"}]','A','有理数减法：0 - 2 = 0 + (-2) = -2','template','approved','通用'),
('qt-rational-b4-7','math','初中',7,'kp-math-rational','single_choice',0.30,'计算：-4 - 2 = ？','[{"key":"A","text":"-6"},{"key":"B","text":"-4"},{"key":"C","text":"-9"},{"key":"D","text":"-5"}]','A','有理数减法：-4 - 2 = -4 + (-2) = -6','template','approved','通用'),
('qt-rational-b4-8','math','初中',7,'kp-math-rational','single_choice',0.38,'计算：7 - 1 = ？','[{"key":"A","text":"6"},{"key":"B","text":"8"},{"key":"C","text":"3"},{"key":"D","text":"7"}]','A','有理数减法：7 - 1 = 7 + (-1) = 6','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-rational-b4-9','math','初中',7,'kp-math-rational','single_choice',0.46,'计算：-4 - 2 = ？','[{"key":"A","text":"-6"},{"key":"B","text":"-4"},{"key":"C","text":"-9"},{"key":"D","text":"-5"}]','A','有理数减法：-4 - 2 = -4 + (-2) = -6','template','approved','通用'),
('qt-rational-b4-10','math','初中',7,'kp-math-rational','single_choice',0.54,'计算：6 - 4 = ？','[{"key":"A","text":"2"},{"key":"B","text":"4"},{"key":"C","text":"-1"},{"key":"D","text":"3"}]','A','有理数减法：6 - 4 = 6 + (-4) = 2','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-rational-op-b4-1','math','初中',7,'kp-math-rational-op','single_choice',0.30,'计算：7 × 8 = ？','[{"key":"A","text":"56"},{"key":"B","text":"64"},{"key":"C","text":"49"},{"key":"D","text":"15"}]','A','同号相乘得正：7×8=56','template','approved','通用'),
('qt-rational-op-b4-2','math','初中',7,'kp-math-rational-op','single_choice',0.38,'计算：3 × 9 = ？','[{"key":"A","text":"27"},{"key":"B","text":"36"},{"key":"C","text":"24"},{"key":"D","text":"12"}]','A','同号相乘得正：3×9=27','template','approved','通用'),
('qt-rational-op-b4-3','math','初中',7,'kp-math-rational-op','single_choice',0.46,'计算：11 × 4 = ？','[{"key":"A","text":"44"},{"key":"B","text":"48"},{"key":"C","text":"33"},{"key":"D","text":"15"}]','A','同号相乘得正：11×4=44','template','approved','通用'),
('qt-rational-op-b4-4','math','初中',7,'kp-math-rational-op','single_choice',0.54,'计算：12 × 3 = ？','[{"key":"A","text":"36"},{"key":"B","text":"39"},{"key":"C","text":"24"},{"key":"D","text":"15"}]','A','同号相乘得正：12×3=36','template','approved','通用'),
('qt-rational-op-b4-5','math','初中',7,'kp-math-rational-op','single_choice',0.62,'计算：3 × 6 = ？','[{"key":"A","text":"18"},{"key":"B","text":"24"},{"key":"C","text":"15"},{"key":"D","text":"9"}]','A','同号相乘得正：3×6=18','template','approved','通用'),
('qt-rational-op-b4-6','math','初中',7,'kp-math-rational-op','single_choice',0.70,'计算：9 × 9 = ？','[{"key":"A","text":"81"},{"key":"B","text":"90"},{"key":"C","text":"72"},{"key":"D","text":"18"}]','A','同号相乘得正：9×9=81','template','approved','通用'),
('qt-rational-op-b4-7','math','初中',7,'kp-math-rational-op','single_choice',0.30,'计算：4 × 8 = ？','[{"key":"A","text":"32"},{"key":"B","text":"40"},{"key":"C","text":"28"},{"key":"D","text":"12"}]','A','同号相乘得正：4×8=32','template','approved','通用'),
('qt-rational-op-b4-8','math','初中',7,'kp-math-rational-op','single_choice',0.38,'计算：4 × 9 = ？','[{"key":"A","text":"36"},{"key":"B","text":"45"},{"key":"C","text":"32"},{"key":"D","text":"13"}]','A','同号相乘得正：4×9=36','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-rational-op-b4-9','math','初中',7,'kp-math-rational-op','single_choice',0.46,'计算：8 × 2 = ？','[{"key":"A","text":"16"},{"key":"B","text":"18"},{"key":"C","text":"8"},{"key":"D","text":"10"}]','A','同号相乘得正：8×2=16','template','approved','通用'),
('qt-rational-op-b4-10','math','初中',7,'kp-math-rational-op','single_choice',0.54,'计算：7 × 5 = ？','[{"key":"A","text":"35"},{"key":"B","text":"40"},{"key":"C","text":"28"},{"key":"D","text":"12"}]','A','同号相乘得正：7×5=35','template','approved','通用'),
('qt-rational-op-b4-11','math','初中',7,'kp-math-rational-op','single_choice',0.62,'计算：11 × 5 = ？','[{"key":"A","text":"55"},{"key":"B","text":"60"},{"key":"C","text":"44"},{"key":"D","text":"16"}]','A','同号相乘得正：11×5=55','template','approved','通用'),
('qt-rational-op-b4-12','math','初中',7,'kp-math-rational-op','single_choice',0.70,'计算：10 × 5 = ？','[{"key":"A","text":"50"},{"key":"B","text":"55"},{"key":"C","text":"40"},{"key":"D","text":"15"}]','A','同号相乘得正：10×5=50','template','approved','通用'),
('qt-rational-op-b4-13','math','初中',7,'kp-math-rational-op','single_choice',0.30,'计算：9 × 6 = ？','[{"key":"A","text":"54"},{"key":"B","text":"60"},{"key":"C","text":"45"},{"key":"D","text":"15"}]','A','同号相乘得正：9×6=54','template','approved','通用'),
('qt-rational-op-b4-14','math','初中',7,'kp-math-rational-op','single_choice',0.38,'计算：7 × 8 = ？','[{"key":"A","text":"56"},{"key":"B","text":"64"},{"key":"C","text":"49"},{"key":"D","text":"15"}]','A','同号相乘得正：7×8=56','template','approved','通用'),
('qt-rational-op-b4-15','math','初中',7,'kp-math-rational-op','single_choice',0.46,'计算：3 × 2 = ？','[{"key":"A","text":"6"},{"key":"B","text":"8"},{"key":"C","text":"3"},{"key":"D","text":"5"}]','A','同号相乘得正：3×2=6','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-rational-num-b4-1','math','初中',7,'kp-math-rational-num','single_choice',0.30,'9 的相反数是？','[{"key":"A","text":"-9"},{"key":"B","text":"9"},{"key":"C","text":"18"},{"key":"D","text":"0"}]','A','只有符号不同的两个数互为相反数，9 的相反数是 -9','template','approved','通用'),
('qt-rational-num-b4-2','math','初中',7,'kp-math-rational-num','single_choice',0.38,'9 的相反数是？','[{"key":"A","text":"-9"},{"key":"B","text":"9"},{"key":"C","text":"18"},{"key":"D","text":"0"}]','A','只有符号不同的两个数互为相反数，9 的相反数是 -9','template','approved','通用'),
('qt-rational-num-b4-3','math','初中',7,'kp-math-rational-num','single_choice',0.46,'3 的相反数是？','[{"key":"A","text":"-3"},{"key":"B","text":"3"},{"key":"C","text":"6"},{"key":"D","text":"0"}]','A','只有符号不同的两个数互为相反数，3 的相反数是 -3','template','approved','通用'),
('qt-rational-num-b4-4','math','初中',7,'kp-math-rational-num','single_choice',0.54,'9 的相反数是？','[{"key":"A","text":"-9"},{"key":"B","text":"9"},{"key":"C","text":"18"},{"key":"D","text":"0"}]','A','只有符号不同的两个数互为相反数，9 的相反数是 -9','template','approved','通用'),
('qt-rational-num-b4-5','math','初中',7,'kp-math-rational-num','single_choice',0.62,'2 的相反数是？','[{"key":"A","text":"-2"},{"key":"B","text":"2"},{"key":"C","text":"4"},{"key":"D","text":"0"}]','A','只有符号不同的两个数互为相反数，2 的相反数是 -2','template','approved','通用'),
('qt-rational-num-b4-6','math','初中',7,'kp-math-rational-num','single_choice',0.70,'6 的相反数是？','[{"key":"A","text":"-6"},{"key":"B","text":"6"},{"key":"C","text":"12"},{"key":"D","text":"0"}]','A','只有符号不同的两个数互为相反数，6 的相反数是 -6','template','approved','通用'),
('qt-rational-num-b4-7','math','初中',7,'kp-math-rational-num','single_choice',0.30,'3 的相反数是？','[{"key":"A","text":"-3"},{"key":"B","text":"3"},{"key":"C","text":"6"},{"key":"D","text":"0"}]','A','只有符号不同的两个数互为相反数，3 的相反数是 -3','template','approved','通用'),
('qt-rational-num-b4-8','math','初中',7,'kp-math-rational-num','single_choice',0.38,'1 的相反数是？','[{"key":"A","text":"-1"},{"key":"B","text":"1"},{"key":"C","text":"2"},{"key":"D","text":"0"}]','A','只有符号不同的两个数互为相反数，1 的相反数是 -1','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-rational-num-b4-9','math','初中',7,'kp-math-rational-num','single_choice',0.46,'1 的相反数是？','[{"key":"A","text":"-1"},{"key":"B","text":"1"},{"key":"C","text":"2"},{"key":"D","text":"0"}]','A','只有符号不同的两个数互为相反数，1 的相反数是 -1','template','approved','通用'),
('qt-rational-num-b4-10','math','初中',7,'kp-math-rational-num','single_choice',0.54,'1 的相反数是？','[{"key":"A","text":"-1"},{"key":"B","text":"1"},{"key":"C","text":"2"},{"key":"D","text":"0"}]','A','只有符号不同的两个数互为相反数，1 的相反数是 -1','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-rational-abs-b4-1','math','初中',7,'kp-math-rational-abs','single_choice',0.30,'|-2| = ？','[{"key":"A","text":"2"},{"key":"B","text":"-2"},{"key":"C","text":"0"},{"key":"D","text":"4"}]','A','绝对值是非负数：|-2|=2','template','approved','通用'),
('qt-rational-abs-b4-2','math','初中',7,'kp-math-rational-abs','single_choice',0.38,'|6| = ？','[{"key":"A","text":"6"},{"key":"B","text":"-6"},{"key":"C","text":"0"},{"key":"D","text":"12"}]','A','绝对值是非负数：|6|=6','template','approved','通用'),
('qt-rational-abs-b4-3','math','初中',7,'kp-math-rational-abs','single_choice',0.46,'|-1| = ？','[{"key":"A","text":"1"},{"key":"B","text":"-1"},{"key":"C","text":"0"},{"key":"D","text":"2"}]','A','绝对值是非负数：|-1|=1','template','approved','通用'),
('qt-rational-abs-b4-4','math','初中',7,'kp-math-rational-abs','single_choice',0.54,'|-6| = ？','[{"key":"A","text":"6"},{"key":"B","text":"-6"},{"key":"C","text":"0"},{"key":"D","text":"12"}]','A','绝对值是非负数：|-6|=6','template','approved','通用'),
('qt-rational-abs-b4-5','math','初中',7,'kp-math-rational-abs','single_choice',0.62,'|2| = ？','[{"key":"A","text":"2"},{"key":"B","text":"-2"},{"key":"C","text":"0"},{"key":"D","text":"4"}]','A','绝对值是非负数：|2|=2','template','approved','通用'),
('qt-rational-abs-b4-6','math','初中',7,'kp-math-rational-abs','single_choice',0.70,'|-1| = ？','[{"key":"A","text":"1"},{"key":"B","text":"-1"},{"key":"C","text":"0"},{"key":"D","text":"2"}]','A','绝对值是非负数：|-1|=1','template','approved','通用'),
('qt-rational-abs-b4-7','math','初中',7,'kp-math-rational-abs','single_choice',0.30,'|9| = ？','[{"key":"A","text":"9"},{"key":"B","text":"-9"},{"key":"C","text":"0"},{"key":"D","text":"18"}]','A','绝对值是非负数：|9|=9','template','approved','通用'),
('qt-rational-abs-b4-8','math','初中',7,'kp-math-rational-abs','single_choice',0.38,'|-4| = ？','[{"key":"A","text":"4"},{"key":"B","text":"-4"},{"key":"C","text":"0"},{"key":"D","text":"8"}]','A','绝对值是非负数：|-4|=4','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-rational-abs-b4-9','math','初中',7,'kp-math-rational-abs','single_choice',0.46,'|-7| = ？','[{"key":"A","text":"7"},{"key":"B","text":"-7"},{"key":"C","text":"0"},{"key":"D","text":"14"}]','A','绝对值是非负数：|-7|=7','template','approved','通用'),
('qt-rational-abs-b4-10','math','初中',7,'kp-math-rational-abs','single_choice',0.54,'|-1| = ？','[{"key":"A","text":"1"},{"key":"B","text":"-1"},{"key":"C","text":"0"},{"key":"D","text":"2"}]','A','绝对值是非负数：|-1|=1','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-exp-b4-1','math','初中',7,'kp-math-exp','single_choice',0.30,'化简：9a + 6b + 8a + 7b = ？','[{"key":"A","text":"17a + 13b"},{"key":"B","text":"17a"},{"key":"C","text":"13b"},{"key":"D","text":"15a + 15b"}]','A','合并同类项：9a+8a=17a，6b+7b=13b','template','approved','通用'),
('qt-exp-b4-2','math','初中',7,'kp-math-exp','single_choice',0.38,'化简：2a + 8b + 3a + 1b = ？','[{"key":"A","text":"5a + 9b"},{"key":"B","text":"5a"},{"key":"C","text":"9b"},{"key":"D","text":"10a + 4b"}]','A','合并同类项：2a+3a=5a，8b+1b=9b','template','approved','通用'),
('qt-exp-b4-3','math','初中',7,'kp-math-exp','single_choice',0.46,'化简：8a + 9b + 7a + 9b = ？','[{"key":"A","text":"15a + 18b"},{"key":"B","text":"15a"},{"key":"C","text":"18b"},{"key":"D","text":"17a + 16b"}]','A','合并同类项：8a+7a=15a，9b+9b=18b','template','approved','通用'),
('qt-exp-b4-4','math','初中',7,'kp-math-exp','single_choice',0.54,'化简：3a + 5b + 9a + 5b = ？','[{"key":"A","text":"12a + 10b"},{"key":"B","text":"12a"},{"key":"C","text":"10b"},{"key":"D","text":"8a + 14b"}]','A','合并同类项：3a+9a=12a，5b+5b=10b','template','approved','通用'),
('qt-exp-b4-5','math','初中',7,'kp-math-exp','single_choice',0.62,'化简：3a + 6b + 4a + 5b = ？','[{"key":"A","text":"7a + 11b"},{"key":"B","text":"7a"},{"key":"C","text":"11b"},{"key":"D","text":"9a + 9b"}]','A','合并同类项：3a+4a=7a，6b+5b=11b','template','approved','通用'),
('qt-exp-b4-6','math','初中',7,'kp-math-exp','single_choice',0.70,'化简：7a + 5b + 4a + 7b = ？','[{"key":"A","text":"11a + 12b"},{"key":"B","text":"11a"},{"key":"C","text":"12b"},{"key":"D","text":"12a + 11b"}]','A','合并同类项：7a+4a=11a，5b+7b=12b','template','approved','通用'),
('qt-exp-b4-7','math','初中',7,'kp-math-exp','single_choice',0.30,'化简：3a + 2b + 4a + 9b = ？','[{"key":"A","text":"7a + 11b"},{"key":"B","text":"7a"},{"key":"C","text":"11b"},{"key":"D","text":"5a + 13b"}]','A','合并同类项：3a+4a=7a，2b+9b=11b','template','approved','通用'),
('qt-exp-b4-8','math','初中',7,'kp-math-exp','single_choice',0.38,'化简：7a + 3b + 8a + 8b = ？','[{"key":"A","text":"15a + 11b"},{"key":"B","text":"15a"},{"key":"C","text":"11b"},{"key":"D","text":"10a + 16b"}]','A','合并同类项：7a+8a=15a，3b+8b=11b','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-exp-b4-9','math','初中',7,'kp-math-exp','single_choice',0.46,'化简：4a + 6b + 8a + 8b = ？','[{"key":"A","text":"12a + 14b"},{"key":"B","text":"12a"},{"key":"C","text":"14b"},{"key":"D","text":"10a + 16b"}]','A','合并同类项：4a+8a=12a，6b+8b=14b','template','approved','通用'),
('qt-exp-b4-10','math','初中',7,'kp-math-exp','single_choice',0.54,'化简：7a + 1b + 1a + 3b = ？','[{"key":"A","text":"8a + 4b"},{"key":"B","text":"8a"},{"key":"C","text":"4b"},{"key":"D","text":"8a + 4b"}]','A','合并同类项：7a+1a=8a，1b+3b=4b','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-equation-b4-1','math','初中',7,'kp-math-equation','single_choice',0.30,'解方程 3x + 2 = 5，x = ？','[{"key":"A","text":"1"},{"key":"B","text":"2"},{"key":"C","text":"0"},{"key":"D","text":"5"}]','A','移项得 3x=5-2=3，系数化一得 x=1','template','approved','通用'),
('qt-equation-b4-2','math','初中',7,'kp-math-equation','single_choice',0.38,'解方程 5x + 6 = 26，x = ？','[{"key":"A","text":"4"},{"key":"B","text":"5"},{"key":"C","text":"3"},{"key":"D","text":"26"}]','A','移项得 5x=26-6=20，系数化一得 x=4','template','approved','通用'),
('qt-equation-b4-3','math','初中',7,'kp-math-equation','single_choice',0.46,'解方程 3x + 4 = 25，x = ？','[{"key":"A","text":"7"},{"key":"B","text":"8"},{"key":"C","text":"6"},{"key":"D","text":"25"}]','A','移项得 3x=25-4=21，系数化一得 x=7','template','approved','通用'),
('qt-equation-b4-4','math','初中',7,'kp-math-equation','single_choice',0.54,'解方程 5x + 1 = 36，x = ？','[{"key":"A","text":"7"},{"key":"B","text":"8"},{"key":"C","text":"6"},{"key":"D","text":"36"}]','A','移项得 5x=36-1=35，系数化一得 x=7','template','approved','通用'),
('qt-equation-b4-5','math','初中',7,'kp-math-equation','single_choice',0.62,'解方程 5x + 5 = 40，x = ？','[{"key":"A","text":"7"},{"key":"B","text":"8"},{"key":"C","text":"6"},{"key":"D","text":"40"}]','A','移项得 5x=40-5=35，系数化一得 x=7','template','approved','通用'),
('qt-equation-b4-6','math','初中',7,'kp-math-equation','single_choice',0.70,'解方程 2x + 9 = 15，x = ？','[{"key":"A","text":"3"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"15"}]','A','移项得 2x=15-9=6，系数化一得 x=3','template','approved','通用'),
('qt-equation-b4-7','math','初中',7,'kp-math-equation','single_choice',0.30,'解方程 5x + 5 = 50，x = ？','[{"key":"A","text":"9"},{"key":"B","text":"10"},{"key":"C","text":"8"},{"key":"D","text":"50"}]','A','移项得 5x=50-5=45，系数化一得 x=9','template','approved','通用'),
('qt-equation-b4-8','math','初中',7,'kp-math-equation','single_choice',0.38,'解方程 4x + 6 = 42，x = ？','[{"key":"A","text":"9"},{"key":"B","text":"10"},{"key":"C","text":"8"},{"key":"D","text":"42"}]','A','移项得 4x=42-6=36，系数化一得 x=9','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-equation-b4-9','math','初中',7,'kp-math-equation','single_choice',0.46,'解方程 1x + 9 = 12，x = ？','[{"key":"A","text":"3"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"12"}]','A','移项得 1x=12-9=3，系数化一得 x=3','template','approved','通用'),
('qt-equation-b4-10','math','初中',7,'kp-math-equation','single_choice',0.54,'解方程 3x + 2 = 26，x = ？','[{"key":"A","text":"8"},{"key":"B","text":"9"},{"key":"C","text":"7"},{"key":"D","text":"26"}]','A','移项得 3x=26-2=24，系数化一得 x=8','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-ineq-b4-1','math','初中',7,'kp-math-ineq','single_choice',0.30,'不等式 1x - 1 > 1 的解集是？','[{"key":"A","text":"x > 2"},{"key":"B","text":"x < 2"},{"key":"C","text":"x > 0"},{"key":"D","text":"x ≥ 2"}]','A','移项 1x>2，除以 1 得 x>2','template','approved','通用'),
('qt-ineq-b4-2','math','初中',7,'kp-math-ineq','single_choice',0.38,'不等式 1x - 1 > 5 的解集是？','[{"key":"A","text":"x > 6"},{"key":"B","text":"x < 6"},{"key":"C","text":"x > 4"},{"key":"D","text":"x ≥ 6"}]','A','移项 1x>6，除以 1 得 x>6','template','approved','通用'),
('qt-ineq-b4-3','math','初中',7,'kp-math-ineq','single_choice',0.46,'不等式 3x - 1 > 23 的解集是？','[{"key":"A","text":"x > 8"},{"key":"B","text":"x < 8"},{"key":"C","text":"x > 6"},{"key":"D","text":"x ≥ 8"}]','A','移项 3x>24，除以 3 得 x>8','template','approved','通用'),
('qt-ineq-b4-4','math','初中',7,'kp-math-ineq','single_choice',0.54,'不等式 3x - 1 > 20 的解集是？','[{"key":"A","text":"x > 7"},{"key":"B","text":"x < 7"},{"key":"C","text":"x > 5"},{"key":"D","text":"x ≥ 7"}]','A','移项 3x>21，除以 3 得 x>7','template','approved','通用'),
('qt-ineq-b4-5','math','初中',7,'kp-math-ineq','single_choice',0.62,'不等式 3x - 1 > 11 的解集是？','[{"key":"A","text":"x > 4"},{"key":"B","text":"x < 4"},{"key":"C","text":"x > 2"},{"key":"D","text":"x ≥ 4"}]','A','移项 3x>12，除以 3 得 x>4','template','approved','通用'),
('qt-ineq-b4-6','math','初中',7,'kp-math-ineq','single_choice',0.70,'不等式 1x - 1 > 4 的解集是？','[{"key":"A","text":"x > 5"},{"key":"B","text":"x < 5"},{"key":"C","text":"x > 3"},{"key":"D","text":"x ≥ 5"}]','A','移项 1x>5，除以 1 得 x>5','template','approved','通用'),
('qt-ineq-b4-7','math','初中',7,'kp-math-ineq','single_choice',0.30,'不等式 1x - 1 > 4 的解集是？','[{"key":"A","text":"x > 5"},{"key":"B","text":"x < 5"},{"key":"C","text":"x > 3"},{"key":"D","text":"x ≥ 5"}]','A','移项 1x>5，除以 1 得 x>5','template','approved','通用'),
('qt-ineq-b4-8','math','初中',7,'kp-math-ineq','single_choice',0.38,'不等式 3x - 1 > 8 的解集是？','[{"key":"A","text":"x > 3"},{"key":"B","text":"x < 3"},{"key":"C","text":"x > 1"},{"key":"D","text":"x ≥ 3"}]','A','移项 3x>9，除以 3 得 x>3','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-ineq-b4-9','math','初中',7,'kp-math-ineq','single_choice',0.46,'不等式 3x - 1 > 20 的解集是？','[{"key":"A","text":"x > 7"},{"key":"B","text":"x < 7"},{"key":"C","text":"x > 5"},{"key":"D","text":"x ≥ 7"}]','A','移项 3x>21，除以 3 得 x>7','template','approved','通用'),
('qt-ineq-b4-10','math','初中',7,'kp-math-ineq','single_choice',0.54,'不等式 2x - 1 > 7 的解集是？','[{"key":"A","text":"x > 4"},{"key":"B","text":"x < 4"},{"key":"C","text":"x > 2"},{"key":"D","text":"x ≥ 4"}]','A','移项 2x>8，除以 2 得 x>4','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-system-b4-1','math','初中',8,'kp-math-system','single_choice',0.30,'方程组 {x+y=6, x-y=-4} 的解是？','[{"key":"A","text":"x=1, y=5"},{"key":"B","text":"x=5, y=1"},{"key":"C","text":"x=2, y=5"},{"key":"D","text":"x=1, y=6"}]','A','两式相加 2x=2，x=1；代入得 y=5','template','approved','通用'),
('qt-system-b4-2','math','初中',8,'kp-math-system','single_choice',0.38,'方程组 {x+y=6, x-y=-2} 的解是？','[{"key":"A","text":"x=2, y=4"},{"key":"B","text":"x=4, y=2"},{"key":"C","text":"x=3, y=4"},{"key":"D","text":"x=2, y=5"}]','A','两式相加 2x=4，x=2；代入得 y=4','template','approved','通用'),
('qt-system-b4-3','math','初中',8,'kp-math-system','single_choice',0.46,'方程组 {x+y=7, x-y=5} 的解是？','[{"key":"A","text":"x=6, y=1"},{"key":"B","text":"x=1, y=6"},{"key":"C","text":"x=7, y=1"},{"key":"D","text":"x=6, y=2"}]','A','两式相加 2x=12，x=6；代入得 y=1','template','approved','通用'),
('qt-system-b4-4','math','初中',8,'kp-math-system','single_choice',0.54,'方程组 {x+y=9, x-y=-3} 的解是？','[{"key":"A","text":"x=3, y=6"},{"key":"B","text":"x=6, y=3"},{"key":"C","text":"x=4, y=6"},{"key":"D","text":"x=3, y=7"}]','A','两式相加 2x=6，x=3；代入得 y=6','template','approved','通用'),
('qt-system-b4-5','math','初中',8,'kp-math-system','single_choice',0.62,'方程组 {x+y=9, x-y=-3} 的解是？','[{"key":"A","text":"x=3, y=6"},{"key":"B","text":"x=6, y=3"},{"key":"C","text":"x=4, y=6"},{"key":"D","text":"x=3, y=7"}]','A','两式相加 2x=6，x=3；代入得 y=6','template','approved','通用'),
('qt-system-b4-6','math','初中',8,'kp-math-system','single_choice',0.70,'方程组 {x+y=5, x-y=3} 的解是？','[{"key":"A","text":"x=4, y=1"},{"key":"B","text":"x=1, y=4"},{"key":"C","text":"x=5, y=1"},{"key":"D","text":"x=4, y=2"}]','A','两式相加 2x=8，x=4；代入得 y=1','template','approved','通用'),
('qt-system-b4-7','math','初中',8,'kp-math-system','single_choice',0.30,'方程组 {x+y=6, x-y=4} 的解是？','[{"key":"A","text":"x=5, y=1"},{"key":"B","text":"x=1, y=5"},{"key":"C","text":"x=6, y=1"},{"key":"D","text":"x=5, y=2"}]','A','两式相加 2x=10，x=5；代入得 y=1','template','approved','通用'),
('qt-system-b4-8','math','初中',8,'kp-math-system','single_choice',0.38,'方程组 {x+y=11, x-y=1} 的解是？','[{"key":"A","text":"x=6, y=5"},{"key":"B","text":"x=5, y=6"},{"key":"C","text":"x=7, y=5"},{"key":"D","text":"x=6, y=6"}]','A','两式相加 2x=12，x=6；代入得 y=5','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-system-b4-9','math','初中',8,'kp-math-system','single_choice',0.46,'方程组 {x+y=5, x-y=3} 的解是？','[{"key":"A","text":"x=4, y=1"},{"key":"B","text":"x=1, y=4"},{"key":"C","text":"x=5, y=1"},{"key":"D","text":"x=4, y=2"}]','A','两式相加 2x=8，x=4；代入得 y=1','template','approved','通用'),
('qt-system-b4-10','math','初中',8,'kp-math-system','single_choice',0.54,'方程组 {x+y=10, x-y=0} 的解是？','[{"key":"A","text":"x=5, y=5"},{"key":"B","text":"x=5, y=5"},{"key":"C","text":"x=6, y=5"},{"key":"D","text":"x=5, y=6"}]','A','两式相加 2x=10，x=5；代入得 y=5','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-multiply-b4-1','math','初中',8,'kp-math-multiply','single_choice',0.30,'计算：(2x + 5)(2x - 5) = ？','[{"key":"A","text":"4x² - 25"},{"key":"B","text":"4x² + 25"},{"key":"C","text":"4x² + 20x + 25"},{"key":"D","text":"4x² - 20x + 25"}]','A','平方差公式：(2x)²-(5)²=4x²-25','template','approved','通用'),
('qt-multiply-b4-2','math','初中',8,'kp-math-multiply','single_choice',0.38,'计算：(7x + 9)(7x - 9) = ？','[{"key":"A","text":"49x² - 81"},{"key":"B","text":"49x² + 81"},{"key":"C","text":"49x² + 126x + 81"},{"key":"D","text":"49x² - 126x + 81"}]','A','平方差公式：(7x)²-(9)²=49x²-81','template','approved','通用'),
('qt-multiply-b4-3','math','初中',8,'kp-math-multiply','single_choice',0.46,'计算：(4x + 2)(4x - 2) = ？','[{"key":"A","text":"16x² - 4"},{"key":"B","text":"16x² + 4"},{"key":"C","text":"16x² + 16x + 4"},{"key":"D","text":"16x² - 16x + 4"}]','A','平方差公式：(4x)²-(2)²=16x²-4','template','approved','通用'),
('qt-multiply-b4-4','math','初中',8,'kp-math-multiply','single_choice',0.54,'计算：(4x + 6)(4x - 6) = ？','[{"key":"A","text":"16x² - 36"},{"key":"B","text":"16x² + 36"},{"key":"C","text":"16x² + 48x + 36"},{"key":"D","text":"16x² - 48x + 36"}]','A','平方差公式：(4x)²-(6)²=16x²-36','template','approved','通用'),
('qt-multiply-b4-5','math','初中',8,'kp-math-multiply','single_choice',0.62,'计算：(4x + 5)(4x - 5) = ？','[{"key":"A","text":"16x² - 25"},{"key":"B","text":"16x² + 25"},{"key":"C","text":"16x² + 40x + 25"},{"key":"D","text":"16x² - 40x + 25"}]','A','平方差公式：(4x)²-(5)²=16x²-25','template','approved','通用'),
('qt-multiply-b4-6','math','初中',8,'kp-math-multiply','single_choice',0.70,'计算：(2x + 2)(2x - 2) = ？','[{"key":"A","text":"4x² - 4"},{"key":"B","text":"4x² + 4"},{"key":"C","text":"4x² + 8x + 4"},{"key":"D","text":"4x² - 8x + 4"}]','A','平方差公式：(2x)²-(2)²=4x²-4','template','approved','通用'),
('qt-multiply-b4-7','math','初中',8,'kp-math-multiply','single_choice',0.30,'计算：(9x + 4)(9x - 4) = ？','[{"key":"A","text":"81x² - 16"},{"key":"B","text":"81x² + 16"},{"key":"C","text":"81x² + 72x + 16"},{"key":"D","text":"81x² - 72x + 16"}]','A','平方差公式：(9x)²-(4)²=81x²-16','template','approved','通用'),
('qt-multiply-b4-8','math','初中',8,'kp-math-multiply','single_choice',0.38,'计算：(9x + 2)(9x - 2) = ？','[{"key":"A","text":"81x² - 4"},{"key":"B","text":"81x² + 4"},{"key":"C","text":"81x² + 36x + 4"},{"key":"D","text":"81x² - 36x + 4"}]','A','平方差公式：(9x)²-(2)²=81x²-4','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-multiply-b4-9','math','初中',8,'kp-math-multiply','single_choice',0.46,'计算：(5x + 6)(5x - 6) = ？','[{"key":"A","text":"25x² - 36"},{"key":"B","text":"25x² + 36"},{"key":"C","text":"25x² + 60x + 36"},{"key":"D","text":"25x² - 60x + 36"}]','A','平方差公式：(5x)²-(6)²=25x²-36','template','approved','通用'),
('qt-multiply-b4-10','math','初中',8,'kp-math-multiply','single_choice',0.54,'计算：(2x + 9)(2x - 9) = ？','[{"key":"A","text":"4x² - 81"},{"key":"B","text":"4x² + 81"},{"key":"C","text":"4x² + 36x + 81"},{"key":"D","text":"4x² - 36x + 81"}]','A','平方差公式：(2x)²-(9)²=4x²-81','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-func-b4-1','math','初中',9,'kp-math-func','single_choice',0.30,'一次函数 y = 2x + 8 与 y 轴的交点是？','[{"key":"A","text":"(0, 8)"},{"key":"B","text":"(8, 0)"},{"key":"C","text":"(0, 0)"},{"key":"D","text":"(1, 10)"}]','A','令 x=0，y=8，故与 y 轴交点 (0, 8)','template','approved','通用'),
('qt-func-b4-2','math','初中',9,'kp-math-func','single_choice',0.38,'一次函数 y = 3x + 9 与 y 轴的交点是？','[{"key":"A","text":"(0, 9)"},{"key":"B","text":"(9, 0)"},{"key":"C","text":"(0, 0)"},{"key":"D","text":"(1, 12)"}]','A','令 x=0，y=9，故与 y 轴交点 (0, 9)','template','approved','通用'),
('qt-func-b4-3','math','初中',9,'kp-math-func','single_choice',0.46,'一次函数 y = 2x + 5 与 y 轴的交点是？','[{"key":"A","text":"(0, 5)"},{"key":"B","text":"(5, 0)"},{"key":"C","text":"(0, 0)"},{"key":"D","text":"(1, 7)"}]','A','令 x=0，y=5，故与 y 轴交点 (0, 5)','template','approved','通用'),
('qt-func-b4-4','math','初中',9,'kp-math-func','single_choice',0.54,'一次函数 y = 2x + 4 与 y 轴的交点是？','[{"key":"A","text":"(0, 4)"},{"key":"B","text":"(4, 0)"},{"key":"C","text":"(0, 0)"},{"key":"D","text":"(1, 6)"}]','A','令 x=0，y=4，故与 y 轴交点 (0, 4)','template','approved','通用'),
('qt-func-b4-5','math','初中',9,'kp-math-func','single_choice',0.62,'一次函数 y = 4x + 2 与 y 轴的交点是？','[{"key":"A","text":"(0, 2)"},{"key":"B","text":"(2, 0)"},{"key":"C","text":"(0, 0)"},{"key":"D","text":"(1, 6)"}]','A','令 x=0，y=2，故与 y 轴交点 (0, 2)','template','approved','通用'),
('qt-func-b4-6','math','初中',9,'kp-math-func','single_choice',0.70,'一次函数 y = 4x + 8 与 y 轴的交点是？','[{"key":"A","text":"(0, 8)"},{"key":"B","text":"(8, 0)"},{"key":"C","text":"(0, 0)"},{"key":"D","text":"(1, 12)"}]','A','令 x=0，y=8，故与 y 轴交点 (0, 8)','template','approved','通用'),
('qt-func-b4-7','math','初中',9,'kp-math-func','single_choice',0.30,'一次函数 y = 2x + 5 与 y 轴的交点是？','[{"key":"A","text":"(0, 5)"},{"key":"B","text":"(5, 0)"},{"key":"C","text":"(0, 0)"},{"key":"D","text":"(1, 7)"}]','A','令 x=0，y=5，故与 y 轴交点 (0, 5)','template','approved','通用'),
('qt-func-b4-8','math','初中',9,'kp-math-func','single_choice',0.38,'一次函数 y = 3x + 6 与 y 轴的交点是？','[{"key":"A","text":"(0, 6)"},{"key":"B","text":"(6, 0)"},{"key":"C","text":"(0, 0)"},{"key":"D","text":"(1, 9)"}]','A','令 x=0，y=6，故与 y 轴交点 (0, 6)','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-func-b4-9','math','初中',9,'kp-math-func','single_choice',0.46,'一次函数 y = 3x + 4 与 y 轴的交点是？','[{"key":"A","text":"(0, 4)"},{"key":"B","text":"(4, 0)"},{"key":"C","text":"(0, 0)"},{"key":"D","text":"(1, 7)"}]','A','令 x=0，y=4，故与 y 轴交点 (0, 4)','template','approved','通用'),
('qt-func-b4-10','math','初中',9,'kp-math-func','single_choice',0.54,'一次函数 y = 3x + 4 与 y 轴的交点是？','[{"key":"A","text":"(0, 4)"},{"key":"B","text":"(4, 0)"},{"key":"C","text":"(0, 0)"},{"key":"D","text":"(1, 7)"}]','A','令 x=0，y=4，故与 y 轴交点 (0, 4)','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-congruent-b4-1','math','初中',9,'kp-math-congruent','single_choice',0.30,'若△ABC≌△DEF，且 BC=8，则 EF = ？','[{"key":"A","text":"8"},{"key":"B","text":"16"},{"key":"C","text":"4"},{"key":"D","text":"无法确定"}]','A','全等三角形对应边相等，BC 对应 EF，故 EF=8','template','approved','通用'),
('qt-congruent-b4-2','math','初中',9,'kp-math-congruent','single_choice',0.38,'若△ABC≌△DEF，且 BC=7，则 EF = ？','[{"key":"A","text":"7"},{"key":"B","text":"14"},{"key":"C","text":"3.5"},{"key":"D","text":"无法确定"}]','A','全等三角形对应边相等，BC 对应 EF，故 EF=7','template','approved','通用'),
('qt-congruent-b4-3','math','初中',9,'kp-math-congruent','single_choice',0.46,'若△ABC≌△DEF，且 BC=4，则 EF = ？','[{"key":"A","text":"4"},{"key":"B","text":"8"},{"key":"C","text":"2"},{"key":"D","text":"无法确定"}]','A','全等三角形对应边相等，BC 对应 EF，故 EF=4','template','approved','通用'),
('qt-congruent-b4-4','math','初中',9,'kp-math-congruent','single_choice',0.54,'若△ABC≌△DEF，且 BC=6，则 EF = ？','[{"key":"A","text":"6"},{"key":"B","text":"12"},{"key":"C","text":"3"},{"key":"D","text":"无法确定"}]','A','全等三角形对应边相等，BC 对应 EF，故 EF=6','template','approved','通用'),
('qt-congruent-b4-5','math','初中',9,'kp-math-congruent','single_choice',0.62,'若△ABC≌△DEF，且 BC=5，则 EF = ？','[{"key":"A","text":"5"},{"key":"B","text":"10"},{"key":"C","text":"2.5"},{"key":"D","text":"无法确定"}]','A','全等三角形对应边相等，BC 对应 EF，故 EF=5','template','approved','通用'),
('qt-congruent-b4-6','math','初中',9,'kp-math-congruent','single_choice',0.70,'若△ABC≌△DEF，且 BC=6，则 EF = ？','[{"key":"A","text":"6"},{"key":"B","text":"12"},{"key":"C","text":"3"},{"key":"D","text":"无法确定"}]','A','全等三角形对应边相等，BC 对应 EF，故 EF=6','template','approved','通用'),
('qt-congruent-b4-7','math','初中',9,'kp-math-congruent','single_choice',0.30,'若△ABC≌△DEF，且 BC=9，则 EF = ？','[{"key":"A","text":"9"},{"key":"B","text":"18"},{"key":"C","text":"4.5"},{"key":"D","text":"无法确定"}]','A','全等三角形对应边相等，BC 对应 EF，故 EF=9','template','approved','通用'),
('qt-congruent-b4-8','math','初中',9,'kp-math-congruent','single_choice',0.38,'若△ABC≌△DEF，且 BC=12，则 EF = ？','[{"key":"A","text":"12"},{"key":"B","text":"24"},{"key":"C","text":"6"},{"key":"D","text":"无法确定"}]','A','全等三角形对应边相等，BC 对应 EF，故 EF=12','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-congruent-b4-9','math','初中',9,'kp-math-congruent','single_choice',0.46,'若△ABC≌△DEF，且 BC=12，则 EF = ？','[{"key":"A","text":"12"},{"key":"B","text":"24"},{"key":"C","text":"6"},{"key":"D","text":"无法确定"}]','A','全等三角形对应边相等，BC 对应 EF，故 EF=12','template','approved','通用'),
('qt-congruent-b4-10','math','初中',9,'kp-math-congruent','single_choice',0.54,'若△ABC≌△DEF，且 BC=3，则 EF = ？','[{"key":"A","text":"3"},{"key":"B","text":"6"},{"key":"C","text":"1.5"},{"key":"D","text":"无法确定"}]','A','全等三角形对应边相等，BC 对应 EF，故 EF=3','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-pythagoras-b4-1','math','初中',10,'kp-math-pythagoras','single_choice',0.30,'直角三角形两直角边为 3 和 4，斜边为？','[{"key":"A","text":"5"},{"key":"B","text":"6"},{"key":"C","text":"7"},{"key":"D","text":"4"}]','A','勾股定理：√(3²+4²)=5','template','approved','通用'),
('qt-pythagoras-b4-2','math','初中',10,'kp-math-pythagoras','single_choice',0.38,'直角三角形两直角边为 5 和 12，斜边为？','[{"key":"A","text":"13"},{"key":"B","text":"14"},{"key":"C","text":"17"},{"key":"D","text":"12"}]','A','勾股定理：√(5²+12²)=13','template','approved','通用'),
('qt-pythagoras-b4-3','math','初中',10,'kp-math-pythagoras','single_choice',0.46,'直角三角形两直角边为 6 和 8，斜边为？','[{"key":"A","text":"10"},{"key":"B","text":"11"},{"key":"C","text":"14"},{"key":"D","text":"9"}]','A','勾股定理：√(6²+8²)=10','template','approved','通用'),
('qt-pythagoras-b4-4','math','初中',10,'kp-math-pythagoras','single_choice',0.54,'直角三角形两直角边为 8 和 15，斜边为？','[{"key":"A","text":"17"},{"key":"B","text":"18"},{"key":"C","text":"23"},{"key":"D","text":"16"}]','A','勾股定理：√(8²+15²)=17','template','approved','通用'),
('qt-pythagoras-b4-5','math','初中',10,'kp-math-pythagoras','single_choice',0.62,'直角三角形两直角边为 9 和 12，斜边为？','[{"key":"A","text":"15"},{"key":"B","text":"16"},{"key":"C","text":"21"},{"key":"D","text":"14"}]','A','勾股定理：√(9²+12²)=15','template','approved','通用'),
('qt-pythagoras-b4-6','math','初中',10,'kp-math-pythagoras','single_choice',0.70,'直角三角形两直角边为 7 和 24，斜边为？','[{"key":"A","text":"25"},{"key":"B","text":"26"},{"key":"C","text":"31"},{"key":"D","text":"24"}]','A','勾股定理：√(7²+24²)=25','template','approved','通用'),
('qt-pythagoras-b4-7','math','初中',10,'kp-math-pythagoras','single_choice',0.30,'直角三角形斜边为 5，一条直角边为 3，另一条直角边为？','[{"key":"A","text":"4"},{"key":"B","text":"5"},{"key":"C","text":"2"},{"key":"D","text":"7"}]','A','勾股定理：√(5²-3²)=4','template','approved','通用'),
('qt-pythagoras-b4-8','math','初中',10,'kp-math-pythagoras','single_choice',0.38,'直角三角形斜边为 13，一条直角边为 5，另一条直角边为？','[{"key":"A","text":"12"},{"key":"B","text":"13"},{"key":"C","text":"8"},{"key":"D","text":"17"}]','A','勾股定理：√(13²-5²)=12','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-pythagoras-b4-9','math','初中',10,'kp-math-pythagoras','single_choice',0.46,'直角三角形斜边为 10，一条直角边为 6，另一条直角边为？','[{"key":"A","text":"8"},{"key":"B","text":"9"},{"key":"C","text":"4"},{"key":"D","text":"14"}]','A','勾股定理：√(10²-6²)=8','template','approved','通用'),
('qt-pythagoras-b4-10','math','初中',10,'kp-math-pythagoras','single_choice',0.54,'直角三角形斜边为 17，一条直角边为 8，另一条直角边为？','[{"key":"A","text":"15"},{"key":"B","text":"16"},{"key":"C","text":"9"},{"key":"D","text":"23"}]','A','勾股定理：√(17²-8²)=15','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-parallelogram-b4-1','math','初中',10,'kp-math-parallelogram','single_choice',0.30,'平行四边形 ABCD 中 ∠A=40°，则 ∠B = ？','[{"key":"A","text":"140°"},{"key":"B","text":"40°"},{"key":"C","text":"130°"},{"key":"D","text":"50°"}]','A','平行四边形邻角互补：∠B=180°-40°=140°','template','approved','通用'),
('qt-parallelogram-b4-2','math','初中',10,'kp-math-parallelogram','single_choice',0.38,'平行四边形 ABCD 中 ∠A=100°，则 ∠B = ？','[{"key":"A","text":"80°"},{"key":"B","text":"100°"},{"key":"C","text":"70°"},{"key":"D","text":"110°"}]','A','平行四边形邻角互补：∠B=180°-100°=80°','template','approved','通用'),
('qt-parallelogram-b4-3','math','初中',10,'kp-math-parallelogram','single_choice',0.46,'平行四边形 ABCD 中 ∠A=50°，则 ∠B = ？','[{"key":"A","text":"130°"},{"key":"B","text":"50°"},{"key":"C","text":"120°"},{"key":"D","text":"60°"}]','A','平行四边形邻角互补：∠B=180°-50°=130°','template','approved','通用'),
('qt-parallelogram-b4-4','math','初中',10,'kp-math-parallelogram','single_choice',0.54,'平行四边形 ABCD 中 ∠A=80°，则 ∠B = ？','[{"key":"A","text":"100°"},{"key":"B","text":"80°"},{"key":"C","text":"90°"},{"key":"D","text":"90°"}]','A','平行四边形邻角互补：∠B=180°-80°=100°','template','approved','通用'),
('qt-parallelogram-b4-5','math','初中',10,'kp-math-parallelogram','single_choice',0.62,'平行四边形 ABCD 中 ∠A=50°，则 ∠B = ？','[{"key":"A","text":"130°"},{"key":"B","text":"50°"},{"key":"C","text":"120°"},{"key":"D","text":"60°"}]','A','平行四边形邻角互补：∠B=180°-50°=130°','template','approved','通用'),
('qt-parallelogram-b4-6','math','初中',10,'kp-math-parallelogram','single_choice',0.70,'平行四边形 ABCD 中 ∠A=60°，则 ∠B = ？','[{"key":"A","text":"120°"},{"key":"B","text":"60°"},{"key":"C","text":"110°"},{"key":"D","text":"70°"}]','A','平行四边形邻角互补：∠B=180°-60°=120°','template','approved','通用'),
('qt-parallelogram-b4-7','math','初中',10,'kp-math-parallelogram','single_choice',0.30,'平行四边形 ABCD 中 ∠A=80°，则 ∠B = ？','[{"key":"A","text":"100°"},{"key":"B","text":"80°"},{"key":"C","text":"90°"},{"key":"D","text":"90°"}]','A','平行四边形邻角互补：∠B=180°-80°=100°','template','approved','通用'),
('qt-parallelogram-b4-8','math','初中',10,'kp-math-parallelogram','single_choice',0.38,'平行四边形 ABCD 中 ∠A=80°，则 ∠B = ？','[{"key":"A","text":"100°"},{"key":"B","text":"80°"},{"key":"C","text":"90°"},{"key":"D","text":"90°"}]','A','平行四边形邻角互补：∠B=180°-80°=100°','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-parallelogram-b4-9','math','初中',10,'kp-math-parallelogram','single_choice',0.46,'平行四边形 ABCD 中 ∠A=60°，则 ∠B = ？','[{"key":"A","text":"120°"},{"key":"B","text":"60°"},{"key":"C","text":"110°"},{"key":"D","text":"70°"}]','A','平行四边形邻角互补：∠B=180°-60°=120°','template','approved','通用'),
('qt-parallelogram-b4-10','math','初中',10,'kp-math-parallelogram','single_choice',0.54,'平行四边形 ABCD 中 ∠A=40°，则 ∠B = ？','[{"key":"A","text":"140°"},{"key":"B","text":"40°"},{"key":"C","text":"130°"},{"key":"D","text":"50°"}]','A','平行四边形邻角互补：∠B=180°-40°=140°','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-quadratic-b4-1','math','初中',11,'kp-math-quadratic','single_choice',0.30,'抛物线 y = 1x² + -2 的对称轴是？','[{"key":"A","text":"x = 0（y 轴）"},{"key":"B","text":"x = 1"},{"key":"C","text":"x = 1"},{"key":"D","text":"y = -2"}]','A','二次函数 y=ax²+c 无一次项，对称轴为 x=0（y 轴）','template','approved','通用'),
('qt-quadratic-b4-2','math','初中',11,'kp-math-quadratic','single_choice',0.38,'抛物线 y = 1x² + 1 的对称轴是？','[{"key":"A","text":"x = 0（y 轴）"},{"key":"B","text":"x = 1"},{"key":"C","text":"x = 1"},{"key":"D","text":"y = 1"}]','A','二次函数 y=ax²+c 无一次项，对称轴为 x=0（y 轴）','template','approved','通用'),
('qt-quadratic-b4-4','math','初中',11,'kp-math-quadratic','single_choice',0.46,'抛物线 y = 2x² + -1 的对称轴是？','[{"key":"A","text":"x = 0（y 轴）"},{"key":"B","text":"x = 3"},{"key":"C","text":"x = 1"},{"key":"D","text":"y = -1"}]','A','二次函数 y=ax²+c 无一次项，对称轴为 x=0（y 轴）','template','approved','通用'),
('qt-quadratic-b4-5','math','初中',11,'kp-math-quadratic','single_choice',0.54,'抛物线 y = 2x² + -3 的对称轴是？','[{"key":"A","text":"x = 0（y 轴）"},{"key":"B","text":"x = 2"},{"key":"C","text":"x = 1"},{"key":"D","text":"y = -3"}]','A','二次函数 y=ax²+c 无一次项，对称轴为 x=0（y 轴）','template','approved','通用'),
('qt-quadratic-b4-7','math','初中',11,'kp-math-quadratic','single_choice',0.62,'抛物线 y = 3x² + 3 的对称轴是？','[{"key":"A","text":"x = 0（y 轴）"},{"key":"B","text":"x = 3"},{"key":"C","text":"x = 1"},{"key":"D","text":"y = 3"}]','A','二次函数 y=ax²+c 无一次项，对称轴为 x=0（y 轴）','template','approved','通用'),
('qt-quadratic-b4-8','math','初中',11,'kp-math-quadratic','single_choice',0.70,'抛物线 y = 2x² + -5 的对称轴是？','[{"key":"A","text":"x = 0（y 轴）"},{"key":"B","text":"x = 1"},{"key":"C","text":"x = 1"},{"key":"D","text":"y = -5"}]','A','二次函数 y=ax²+c 无一次项，对称轴为 x=0（y 轴）','template','approved','通用'),
('qt-quadratic-b4-9','math','初中',11,'kp-math-quadratic','single_choice',0.30,'抛物线 y = 3x² + 4 的对称轴是？','[{"key":"A","text":"x = 0（y 轴）"},{"key":"B","text":"x = 2"},{"key":"C","text":"x = 1"},{"key":"D","text":"y = 4"}]','A','二次函数 y=ax²+c 无一次项，对称轴为 x=0（y 轴）','template','approved','通用'),
('qt-quadratic-b4-10','math','初中',11,'kp-math-quadratic','single_choice',0.38,'抛物线 y = 2x² + -2 的对称轴是？','[{"key":"A","text":"x = 0（y 轴）"},{"key":"B","text":"x = 2"},{"key":"C","text":"x = 1"},{"key":"D","text":"y = -2"}]','A','二次函数 y=ax²+c 无一次项，对称轴为 x=0（y 轴）','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-quadeq-b4-1','math','初中',11,'kp-math-quadeq','single_choice',0.30,'方程 x² - 7x + 12 = 0 的两根是？','[{"key":"A","text":"3 和 4"},{"key":"B","text":"-3 和 -4"},{"key":"C","text":"3 和 -4"},{"key":"D","text":"-3 和 4"}]','A','(x-3)(x-4)=0，故 x=3 或 x=4','template','approved','通用'),
('qt-quadeq-b4-2','math','初中',11,'kp-math-quadeq','single_choice',0.38,'方程 x² - 7x + 12 = 0 的两根是？','[{"key":"A","text":"3 和 4"},{"key":"B","text":"-3 和 -4"},{"key":"C","text":"3 和 -4"},{"key":"D","text":"-3 和 4"}]','A','(x-3)(x-4)=0，故 x=3 或 x=4','template','approved','通用'),
('qt-quadeq-b4-3','math','初中',11,'kp-math-quadeq','single_choice',0.46,'方程 x² - 6x + 8 = 0 的两根是？','[{"key":"A","text":"2 和 4"},{"key":"B","text":"-2 和 -4"},{"key":"C","text":"2 和 -4"},{"key":"D","text":"-2 和 4"}]','A','(x-2)(x-4)=0，故 x=2 或 x=4','template','approved','通用'),
('qt-quadeq-b4-4','math','初中',11,'kp-math-quadeq','single_choice',0.54,'方程 x² - 6x + 8 = 0 的两根是？','[{"key":"A","text":"2 和 4"},{"key":"B","text":"-2 和 -4"},{"key":"C","text":"2 和 -4"},{"key":"D","text":"-2 和 4"}]','A','(x-2)(x-4)=0，故 x=2 或 x=4','template','approved','通用'),
('qt-quadeq-b4-5','math','初中',11,'kp-math-quadeq','single_choice',0.62,'方程 x² - 6x + 9 = 0 的两根是？','[{"key":"A","text":"3 和 3"},{"key":"B","text":"-3 和 -3"},{"key":"C","text":"3 和 -3"},{"key":"D","text":"-3 和 3"}]','A','(x-3)(x-3)=0，故 x=3 或 x=3','template','approved','通用'),
('qt-quadeq-b4-6','math','初中',11,'kp-math-quadeq','single_choice',0.70,'方程 x² - 7x + 10 = 0 的两根是？','[{"key":"A","text":"2 和 5"},{"key":"B","text":"-2 和 -5"},{"key":"C","text":"2 和 -5"},{"key":"D","text":"-2 和 5"}]','A','(x-2)(x-5)=0，故 x=2 或 x=5','template','approved','通用'),
('qt-quadeq-b4-7','math','初中',11,'kp-math-quadeq','single_choice',0.30,'方程 x² - 7x + 10 = 0 的两根是？','[{"key":"A","text":"2 和 5"},{"key":"B","text":"-2 和 -5"},{"key":"C","text":"2 和 -5"},{"key":"D","text":"-2 和 5"}]','A','(x-2)(x-5)=0，故 x=2 或 x=5','template','approved','通用'),
('qt-quadeq-b4-8','math','初中',11,'kp-math-quadeq','single_choice',0.38,'方程 x² - 4x + 4 = 0 的两根是？','[{"key":"A","text":"2 和 2"},{"key":"B","text":"-2 和 -2"},{"key":"C","text":"2 和 -2"},{"key":"D","text":"-2 和 2"}]','A','(x-2)(x-2)=0，故 x=2 或 x=2','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-quadeq-b4-9','math','初中',11,'kp-math-quadeq','single_choice',0.46,'方程 x² - 7x + 10 = 0 的两根是？','[{"key":"A","text":"5 和 2"},{"key":"B","text":"-5 和 -2"},{"key":"C","text":"5 和 -2"},{"key":"D","text":"-5 和 2"}]','A','(x-5)(x-2)=0，故 x=5 或 x=2','template','approved','通用'),
('qt-quadeq-b4-10','math','初中',11,'kp-math-quadeq','single_choice',0.54,'方程 x² - 8x + 15 = 0 的两根是？','[{"key":"A","text":"3 和 5"},{"key":"B","text":"-3 和 -5"},{"key":"C","text":"3 和 -5"},{"key":"D","text":"-3 和 5"}]','A','(x-3)(x-5)=0，故 x=3 或 x=5','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-circle-b4-1','math','初中',12,'kp-math-circle','single_choice',0.30,'半径为 7 的圆的周长是？','[{"key":"A","text":"14π"},{"key":"B","text":"7π"},{"key":"C","text":"49π"},{"key":"D","text":"14"}]','A','圆周长 C=2πr=2π×7=14π','template','approved','通用'),
('qt-circle-b4-2','math','初中',12,'kp-math-circle','single_choice',0.38,'半径为 8 的圆的周长是？','[{"key":"A","text":"16π"},{"key":"B","text":"8π"},{"key":"C","text":"64π"},{"key":"D","text":"16"}]','A','圆周长 C=2πr=2π×8=16π','template','approved','通用'),
('qt-circle-b4-3','math','初中',12,'kp-math-circle','single_choice',0.46,'半径为 8 的圆的周长是？','[{"key":"A","text":"16π"},{"key":"B","text":"8π"},{"key":"C","text":"64π"},{"key":"D","text":"16"}]','A','圆周长 C=2πr=2π×8=16π','template','approved','通用'),
('qt-circle-b4-4','math','初中',12,'kp-math-circle','single_choice',0.54,'半径为 8 的圆的周长是？','[{"key":"A","text":"16π"},{"key":"B","text":"8π"},{"key":"C","text":"64π"},{"key":"D","text":"16"}]','A','圆周长 C=2πr=2π×8=16π','template','approved','通用'),
('qt-circle-b4-5','math','初中',12,'kp-math-circle','single_choice',0.62,'半径为 4 的圆的周长是？','[{"key":"A","text":"8π"},{"key":"B","text":"4π"},{"key":"C","text":"16π"},{"key":"D","text":"8"}]','A','圆周长 C=2πr=2π×4=8π','template','approved','通用'),
('qt-circle-b4-6','math','初中',12,'kp-math-circle','single_choice',0.70,'半径为 3 的圆的周长是？','[{"key":"A","text":"6π"},{"key":"B","text":"3π"},{"key":"C","text":"9π"},{"key":"D","text":"6"}]','A','圆周长 C=2πr=2π×3=6π','template','approved','通用'),
('qt-circle-b4-7','math','初中',12,'kp-math-circle','single_choice',0.30,'半径为 8 的圆的周长是？','[{"key":"A","text":"16π"},{"key":"B","text":"8π"},{"key":"C","text":"64π"},{"key":"D","text":"16"}]','A','圆周长 C=2πr=2π×8=16π','template','approved','通用'),
('qt-circle-b4-8','math','初中',12,'kp-math-circle','single_choice',0.38,'半径为 4 的圆的周长是？','[{"key":"A","text":"8π"},{"key":"B","text":"4π"},{"key":"C","text":"16π"},{"key":"D","text":"8"}]','A','圆周长 C=2πr=2π×4=8π','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-circle-b4-9','math','初中',12,'kp-math-circle','single_choice',0.46,'半径为 8 的圆的周长是？','[{"key":"A","text":"16π"},{"key":"B","text":"8π"},{"key":"C","text":"64π"},{"key":"D","text":"16"}]','A','圆周长 C=2πr=2π×8=16π','template','approved','通用'),
('qt-circle-b4-10','math','初中',12,'kp-math-circle','single_choice',0.54,'半径为 7 的圆的周长是？','[{"key":"A","text":"14π"},{"key":"B","text":"7π"},{"key":"C","text":"49π"},{"key":"D","text":"14"}]','A','圆周长 C=2πr=2π×7=14π','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-trigacute-b4-1','math','初中',12,'kp-math-trigacute','single_choice',0.30,'sin60° = ？','[{"key":"A","text":"√3/2"},{"key":"B","text":"1"},{"key":"C","text":"1/2"},{"key":"D","text":"√3"}]','A','sin60°=√3/2（特殊角三角函数值）','template','approved','通用'),
('qt-trigacute-b4-2','math','初中',12,'kp-math-trigacute','single_choice',0.38,'sin30° = ？','[{"key":"A","text":"1/2"},{"key":"B","text":"1"},{"key":"C","text":"1/2"},{"key":"D","text":"√3"}]','A','sin30°=1/2（特殊角三角函数值）','template','approved','通用'),
('qt-trigacute-b4-3','math','初中',12,'kp-math-trigacute','single_choice',0.46,'sin30° = ？','[{"key":"A","text":"1/2"},{"key":"B","text":"1"},{"key":"C","text":"1/2"},{"key":"D","text":"√3"}]','A','sin30°=1/2（特殊角三角函数值）','template','approved','通用'),
('qt-trigacute-b4-4','math','初中',12,'kp-math-trigacute','single_choice',0.54,'sin45° = ？','[{"key":"A","text":"√2/2"},{"key":"B","text":"1"},{"key":"C","text":"1/2"},{"key":"D","text":"√3"}]','A','sin45°=√2/2（特殊角三角函数值）','template','approved','通用'),
('qt-trigacute-b4-5','math','初中',12,'kp-math-trigacute','single_choice',0.62,'sin45° = ？','[{"key":"A","text":"√2/2"},{"key":"B","text":"1"},{"key":"C","text":"1/2"},{"key":"D","text":"√3"}]','A','sin45°=√2/2（特殊角三角函数值）','template','approved','通用'),
('qt-trigacute-b4-6','math','初中',12,'kp-math-trigacute','single_choice',0.70,'sin45° = ？','[{"key":"A","text":"√2/2"},{"key":"B","text":"1"},{"key":"C","text":"1/2"},{"key":"D","text":"√3"}]','A','sin45°=√2/2（特殊角三角函数值）','template','approved','通用'),
('qt-trigacute-b4-7','math','初中',12,'kp-math-trigacute','single_choice',0.30,'sin60° = ？','[{"key":"A","text":"√3/2"},{"key":"B","text":"1"},{"key":"C","text":"1/2"},{"key":"D","text":"√3"}]','A','sin60°=√3/2（特殊角三角函数值）','template','approved','通用'),
('qt-trigacute-b4-8','math','初中',12,'kp-math-trigacute','single_choice',0.38,'sin30° = ？','[{"key":"A","text":"1/2"},{"key":"B","text":"1"},{"key":"C","text":"1/2"},{"key":"D","text":"√3"}]','A','sin30°=1/2（特殊角三角函数值）','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-trigacute-b4-9','math','初中',12,'kp-math-trigacute','single_choice',0.46,'sin45° = ？','[{"key":"A","text":"√2/2"},{"key":"B","text":"1"},{"key":"C","text":"1/2"},{"key":"D","text":"√3"}]','A','sin45°=√2/2（特殊角三角函数值）','template','approved','通用'),
('qt-trigacute-b4-10','math','初中',12,'kp-math-trigacute','single_choice',0.54,'sin45° = ？','[{"key":"A","text":"√2/2"},{"key":"B","text":"1"},{"key":"C","text":"1/2"},{"key":"D","text":"√3"}]','A','sin45°=√2/2（特殊角三角函数值）','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-sets-b4-1','math','高中',13,'kp-math-sets','single_choice',0.30,'已知 A={3,11}，B={3,17}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{3,11}"},{"key":"C","text":"{3,17}"},{"key":"D","text":"{3,11,3,17}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用'),
('qt-sets-b4-2','math','高中',13,'kp-math-sets','single_choice',0.38,'已知 A={2,10}，B={5,18}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{2,10}"},{"key":"C","text":"{5,18}"},{"key":"D","text":"{2,10,5,18}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用'),
('qt-sets-b4-3','math','高中',13,'kp-math-sets','single_choice',0.46,'已知 A={7,15}，B={7,17}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{7,15}"},{"key":"C","text":"{7,17}"},{"key":"D","text":"{7,15,7,17}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用'),
('qt-sets-b4-4','math','高中',13,'kp-math-sets','single_choice',0.54,'已知 A={7,13}，B={4,19}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{7,13}"},{"key":"C","text":"{4,19}"},{"key":"D","text":"{7,13,4,19}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用'),
('qt-sets-b4-5','math','高中',13,'kp-math-sets','single_choice',0.62,'已知 A={4,10}，B={4,17}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{4,10}"},{"key":"C","text":"{4,17}"},{"key":"D","text":"{4,10,4,17}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用'),
('qt-sets-b4-6','math','高中',13,'kp-math-sets','single_choice',0.70,'已知 A={3,10}，B={2,18}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{3,10}"},{"key":"C","text":"{2,18}"},{"key":"D","text":"{3,10,2,18}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用'),
('qt-sets-b4-7','math','高中',13,'kp-math-sets','single_choice',0.30,'已知 A={2,10}，B={5,19}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{2,10}"},{"key":"C","text":"{5,19}"},{"key":"D","text":"{2,10,5,19}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用'),
('qt-sets-b4-8','math','高中',13,'kp-math-sets','single_choice',0.38,'已知 A={1,9}，B={7,20}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{1,9}"},{"key":"C","text":"{7,20}"},{"key":"D","text":"{1,9,7,20}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-sets-b4-9','math','高中',13,'kp-math-sets','single_choice',0.46,'已知 A={8,13}，B={4,17}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{8,13}"},{"key":"C","text":"{4,17}"},{"key":"D","text":"{8,13,4,17}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用'),
('qt-sets-b4-10','math','高中',13,'kp-math-sets','single_choice',0.54,'已知 A={5,14}，B={8,19}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{5,14}"},{"key":"C","text":"{8,19}"},{"key":"D","text":"{5,14,8,19}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用'),
('qt-sets-b4-11','math','高中',13,'kp-math-sets','single_choice',0.62,'已知 A={6,14}，B={8,19}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{6,14}"},{"key":"C","text":"{8,19}"},{"key":"D","text":"{6,14,8,19}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用'),
('qt-sets-b4-12','math','高中',13,'kp-math-sets','single_choice',0.70,'已知 A={4,12}，B={3,17}，则 A∩B = ？','[{"key":"A","text":"∅"},{"key":"B","text":"{4,12}"},{"key":"C","text":"{3,17}"},{"key":"D","text":"{4,12,3,17}"}]','A','两集合无公共元素，交集为空集 ∅','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-func-basic-b4-1','math','高中',13,'kp-math-func-basic','single_choice',0.30,'函数 f(x)=1/(x-1) 的定义域是？','[{"key":"A","text":"x≠1"},{"key":"B","text":"x>1"},{"key":"C","text":"x≥1"},{"key":"D","text":"x≠7"}]','A','分母不为 0：x-1≠0，即 x≠1','template','approved','通用'),
('qt-func-basic-b4-2','math','高中',13,'kp-math-func-basic','single_choice',0.38,'函数 f(x)=1/(x-6) 的定义域是？','[{"key":"A","text":"x≠6"},{"key":"B","text":"x>6"},{"key":"C","text":"x≥6"},{"key":"D","text":"x≠8"}]','A','分母不为 0：x-6≠0，即 x≠6','template','approved','通用'),
('qt-func-basic-b4-3','math','高中',13,'kp-math-func-basic','single_choice',0.46,'函数 f(x)=1/(x-3) 的定义域是？','[{"key":"A","text":"x≠3"},{"key":"B","text":"x>3"},{"key":"C","text":"x≥3"},{"key":"D","text":"x≠7"}]','A','分母不为 0：x-3≠0，即 x≠3','template','approved','通用'),
('qt-func-basic-b4-4','math','高中',13,'kp-math-func-basic','single_choice',0.54,'函数 f(x)=1/(x-9) 的定义域是？','[{"key":"A","text":"x≠9"},{"key":"B","text":"x>9"},{"key":"C","text":"x≥9"},{"key":"D","text":"x≠3"}]','A','分母不为 0：x-9≠0，即 x≠9','template','approved','通用'),
('qt-func-basic-b4-5','math','高中',13,'kp-math-func-basic','single_choice',0.62,'函数 f(x)=1/(x-3) 的定义域是？','[{"key":"A","text":"x≠3"},{"key":"B","text":"x>3"},{"key":"C","text":"x≥3"},{"key":"D","text":"x≠9"}]','A','分母不为 0：x-3≠0，即 x≠3','template','approved','通用'),
('qt-func-basic-b4-6','math','高中',13,'kp-math-func-basic','single_choice',0.70,'函数 f(x)=1/(x-7) 的定义域是？','[{"key":"A","text":"x≠7"},{"key":"B","text":"x>7"},{"key":"C","text":"x≥7"},{"key":"D","text":"x≠3"}]','A','分母不为 0：x-7≠0，即 x≠7','template','approved','通用'),
('qt-func-basic-b4-7','math','高中',13,'kp-math-func-basic','single_choice',0.30,'函数 f(x)=1/(x-3) 的定义域是？','[{"key":"A","text":"x≠3"},{"key":"B","text":"x>3"},{"key":"C","text":"x≥3"},{"key":"D","text":"x≠7"}]','A','分母不为 0：x-3≠0，即 x≠3','template','approved','通用'),
('qt-func-basic-b4-8','math','高中',13,'kp-math-func-basic','single_choice',0.38,'函数 f(x)=1/(x-6) 的定义域是？','[{"key":"A","text":"x≠6"},{"key":"B","text":"x>6"},{"key":"C","text":"x≥6"},{"key":"D","text":"x≠5"}]','A','分母不为 0：x-6≠0，即 x≠6','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-func-basic-b4-9','math','高中',13,'kp-math-func-basic','single_choice',0.46,'函数 f(x)=1/(x-5) 的定义域是？','[{"key":"A","text":"x≠5"},{"key":"B","text":"x>5"},{"key":"C","text":"x≥5"},{"key":"D","text":"x≠6"}]','A','分母不为 0：x-5≠0，即 x≠5','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-explog-b4-1','math','高中',13,'kp-math-explog','single_choice',0.30,'log₂16 = ？','[{"key":"A","text":"4"},{"key":"B","text":"5"},{"key":"C","text":"3"},{"key":"D","text":"16"}]','A','2^4=16，故 log₂16=4','template','approved','通用'),
('qt-explog-b4-2','math','高中',13,'kp-math-explog','single_choice',0.38,'log₂8 = ？','[{"key":"A","text":"3"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"8"}]','A','2^3=8，故 log₂8=3','template','approved','通用'),
('qt-explog-b4-3','math','高中',13,'kp-math-explog','single_choice',0.46,'log₂2 = ？','[{"key":"A","text":"1"},{"key":"B","text":"2"},{"key":"C","text":"0"},{"key":"D","text":"2"}]','A','2^1=2，故 log₂2=1','template','approved','通用'),
('qt-explog-b4-4','math','高中',13,'kp-math-explog','single_choice',0.54,'log₂16 = ？','[{"key":"A","text":"4"},{"key":"B","text":"5"},{"key":"C","text":"3"},{"key":"D","text":"16"}]','A','2^4=16，故 log₂16=4','template','approved','通用'),
('qt-explog-b4-5','math','高中',13,'kp-math-explog','single_choice',0.62,'log₂8 = ？','[{"key":"A","text":"3"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"8"}]','A','2^3=8，故 log₂8=3','template','approved','通用'),
('qt-explog-b4-6','math','高中',13,'kp-math-explog','single_choice',0.70,'log₂16 = ？','[{"key":"A","text":"4"},{"key":"B","text":"5"},{"key":"C","text":"3"},{"key":"D","text":"16"}]','A','2^4=16，故 log₂16=4','template','approved','通用'),
('qt-explog-b4-7','math','高中',13,'kp-math-explog','single_choice',0.30,'log₂4 = ？','[{"key":"A","text":"2"},{"key":"B","text":"3"},{"key":"C","text":"1"},{"key":"D","text":"4"}]','A','2^2=4，故 log₂4=2','template','approved','通用'),
('qt-explog-b4-8','math','高中',13,'kp-math-explog','single_choice',0.38,'log₂4 = ？','[{"key":"A","text":"2"},{"key":"B","text":"3"},{"key":"C","text":"1"},{"key":"D","text":"4"}]','A','2^2=4，故 log₂4=2','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-explog-b4-9','math','高中',13,'kp-math-explog','single_choice',0.46,'log₂4 = ？','[{"key":"A","text":"2"},{"key":"B","text":"3"},{"key":"C","text":"1"},{"key":"D","text":"4"}]','A','2^2=4，故 log₂4=2','template','approved','通用'),
('qt-explog-b4-10','math','高中',13,'kp-math-explog','single_choice',0.54,'log₂8 = ？','[{"key":"A","text":"3"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"8"}]','A','2^3=8，故 log₂8=3','template','approved','通用'),
('qt-explog-b4-11','math','高中',13,'kp-math-explog','single_choice',0.62,'log₂4 = ？','[{"key":"A","text":"2"},{"key":"B","text":"3"},{"key":"C","text":"1"},{"key":"D","text":"4"}]','A','2^2=4，故 log₂4=2','template','approved','通用'),
('qt-explog-b4-12','math','高中',13,'kp-math-explog','single_choice',0.70,'log₂8 = ？','[{"key":"A","text":"3"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"8"}]','A','2^3=8，故 log₂8=3','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-vector2d-b4-1','math','高中',14,'kp-math-vector2d','single_choice',0.30,'a=(3,1)，b=(3,2)，则 a+b = ？','[{"key":"A","text":"(6,3)"},{"key":"B","text":"(0,-1)"},{"key":"C","text":"(3,2)"},{"key":"D","text":"(3,1)"}]','A','向量加法坐标相加：(3+3, 1+2)=(6,3)','template','approved','通用'),
('qt-vector2d-b4-2','math','高中',14,'kp-math-vector2d','single_choice',0.38,'a=(2,3)，b=(5,5)，则 a+b = ？','[{"key":"A","text":"(7,8)"},{"key":"B","text":"(-3,-2)"},{"key":"C","text":"(2,5)"},{"key":"D","text":"(5,3)"}]','A','向量加法坐标相加：(2+5, 3+5)=(7,8)','template','approved','通用'),
('qt-vector2d-b4-3','math','高中',14,'kp-math-vector2d','single_choice',0.46,'a=(3,2)，b=(1,5)，则 a+b = ？','[{"key":"A","text":"(4,7)"},{"key":"B","text":"(2,-3)"},{"key":"C","text":"(3,5)"},{"key":"D","text":"(1,2)"}]','A','向量加法坐标相加：(3+1, 2+5)=(4,7)','template','approved','通用'),
('qt-vector2d-b4-4','math','高中',14,'kp-math-vector2d','single_choice',0.54,'a=(5,5)，b=(2,4)，则 a+b = ？','[{"key":"A","text":"(7,9)"},{"key":"B","text":"(3,1)"},{"key":"C","text":"(5,4)"},{"key":"D","text":"(2,5)"}]','A','向量加法坐标相加：(5+2, 5+4)=(7,9)','template','approved','通用'),
('qt-vector2d-b4-5','math','高中',14,'kp-math-vector2d','single_choice',0.62,'a=(4,3)，b=(4,5)，则 a+b = ？','[{"key":"A","text":"(8,8)"},{"key":"B","text":"(0,-2)"},{"key":"C","text":"(4,5)"},{"key":"D","text":"(4,3)"}]','A','向量加法坐标相加：(4+4, 3+5)=(8,8)','template','approved','通用'),
('qt-vector2d-b4-6','math','高中',14,'kp-math-vector2d','single_choice',0.70,'a=(1,3)，b=(1,2)，则 a+b = ？','[{"key":"A","text":"(2,5)"},{"key":"B","text":"(0,1)"},{"key":"C","text":"(1,2)"},{"key":"D","text":"(1,3)"}]','A','向量加法坐标相加：(1+1, 3+2)=(2,5)','template','approved','通用'),
('qt-vector2d-b4-7','math','高中',14,'kp-math-vector2d','single_choice',0.30,'a=(5,5)，b=(2,5)，则 a+b = ？','[{"key":"A","text":"(7,10)"},{"key":"B","text":"(3,0)"},{"key":"C","text":"(5,5)"},{"key":"D","text":"(2,5)"}]','A','向量加法坐标相加：(5+2, 5+5)=(7,10)','template','approved','通用'),
('qt-vector2d-b4-8','math','高中',14,'kp-math-vector2d','single_choice',0.38,'a=(4,3)，b=(4,4)，则 a+b = ？','[{"key":"A","text":"(8,7)"},{"key":"B","text":"(0,-1)"},{"key":"C","text":"(4,4)"},{"key":"D","text":"(4,3)"}]','A','向量加法坐标相加：(4+4, 3+4)=(8,7)','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-vector2d-b4-9','math','高中',14,'kp-math-vector2d','single_choice',0.46,'a=(5,2)，b=(1,5)，则 a+b = ？','[{"key":"A","text":"(6,7)"},{"key":"B","text":"(4,-3)"},{"key":"C","text":"(5,5)"},{"key":"D","text":"(1,2)"}]','A','向量加法坐标相加：(5+1, 2+5)=(6,7)','template','approved','通用'),
('qt-vector2d-b4-10','math','高中',14,'kp-math-vector2d','single_choice',0.54,'a=(5,5)，b=(5,5)，则 a+b = ？','[{"key":"A","text":"(10,10)"},{"key":"B","text":"(0,0)"},{"key":"C","text":"(5,5)"},{"key":"D","text":"(5,5)"}]','A','向量加法坐标相加：(5+5, 5+5)=(10,10)','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-complex-b4-1','math','高中',14,'kp-math-complex','single_choice',0.30,'复数 z=5+6i，则 z 的虚部是？','[{"key":"A","text":"6"},{"key":"B","text":"5"},{"key":"C","text":"6i"},{"key":"D","text":"-6"}]','A','z=a+bi 的虚部为 b=6（不含虚数单位 i）','template','approved','通用'),
('qt-complex-b4-2','math','高中',14,'kp-math-complex','single_choice',0.38,'复数 z=6+6i，则 z 的虚部是？','[{"key":"A","text":"6"},{"key":"B","text":"6"},{"key":"C","text":"6i"},{"key":"D","text":"-6"}]','A','z=a+bi 的虚部为 b=6（不含虚数单位 i）','template','approved','通用'),
('qt-complex-b4-3','math','高中',14,'kp-math-complex','single_choice',0.46,'复数 z=3+7i，则 z 的虚部是？','[{"key":"A","text":"7"},{"key":"B","text":"3"},{"key":"C","text":"7i"},{"key":"D","text":"-7"}]','A','z=a+bi 的虚部为 b=7（不含虚数单位 i）','template','approved','通用'),
('qt-complex-b4-4','math','高中',14,'kp-math-complex','single_choice',0.54,'复数 z=6+8i，则 z 的虚部是？','[{"key":"A","text":"8"},{"key":"B","text":"6"},{"key":"C","text":"8i"},{"key":"D","text":"-8"}]','A','z=a+bi 的虚部为 b=8（不含虚数单位 i）','template','approved','通用'),
('qt-complex-b4-5','math','高中',14,'kp-math-complex','single_choice',0.62,'复数 z=3+2i，则 z 的虚部是？','[{"key":"A","text":"2"},{"key":"B","text":"3"},{"key":"C","text":"2i"},{"key":"D","text":"-2"}]','A','z=a+bi 的虚部为 b=2（不含虚数单位 i）','template','approved','通用'),
('qt-complex-b4-6','math','高中',14,'kp-math-complex','single_choice',0.70,'复数 z=6+5i，则 z 的虚部是？','[{"key":"A","text":"5"},{"key":"B","text":"6"},{"key":"C","text":"5i"},{"key":"D","text":"-5"}]','A','z=a+bi 的虚部为 b=5（不含虚数单位 i）','template','approved','通用'),
('qt-complex-b4-7','math','高中',14,'kp-math-complex','single_choice',0.30,'复数 z=4+6i，则 z 的虚部是？','[{"key":"A","text":"6"},{"key":"B","text":"4"},{"key":"C","text":"6i"},{"key":"D","text":"-6"}]','A','z=a+bi 的虚部为 b=6（不含虚数单位 i）','template','approved','通用'),
('qt-complex-b4-8','math','高中',14,'kp-math-complex','single_choice',0.38,'复数 z=7+6i，则 z 的虚部是？','[{"key":"A","text":"6"},{"key":"B","text":"7"},{"key":"C","text":"6i"},{"key":"D","text":"-6"}]','A','z=a+bi 的虚部为 b=6（不含虚数单位 i）','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-complex-b4-9','math','高中',14,'kp-math-complex','single_choice',0.46,'复数 z=3+8i，则 z 的虚部是？','[{"key":"A","text":"8"},{"key":"B","text":"3"},{"key":"C","text":"8i"},{"key":"D","text":"-8"}]','A','z=a+bi 的虚部为 b=8（不含虚数单位 i）','template','approved','通用'),
('qt-complex-b4-10','math','高中',14,'kp-math-complex','single_choice',0.54,'复数 z=8+3i，则 z 的虚部是？','[{"key":"A","text":"3"},{"key":"B","text":"8"},{"key":"C","text":"3i"},{"key":"D","text":"-3"}]','A','z=a+bi 的虚部为 b=3（不含虚数单位 i）','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-trig-b4-1','math','高中',15,'kp-math-trig','single_choice',0.30,'函数 y=sin(3x) 的最小正周期是？','[{"key":"A","text":"2π/3"},{"key":"B","text":"2π"},{"key":"C","text":"3π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/3=2π/3','template','approved','通用'),
('qt-trig-b4-2','math','高中',15,'kp-math-trig','single_choice',0.38,'函数 y=sin(2x) 的最小正周期是？','[{"key":"A","text":"π"},{"key":"B","text":"2π"},{"key":"C","text":"2π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/2=π','template','approved','通用'),
('qt-trig-b4-3','math','高中',15,'kp-math-trig','single_choice',0.46,'函数 y=sin(4x) 的最小正周期是？','[{"key":"A","text":"π/2"},{"key":"B","text":"2π"},{"key":"C","text":"4π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/4=π/2','template','approved','通用'),
('qt-trig-b4-4','math','高中',15,'kp-math-trig','single_choice',0.54,'函数 y=sin(2x) 的最小正周期是？','[{"key":"A","text":"π"},{"key":"B","text":"2π"},{"key":"C","text":"2π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/2=π','template','approved','通用'),
('qt-trig-b4-5','math','高中',15,'kp-math-trig','single_choice',0.62,'函数 y=sin(3x) 的最小正周期是？','[{"key":"A","text":"2π/3"},{"key":"B","text":"2π"},{"key":"C","text":"3π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/3=2π/3','template','approved','通用'),
('qt-trig-b4-6','math','高中',15,'kp-math-trig','single_choice',0.70,'函数 y=sin(4x) 的最小正周期是？','[{"key":"A","text":"π/2"},{"key":"B","text":"2π"},{"key":"C","text":"4π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/4=π/2','template','approved','通用'),
('qt-trig-b4-7','math','高中',15,'kp-math-trig','single_choice',0.30,'函数 y=sin(3x) 的最小正周期是？','[{"key":"A","text":"2π/3"},{"key":"B","text":"2π"},{"key":"C","text":"3π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/3=2π/3','template','approved','通用'),
('qt-trig-b4-8','math','高中',15,'kp-math-trig','single_choice',0.38,'函数 y=sin(2x) 的最小正周期是？','[{"key":"A","text":"π"},{"key":"B","text":"2π"},{"key":"C","text":"2π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/2=π','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-trig-b4-9','math','高中',15,'kp-math-trig','single_choice',0.46,'函数 y=sin(4x) 的最小正周期是？','[{"key":"A","text":"π/2"},{"key":"B","text":"2π"},{"key":"C","text":"4π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/4=π/2','template','approved','通用'),
('qt-trig-b4-10','math','高中',15,'kp-math-trig','single_choice',0.54,'函数 y=sin(4x) 的最小正周期是？','[{"key":"A","text":"π/2"},{"key":"B","text":"2π"},{"key":"C","text":"4π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/4=π/2','template','approved','通用'),
('qt-trig-b4-11','math','高中',15,'kp-math-trig','single_choice',0.62,'函数 y=sin(4x) 的最小正周期是？','[{"key":"A","text":"π/2"},{"key":"B","text":"2π"},{"key":"C","text":"4π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/4=π/2','template','approved','通用'),
('qt-trig-b4-12','math','高中',15,'kp-math-trig','single_choice',0.70,'函数 y=sin(2x) 的最小正周期是？','[{"key":"A","text":"π"},{"key":"B","text":"2π"},{"key":"C","text":"2π"},{"key":"D","text":"π"}]','A','T=2π/ω=2π/2=π','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-seq-b4-1','math','高中',15,'kp-math-seq','single_choice',0.30,'等差数列 a₁=2，公差 d=5，则 a6 = ？','[{"key":"A","text":"27"},{"key":"B","text":"32"},{"key":"C","text":"22"},{"key":"D","text":"8"}]','A','aₙ=a₁+(n-1)d=2+(6-1)×5=27','template','approved','通用'),
('qt-seq-b4-2','math','高中',15,'kp-math-seq','single_choice',0.38,'等差数列 a₁=4，公差 d=6，则 a9 = ？','[{"key":"A","text":"52"},{"key":"B","text":"58"},{"key":"C","text":"46"},{"key":"D","text":"13"}]','A','aₙ=a₁+(n-1)d=4+(9-1)×6=52','template','approved','通用'),
('qt-seq-b4-3','math','高中',15,'kp-math-seq','single_choice',0.46,'等差数列 a₁=1，公差 d=2，则 a5 = ？','[{"key":"A","text":"9"},{"key":"B","text":"11"},{"key":"C","text":"7"},{"key":"D","text":"6"}]','A','aₙ=a₁+(n-1)d=1+(5-1)×2=9','template','approved','通用'),
('qt-seq-b4-4','math','高中',15,'kp-math-seq','single_choice',0.54,'等差数列 a₁=4，公差 d=2，则 a10 = ？','[{"key":"A","text":"22"},{"key":"B","text":"24"},{"key":"C","text":"20"},{"key":"D","text":"14"}]','A','aₙ=a₁+(n-1)d=4+(10-1)×2=22','template','approved','通用'),
('qt-seq-b4-5','math','高中',15,'kp-math-seq','single_choice',0.62,'等差数列 a₁=5，公差 d=4，则 a8 = ？','[{"key":"A","text":"33"},{"key":"B","text":"37"},{"key":"C","text":"29"},{"key":"D","text":"13"}]','A','aₙ=a₁+(n-1)d=5+(8-1)×4=33','template','approved','通用'),
('qt-seq-b4-6','math','高中',15,'kp-math-seq','single_choice',0.70,'等差数列 a₁=3，公差 d=4，则 a7 = ？','[{"key":"A","text":"27"},{"key":"B","text":"31"},{"key":"C","text":"23"},{"key":"D","text":"10"}]','A','aₙ=a₁+(n-1)d=3+(7-1)×4=27','template','approved','通用'),
('qt-seq-b4-7','math','高中',15,'kp-math-seq','single_choice',0.30,'等差数列 a₁=5，公差 d=6，则 a5 = ？','[{"key":"A","text":"29"},{"key":"B","text":"35"},{"key":"C","text":"23"},{"key":"D","text":"10"}]','A','aₙ=a₁+(n-1)d=5+(5-1)×6=29','template','approved','通用'),
('qt-seq-b4-8','math','高中',15,'kp-math-seq','single_choice',0.38,'等差数列 a₁=2，公差 d=5，则 a9 = ？','[{"key":"A","text":"42"},{"key":"B","text":"47"},{"key":"C","text":"37"},{"key":"D","text":"11"}]','A','aₙ=a₁+(n-1)d=2+(9-1)×5=42','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-seq-b4-9','math','高中',15,'kp-math-seq','single_choice',0.46,'等差数列 a₁=1，公差 d=2，则 a8 = ？','[{"key":"A","text":"15"},{"key":"B","text":"17"},{"key":"C","text":"13"},{"key":"D","text":"9"}]','A','aₙ=a₁+(n-1)d=1+(8-1)×2=15','template','approved','通用'),
('qt-seq-b4-10','math','高中',15,'kp-math-seq','single_choice',0.54,'等差数列 a₁=4，公差 d=3，则 a10 = ？','[{"key":"A","text":"31"},{"key":"B","text":"34"},{"key":"C","text":"28"},{"key":"D","text":"14"}]','A','aₙ=a₁+(n-1)d=4+(10-1)×3=31','template','approved','通用'),
('qt-seq-b4-11','math','高中',15,'kp-math-seq','single_choice',0.62,'等差数列 a₁=1，公差 d=2，则 a6 = ？','[{"key":"A","text":"11"},{"key":"B","text":"13"},{"key":"C","text":"9"},{"key":"D","text":"7"}]','A','aₙ=a₁+(n-1)d=1+(6-1)×2=11','template','approved','通用'),
('qt-seq-b4-12','math','高中',15,'kp-math-seq','single_choice',0.70,'等差数列 a₁=3，公差 d=4，则 a10 = ？','[{"key":"A","text":"39"},{"key":"B","text":"43"},{"key":"C","text":"35"},{"key":"D","text":"13"}]','A','aₙ=a₁+(n-1)d=3+(10-1)×4=39','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-count-b4-1','math','高中',16,'kp-math-count','single_choice',0.30,'从 5 名同学中选出 2 名，共有多少种选法？','[{"key":"A","text":"10"},{"key":"B","text":"5"},{"key":"C","text":"20"},{"key":"D","text":"7"}]','A','C(5,2)=5×4/2=10','template','approved','通用'),
('qt-count-b4-2','math','高中',16,'kp-math-count','single_choice',0.38,'从 6 名同学中选出 2 名，共有多少种选法？','[{"key":"A","text":"15"},{"key":"B","text":"6"},{"key":"C","text":"30"},{"key":"D","text":"8"}]','A','C(6,2)=6×5/2=15','template','approved','通用'),
('qt-count-b4-3','math','高中',16,'kp-math-count','single_choice',0.46,'从 6 名同学中选出 2 名，共有多少种选法？','[{"key":"A","text":"15"},{"key":"B","text":"6"},{"key":"C","text":"30"},{"key":"D","text":"8"}]','A','C(6,2)=6×5/2=15','template','approved','通用'),
('qt-count-b4-4','math','高中',16,'kp-math-count','single_choice',0.54,'从 5 名同学中选出 2 名，共有多少种选法？','[{"key":"A","text":"10"},{"key":"B","text":"5"},{"key":"C","text":"20"},{"key":"D","text":"7"}]','A','C(5,2)=5×4/2=10','template','approved','通用'),
('qt-count-b4-5','math','高中',16,'kp-math-count','single_choice',0.62,'从 4 名同学中选出 2 名，共有多少种选法？','[{"key":"A","text":"6"},{"key":"B","text":"4"},{"key":"C","text":"12"},{"key":"D","text":"6"}]','A','C(4,2)=4×3/2=6','template','approved','通用'),
('qt-count-b4-6','math','高中',16,'kp-math-count','single_choice',0.70,'从 5 名同学中选出 2 名，共有多少种选法？','[{"key":"A","text":"10"},{"key":"B","text":"5"},{"key":"C","text":"20"},{"key":"D","text":"7"}]','A','C(5,2)=5×4/2=10','template','approved','通用'),
('qt-count-b4-7','math','高中',16,'kp-math-count','single_choice',0.30,'从 6 名同学中选出 2 名，共有多少种选法？','[{"key":"A","text":"15"},{"key":"B","text":"6"},{"key":"C","text":"30"},{"key":"D","text":"8"}]','A','C(6,2)=6×5/2=15','template','approved','通用'),
('qt-count-b4-8','math','高中',16,'kp-math-count','single_choice',0.38,'从 6 名同学中选出 2 名，共有多少种选法？','[{"key":"A","text":"15"},{"key":"B","text":"6"},{"key":"C","text":"30"},{"key":"D","text":"8"}]','A','C(6,2)=6×5/2=15','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-count-b4-9','math','高中',16,'kp-math-count','single_choice',0.46,'从 4 名同学中选出 2 名，共有多少种选法？','[{"key":"A","text":"6"},{"key":"B","text":"4"},{"key":"C","text":"12"},{"key":"D","text":"6"}]','A','C(4,2)=4×3/2=6','template','approved','通用'),
('qt-count-b4-10','math','高中',16,'kp-math-count','single_choice',0.54,'从 4 名同学中选出 2 名，共有多少种选法？','[{"key":"A","text":"6"},{"key":"B","text":"4"},{"key":"C","text":"12"},{"key":"D","text":"6"}]','A','C(4,2)=4×3/2=6','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-randomvar-b4-1','math','高中',16,'kp-math-randomvar','single_choice',0.30,'随机变量 X 分布：P(X=0)=0.5，P(X=1)=0.5，则 E(X) = ？','[{"key":"A","text":"0.5"},{"key":"B","text":"0.5"},{"key":"C","text":"1"},{"key":"D","text":"1"}]','A','E(X)=0×0.5+1×0.5=0.5','template','approved','通用'),
('qt-randomvar-b4-2','math','高中',16,'kp-math-randomvar','single_choice',0.38,'随机变量 X 分布：P(X=0)=0.2，P(X=1)=0.8，则 E(X) = ？','[{"key":"A","text":"0.8"},{"key":"B","text":"0.2"},{"key":"C","text":"1"},{"key":"D","text":"1.6"}]','A','E(X)=0×0.2+1×0.8=0.8','template','approved','通用'),
('qt-randomvar-b4-3','math','高中',16,'kp-math-randomvar','single_choice',0.46,'随机变量 X 分布：P(X=0)=0.4，P(X=1)=0.6，则 E(X) = ？','[{"key":"A","text":"0.6"},{"key":"B","text":"0.4"},{"key":"C","text":"1"},{"key":"D","text":"1.2"}]','A','E(X)=0×0.4+1×0.6=0.6','template','approved','通用'),
('qt-randomvar-b4-4','math','高中',16,'kp-math-randomvar','single_choice',0.54,'随机变量 X 分布：P(X=0)=0.4，P(X=1)=0.6，则 E(X) = ？','[{"key":"A","text":"0.6"},{"key":"B","text":"0.4"},{"key":"C","text":"1"},{"key":"D","text":"1.2"}]','A','E(X)=0×0.4+1×0.6=0.6','template','approved','通用'),
('qt-randomvar-b4-5','math','高中',16,'kp-math-randomvar','single_choice',0.62,'随机变量 X 分布：P(X=0)=0.5，P(X=1)=0.5，则 E(X) = ？','[{"key":"A","text":"0.5"},{"key":"B","text":"0.5"},{"key":"C","text":"1"},{"key":"D","text":"1"}]','A','E(X)=0×0.5+1×0.5=0.5','template','approved','通用'),
('qt-randomvar-b4-6','math','高中',16,'kp-math-randomvar','single_choice',0.70,'随机变量 X 分布：P(X=0)=0.5，P(X=1)=0.5，则 E(X) = ？','[{"key":"A","text":"0.5"},{"key":"B","text":"0.5"},{"key":"C","text":"1"},{"key":"D","text":"1"}]','A','E(X)=0×0.5+1×0.5=0.5','template','approved','通用'),
('qt-randomvar-b4-7','math','高中',16,'kp-math-randomvar','single_choice',0.30,'随机变量 X 分布：P(X=0)=0.5，P(X=1)=0.5，则 E(X) = ？','[{"key":"A","text":"0.5"},{"key":"B","text":"0.5"},{"key":"C","text":"1"},{"key":"D","text":"1"}]','A','E(X)=0×0.5+1×0.5=0.5','template','approved','通用'),
('qt-randomvar-b4-8','math','高中',16,'kp-math-randomvar','single_choice',0.38,'随机变量 X 分布：P(X=0)=0.2，P(X=1)=0.8，则 E(X) = ？','[{"key":"A","text":"0.8"},{"key":"B","text":"0.2"},{"key":"C","text":"1"},{"key":"D","text":"1.6"}]','A','E(X)=0×0.2+1×0.8=0.8','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-randomvar-b4-9','math','高中',16,'kp-math-randomvar','single_choice',0.46,'随机变量 X 分布：P(X=0)=0.2，P(X=1)=0.8，则 E(X) = ？','[{"key":"A","text":"0.8"},{"key":"B","text":"0.2"},{"key":"C","text":"1"},{"key":"D","text":"1.6"}]','A','E(X)=0×0.2+1×0.8=0.8','template','approved','通用'),
('qt-randomvar-b4-10','math','高中',16,'kp-math-randomvar','single_choice',0.54,'随机变量 X 分布：P(X=0)=0.3，P(X=1)=0.7，则 E(X) = ？','[{"key":"A","text":"0.7"},{"key":"B","text":"0.3"},{"key":"C","text":"1"},{"key":"D","text":"1.4"}]','A','E(X)=0×0.3+1×0.7=0.7','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-derivative-b4-1','math','高中',17,'kp-math-derivative','single_choice',0.30,'f(x)=x^5，则 f′(x) = ？','[{"key":"A","text":"5x²"},{"key":"B","text":"x^4"},{"key":"C","text":"5x^5"},{"key":"D","text":"4x^4"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=5x²','template','approved','通用'),
('qt-derivative-b4-2','math','高中',17,'kp-math-derivative','single_choice',0.38,'f(x)=x^3，则 f′(x) = ？','[{"key":"A","text":"3x²"},{"key":"B","text":"x^2"},{"key":"C","text":"3x^3"},{"key":"D","text":"2x^2"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=3x²','template','approved','通用'),
('qt-derivative-b4-3','math','高中',17,'kp-math-derivative','single_choice',0.46,'f(x)=x^5，则 f′(x) = ？','[{"key":"A","text":"5x²"},{"key":"B","text":"x^4"},{"key":"C","text":"5x^5"},{"key":"D","text":"4x^4"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=5x²','template','approved','通用'),
('qt-derivative-b4-4','math','高中',17,'kp-math-derivative','single_choice',0.54,'f(x)=x^4，则 f′(x) = ？','[{"key":"A","text":"4x²"},{"key":"B","text":"x^3"},{"key":"C","text":"4x^4"},{"key":"D","text":"3x^3"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=4x²','template','approved','通用'),
('qt-derivative-b4-5','math','高中',17,'kp-math-derivative','single_choice',0.62,'f(x)=x^5，则 f′(x) = ？','[{"key":"A","text":"5x²"},{"key":"B","text":"x^4"},{"key":"C","text":"5x^5"},{"key":"D","text":"4x^4"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=5x²','template','approved','通用'),
('qt-derivative-b4-6','math','高中',17,'kp-math-derivative','single_choice',0.70,'f(x)=x^4，则 f′(x) = ？','[{"key":"A","text":"4x²"},{"key":"B","text":"x^3"},{"key":"C","text":"4x^4"},{"key":"D","text":"3x^3"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=4x²','template','approved','通用'),
('qt-derivative-b4-7','math','高中',17,'kp-math-derivative','single_choice',0.30,'f(x)=x^5，则 f′(x) = ？','[{"key":"A","text":"5x²"},{"key":"B","text":"x^4"},{"key":"C","text":"5x^5"},{"key":"D","text":"4x^4"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=5x²','template','approved','通用'),
('qt-derivative-b4-8','math','高中',17,'kp-math-derivative','single_choice',0.38,'f(x)=x^2，则 f′(x) = ？','[{"key":"A","text":"2x"},{"key":"B","text":"x^1"},{"key":"C","text":"2x^2"},{"key":"D","text":"1x^1"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=2x','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-derivative-b4-9','math','高中',17,'kp-math-derivative','single_choice',0.46,'f(x)=x^4，则 f′(x) = ？','[{"key":"A","text":"4x²"},{"key":"B","text":"x^3"},{"key":"C","text":"4x^4"},{"key":"D","text":"3x^3"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=4x²','template','approved','通用'),
('qt-derivative-b4-10','math','高中',17,'kp-math-derivative','single_choice',0.54,'f(x)=x^3，则 f′(x) = ？','[{"key":"A","text":"3x²"},{"key":"B","text":"x^2"},{"key":"C","text":"3x^3"},{"key":"D","text":"2x^2"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=3x²','template','approved','通用'),
('qt-derivative-b4-11','math','高中',17,'kp-math-derivative','single_choice',0.62,'f(x)=x^3，则 f′(x) = ？','[{"key":"A","text":"3x²"},{"key":"B","text":"x^2"},{"key":"C","text":"3x^3"},{"key":"D","text":"2x^2"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=3x²','template','approved','通用'),
('qt-derivative-b4-12','math','高中',17,'kp-math-derivative','single_choice',0.70,'f(x)=x^5，则 f′(x) = ？','[{"key":"A","text":"5x²"},{"key":"B","text":"x^4"},{"key":"C","text":"5x^5"},{"key":"D","text":"4x^4"}]','A','幂函数求导 (xⁿ)′=nxⁿ⁻¹=5x²','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-vector-b4-1','math','高中',17,'kp-math-vector','single_choice',0.30,'向量 a=(1,3,0)，b=(1,2,0)，则 a·b = ？','[{"key":"A","text":"7"},{"key":"B","text":"8"},{"key":"C","text":"1"},{"key":"D","text":"6"}]','A','点积=1×1+3×2=7','template','approved','通用'),
('qt-vector-b4-2','math','高中',17,'kp-math-vector','single_choice',0.38,'向量 a=(3,2,0)，b=(3,1,0)，则 a·b = ？','[{"key":"A","text":"11"},{"key":"B","text":"12"},{"key":"C","text":"9"},{"key":"D","text":"2"}]','A','点积=3×3+2×1=11','template','approved','通用'),
('qt-vector-b4-3','math','高中',17,'kp-math-vector','single_choice',0.46,'向量 a=(3,2,0)，b=(1,1,0)，则 a·b = ？','[{"key":"A","text":"5"},{"key":"B","text":"6"},{"key":"C","text":"3"},{"key":"D","text":"2"}]','A','点积=3×1+2×1=5','template','approved','通用'),
('qt-vector-b4-4','math','高中',17,'kp-math-vector','single_choice',0.54,'向量 a=(3,2,0)，b=(2,3,0)，则 a·b = ？','[{"key":"A","text":"12"},{"key":"B","text":"13"},{"key":"C","text":"6"},{"key":"D","text":"6"}]','A','点积=3×2+2×3=12','template','approved','通用'),
('qt-vector-b4-5','math','高中',17,'kp-math-vector','single_choice',0.62,'向量 a=(1,2,0)，b=(1,1,0)，则 a·b = ？','[{"key":"A","text":"3"},{"key":"B","text":"4"},{"key":"C","text":"1"},{"key":"D","text":"2"}]','A','点积=1×1+2×1=3','template','approved','通用'),
('qt-vector-b4-6','math','高中',17,'kp-math-vector','single_choice',0.70,'向量 a=(2,2,0)，b=(1,3,0)，则 a·b = ？','[{"key":"A","text":"8"},{"key":"B","text":"9"},{"key":"C","text":"2"},{"key":"D","text":"6"}]','A','点积=2×1+2×3=8','template','approved','通用'),
('qt-vector-b4-7','math','高中',17,'kp-math-vector','single_choice',0.30,'向量 a=(2,3,0)，b=(3,2,0)，则 a·b = ？','[{"key":"A","text":"12"},{"key":"B","text":"13"},{"key":"C","text":"6"},{"key":"D","text":"6"}]','A','点积=2×3+3×2=12','template','approved','通用'),
('qt-vector-b4-8','math','高中',17,'kp-math-vector','single_choice',0.38,'向量 a=(1,2,0)，b=(1,4,0)，则 a·b = ？','[{"key":"A","text":"9"},{"key":"B","text":"10"},{"key":"C","text":"1"},{"key":"D","text":"8"}]','A','点积=1×1+2×4=9','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-vector-b4-9','math','高中',17,'kp-math-vector','single_choice',0.46,'向量 a=(1,2,0)，b=(2,4,0)，则 a·b = ？','[{"key":"A","text":"10"},{"key":"B","text":"11"},{"key":"C","text":"2"},{"key":"D","text":"8"}]','A','点积=1×2+2×4=10','template','approved','通用'),
('qt-vector-b4-10','math','高中',17,'kp-math-vector','single_choice',0.54,'向量 a=(3,2,0)，b=(1,4,0)，则 a·b = ？','[{"key":"A","text":"11"},{"key":"B","text":"12"},{"key":"C","text":"3"},{"key":"D","text":"8"}]','A','点积=3×1+2×4=11','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-conic-b4-1','math','高中',17,'kp-math-conic','single_choice',0.30,'椭圆 x²/16 + y²/4 = 1 的长轴长是？','[{"key":"A","text":"8"},{"key":"B","text":"4"},{"key":"C","text":"4"},{"key":"D","text":"8"}]','A','a²=16，a=4，长轴长 2a=8','template','approved','通用'),
('qt-conic-b4-2','math','高中',17,'kp-math-conic','single_choice',0.38,'椭圆 x²/9 + y²/4 = 1 的长轴长是？','[{"key":"A","text":"6"},{"key":"B","text":"3"},{"key":"C","text":"4"},{"key":"D","text":"6"}]','A','a²=9，a=3，长轴长 2a=6','template','approved','通用'),
('qt-conic-b4-4','math','高中',17,'kp-math-conic','single_choice',0.46,'椭圆 x²/25 + y²/1 = 1 的长轴长是？','[{"key":"A","text":"10"},{"key":"B","text":"5"},{"key":"C","text":"2"},{"key":"D","text":"5"}]','A','a²=25，a=5，长轴长 2a=10','template','approved','通用'),
('qt-conic-b4-6','math','高中',17,'kp-math-conic','single_choice',0.54,'椭圆 x²/16 + y²/1 = 1 的长轴长是？','[{"key":"A","text":"8"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"4"}]','A','a²=16，a=4，长轴长 2a=8','template','approved','通用'),
('qt-conic-b4-7','math','高中',17,'kp-math-conic','single_choice',0.62,'椭圆 x²/9 + y²/4 = 1 的长轴长是？','[{"key":"A","text":"6"},{"key":"B","text":"3"},{"key":"C","text":"4"},{"key":"D","text":"6"}]','A','a²=9，a=3，长轴长 2a=6','template','approved','通用'),
('qt-conic-b4-9','math','高中',17,'kp-math-conic','single_choice',0.70,'椭圆 x²/16 + y²/1 = 1 的长轴长是？','[{"key":"A","text":"8"},{"key":"B","text":"4"},{"key":"C","text":"2"},{"key":"D","text":"4"}]','A','a²=16，a=4，长轴长 2a=8','template','approved','通用'),
('qt-conic-b4-10','math','高中',17,'kp-math-conic','single_choice',0.30,'椭圆 x²/25 + y²/9 = 1 的长轴长是？','[{"key":"A","text":"10"},{"key":"B","text":"5"},{"key":"C","text":"6"},{"key":"D","text":"15"}]','A','a²=25，a=5，长轴长 2a=10','template','approved','通用'),
('qt-conic-b4-11','math','高中',17,'kp-math-conic','single_choice',0.38,'椭圆 x²/25 + y²/16 = 1 的长轴长是？','[{"key":"A","text":"10"},{"key":"B","text":"5"},{"key":"C","text":"8"},{"key":"D","text":"20"}]','A','a²=25，a=5，长轴长 2a=10','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-conic-b4-12','math','高中',17,'kp-math-conic','single_choice',0.46,'椭圆 x²/16 + y²/9 = 1 的长轴长是？','[{"key":"A","text":"8"},{"key":"B","text":"4"},{"key":"C","text":"6"},{"key":"D","text":"12"}]','A','a²=16，a=4，长轴长 2a=8','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-probstat-b4-1','math','高中',17,'kp-math-probstat','single_choice',0.30,'从 1~7 中随机取一个数，取到偶数的概率是？','[{"key":"A","text":"3/7"},{"key":"B","text":"1/2"},{"key":"C","text":"4/7"},{"key":"D","text":"1/7"}]','A','1~7 中偶数 3 个，P=3/7','template','approved','通用'),
('qt-probstat-b4-2','math','高中',17,'kp-math-probstat','single_choice',0.38,'从 1~8 中随机取一个数，取到偶数的概率是？','[{"key":"A","text":"4/8"},{"key":"B","text":"1/2"},{"key":"C","text":"4/8"},{"key":"D","text":"1/8"}]','A','1~8 中偶数 4 个，P=4/8','template','approved','通用'),
('qt-probstat-b4-3','math','高中',17,'kp-math-probstat','single_choice',0.46,'从 1~5 中随机取一个数，取到偶数的概率是？','[{"key":"A","text":"2/5"},{"key":"B","text":"1/2"},{"key":"C","text":"3/5"},{"key":"D","text":"1/5"}]','A','1~5 中偶数 2 个，P=2/5','template','approved','通用'),
('qt-probstat-b4-4','math','高中',17,'kp-math-probstat','single_choice',0.54,'从 1~6 中随机取一个数，取到偶数的概率是？','[{"key":"A","text":"3/6"},{"key":"B","text":"1/2"},{"key":"C","text":"3/6"},{"key":"D","text":"1/6"}]','A','1~6 中偶数 3 个，P=3/6','template','approved','通用'),
('qt-probstat-b4-5','math','高中',17,'kp-math-probstat','single_choice',0.62,'从 1~6 中随机取一个数，取到偶数的概率是？','[{"key":"A","text":"3/6"},{"key":"B","text":"1/2"},{"key":"C","text":"3/6"},{"key":"D","text":"1/6"}]','A','1~6 中偶数 3 个，P=3/6','template','approved','通用'),
('qt-probstat-b4-6','math','高中',17,'kp-math-probstat','single_choice',0.70,'从 1~8 中随机取一个数，取到偶数的概率是？','[{"key":"A","text":"4/8"},{"key":"B","text":"1/2"},{"key":"C","text":"4/8"},{"key":"D","text":"1/8"}]','A','1~8 中偶数 4 个，P=4/8','template','approved','通用'),
('qt-probstat-b4-7','math','高中',17,'kp-math-probstat','single_choice',0.30,'从 1~6 中随机取一个数，取到偶数的概率是？','[{"key":"A","text":"3/6"},{"key":"B","text":"1/2"},{"key":"C","text":"3/6"},{"key":"D","text":"1/6"}]','A','1~6 中偶数 3 个，P=3/6','template','approved','通用'),
('qt-probstat-b4-8','math','高中',17,'kp-math-probstat','single_choice',0.38,'从 1~8 中随机取一个数，取到偶数的概率是？','[{"key":"A","text":"4/8"},{"key":"B","text":"1/2"},{"key":"C","text":"4/8"},{"key":"D","text":"1/8"}]','A','1~8 中偶数 4 个，P=4/8','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-probstat-b4-9','math','高中',17,'kp-math-probstat','single_choice',0.46,'从 1~8 中随机取一个数，取到偶数的概率是？','[{"key":"A","text":"4/8"},{"key":"B","text":"1/2"},{"key":"C","text":"4/8"},{"key":"D","text":"1/8"}]','A','1~8 中偶数 4 个，P=4/8','template','approved','通用'),
('qt-probstat-b4-10','math','高中',17,'kp-math-probstat','single_choice',0.54,'从 1~8 中随机取一个数，取到偶数的概率是？','[{"key":"A","text":"4/8"},{"key":"B","text":"1/2"},{"key":"C","text":"4/8"},{"key":"D","text":"1/8"}]','A','1~8 中偶数 4 个，P=4/8','template','approved','通用');

INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-review-b4-1','math','高中',18,'kp-math-review','single_choice',0.30,'等比数列首项 2，公比 2，第 6 项是？','[{"key":"A","text":"64"},{"key":"B","text":"128"},{"key":"C","text":"12"},{"key":"D","text":"32"}]','A','aₙ=a₁qⁿ⁻¹=2×2^5=64','template','approved','通用'),
('qt-review-b4-2','math','高中',18,'kp-math-review','single_choice',0.38,'等比数列首项 3，公比 2，第 6 项是？','[{"key":"A","text":"96"},{"key":"B","text":"192"},{"key":"C","text":"13"},{"key":"D","text":"48"}]','A','aₙ=a₁qⁿ⁻¹=3×2^5=96','template','approved','通用'),
('qt-review-b4-3','math','高中',18,'kp-math-review','single_choice',0.46,'等比数列首项 1，公比 4，第 6 项是？','[{"key":"A","text":"1024"},{"key":"B","text":"4096"},{"key":"C","text":"21"},{"key":"D","text":"256"}]','A','aₙ=a₁qⁿ⁻¹=1×4^5=1024','template','approved','通用'),
('qt-review-b4-4','math','高中',18,'kp-math-review','single_choice',0.54,'等比数列首项 1，公比 2，第 5 项是？','[{"key":"A","text":"16"},{"key":"B","text":"32"},{"key":"C","text":"9"},{"key":"D","text":"8"}]','A','aₙ=a₁qⁿ⁻¹=1×2^4=16','template','approved','通用'),
('qt-review-b4-5','math','高中',18,'kp-math-review','single_choice',0.62,'等比数列首项 1，公比 3，第 6 项是？','[{"key":"A","text":"243"},{"key":"B","text":"729"},{"key":"C","text":"16"},{"key":"D","text":"81"}]','A','aₙ=a₁qⁿ⁻¹=1×3^5=243','template','approved','通用'),
('qt-review-b4-6','math','高中',18,'kp-math-review','single_choice',0.70,'等比数列首项 3，公比 3，第 5 项是？','[{"key":"A","text":"243"},{"key":"B","text":"729"},{"key":"C","text":"15"},{"key":"D","text":"81"}]','A','aₙ=a₁qⁿ⁻¹=3×3^4=243','template','approved','通用'),
('qt-review-b4-7','math','高中',18,'kp-math-review','single_choice',0.30,'等比数列首项 2，公比 2，第 5 项是？','[{"key":"A","text":"32"},{"key":"B","text":"64"},{"key":"C","text":"10"},{"key":"D","text":"16"}]','A','aₙ=a₁qⁿ⁻¹=2×2^4=32','template','approved','通用'),
('qt-review-b4-8','math','高中',18,'kp-math-review','single_choice',0.38,'等比数列首项 3，公比 4，第 5 项是？','[{"key":"A","text":"768"},{"key":"B","text":"3072"},{"key":"C","text":"19"},{"key":"D","text":"192"}]','A','aₙ=a₁qⁿ⁻¹=3×4^4=768','template','approved','通用');
INSERT OR IGNORE INTO questions (id, subject, stage, grade_level, knowledge_point_id, type, difficulty, content, options, answer, analysis, source, review_status, textbook_version) VALUES
('qt-review-b4-9','math','高中',18,'kp-math-review','single_choice',0.46,'等比数列首项 3，公比 2，第 4 项是？','[{"key":"A","text":"24"},{"key":"B","text":"48"},{"key":"C","text":"9"},{"key":"D","text":"12"}]','A','aₙ=a₁qⁿ⁻¹=3×2^3=24','template','approved','通用'),
('qt-review-b4-10','math','高中',18,'kp-math-review','single_choice',0.54,'等比数列首项 1，公比 3，第 5 项是？','[{"key":"A","text":"81"},{"key":"B","text":"243"},{"key":"C","text":"13"},{"key":"D","text":"27"}]','A','aₙ=a₁qⁿ⁻¹=1×3^4=81','template','approved','通用'),
('qt-review-b4-11','math','高中',18,'kp-math-review','single_choice',0.62,'等比数列首项 1，公比 3，第 5 项是？','[{"key":"A","text":"81"},{"key":"B","text":"243"},{"key":"C","text":"13"},{"key":"D","text":"27"}]','A','aₙ=a₁qⁿ⁻¹=1×3^4=81','template','approved','通用'),
('qt-review-b4-12','math','高中',18,'kp-math-review','single_choice',0.70,'等比数列首项 1，公比 2，第 4 项是？','[{"key":"A","text":"8"},{"key":"B","text":"16"},{"key":"C","text":"7"},{"key":"D","text":"4"}]','A','aₙ=a₁qⁿ⁻¹=1×2^3=8','template','approved','通用');
